eqlabs/pathfinder

- crates/gateway-client/src/lib.rs
- crates/pathfinder/src/state/sync/l2.rs
Starknet feeder gateway added a new `headerOnly` flag to their `get_block` endpoint that returns just the block number and the block hash for the requested block.
We can utilize that new feature when polling for the latest block.
Note: we cannot make a release with this before this gets rolled out on mainnet as well.
> feat(gateway-client): poll latest block header using headerOnly flag

- CHANGELOG.md
- crates/common/src/lib.rs
- crates/pathfinder/src/p2p_network/sync_handlers/v0.rs
- crates/rpc/src/v03/method/get_events.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/event.rs
`continuation_token` now includes a block number to continue from and a relative offset to the beginning of that page. Page number for the pending page is considered to be latest block number plus one.
This approach has two advantages:
* we can use the block number from the token as from_block in the query, leading to a smaller range to check
* we can construct the next continuation_token without knowing the number of all events matching in the database even for the pending case
> feat(rpc/get_events): improve continuation_token handling

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/state/sync/l2.rs
Computing a block hash and verifying transaction hashes sequentially takes ~350ms, most of which is spent calculating Pedersen hashes.
There are some points in those calculations where we're calculating hashes for individual items (transactions, events) which are easy to compute in parallel with `rayon`.
This brings down total processing time to ~75ms.
> feat(state): paralellize block verification calculations

- Cargo.lock
- crates/executor/Cargo.toml
- crates/executor/src/execution_state.rs
- crates/executor/src/state_reader.rs
As instructed in #1364, this PR aims at adding a cache for the compiled contract classes.
As contract classes are insert-only and their absence isn't cached, this PR should not have any other effect than improving performance in the typical use-cases.
This cache brings a 20-30% speed improvement to the `re_execute` scenario. 16MB are enough to get most of the benefits.
Delete once completed: #1364
> feat: Add a global class cache

- crates/load-test/Cargo.lock
- crates/pathfinder/Cargo.toml
We no longer need `process` (was used previously for the Python subprocess code) -- but rely on `rt-multi-thread` and `macros` so those should be added to `features`.
> fix(pathfinder): update `tokio` required feature list

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/examples/re_execute.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
In favor of just using `std::thread::available_parallelism()`.
> chore(pathfinder): remove num_cpus crate dependency

- crates/storage/src/connection/event.rs
If there is no key filter specified in the event filter `select_query_stragegy()` will always return `BlockRangeFirst`.
Previously it still determined the number of events covered by the block range query but this is unnecessary since it has no effect on the result and is quite slow for huge ranges.
> fix(storage/event): improve performance of getEvents queries without a key filter

- crates/common/src/macros.rs
Rely on the existing logic of the regular Felt struct.
This avoid some duplicated code and boilerplate, but has the side effect of changing the error message:
From
```
A hex string with at most 251 bits set.
```
To
```
a hex string of up to 64 digits with an optional '0x' prefix
```
[`impl Deserialize for Felt`](https://github.com/eqlabs/pathfinder/blob/main/crates/rpc/src/felt.rs#L215)
> Simplify the Felt251 deserializer

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/main.rs
If any of our running-forever service tasks (sync/RPC/monitoring/P2P) exits that means a fatal error and pathfinder exits.
In those cases pathfinder should exit with a non-zero exit status.
> fix(pathfinder): exit with non-zero exit status on unintended shutdown

- CHANGELOG.md
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/pending.rs
This PR fixes a rare crash in the sync process caused by a database race condition between the producer and consumer of L2 blocks.
The scenario that this fixes is:
1. Consumer updates database to block N
2. Producer emits block N+1 into queue for consumer
3. Producer crashes
4. Producer is restarted with the latest block in database (N)
5. Producer emits block N+1
6. Consumer updates database with block N+1
7. Consumer attempts to update database with block N+1 again and crashes due to Primary key constraint
The "fix" is to ignore blocks that are below the consumers latest block.
In addition this PR also now ignores pending blocks who's classes are missing. This was the cause of the crashes in (3) for the user who reported this issue. The missing classes can occur if we get unlucky and …
> fix: sync crash due to duplicate blocks submitted by producer

- crates/rpc/src/felt.rs
- crates/storage/src/params.rs
> chore: fix `redundant explicit link target` errors for `cargo doc`

- .github/CODEOWNERS
Later matches have a precedence so we should have all default codeowners in a single line.
> chore(CODEOWNERS): fix global rule

- CHANGELOG.md
- crates/rpc/src/v02/method/get_storage_at.rs
Due to a bug in our fallback logic we returned "Contract not found" errors when the contract has been deployed in the pending block.
This PR fixes this by enabling the zero-fallback if the contract exists in the pending block (as opposed to our previous requirement of existing on the latest block).
Closes #1408
> fix(rpc/get_storage_at): return zero for non-existent keys of contracts deployed in pending

- crates/pathfinder/src/state/sync.rs
The next expected block was never reset after a reorg, causing subsequent block to be sklpped entirely as "duplicates".
This doesn't affect any production code, this was a bug introduced in the unreleased PR #1405.
> fix: reorg'd blocks are skipped

- crates/merkle-tree/src/class.rs
- crates/merkle-tree/src/contract.rs
- crates/merkle-tree/src/merkle_node.rs
- crates/merkle-tree/src/storage.rs
- crates/merkle-tree/src/transaction.rs
- crates/merkle-tree/src/tree.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/trie.rs
- crates/storage/src/params.rs
Current node indices are u32 of which 31 bits are already fully used on mainnet. This PR bumps this to u64.
A more correct approach would be using new types which will be attemped in a more robust PR in the following days. This PR is more a bandaid to get a release out sooner.
> feat: increase node index from u32 to u64

- CHANGELOG.md
- crates/rpc/src/v02/method/get_nonce.rs
Due to a bug in our fallback logic we returned "Contract not found" errors when the contract has been deployed in the pending block.
This PR fixes this by enabling the zero-fallback if the contract has been (re)deployed in the pending block (as opposed to our previous requirement of existing on the latest block).
Closes #1409
> fix(rpc/get_nonce): return zero for nonce of contracts deployed in pending

- crates/rpc/src/v02/method/get_storage_at.rs
This fix reverts the previous fix and adds one that avoids doing DB queries for contracts that have been deployed in the pending blocks.
> fix(rpc/get_storage_at): simplify fix for pending getStorageAt

- README.md
It looks like accessing the bucket doesn't work reliably without the access key. Until we figure this out this PR adds a read-only access key to the configuration that only has access to `pathfinder-snapshots`.
> fix(README): update rclone config

- README.md
Syncing the integration network takes a long time due to the large number of blocks _and_ the pretty low rate limit we're allowed to access the feeder gateway.
This PR adds details of a compressed snapshot we've published on Cloudflare R2.
> chore(README): add integration snapshot link

- CHANGELOG.md
- crates/rpc/src/jsonrpc/router.rs
This PR sets the `content-type` header to `application/json`. 
Currently axum defaults it to `content-type: application/octet-stream` which is of course incorrect.
I'm not sure if this is the correct way of handling this - apparently one should respect the `Accept` header of the request? But since this is always json, I don't think we need to check or worry about this?
Fixes #1431
> fix(rpc): set content-type header to application/json

- Cargo.lock
- Cargo.toml
- crates/executor/Cargo.toml
- crates/executor/src/block_context.rs
cairo-vm 0.8.7 turns out to be incompatible with 0.8.2 which causes issues when producing a traceback for recursive calls.
This change downgrades cairo-vm to 0.8.2.
> fix(executor): downgrade cairo-vm to 0.8.2

- CHANGELOG.md
- Cargo.lock
- crates/rpc/Cargo.toml
- crates/rpc/src/jsonrpc/router.rs
This PR allows for `content-type: application/json; charset=utf-8` for RPC requests.
Previously only `content-type: application/json` was allowed. It seems the spec for this is quite unofficial and is separated in multiple locations.
From what I could piece together it seems json itself defaults to utf-8 if not specified, but allows other utf-X encodings in theory.
This PR only whitelists utf-8 because that's what the internal parsing assumes. We can in theory attempt to support other utf encodings but I don't think that's really worth trying.
> fix(rpc): accept json content with encoding specified

- crates/rpc/src/lib.rs
- crates/rpc/src/v04.rs
- crates/rpc/src/v05.rs
- crates/rpc/src/v05/method.rs
- crates/rpc/src/v05/method/get_block_with_tx_hashes.rs
- crates/rpc/src/v05/method/get_block_with_txs.rs
- crates/rpc/src/v05/types.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/transaction.rs
This PR adds implementation for `starknet_getBlockWithTxs` and `starknet_getBlockWithTxHashes` for the 0.5 JSON-RPC API.
The only difference in the specification compared to 0.4 is that the `l1_gas_price` and `starknet_version` properties have been added to the response.
The implementation for `starknet_getBlockWithTxHashes` is now more efficient since it avoids fetching the actual transaction and receipt data from storage.
Closes issue #1401 
Closes issue #1402
> feat(rpc/v05): implement `starknet_getBlockWith{Txs,TxHashes}` for JSON-RPC 0.5

- crates/rpc/src/lib.rs
- crates/rpc/src/v04/method.rs
- crates/rpc/src/v05.rs
Closes #1442, closes #1443 and closes #1444.
There were no changes in any of these from v0.4. The specification types got juggled around a bit, but ended up identical to what we already had before.
In addition, `starknet_estimateFee` still accepts Declare v0 since these were re-activated on mainnet and it seems like a bad idea to disable this.
> feat(rpc/v0.5): support execution methods

- crates/rpc/src/lib.rs
- doc/rpc/v03/starknet_api_openrpc.json
- doc/rpc/v03/starknet_trace_api_openrpc.json
- doc/rpc/v03/starknet_write_api.json
- doc/rpc/v04/starknet_api_openrpc.json
- doc/rpc/v04/starknet_trace_api_openrpc.json
- doc/rpc/v04/starknet_write_api.json
- doc/rpc/v05/starknet_api_openrpc.json
- doc/rpc/v05/starknet_trace_api_openrpc.json
- doc/rpc/v05/starknet_write_api.json
This PR pulls the RPC methods from the specification itself, and ensures that the required methods are present on each route.
This changes the existing implementation which requires manually adding each implemented method to the list. This is of course error prone; the new test instead requires a path to the specification and a list of exlcuded / unimplemented methods. The test is robust and also ensures that excluded methods are both
- present in the specification, and
- are actually not implemented
Closes #1369
> feat: automate RPC route tests

- crates/gateway-client/src/lib.rs
- crates/gateway-test-fixtures/fixtures/0.9.0/txn/declare.json
- crates/gateway-test-fixtures/fixtures/0.9.0/txn/deploy.json
- crates/gateway-test-fixtures/fixtures/0.9.0/txn/invoke.json
- crates/gateway-test-fixtures/fixtures/0.9.0/txn/status.json
- crates/gateway-test-fixtures/src/lib.rs
- crates/gateway-types/src/reply.rs
- crates/pathfinder/src/p2p_network/client.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v05.rs
- crates/rpc/src/v05/method.rs
- crates/rpc/src/v05/method/get_transaction_status.rs
This PR adds an implementation for `starknet_getTransactionStatus`.
Implementation is mostly straightforward, except for the mapping of responses from the feeder gateway where there's a slight difference in representation of `REJECTED` and `RECEIVED` transactions.
In the JSON-RPC specification `REJECTED` transactions are represented with `finality_status: "REJECTED"` and no `execution_status` whereas on the feeder gateway they are `finality_status: "RECEIVED"` and `execution_status: "REJECTED"`.
For JSON-RPC there's no `execution_status` for `RECEIVED` / `REJECTED` transactions.
Closes issue #1440
> feat(rpc/v05): add `starknet_getTransactionStatus` implementation

- crates/rpc/src/lib.rs
- crates/rpc/src/v05.rs
- crates/rpc/src/v05/method.rs
- crates/rpc/src/v05/method/get_transaction_receipt.rs
- crates/serde/src/lib.rs
This PR adds an implementation for `starknet_getTransactionReceipt`.
The only change I have found in the spec is, as mentioned in the original issue, the addition of the `execution_resources` resources field.
The first commit consists in copy-pasting the v0.4 implementation, so I recommend reviewing this PR commit by commit.
Please let me know all that I can improve, including:
- how far should we go in terms of code reuse/duplication
- how to test this properly
- how close should we stay to the spec (using strings because specified like this in the spec when it's just numbers?)
Closes #1429
>  feat(rpc/v05): add `starknet_getTransactionReceipt` implementation

- crates/rpc/src/v03/method/simulate_transaction.rs
- crates/rpc/src/v04/method/simulate_transactions.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
The field name should be `revert_reason` instead of `reverted_reason`.
> fix: incorrect trace field name

- CHANGELOG.md
- crates/rpc/src/error.rs
- crates/rpc/src/jsonrpc/error.rs
- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/pathfinder/methods/get_proof.rs
- crates/rpc/src/v02/method/add_declare_transaction.rs
- crates/rpc/src/v02/method/add_deploy_account_transaction.rs
- crates/rpc/src/v02/method/add_invoke_transaction.rs
- crates/rpc/src/v03/method/get_events.rs
- crates/rpc/src/v04/method/add_declare_transaction.rs
- crates/rpc/src/v04/method/add_deploy_account_transaction.rs
- crates/rpc/src/v04/method/add_invoke_transaction.rs
- crates/rpc/src/v04/method/trace_transaction.rs
- crates/rpc/src/v05/method/call.rs
- crates/rpc/src/v05/method/estimate_fee.rs
- crates/rpc/src/v05/method/estimate_message_fee.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v05/method/trace_transaction.rs
This PR maps RPC errors with state to the error response's `data` field.
The JSON-RPC specification allows for an optional `data` field for errors. This PR maps any error state to this field. Currently, any state is manually surfaced via the error's message property but we often forget to pipe this through.
This PR instead separates the two concerns, making it harder to forget. State is now mapped to `data` and an error's message should remain constant.
As an example, the response for error `UnexpectedError("root cause")`. Before
```json
{
"code": 63,
"message": "An unexpected error occurred"
}
```
after
```json
{
"code": 63,
"message": "An unexpected error occurred",
"data": {
"error": "root_cause"
}
}
```
One notable change is that internal errors now contain their actual errors in the …
> fix: nested RPC error messages are hidden

- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v05/method/trace_transaction.rs
This PR adds test cases for tracing pending transactions.
Closes #1456
> fix(rpc/v05/trace_{block_transactions,transaction}): add tests for pending block

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/src/context.rs
- crates/rpc/src/jsonrpc/router.rs
Makes the `RpcRouter` capable of handling request batches concurrently.
Adds a `rpc-batch-concurrency-limit` CLI argument to control this.
Closes #1448
> Concurrent RPC batch processing

- Cargo.lock
- Cargo.toml
- crates/executor/src/block_context.rs
- crates/executor/src/simulate.rs
- crates/executor/src/state_reader.rs
- crates/executor/src/transaction.rs
- crates/executor/src/types.rs
- crates/pathfinder/Cargo.toml
- crates/rpc/src/executor.rs
- crates/rpc/src/v05/method/estimate_message_fee.rs
NOTE: this is supposed to be a temporary measure until fixes are merged back to the blockifier branch for 0.13.0.
This PR downgrades our `blockifier` dependency to use the `main-v0.12.3` branch. This branch will later contain a fix for the query version issue but is using a much older `starknet_api` dependency which we need to adapt our code to.
We also have to downgrade a few third party dependencies (like `serde` and `time`) so that they are compatible with this branch of `starknet_api` and `blockifier`.
> feat(executor): use blockifier `main-v0.12.3` branch

- CHANGELOG.md
- crates/executor/src/block_context.rs
Our previous value of 1M might cause execution-related methods to run out of steps and return an error, while the exact same calls did work on the Starknet gateway.
Closes #1474
> fix(executor): bump `invoke_tx_max_n_steps` to 3M

- Cargo.lock
- Cargo.toml
- crates/common/src/lib.rs
- crates/executor/src/transaction.rs
- crates/rpc/src/executor.rs
- crates/rpc/src/v05/method/estimate_message_fee.rs
This version solves the query version flag issue (where the flag was not set when queried via the `get_execution_info` syscall).
> fix(executor): upgrade blockifier dependency to latest main-v0.12.3

- CHANGELOG.md
- crates/rpc/src/v05/method/simulate_transactions.rs
In the 0.5.0 spec TRANSACTION_TRACE now has a `type` property carrying the type of the transaction that has produced the trace.
> fix(rpc/v05): fix TRANSACTION_TRACE type

- CHANGELOG.md
- crates/executor/src/error.rs
- crates/gateway-types/src/error.rs
- crates/rpc/src/error.rs
- crates/rpc/src/jsonrpc/error.rs
- crates/rpc/src/jsonrpc/response.rs
- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/pathfinder/methods/get_proof.rs
- crates/rpc/src/v02/method/add_declare_transaction.rs
- crates/rpc/src/v02/method/add_deploy_account_transaction.rs
- crates/rpc/src/v02/method/add_invoke_transaction.rs
- crates/rpc/src/v02/method/call.rs
- crates/rpc/src/v03/method/estimate_fee.rs
- crates/rpc/src/v03/method/estimate_message_fee.rs
- crates/rpc/src/v03/method/get_events.rs
- crates/rpc/src/v03/method/simulate_transaction.rs
- crates/rpc/src/v04/method/add_deploy_account_transaction.rs
- crates/rpc/src/v04/method/add_invoke_transaction.rs
- crates/rpc/src/v04/method/estimate_message_fee.rs
- crates/rpc/src/v04/method/simulate_transactions.rs
- crates/rpc/src/v04/method/trace_block_transactions.rs
- crates/rpc/src/v04/method/trace_transaction.rs
- crates/rpc/src/v05/method/call.rs
- crates/rpc/src/v05/method/estimate_fee.rs
- crates/rpc/src/v05/method/estimate_message_fee.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v05/method/trace_transaction.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/event.rs
Distinguish internal errors from custom errors.
Internal errors may contain sensitive data that should not reach the end user. These are logged upon serialization, and serialization always results in the single "internal error" message.
Custom errors are errors that may occur, that aren't defined in the Starknet spec, and whose details may benefit the end user. These will still be serialized as an internal error, with the underlying error provided in the JSON-RPC error `data` field.
1. Introduce a custom variant in various enums.
2. Use the custom variant where the error details provide value to the end user while not disclosing sensitive information.
3. Keep all `From<anyhow::Error>` implementations mapped to `InternalError` variants. This maintains the …
> feat: distinguish internal and custom errs

- .github/workflows/ci.yml
- .github/workflows/msrv.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- build/prepare.sh
- crates/ethereum/Cargo.toml
- doc/install-from-source.md
This PR (hopefully) improves the current CI situation by reducing the time tests take to build.
Highlights:
- Use `mold` linker (somehow this got removed for tests - probably my fault).
- Only cache pushes to main branch. Each entry is 1.2GB which means that we are getting cache churn (max cache is 10GB); instead only cache main which at least should have the bulk of the deps cached then.
- Refactored some deps so that expensive `-sys` crates are no longer bundled but rather use the vendored crates. ~This might cause an issue with docker?~ It does cause docker changes but those have been applied.
> ci: refactor and improve times

- .github/workflows/ci.yml
We're using the [maximize-build-space](https://github.com/easimon/maximize-build-space) action so that we have plenty of space for the `target` directory in the build. However, the default settings of that action mean that it leaves very minimal free space on `/` and `/mnt`.
We've seen `rust-cache` restores fail because because of lack of disk space -- with the cache item being ~1.2 GB it's entirely possible that it ran out of temporary space for the compressed archive.
> chore(github/ci): leave more space on `/` and `/mnt` for the test job

- CHANGELOG.md
- crates/executor/src/simulate.rs
- crates/executor/src/types.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
To comply with version 0.5.1 of the RPC specification, this commit adds the `state_diff` to L1 handler transaction traces.
> feat(rpc): add `state_diff` property to `L1_HANDLER_TRANSACTION_TRACE`

- .github/workflows/ci.yml
These only cache on main branch, same as test job.
These caches were previously removed as they were evicting test caches. But now that we only cache on main branch this is no longer an issue.
> ci: re-add caching to clippy and doc jobs

- CHANGELOG.md
- README.md
- crates/rpc/src/lib.rs
Add RPC endpoints using `/rpc/vX_Y` in addition to `/rpc/vX.Y`.
This is part of an effort to standardize these endpoints across all nodes. In time we will deprecate and remove `/rpc/vX.Y`.
An open question is: should we instead move to hosting them on root instead of in `/rpc`. i.e. `/vX_Y` which is more inline with other nodes. We originally chose a more directory like structure, in case we ever wanted to host more (non-json-rpc) things on the same port. This still makes sense to me, but we also have nothing else hosted here..
Update: waiting on starkware feedback regarding `/rpc/xxx` or `/xxx`.
> feat(rpc): add standardize RPC endpoints

- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
Version 0.5.1 of the JSON-RPC specification made the `state_diff` field optional in transaction traces (all variants).
This allows us to just skip serializing the `state_diff` altogether instead of using an empty state diff if we have none (like when we're fetching the traces from the gateway).
Fixes #1512
> feat(rpc/v05/trace): make `state_diff` property optional in transaction traces

- README.md
- crates/rpc/src/v05.rs
- crates/rpc/src/v05/method.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v05/method/spec_version.rs
- doc/rpc/v05/starknet_api_openrpc.json
- doc/rpc/v05/starknet_trace_api_openrpc.json
- doc/rpc/v05/starknet_write_api.json
This PR keeps the blockifier's `CallType::Delegate` variant instead of mapping it to `LibraryCall`. 
This was previously done to comply with the previous RPC spec which did not have the delegate variant.
Also simplify `starknet_specVersion` implementation and bump it to v0.5.1, and update the docs to reflect the v0.5.0 to v0.5.1 bump.
Closes #1511 and closes #1513
> feat(rpc/v0.5.1): use delegate instead of library call

- crates/rpc/src/v05.rs
That's what we're supposed to return according to the specification.
> fix(rpc/v05/spec_version): return "0.5.1" without the "v" prefix

- crates/common/src/state_update.rs
- crates/gateway-types/src/reply.rs
State diff commitments are one piece of the data that's signed by the feeder gateway for [P2P authentication](https://community.starknet.io/t/introducing-p2p-authentication-and-mismatch-resolution-in-v0-12-2/97993).
This PR adds a method to compute the commitment along with a test that checks that the commitment value matches the one returned by the gateway.
> feat(common/state_update): add method to compute state diff commitment

- crates/rpc/src/v02/method/get_transaction_receipt.rs
Since introducing custom errors recently internal errors are now logged on WARN level. This causes pathfinder to log a WARN-level error when it's in fact running perfectly OK and returning the expected RPC response. (Which is a custom error for reverted transactions.)
> fix(rpc/v02/get_transaction_receipt): reverted transactions should be a custom error

- CHANGELOG.md
- crates/rpc/src/v02/types.rs
- crates/rpc/src/v05/method/get_block_with_txs.rs
An alternative implementation would be an `Option<BlockStatus>` but that requires checking the status mapping in various places.
Closes #1527
> fix(rpc): `starknet_getBlockWithXXX` has status for pending responses

- CHANGELOG.md
- crates/executor/src/error.rs
- crates/executor/src/simulate.rs
Otherwise we don't properly return those to the JSON-RPC client and log them on WARN log level instead.
None of these errors (apart from the anyhow::Error mapping) are internal issues but instead errors that were encountered during contract execution.
Closes #1530
> fix(executor): map VM errors to custom errors

- .github/workflows/docker.yml
This PR couples the docker image tagging to run after a github release, instead of on a tag being pushed.
Our current release workflow is:
1. Push version tag
2. Docker workflow runs and uploads an image. This includes tagging the image with the version and `latest`
3. Formally release on github
External parties moniter our docker images for new releases, instead of our github releases. So what occasionally occurs is that we find a bug between steps (2) and (3) but since some users already have the "release" via dockerhub we cannot properly abort the faulty release.
What this PR does is change the workflow to:
1. Push version tag
2. Docker workflow runs and uploads an image **without** tagging it
3. Formally release on github
4. This triggers another workflow which will tag the image from …
> ci: harden docker workflow

- CHANGELOG.md
- crates/executor/src/execution_state.rs
- crates/executor/src/simulate.rs
Historical block hashes (up to block_number - 10) should be available in the state with contract_address=1, key=block_number. This is not a problem for non-trace methods as there we use the state from the block specified (which already has this update from system contracts), but for tracing we're setting up our state reader with the state at the previous block.
Because of this we're missing the block hash value for block_number - 10 specifically which might cause execution issues with contracts using the `get_block_hash` system call.
Closes #1547
> fix(executor): add block hash value to the state for trace execution

- CHANGELOG.md
- crates/common/src/consts.rs
- crates/common/src/lib.rs
- crates/ethereum/src/lib.rs
- crates/gateway-client/src/lib.rs
- crates/gateway-types/src/transaction_hash.rs
- crates/pathfinder/examples/feeder_gateway.rs
- crates/pathfinder/examples/re_execute.rs
- crates/pathfinder/examples/verify_block_hashes.rs
- crates/pathfinder/examples/verify_transaction_hashes.rs
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/rpc/src/context.rs
Remove most of the occurrences of "testnet2", leaving only these required for [gateway-types::transaction_hash::tests::computation](https://github.com/pierre-l/pathfinder/blob/deprecate-testnet2/crates/gateway-types/src/transaction_hash.rs#L473)
Running Pathfinder with `--network testnet2` will now result in an error:
```
error: invalid value 'testnet2' for '--network <NETWORK>'
[possible values: mainnet, testnet, integration, custom]
```
Related: #1548
> chore: Remove support for testnet2

- Cargo.lock
- Cargo.toml
- crates/compiler/Cargo.toml
- crates/executor/src/block_context.rs
- crates/executor/src/call.rs
- crates/executor/src/estimate.rs
- crates/executor/src/felt.rs
- crates/executor/src/simulate.rs
- crates/executor/src/state_reader.rs
- crates/executor/src/transaction.rs
- crates/executor/src/types.rs
- crates/pathfinder/Cargo.toml
- crates/rpc/src/executor.rs
- crates/rpc/src/v05/method/estimate_message_fee.rs
This PR upgrades our execution related crates to the versions required by Starknet 0.13.0.
A new `starknet_api` crate version is required so that we can represent v3 transactions and some blockifier APIs have also changed.
Closes #1520 
Closes #1482
> feat(executor): upgrade Cairo compiler to 2.4.0-rc2 and blockifier to 0.4.0-rc6

- crates/rpc/src/lib.rs
- crates/rpc/src/v05.rs
- crates/rpc/src/v06.rs
- crates/rpc/src/v06/method.rs
- crates/rpc/src/v06/method/get_block_with_txs.rs
This PR adds a JSON-RPC 0.6.0-specific implementation of `starknet_getBlockWithTxs`. We need this because the transaction representation for v3 transactions is different between earlier versions and 0.6.0.
> feat(rpc/v06): add `starknet_getBlockWithTxs`

- crates/executor/src/types.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v06.rs
- crates/rpc/src/v06/method.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
This PR adds execution resources to executor output and the new `execution_resources` property to `FUNCTION_INVOCATION` in our transaction trace output.
> feat(rpc/v06): add `starknet_simulateTransactions`

- crates/executor/src/simulate.rs
- crates/executor/src/types.rs
- crates/rpc/src/v04/method/simulate_transactions.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
`starknet_simulateTransactions` used to return an error upon the first reverted transaction.
With the JSON-RPC 0.6.0 API we've agreed to return traces with the reverted reason instead.
Post-execution checks are added to `starknet_simulateTransactions` implementations for older JSON-RPC versions that check if there were reverted transactions and throw the same error they were mapping `CallError::Reverted` to.
> feat(rpc/v06): `starknet_simulateTransaction` should return traces for reverted transactions

- crates/rpc/src/v06.rs
- crates/rpc/src/v06/method.rs
- crates/rpc/src/v06/method/get_block_with_tx_hashes.rs
- crates/rpc/src/v06/types.rs
This was previously overlooked and the 0.6.0 implementation just used the block header from v05.
> fix(rpc/v06): add `price_in_strk` gas price to block header

- crates/rpc/src/lib.rs
- crates/rpc/src/v06.rs
- crates/rpc/src/v06/method.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
These are really just copies of the v05 implementation but using the `TransansactionTrace` type for v06.
> feat(rpc/v06): add `starknet_trace*` methods

- CHANGELOG.md
- README.md
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/rpc/src/jsonrpc/websocket.rs
- crates/rpc/src/jsonrpc/websocket/data.rs
- crates/rpc/src/jsonrpc/websocket/logic.rs
- doc/rpc/pathfinder_rpc_api.json
- doc/rpc/pathfinder_ws.json
This PR updates the newHeads subscription's documentation and event data. 
We removed and then re-added websocket support. During this process we also removed the specification for these methods, but never added it back.
This PR also changes the event data to reflect the common block header type instead of the gateway type. This is a breaking change, but since we're already breaking things I think this is good.
I'm not very good at writing nor reading JSON-RPC specs, so a careful eye on it would be appreciated.
> feat: update newHeads subscription

- crates/p2p_stream/src/codec.rs
- crates/p2p_stream/src/handler.rs
- crates/p2p_stream/src/handler/protocol.rs
- crates/p2p_stream/src/lib.rs
In four places it was missing the first 'i'
> fix spelling of Equilibrium

- crates/rpc/src/v06/types.rs
To follow-up changes in the upstream spec version 0.6.0-rc3: https://github.com/starkware-libs/starknet-specs/blob/34fa3650b1026f94861637c7d374b31861248d9c/api/starknet_api_openrpc.json#L3752
Closes #1581
> fix(rpc/v06): rename `price_in_strk` to `price_in_fri`

- crates/executor/src/error.rs
- crates/executor/src/estimate.rs
- crates/executor/src/lib.rs
- crates/executor/src/simulate.rs
- crates/rpc/src/error.rs
- crates/rpc/src/v04/method/simulate_transactions.rs
- crates/rpc/src/v04/method/trace_block_transactions.rs
- crates/rpc/src/v04/method/trace_transaction.rs
- crates/rpc/src/v05/method/call.rs
- crates/rpc/src/v05/method/estimate_fee.rs
- crates/rpc/src/v05/method/estimate_message_fee.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v05/method/trace_transaction.rs
- crates/rpc/src/v06.rs
- crates/rpc/src/v06/method.rs
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
In the 0.6.0-rc3 version of the JSON-RPC specification `starknet_estimateFee` and `starknet_simulateTransactions` are expected to return a `TRANSACTION_EXECUTION_ERROR` in case execution fails. This new error type contains the transaction index (and the error string) in a structured way as additional data.
This PR introduces a `TransactionExecutionError` type into the `pathfinder_executor` crate that can better describe errors during executing a sequence of transactions. The `CallError` type is now only used for stand-alone contract calls (eg by `starknet_call`).
It then uses the information available in the new `TransactionExecutionError` type to return the new error info required by the specification.
Closes #1582
> feat(rpc/v06): add `TRANSACTION_EXECUTION_ERROR`

- crates/executor/src/estimate.rs
- crates/pathfinder/examples/re_execute.rs
- crates/rpc/src/v05/method/estimate_fee.rs
- crates/rpc/src/v05/method/estimate_message_fee.rs
- crates/rpc/src/v06/method/estimate_fee.rs
The latest 0.6.0-rc3 JSON-RPC specification has added a flag to skip transaction validation.
Closes #1580
> fix(rpc/v06): add `simulation_flags` argument to `starknet_estimateFee`

- Cargo.lock
- Cargo.toml
- crates/compiler/Cargo.toml
This also requires upgrading `starknet_api` (to 0.6.0-rc3) and the Cairo compiler (to 2.4.0-rc6).
Closes #1586
> chore: upgrade blockifier to 0.4.0-rc9.1

- Cargo.toml
- Dockerfile
Current main branch does not compile with Rust 1.73 anymore.
> chore: bump rust version to 1.74.0

- Cargo.lock
- crates/crypto/Cargo.toml
- crates/crypto/src/algebra/field/derive.rs
- crates/crypto/src/algebra/field/felt.rs
Adds x86-asm for the field via ark-ff-asm. Also inlines field operations, and properly use rand instead of rand_core.
This speed up some crypto operations with 10-30% when compiled with: 
```
RUSTFLAGS="-C target-feature=+bmi2,+adx"
```
> feat: ff-asm and inlining

- crates/executor/src/estimate.rs
- crates/executor/src/simulate.rs
- crates/rpc/src/pending.rs
- crates/rpc/src/test_setup.rs
- crates/rpc/src/v06/method/estimate_fee.rs
v3 transactions are supposed to use the STRK gas price for the calculation of the fee estimation. This PR fixes that, and also adds a missing initialization to the STRK gas price when the pending block is invalid/missing.
Closes #1604
> fix(rpc): fix `gas_consumed` calculation for v3 transactions

- crates/executor/src/types.rs
The checks `get_sorted_l2_to_l1_payloads_length()` does are valid only for the top-level `CallInfo` objects in a `TransactionExecutionInfo` object. Blockifier already does that check during fee calculation.
Since we were calling it in a `TryFrom` implementation that calls itself recursively for inner calls this might have lead to false positive errors.
Closes #1605
> fix(executor): remove check for L2-to-L1 message ordering correctness

- crates/rpc/src/v06.rs
- crates/rpc/src/v06/method.rs
- crates/rpc/src/v06/method/get_transaction_by_block_id_and_index.rs
- crates/rpc/src/v06/method/get_transaction_by_hash.rs
These map to the v06 representation of transactions -- that is, they are returning v3 transactions as intended, not their v1-mapped representation.
Closes: #1607
> fix(rpc/v06): add v06-specific `starknet_getTransaction*` methods

- crates/gateway-types/src/reply.rs
- crates/pathfinder/examples/feeder_gateway.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/signature.rs
- crates/storage/src/params.rs
This PR updates our "fake" feeder gateway server so that we can still sync from that using recent pathfinder releases:
- adds the `get_signature` endpoint (not quite correct, it fakes the state diff commitment value in the response because calculating that is quite slow, and also uses a fake signature if it's missing from the database)
- adds the `includeBlock` query parameter to `get_state_update`
> fix(examples/feeder_gateway): update for Starknet 0.13.0

- CHANGELOG.md
- crates/executor/src/error.rs
- crates/executor/src/estimate.rs
- crates/executor/src/simulate.rs
- crates/executor/src/types.rs
This PR adds custom formatting for opaque blockifier error variants.
Example before:
```json
{
"jsonrpc": "2.0",
"error": {
"code": 41,
"message": "Transaction execution error",
"data": {
"execution_error": "Transaction validation has failed.",
"transaction_index": 0
}
},
"id": 1
}
```
After
```json
{
"jsonrpc": "2.0",
"error": {
"code": 41,
"message": "Transaction execution error",
"data": {
"execution_error": "Transaction validation has failed. Execution failed. Failure reason: 0x496e70757420746f6f206c6f6e6720666f7220617267756d656e7473 ('Input too long for arguments').",
"transaction_index": 0
}
},
"id": 1
}
```
> fix: work-around opaque execution errors

- CHANGELOG.md
- crates/rpc/src/error.rs
- crates/rpc/src/v06.rs
- crates/rpc/src/v06/method.rs
- crates/rpc/src/v06/method/add_declare_transaction.rs
- crates/rpc/src/v06/method/add_deploy_account_transaction.rs
- crates/rpc/src/v06/method/add_invoke_transaction.rs
- doc/rpc/v06/starknet_write_api.json
Version 0.6.0-rc5 of the JSON-RPC specification adds a string-typed additional data field to the VALIDATION_ERROR error so that we can return the original error message from the gateway.
This commit adds the new variant to the RPC error type and adds v06-specific mapping of gateway errors and bumps JSON-RPC 0.6 version to 0.6.0-rc5.
> feat(rpc): add v06-specific VALIDATION_ERROR variant

- CHANGELOG.md
- Cargo.lock
- crates/rpc/Cargo.toml
- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/middleware.rs
- crates/rpc/src/middleware/request_id.rs
- crates/rpc/src/middleware/tracing.rs
This PR improves the RPC logging situation. 
We lost the ability to log request bodies when we moved to our own json-rpc framework. This PR adds this back and also adds `x-request-id` header which can be used to correlate specific requests from clients.
Note that I also removed the HTTP method from the trace fields - since this is almost always POST I thought it is just clutter..
The following logs were obtained with `RUST_LOG=pathfinder_rpc=debug,tower_http=debug`.
Before
```
DEBUG request{method=POST uri=/ version=HTTP/1.1}: tower_http::trace::on_request: started processing request
DEBUG request{method=POST uri=/ version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=0 ms status=200
```
After
```
DEBUG request{uri=/ version=HTTP/1.1 x_request_id="0"}: …
```
> feat(rpc): improve logging

- .github/workflows/ci.yml
This PR periodically clears our rust-cache which otherwise grows indefinitely.
For context see this [rust-cache issue](https://github.com/Swatinem/rust-cache/issues/181).
In addition, this PR restricts the test compilation to single threaded in the hope that it reduces the odds of going OOM and failing the run. This is (probably) the cause of many CI failures which timeout after 30+ minutes.
Note: I haven't tested this cache refresh idea. The concept is to still use the caching action but then to delete it all. And build from scratch instead, and then the action will re-upload the fresh cache.
> ci: periodically refresh cache

- CHANGELOG.md
- crates/rpc/src/v05/method/simulate_transactions.rs
The error code for reverted transactions should be CONTRACT_ERROR, since in the 0.5.1 JSON-RPC specification that error code has the revert reason as additional data.
Closes #1626
> fix(rpc/v05/simulate_transactions): fix error code for reverted transactions

- CHANGELOG.md
- crates/rpc/src/v06.rs
The stable relase is now available and made no difference from `rc5`.
> feat(v0.6): drop `-rc5` for `starknet_specVersion`

- CHANGELOG.md
- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/middleware/tracing.rs
Debug level is a bit too spammy since one often enables `pathfinder=debug` which unfortunately also enables the rpc logs at the same level.
The tracing spans are left at debug level which I think is fine?
> chore: drop default rpc log level to trace

- crates/rpc/src/jsonrpc/router.rs
This prevents silently overwriting an existing method.
> feat(rpc): panic on duplicate method registration

- crates/gateway-client/src/lib.rs
- crates/gateway-types/src/reply.rs
- crates/rpc/src/v02/types.rs
- crates/rpc/src/v04/method/add_deploy_account_transaction.rs
- crates/rpc/src/v06/method/add_deploy_account_transaction.rs
It looks like the Starknet gateway's `add_transaction` endpoint does not return the address of the deployed contract in the response for DEPLOY_ACCOUNT v3 transactions.
We don't really need that address in the response: it's computed from data available in the transaction so we can also just compute that ourselves.
> fix(rpc): add workaround for gateway not returning deployed contract address

- crates/storage/src/connection/event.rs
Since we already have a cost limit on the event queries there's no point in counting the exact number of matching events by the keys or range.
It's sufficient to be able to count up to reaching a limit where the cost would be too much anyway.
This avoids issues with queries using keys of which there are a few hundred million events in the database.
> fix(storage/events): add upper bounds on queries used to select strategy

- CHANGELOG.md
- crates/rpc/src/lib.rs
- crates/rpc/src/v05/method/get_transaction_receipt.rs
- crates/rpc/src/v06/method/get_transaction_receipt.rs
The values are expected to be numbers, not hex-encoded strings.
This PR also adds the `segment_arena_builtin` counter that was previously missing.
Only `steps` is required now so we're skipping serialization for other zero-valued counters.
> fix(rpc/v06): fix execution resources

- crates/executor/src/lib.rs
- crates/executor/src/lru_cache.rs
- crates/executor/src/state_reader.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/class.rs
Replace the global cache with a height-constrained cache
Invert the cache<->reader relationship: let the reader wrap the cache instead of the other way around
Provide `with_block_number`-suffixed methods to retrieve class definitions
Let the `CachedState` rely on a local cache
**Review commits separately.** The first one was extracted for improved readability.
Closes #1570
> Prevent the global class cache from returning classes that are not yet declared

- CHANGELOG.md
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v06/method/estimate_message_fee.rs
- crates/rpc/src/v06/method/get_transaction_receipt.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
- crates/rpc/src/v06/types.rs
`starknet_getTransactionReceipt` was still returning STRK as the fee token type for v3 transactions.
> fix(rpc/v06): fix price unit in transaction receipt

- crates/load-test/Cargo.lock
- crates/load-test/src/main.rs
- crates/load-test/src/requests/v05.rs
- crates/load-test/src/tasks/v05.rs
This task does a call to `starknet_getNonce` on the `pending` block. This is a fairly common operation clients do when sending transactions: they first need to determine the current nonce for the account.
> feat(load-test): add starknet_getNonce task to load test

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder/main.rs
Cairo VM performance seems to be hugely affected by memory allocator performance since it tends to allocate lot of small objects. This change switches our global allocator to mimalloc which was shown to improve execution performance of `starknet_call` calls invoking StarkGate `balanceOf` by 40%.
> feat(pathfinder): use the mimalloc memory allocator

- CHANGELOG.md
- crates/rpc/src/v02/types.rs
The transaction hash computation was incorrect for v3 transactions using the query flag in the version field because it was always using the version without the query flag.
> fix(rpc): fix v3 transaction hash computation

- CHANGELOG.md
- crates/rpc/src/jsonrpc/error.rs
- crates/rpc/src/jsonrpc/request.rs
- crates/rpc/src/jsonrpc/response.rs
- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/jsonrpc/websocket/data.rs
- crates/rpc/src/jsonrpc/websocket/logic.rs
This PR exposes the error reason for RPC parsing errors via the error's `data` property.
Currently users simply receive `"Invalid params"` or `"Invalid request"` which can be difficult to track down what exactly is wrong in complicated json structures. typos, wrong field names are all difficult to spot.
This PR surfaces the core serde parsing error in an attempt to help.
Here are some downsides to the current implementation
- `serde_json::Error` does not implement serialize so we have to use `to_string` before serializing
- `serde` errors are terrible when combined with untagged enums. Essentially just says "data matched no known enum variant".
- Errors may at times be confusing as we use helper structs for some serde which can be visible in the error message.
Open question: should the …
> feat(rpc): expose parsing errors

- CHANGELOG.md
- crates/common/src/state_update.rs
- crates/executor/src/execution_state.rs
- crates/executor/src/pending.rs
- crates/load-test/src/requests/v05.rs
- crates/load-test/src/tasks/v05.rs
- crates/pathfinder/src/state/sync.rs
- crates/rpc/src/context.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/pending.rs
- crates/rpc/src/v03/method/get_state_update.rs
- crates/rpc/src/v04/method/get_block_with_tx_hashes.rs
- crates/rpc/src/v04/method/get_block_with_txs.rs
- crates/rpc/src/v05/method/call.rs
- crates/rpc/src/v05/method/get_block_with_tx_hashes.rs
- crates/rpc/src/v05/method/get_block_with_txs.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v06/method/get_block_with_tx_hashes.rs
- crates/rpc/src/v06/method/get_block_with_txs.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
This PR changes how we apply pending state updates to the executor state and improves execution performance for trivial calls involving the `pending` block by a factor of 10.
---
Some background: our executor has been applying updates in the pending state to the `CachedState` object we've constructed. This object stores these updates in-memory and returns the updated values it has in its "cache" when queried during exectution. There is some missing functionality on the `State` trait though: we can't explicitly set nonces: the only operation exposed is `increment_nonce()`... As a workaround we've been fetching current `latest` nonces for each contract and determined how many times we'd need to call `increment_nonce()` to get to the desired value.
Unfortunately this does not scale well: …
> feat(executor): rework handling of pending state update

- .github/workflows/docker.yml
Tested on my own fork.
Github also has an additional checkbox to mark a release as latest -- but I couldn't find that information in the github event.
> ci(docker): don't tag prereleases as latest

- crates/gateway-client/src/builder.rs
Some of these methods were missing these events so that we didn't have all requests logged even with `starknet_gateway_client=trace` enabled.
> fix(gateway-client): add tracing events for all GET and POST requests

- CHANGELOG.md
- Cargo.lock
- crates/pathfinder/Cargo.toml
This is release prep for pricing compatibility with starknet v0.13. It **should not** be used on mainnet until v0.13 has been released there.
> chore: testnet only release

- crates/common/src/lib.rs
- crates/pathfinder/src/state/block_hash.rs
- doc/rpc/v03/starknet_api_openrpc.json
- doc/rpc/v04/starknet_api_openrpc.json
- doc/rpc/v05/starknet_api_openrpc.json
- doc/rpc/v06/starknet_api_openrpc.json
This PR updates the outdated links pointing to Starknet documentation. Outdated links are replaced with working links and it is ensured, that links reference the same topic as the original links.
> fix: update of outdated links

- contributing.md
I've corrected a small typo in the `contributing.md` file, where the word "checks" was mistakenly duplicated. This change is intended to improve the clarity and readability of the documentation.
**Details:**
- **File:** `contributing.md`
- **Change:** Removed the redundant word "checks" from the guidelines section.
**Commit ID:** a8a6430d7743cad99c6b9e9ca9a310cd4b9eb761
Here's the quick diff:
```diff
- Ensure CI is happy. CI will run automatically when the PR is opened. This includes checks checks for
+ Ensure CI is happy. CI will run automatically when the PR is opened. This includes checks for
```
> docs: typo in contributing documentation

- README.md
PR is updates available API versions and paths after 0.10.0 version, added info about available WS path
> update README.md: actualize info about JSON-RPC API versions and paths

- crates/crypto/src/algebra/curve/mod.rs
- crates/executor/src/pending.rs
- crates/p2p/src/main_loop.rs
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/p2p_network.rs
- crates/rpc/src/jsonrpc.rs
- crates/rpc/src/v04/method/pending_transactions.rs
- crates/rpc/src/v04/types.rs
- crates/rpc/src/v06/types.rs
- crates/storage/src/connection/transaction.rs
This PR:
- adds the `p2p.predefined-peers` config option, which is a list of peers that we'd like to dial and add to the dht immediately after starting pathfinder; it's an addition to how the node used to work, which is using bootstrap nodes and periodic node discovery (rebootstraping)
- removes the requirement of setting at least one bootstrap node when starting pathfinder
- fixes #1655
> config option to set peers explicitly

- CHANGELOG.md
- crates/rpc/src/lib.rs
- crates/rpc/src/v03/method/get_events.rs
- crates/rpc/src/v04/method/get_transaction_receipt.rs
- crates/rpc/src/v06/method/get_transaction_receipt.rs
Empty lists in the key filter array were not handled correctly: these are supposed to match all events, but the code was treating them as non-matching.
Closes #1666
> fix(rpc/get_events): fix pending events key filtering

- crates/rpc/src/v03/method/get_events.rs
In the fix for issue #1666 a bug slipped in: after truncating the list of keys we should use the _truncated_ list to construct the filter.
> fix(rpc/get_events): use truncated key list for filter

- Cargo.lock
- Cargo.toml
- crates/common/src/lib.rs
- crates/crypto/src/algebra/field/felt.rs
- crates/gateway-types/src/reply.rs
- crates/p2p/Cargo.toml
- crates/p2p/src/client/peer_agnostic.rs
- crates/p2p/src/client/peer_agnostic/parse.rs
- crates/p2p/src/client/types.rs
- crates/p2p_proto/proto/transaction.proto
- crates/p2p_proto/src/transaction.rs
- crates/pathfinder/Cargo.toml
- crates/pathfinder/proptest-regressions/p2p_network/sync_handlers/tests.txt
- crates/pathfinder/src/p2p_network/sync_handlers/conv.rs
- crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/rpc/src/v02/types.rs
I added those fields in anticipation of a spec update but it turns out I didn't notice these fields are [redundant and can just be computed locally](https://github.com/starknet-io/starknet-p2p-specs/pull/23#discussion_r1447011560).
---
Edit: I updated the code to defer computing those addresses after all other parsing is done.
> feat(p2p_proto): remove redundant address fields

- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/bin/pathfinder/update.rs
The release monitoring task crashes if pathfinder is started with a non-semver version or there's an issue setting up the HTTP client to GitHub. This change makes the task non-critical, so that it doesn't crash pathfinder if it fails.
A log message is added to indicate that we won't poll for new releases but otherwise the errors are ignored.
Closes #1686
> fix(pathfinder): make polling for new releases non-critical

- Cargo.lock
- crates/common/src/header.rs
- crates/common/src/lib.rs
- crates/p2p/Cargo.toml
- crates/p2p/src/client/peer_agnostic.rs
- crates/p2p/src/client/peer_agnostic/parse.rs
- crates/p2p/src/client/types.rs
- crates/p2p/src/lib.rs
- crates/pathfinder/src/lib.rs
- crates/pathfinder/src/sync.rs
- crates/pathfinder/src/sync/p2p.rs
- crates/pathfinder/src/sync/p2p/headers.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/block.rs
Initial stab at a p2p sync implementation. This only implements the header sync portion and is not yet connected to the binary at all.
This has changed significantly from the original demo. The original used tasks connected via channels whereas this new design uses streams and stream adapters which I think is much easier to read.
The driving idea is that we can speed up disk IO by only syncing one type of data at a time e.g. only block headers, then transaction data etc. This has the additional advantage of keeping processing simple since much less needs to be done by a single process.
This PR implements the sync skeleton and then the header sync portion of it.
I use two "definitions" throughout the code and comments:
1. **checkpoint** An L1 starknet checkpoint aka `EthereumStateUpdate` …
> Initial p2p sync implementation

- crates/gateway-types/src/transaction_hash.rs
- crates/pathfinder/examples/verify_transaction_hashes.rs
- crates/pathfinder/src/state/sync/l2.rs
Starknet 0.7 introduced L1_HANDLER transactions and added a nonce to these transactions. This means that the transaction hash calculation already uses the `l1_handler` prefix, but it still does not include a transaction version in the hash -- so effectively it's another legacy variant.
This change makes it possible to remove the non-verifiable block range for transaction hashes.
> feat(gateway-types): add transaction hash calculation for 0.7 L1_HANDLER transactions

- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/state/sync/pending.rs
This PR switches to continuously and separately polling for pending data.
This polling is initiated on first reaching the head of the chain. Ideally we would also abort it if we ever fall far enough behind but with our current chaotic layout its a bit difficult.
This does mean we may have duplicate class downloading and processing; this could be improved separately but its non-trivial and probably not worth it at this juncture. The sqlite inserts are duplicate safe i.e. use insert or ignore/replace.
> feat(sync): poll pending continuously

- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
The `get_state_update` feeder gateway endpoint can return both the block and the state update, so we'd better use that to request both objects at the same time.
> feat(pathfinder/sync/l2): download block and state update with a single request

- crates/gateway-client/src/builder.rs
- crates/gateway-client/src/lib.rs
- crates/retry/src/lib.rs
Individual requests to the feeder gateway can sometimes take a long time to complete (we've observed ~30s for polling the pending block). These requests potentially block our progress with syncing. In these cases it can be generally better to just time out the request more aggressively (after just 5 seconds) and retry.
The retry strategy also requires some tuning for the lower request timeout to be effective. The initial delay is 2s, then it doubles every time up to 10s.
> feat(gateway-client): use a more aggressive request timeout and retry strategy

- crates/executor/src/simulate.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v05/method/trace_transaction.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
The trace caching code uses `pending.hash` for caching, which is set to zero. So tracing pending blocks and transactions was completely broken.
The fix is hacky, but all this code is getting refactored by @Mirko-von-Leipzig anyway, so it doesn't really matter.
Also worth noting: to avoid mistakes like this in the future it might make sense to turn `pending.hash` into an `Option`, since logically pending blocks _don't_ have a hash (their hash is not zero - they don't have one).
> fix(rpc): trace caching oversight

- Cargo.lock
- crates/common/Cargo.toml
- crates/common/src/transaction.rs
- crates/crypto/src/hash/pedersen/chain.rs
- crates/crypto/src/hash/poseidon/hash.rs
- crates/gateway-types/src/reply.rs
- crates/gateway-types/src/transaction_hash.rs
- crates/p2p/src/client/types.rs
- crates/pathfinder/examples/verify_transaction_hashes.rs
- crates/rpc/src/v04/types/transaction.rs
- crates/rpc/src/v06/types/transaction.rs
This PR adds a hashing to the common transaction type.
This is a pre-requisite for p2p sync; we don't want to reuse the gateway types there.
This is also a step towards turning the gateway types into simple dto's instead of infecting the rest of the codebase. A hard blocker to this is the use of the gateway transaction types within storage.
There is a test-case for every known hash derivation that we know of. We should double-check this by running the hash checker on every network using the new code. I confirmed that the applicable test cases fail if a part of the hash verification is commented out e.g. commenting out the l1 handler's v0.7 check causes that test case to fail.
Updated L1 Handler transactions to reflect that they always have version zero.
> feat(common): implement transaction hashing

- crates/gateway-types/src/error.rs
- crates/rpc/src/v04/method/add_declare_transaction.rs
- crates/rpc/src/v04/method/add_deploy_account_transaction.rs
- crates/rpc/src/v04/method/add_invoke_transaction.rs
- crates/rpc/src/v06/method/add_declare_transaction.rs
- crates/rpc/src/v06/method/add_deploy_account_transaction.rs
- crates/rpc/src/v06/method/add_invoke_transaction.rs
Changes the starknet display fmt from struct debug to message.
See the attached bug issue for details.
Closes #1750
> fix: align `UNEXPECTED_ERROR` message with other nodes

- crates/common/src/lib.rs
- crates/common/src/receipt.rs
- crates/crypto/examples/consts_poseidon.rs
- crates/gateway-types/src/reply.rs
- crates/pathfinder/examples/feeder_gateway.rs
- crates/pathfinder/examples/re_execute.rs
- crates/pathfinder/examples/verify_block_hashes.rs
- crates/pathfinder/examples/verify_transaction_hashes.rs
- crates/pathfinder/src/p2p_network/sync_handlers.rs
- crates/pathfinder/src/p2p_network/sync_handlers/conv.rs
- crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
- crates/pathfinder/src/state/sync.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/pathfinder/methods/get_transaction_status.rs
- crates/rpc/src/v02/method/get_transaction_by_block_id_and_index.rs
- crates/rpc/src/v02/method/get_transaction_by_hash.rs
- crates/rpc/src/v05/method/get_transaction_status.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v05/method/trace_transaction.rs
- crates/rpc/src/v06/method/get_transaction_receipt.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/event.rs
- crates/storage/src/connection/transaction.rs
- crates/storage/src/fake.rs
- crates/storage/src/test_utils.rs
This PR replaces the remaining gateway types from the public storage connection API by replacing them with the common types. This impacts the transaction and receipts types.
This is an intermediete step to hiding the gateway dto types from the rest of the codebase. Especially the transaction types are fairly pervasive still. Most code relies on the gateway types so a lot of this PR involves casting from common to gateway type. Not optimal but follow-up work will hide more and more of the gateway type, forcing code to adapt to only common.
Storage crate uses the gateway dto as its storage schema. To remove this coupling I've copied the dto definitions over. There is already work scoped to rework the storage schema - not this PRs problem.
The storage crate still relies on the gateway types …
> refactor(storage): decouple from gateway types

- crates/gateway-client/src/lib.rs
- crates/gateway-client/tests/metrics.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/state/sync/pending.rs
- crates/rpc/src/gas_price.rs
Separates gateway queries for pending and full block data.
This simplifies the `MaybePendingBlock` deserialization by side-stepping the issue entirely.
Note that this PR does not actually remove the type - and indeed it is still actively relied on by some of the gateway methods. However these methods are only used in tests which should be replaced by tests for the actually-in-use methods.
I decided to not actually do this work in order to reduce the rebase breakage.
There is one exception to this - the gas price still uses the deprecated method, however I believe this file/function is no longer used? If it is, then this PR requires a bit more work to add a non-retry method alternative.
> feat(gateway): specialize pending block

- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v06.rs
- crates/rpc/src/v07.rs
- doc/rpc/v07/starknet_api_openrpc.json
- doc/rpc/v07/starknet_trace_api_openrpc.json
- doc/rpc/v07/starknet_write_api.json
Adds the basic configuration options for RPC v0.7.
Includes a "minor" fix - our v0.6 metrics were using `v0.5` as the version string..
Closes #1775
> feat(rpc/v0.7): configuration and skeleton

- crates/common/src/header.rs
- crates/p2p/src/client/peer_agnostic.rs
- crates/p2p/src/client/types.rs
- crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
- crates/pathfinder/src/sync/p2p.rs
- crates/pathfinder/src/sync/p2p/headers.rs
Caveat: `[class, storage]_commitment` is persisted as 0 for now.
We may choose to defer persisting the headers later or extract storage and class commitments from the headers table.
> feat(sync/p2p): adapt header sync to the latest p2p spec changes

- Cargo.lock
- crates/executor/src/lib.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/executor.rs
We're already exposing some types from blockifier (like the transaction type) on our executor API. This PR does the same for `CallInfo` and removes the direct dependency on blockifier from the RPC crate.
Closes #1783
> fix(rpc): remove direct dependency on `blockifier`

- crates/rpc/src/jsonrpc/websocket/logic.rs
Pathfinder treats WebSocket control frames (ping/pong/close) as data frames (text/binary). When it receives ping frames, it tries to parse non-data empty messages and outputs errors like these:
```
$ wscat -c ...
Connected (press CTRL+C to quit)
< {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request","data":{"reason":"EOF while parsing a value at line 1 column 0"}},"id":null}
< {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request","data":{"reason":"EOF while parsing a value at line 1 column 0"}},"id":null}
< {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request","data":{"reason":"EOF while parsing a value at line 1 column 0"}},"id":null}
>
```
> fix(rpc): handle WebSocket control frames

- Cargo.lock
- Cargo.toml
- crates/common/src/header.rs
- crates/compiler/Cargo.toml
- crates/executor/Cargo.toml
- crates/executor/resources/versioned_constants_13_0.json
- crates/executor/src/execution_state.rs
- crates/executor/src/lib.rs
- crates/pathfinder/Cargo.toml
- crates/rpc/src/executor.rs
- crates/rpc/src/test_setup.rs
- crates/rpc/src/v04/method/simulate_transactions.rs
- crates/rpc/src/v05/method/estimate_fee.rs
- crates/rpc/src/v05/method/estimate_message_fee.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v06/method/estimate_message_fee.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
This PR upgrades blockifier and the Cairo compiler to the most recent version.
This version of blockifier is adding support for VersionedConstants for Starknet 0.13.0, so the executor code was updated to use the constants appropriate for the Starknet version of the block we're doing execution on.
Some simulation tests for Starknet 0.13.0 had to be updated: even though fee estimates match, transaction traces now report resource use for syscalls too, thus causing differences in `execution_resources`.
A new test for testing Starknet 0.13.1 fee estimation & traces has been added to JSON-RPC 0.6 `starknet_simulateTransactions`.
Closes: #1769
> feat(rpc): upgrade blockifier to 0.5.0-rc.3

- crates/common/src/receipt.rs
- crates/pathfinder/src/p2p_network/sync_handlers/conv.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v06/method/get_transaction_receipt.rs
- crates/rpc/src/v07.rs
- crates/rpc/src/v07/dto.rs
- crates/rpc/src/v07/dto/header.rs
- crates/rpc/src/v07/dto/receipt.rs
- crates/rpc/src/v07/method.rs
- crates/rpc/src/v07/method/get_block_with_receipts.rs
Implements `starknet_getblockwithreceipts` for RPC v0.7.
This PR adds DTOs for all new and updated components (afaict) for RPC v0.7.0-rc1 + an additional upcoming fix that will become rc2.
This PR *does not* implement any other methods which need to be changed for v0.7 due to the type changes.
Closes #1774, closes #1771, closes #1772.
> feat(rpc/v0.7): `starknet_getBlockWithReceipts`

- crates/executor/src/estimate.rs
- crates/executor/src/execution_state.rs
- crates/executor/src/lib.rs
- crates/executor/src/simulate.rs
- crates/executor/src/types.rs
- crates/pathfinder/examples/re_execute.rs
- crates/rpc/src/test_setup.rs
- crates/rpc/src/v05/method/call.rs
- crates/rpc/src/v05/method/estimate_fee.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v06/method/estimate_message_fee.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
If the block has its `l1_da_mode` set to blob we now enable using it in the block context for blockifier.
Pre-v0.7 JSON-RPC estimate/simulate methods purpusefully disable this feature even if the block we're executing on has it enabled. This is because these methods do not return `data_gas_consumed` so `resource_bounds` would not be initialized properly based on that partial fee estimate.
Since we don't have JSON-RPC 0.7 methods using this feature I have only tested this feature using the `re_execute` tool on Sepolia integration.
Partially implements #1782
> feat(executor): enable L1 blob data availability mode for execution

- crates/rpc/src/lib.rs
- crates/rpc/src/v07.rs
- crates/rpc/src/v07/dto/receipt.rs
- crates/rpc/src/v07/method.rs
- crates/rpc/src/v07/method/get_block_with_tx_hashes.rs
- crates/rpc/src/v07/method/get_block_with_txs.rs
- crates/rpc/src/v07/method/get_transaction_receipt.rs
This PR adds RPC v0.7 implementations for 
- `starknet_getBlockWithTxs`
- `starknet_getBlockWithTxHashes`
- `starknet_getTransactionReceipt`
The implementations are largely just copied over from the v0.6 implementations, but with some additions to account for the new v0.7 DTOs.
This PR is light on tests - I thought these are simple enough, and covered by v0.6 tests and the DTO tests themselves. However, let me know if I should transfer the v0.6 tests over.
Closes #1801, closes #1802, closes #1803.
> feat(rpc/v0.7): add methods impacted by receipt DTOs

- .github/workflows/ci.yml
- .github/workflows/deploy_website.yml
- .github/workflows/docker.yml
- .github/workflows/msrv.yml
- .github/workflows/stark_hash_python.yml
Some of the actions we have are using the now deprecated Node 16 runtime: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> chore(github): upgrade GitHub actions

- crates/executor/src/execution_state.rs
Previously we did an optimization here: if we were using state from the end of a block then the state already had the system contract updates applied so we skipped looking up the block hash.
Now blockifier's `pre_process_block` requires that we always supply this value for blocks > 10, leading to errors with `starknet_call`, `starknet_estimateFee` and `starknet_simulateTransactions` for block height > 10.
> fix(executor): always provide old block number and hash to `pre_process_block()`

- CHANGELOG.md
- Cargo.lock
- crates/load-test/Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/examples/re_execute.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
Compared to mimalloc, jemalloc seems to have even better performance with the Cairo VM.
With the `v06_scripted_mainnet_without_huge_calls` scenario in load-test we seem to get ~23% better performance with jemalloc.
> feat(pathfinder): switch memory allocator to jemalloc

- crates/executor/src/simulate.rs
- crates/executor/src/types.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v06/method.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
- crates/rpc/src/v07.rs
- crates/rpc/src/v07/method.rs
- crates/rpc/src/v07/method/simulate_transactions.rs
- crates/rpc/src/v07/method/trace_block_transactions.rs
- crates/rpc/src/v07/method/trace_transaction.rs
This PR adds the `starknet_simulateTransactions`, `starknet_traceTransaction` and `starknet_traceBlockTransactions` JSON-RPC methods to our v07 API.
All methods are re-using the actual implementation from v06. New fields (`data_gas_consumed` and `data_gas_price` for fee estimates, top-level `execution_resources` for transaction traces) were added to v06 DTOs but the respective v06 method implementations clear these so that they don't get serialized into the response.
Closes #1806
Closes #1807 
Closes #1809
> feat(rpc/v0.7): add trace API methods

- build/prepare.sh
Building jemalloc now requires make.
> chore(Dockerfile): add `make` as a build dependency

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/pathfinder/src/bin/pathfinder/config.rs
This PR updates the changelog and bumps the crate version for v0.11.0 release. In addition, also changes the default RPC version to v0.6.
> feat: v0.11.0 preparation

- Cargo.toml
- justfile
flate2 1.0.28 built unoptimized is significantly slower than before an unsafe unsoundness was fixed. This unnecessarily slows down some of our tests which use `flate2` during test setup. (For more info please check https://github.com/rust-lang/flate2-rs/issues/395)
This PR makes sure that `flate2` is optimized even for a `dev` build.
In addition, `just test` now skips running the p2p proptests which take a long time to run. You can explicitly run those using `just proptest`.
> chore: make tests faster

- .github/workflows/docker.yml
So that we avoid a warning about the Node 20 upgrade: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> chore(github): upgrade docker/metadata-action

- CHANGELOG.md
- crates/common/src/lib.rs
- crates/common/src/transaction.rs
- crates/rpc/src/v02/types.rs
A recent refactor broke transaction hash calculation for BroadcastedTransaction instances with the query flag set in their version field.
The common `TransactionVariant` type cannot represent the "query only" flag so we were losing that bit of information when converting the broadcasted transaction type to perform hash calculation.
This change adds a `query_only` flag to the hash calculation itself, as that is the only place we should care about the value of this flag.
> fix(rpc): fix transaction hash calculation for query only transactions

- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/src/dto.rs
- crates/rpc/src/dto/serialize.rs
- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/middleware/cors.rs
- crates/rpc/src/pathfinder.rs
- crates/rpc/src/v04.rs
- crates/rpc/src/v05.rs
- crates/rpc/src/v06.rs
- crates/rpc/src/v07.rs
This PR adds a new serialization trait which is aware of the RPC version calling it.
This allows DTOs to adapt their serialization to each RPC version, making it much easier to implement and audit RPC specification updates.
This PR only adds the new framework, but doesn't implement it for any specific DTO. Existing methods and DTOs automatically use the new trait due to its blanket impl for `serde::Serialize`.
> feat(rpc): RPC version-aware serialization

- CHANGELOG.md
- crates/gateway-client/src/builder.rs
- crates/gateway-client/src/lib.rs
This PR removes the timeout from the RPC write transaction submissions to the gateway.
This is done in a somewhat clumsy fashion by adding a timeout to those methods and setting it to `MAX` to override the builtin timeout from the client.
Ideally we would refactor this to make all of these things much simpler again.
Unsure how to test this properly.
Fixes #1839
> fix(gateway): add transactions should not timeout

- CHANGELOG.md
- crates/rpc/src/v05/method/get_transaction_status.rs
`starknet_getTransactionStatus` does some incorrect error mapping, which this PR corrects.
1. Gateway's `NotReceived` status is incorrectly mapped to an internal error instead of `TxnNotFound`.
2. All gateway errors are incorrect mapped to `TxnNotFound`. These are now an internal error.
> fix(rpc): transaction status not found is an internal error

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder/main.rs
So that the SQLite DB is properly closed and we don't leave WAL and SHM files behind.
> fix(pathfinder): exit gracefully on INT/TERM signal

- crates/rpc/src/dto.rs
- crates/rpc/src/dto/primitives.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/method.rs
- crates/rpc/src/method/block_hash_and_number.rs
- crates/rpc/src/method/block_number.rs
- crates/rpc/src/method/chain_id.rs
- crates/rpc/src/method/syncing.rs
- crates/rpc/src/v07.rs
Implements some of the simpler RPC methods using the new trait.
Note that this explicly targets RPC v0.7-rc2 only. No backwards compatibility yet - let's fully support v0.7 and then we can work backwards. This let's us skip work for v0.4 and v0.5 if we manage to remove them before this work gets there.
------------------------
Particular review focus should be on the correctness of the DTO serialization ito inner types being used. i.e. ensure that if the spec says `BLOCK_HASH` is a `FELT` then the serialization implementation should use `serialize(&Felt(...))`. 
There isn't really a super easy way to enforce this apart from rigorous manual auditing when adding/updating DTOs.
------------------------
Adds DTO implementations for:
```
FELT
BLOCK_HASH
BLOCK_NUMBER
SYNC_STATUS
CHAIN_ID
``` …
> feat(rpc): trivial methods using new serialization trait

- doc/rpc/v07/starknet_api_openrpc.json
- doc/rpc/v07/starknet_trace_api_openrpc.json
- doc/rpc/v07/starknet_write_api.json
The current docs are from some older commit. These updated spec docs are required for auditing the RPC rework.
Files copied verbatim from the spec repo at the v0.7.0-rc2 tag.
> docs: update RPC spec to v0.7.0-rc2

- crates/pathfinder/src/bin/pathfinder/config.rs
When running bare `cargo clippy` the tool complains about the unit arg which is used when the `p2p` feature is disabled. As the CI runs clippy with all features the warning is not visible there.
This patch silences clippy's `unit_arg` lint but only of the `p2p` feature is enabled.
Short description of what this PR does.
There are no issues nor a changelog entry since this is a really minor change that would only be noticed by developers.
Thanks for your time! :wave:
> chore: Fix clippy warnings when running with no `p2p` feature enabled

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/state/sync/pending.rs
This PR separates pending producer from the L2 producer.
The pending producer task is now always running, but only emits pending data when local sync is within 6 blocks of the latest on chain block.
I've also create a separate task which exclusively tracks the gateways latest block ID. This feeds both the sync status and the L2 producer now, reducing the number of these calls we make.
I'm a bit unsure of these changes -- the code feels brittle.
Fixes #1864
> fix: sync restarts leave a zombie task behind

- Cargo.toml
Fix the daily MSRV CI workflow failures by bumping the MSRV.
No longer compiles on 1.74 (current MSRV) as we use `Result::inspect_err`.
> ci: bump package MSRV to 1.76

- Cargo.lock
- Cargo.toml
- crates/p2p/Cargo.toml
- crates/p2p/src/client/peer_agnostic.rs
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/sync/p2p.rs
- crates/pathfinder/src/sync/p2p/state_updates.rs
Use a separate stream for state update count data. I've experimented quite a bit but couldn't make any reasonable use of stream combinators from `StreamExt` or `TryStreamExt`, so I decided to just replace the getter with a stream.
Fixes #1856
> split contract updates stream

- Dockerfile
Now that we've bumped MSRV to 1.76 the Docker container would no longer build.
> fix(Dockerfile): upgrade Rust toolchain to 1.77

- crates/merkle-tree/src/class.rs
- crates/merkle-tree/src/contract.rs
- crates/merkle-tree/src/contract_state.rs
- crates/merkle-tree/src/merkle_node.rs
- crates/merkle-tree/src/transaction.rs
- crates/merkle-tree/src/tree.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/revert.rs
- crates/pathfinder/src/sync/p2p/state_updates.rs
- crates/rpc/src/lib.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/trie.rs
- justfile
As a requirement for Merkle trie pruning, this PR adds code for tracking the storage indices for trie nodes that have been removed during trie updates and fixes a node-reuse issue that prevents actually removing nodes from Merkle tries constructed by our previous implementation.
This PR does _not_ add the actual removal of these nodes from storage -- that will be left for a follow-up PR.
Rough list of changes:
- Merkle tree `InternalNode` now stores the storage index of the node if it was loaded from storage.
- `MerkleTree::commit()` now returns a `TrieUpdate` structure instead of the commitment and the new nodes. `TrieUpdate` contains the commitment, the nodes added and the storage ids for the nodes that have been removed during the update.
- Previously we were using a HashMap to return …
> feat(merkle-tree): track removed nodes

- crates/pathfinder/src/state/sync/revert.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/trie.rs
Trie roots can be NULL in the database (meaning an empty trie). If the trie at the revert target was empty (but present) we incorrectly tried to revert state.
> fix(pathfinder/state/revert): properly detect if trie roots are present

- CHANGELOG.md
- crates/executor/src/estimate.rs
- crates/executor/src/simulate.rs
- crates/executor/src/types.rs
- crates/rpc/src/v05/method/estimate_fee.rs
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v07/method/estimate_fee.rs
Blockifier has some minimum gas usage estimates and all transactions submitted for inclusion on the chain are expected to pay _at least_ the cost of those estimates.
When Pathfinder is doing fee estimations we're skipping the actual fee transfer costs -- while the minimum expected gas usage estimates do contain the storage updates resulting from the fee transfer.
This PR updates our code so that we don't return gas usage values that are _lower_ than the minimum values expected.
In particular, trivial version 0 invoke transactions were found to have an estimate that is too low.
Closes: #1901
> fix(executor): never return fee estimates lower than the minimal values expected by blockifier

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/compiler/Cargo.toml
- crates/executor/resources/versioned_constants_13_1.json
- crates/executor/src/execution_state.rs
- crates/pathfinder/Cargo.toml
- crates/rpc/src/v07/method/estimate_fee.rs
This PR upgrades blockifier to 0.6.0-rc.0 so that we support new declare transaction estimations in Starknet 0.13.1.1 and adds versioned constants for Starknet 0.13.1 so that we keep compatibility.
Closes #1888
> feat(executor): upgrade blockifier to 0.6.0-rc.0

- README.md
Remove links to Goerli snapshots as well as snapshots for old pathfinder 0.9 releases.
> chore: remove old snapshot links

- crates/merkle-tree/src/class.rs
- crates/merkle-tree/src/contract.rs
- crates/merkle-tree/src/contract_state.rs
- crates/merkle-tree/src/transaction.rs
- crates/merkle-tree/src/tree.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/revert.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/pathfinder/methods/get_proof.rs
- crates/storage/src/connection.rs
- crates/storage/src/connection/trie.rs
If the root node is unresolved then the Merkle tree has been created but no update operations have been made.
In this case the previous code caused `commit()` to always re-create the root node so that opening a tree, then committing without changes added a new root node. This change makes sure we return the current root commitment  in that case instead.
Tree root updates also have to be done correctly. An unchanged root index should _not_ be inserted into storage, while in case the tree has became empty as a result of an update a NULL shall be recorded as a root index.
This change simplifies handling of these cases: `insert_XXX_trie()` now returns a `RootIndexUpdate` type that explicitly represents the three different cases. `insert_XXX_root()` takes that update value directly as its …
> fix(merke-tree): don't re-create tree root node when committing

- crates/pathfinder/examples/test_state_rollback.rs
- crates/pathfinder/src/state/sync/revert.rs
- crates/storage/src/connection/block.rs
- crates/storage/src/connection/trie.rs
- crates/storage/src/schema/revision_0055.rs
During a reorg we check if the target block still has a state trie available. If it's out of the region we're keeping state trie data for we re-compute the state by applying a reverse-diff to the latest state.
Handling of delayed removal of trie data is more complicated: we have to account for removed trie nodes separately.
In general, removing the trie nodes deleted at block N is only safe if we don't ever need to access trie state at block < N. This is not necessarily the case during a reorg: if our reorg/revert target is still in the range of blocks we're keeping trie history for then removing deleted nodes for the reorged-away blocks would break the trie for the blocks _before_ the reorg target. Instead, we move all the removed nodes in the reorged-away range to be "owned" by the …
> Fix reorg with state pruning enabled

- .github/workflows/ci.yml
- .github/workflows/stark_hash_python.yml
To avoid using the now deprecated Node 16 runtime: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> chore(github): upgrade some more actions

- .github/workflows/ci.yml
- crates/load-test/Cargo.lock
- crates/load-test/src/main.rs
- crates/load-test/src/requests/v05.rs
- crates/load-test/src/tasks/scripted.rs
- crates/load-test/src/tasks/v05.rs
- crates/load-test/src/types.rs
This PR does some chores, like updating the lockfile and reformatting with the new rustfmt config, then updates the `starknet_getEvents` scenario to be more realistic (querying ETH token transfer events).
> chore(load-test): update `starknet_getEvent` scenario

- crates/common/src/lib.rs
- crates/common/src/signature.rs
- crates/crypto/src/signature/mod.rs
- crates/gateway-client/src/builder.rs
- crates/gateway-client/src/lib.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
This change adds a verification step to L2 sync for block commitment signatures downloaded from the feeder gateway.
Upon startup pathfinder fetches the public key from the gateway. During sync downloaded block commitment signatures are verified to make sure that the data we add to our database is consistent.
Closes: #1374
> feat(pathfinder): verify block commitment signatures

- crates/p2p/src/client/conv.rs
- crates/p2p/src/client/peer_agnostic.rs
- crates/pathfinder/src/sync.rs
- crates/pathfinder/src/sync/error.rs
- crates/pathfinder/src/sync/events.rs
- crates/pathfinder/src/sync/headers.rs
- crates/pathfinder/src/sync/stream.rs
- crates/pathfinder/src/sync/track.rs
This PR introduces `ProcessStage` abstraction and uses it to implement a basic p2p tracking skeleton. This implementation is clumsy in certain places, but should suffice for now.
`SyncResult<T>` is an alias for `Result<PeerData<T>, PeerData<SyncError>>`. This is a bit clumsy, but I think its ok for now.
`SyncReceiver` is a wrapper around a tokio channel receiver. This was originally a stream extension trait but this proved unwieldy ito generics and bounds. This type acts like a pipeline, allowing you to process data concurrently in a pipeline of `ProcessStage`s. Important is that errors are fowarded and short circuit. This means that the entire pipeline will end its stages as the error progresses through until it can be handled at the end.
`ProcessStage` is a trait which simplifies …
> feat(sync): initial p2p tracking implementation

- CHANGELOG.md
- crates/rpc/src/v07/method/get_block_with_tx_hashes.rs
- crates/rpc/src/v07/method/get_block_with_txs.rs
According to the JSON-RPC specification the pending block has no `status` property. This has been the case for all supported JSON-RPC versions.
Since we've pretty much forever have served this extra property we only fix this for the latest JSON-RPC 0.7 API endpoint.
Closes #1974
> fix(rpc/v07): remove `status` property from pending block responses

- crates/merkle-tree/src/lib.rs
Make storage mod public in the MerkleTree trait
I want to use the MerkleTree crate in an external project. Currently, this is not possible, as the Storage trait is not accessible.
> chore: make MerkleTree::storage mod public

- crates/pathfinder/src/state/sync/l2.rs
Since we've found at least one instance (mainnet block 94) where the state diff commitment we're calculating doesn't match the one returned by the feeder gateway we should demote the error to a warning for now.
> fix(pathfinder/sync/l2): make block commitment signature mismatches a warning

- crates/crypto/src/algebra/field/montfelt/multiplicative.rs
In very unique scenario's the carry handling of the current CIOS multiplication overflows.
This PR reverts it back to SOS algorithm until proper analysis/handling.
> (fix) montfelt cios revert

- crates/common/src/receipt.rs
- crates/gateway-types/src/reply.rs
- crates/p2p/src/client/conv.rs
- crates/pathfinder/src/p2p_network/sync_handlers/conv.rs
- crates/rpc/src/dto/receipt.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v04/method/get_transaction_receipt.rs
- crates/rpc/src/v06/method/get_transaction_receipt.rs
- crates/storage/src/connection/transaction.rs
- crates/storage/src/schema/revision_0052.rs
- crates/storage/src/schema/revision_0057.rs
Our internal representation of an L1 message's `to_address` field is incorrect.
Though this is meant to represent an Ethereum address, starknet accepts any Felt. This fixes our representation of this type to match this expectation.
Unfortunately, the p2p specification also has this typed (incorrectly) as an Ethereum address. Until then we have a "lossy" conversion there still.
Another concern is that this touches migrations - but I *think* this doesn't actually change anything there.
> fix: message to L1's to_address should be Felt

- crates/rpc/src/jsonrpc.rs
- crates/rpc/src/jsonrpc/request.rs
- crates/rpc/src/jsonrpc/response.rs
- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/jsonrpc/websocket/data.rs
- crates/rpc/src/jsonrpc/websocket/logic.rs
- crates/rpc/src/lib.rs
This PR exposes the "normal" JSON-RPC methods over a set of versioned WebSocket endpoints. In addition to the `/ws` endpoint (exposing the default JSON-RPC version) this change adds `/ws/rpc/v0_6` and `/ws/rpc/v0_7` for the 0.6 and 0.7 JSON-RPC API.
The implementation is sub-optimal: because the `pathfinder_subscribe` and `pathfinder_unsubscribe` require per-connection context (for the subscription management) these two are not handled as all other methods but are left as special cases in the Websocket code.
Closes #2001.
> feat(rpc/websocket): expose "normal" JSON-RPC methods over Websockets

- crates/storage/src/connection/transaction.rs
- crates/storage/src/fake.rs
- crates/storage/src/schema/revision_0052.rs
- crates/storage/src/schema/revision_0057.rs
This PR fixes storage which was broken by me in #2011.
#2011 forced a change of `H160` to `MinimalFelt` which are incompatible ito schema (`[u8; 20]` vs `Vec<u8>`). This PR reverts the damage and then introduces a new schema variant which correctly allows for this.
i.e. we now have `v0 = [u8; 20]` and `v1 = Vec<u8>`.
The reversion was done by reverting the storage file changes from #2011 entirely and then fixing up from there.
No migration required as the "schema" change is entirely encapsulated as a blob.
> fix: broken storage from changes to to_address

- crates/common/src/state_update.rs
- crates/pathfinder/src/sync/class_definitions.rs
- crates/pathfinder/src/sync/state_updates.rs
- crates/pathfinder/src/sync/track.rs
- crates/pathfinder/src/sync/transactions.rs
This PR fleshes out the tracking pipeline skeleton.
Sources and pipelines for state updates, transactions and classes are added. State trie updates are not implemented yet as it is not critical for the initial p2p mvp.
Types are not 100% correct as it might change as they are implemented. This should give a solid starting place though.
> feat(sync): tracking outline skeleton

- crates/common/src/transaction.rs
- crates/crypto/src/algebra/field/felt.rs
- crates/gateway-types/src/reply.rs
- crates/p2p/src/client/conv.rs
- crates/pathfinder/src/p2p_network/sync_handlers/conv.rs
- crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/sync/checkpoint.rs
- crates/rpc/src/dto/receipt.rs
- crates/rpc/src/executor.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v04/method/get_transaction_receipt.rs
- crates/rpc/src/v04/method/pending_transactions.rs
- crates/rpc/src/v04/types/transaction.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/get_transaction_receipt.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/types/transaction.rs
- crates/rpc/src/v07/dto/receipt.rs
- crates/storage/src/connection/transaction.rs
- crates/storage/src/fake.rs
- crates/storage/src/schema/revision_0052.rs
- crates/storage/src/schema/revision_0057.rs
- crates/storage/src/test_utils.rs
The only possible versions for deploy transactions are 0 and 1, so we can split `TransactionVariant::Deploy` into a V0 and a V1 variant and remove the `version` field.
Closes #1723
> feat(common/transaction): split TransactionVariant::Deploy into V0 and V1

- Cargo.lock
- crates/p2p/Cargo.toml
- crates/p2p/src/client/conv.rs
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/p2p_network.rs
- crates/pathfinder/src/p2p_network/sync_handlers.rs
- crates/pathfinder/src/p2p_network/sync_handlers/conv.rs
The protocol expects the program of Cairo 0 classes to be represented as a Base64-encoded, gzip compressed JSON.
In addition to fixing that the PR also adds some tracing events/spans to sync handlers and a fix for logging errors.
> fix(p2p): send compressed program for Cairo 0 classes

- crates/pathfinder/examples/verify_block_hashes.rs
The tool defaulted the Starknet version for each block instead of using the version right from the header.
> fix(examples/verify_block_hashes): use the correct Starknet version

- crates/p2p/src/client/conv.rs
- crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
- crates/storage/src/connection/transaction.rs
The `contract_address` field needs to be computed based on the constructor calldata, contract address salt and class hash of the transaction.
> fix(p2p/client/conv): fix Deploy/DeployAccount conversion

- Cargo.lock
So that pathfinder builds with current nightly Rust.
> chore(Cargo.lock): upgrade time and curve25519-dalek

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/lib.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/sync.rs
- crates/pathfinder/src/sync/class_definitions.rs
- crates/pathfinder/src/sync/transactions.rs
This change makes _most_ of our code implementing P2P compile even without the "p2p" feature enabled and starts the P2P sync client instead of gateway sync if "p2p" is enabled unless the `p2p.proxy` CLI argument is enabled.
The actual enablement of P2P and related config options are still gated by the "p2p" feature so our release builds will still not contain any P2P functionality -- but conditional compilation is done only in the "pathfinder" crate.
(Note that the P2P sync client is not really functional yet without further fixes.)
> feat(pathfinder): enable P2P sync client

- Cargo.lock
- crates/pathfinder/src/sync/class_definitions.rs
- crates/pathfinder/src/sync/events.rs
- crates/pathfinder/src/sync/headers.rs
- crates/pathfinder/src/sync/state_updates.rs
- crates/pathfinder/src/sync/stream.rs
- crates/pathfinder/src/sync/track.rs
- crates/pathfinder/src/sync/transactions.rs
This PR adds tracing to the P2P sync stages.
Example trace looks something like this
```
DEBUG stage=Headers::Verify, input_queue=50%, (50/100), throughput=1234, Item processed
```
It displays the assigned stage name, the input queue fullness (both in percentage and actual amount) and the instantaneous throughput this iteration was processed at.
Things I'm on the fence about
- `throughput` is a misleading term here, but dunno what else to use
- the stage name could instead be `spans` which might be more appropriate?
- `Item processed` is quite generic and pointless
Its also unclear to me which metrics would be useful here. Probably both queue fullness and throughput would be something we want to measure. However, for metrics the consumer can also compute the averages if they want.
Also …
> feat(p2p): tracing for sync stages

- crates/p2p_stream/src/lib.rs
10 seconds is not enough for streaming/processing all responses of a request for all transactions or classes of a 100 block range.
Currently there's a single timeout for the whole duration of the subchannel: that is the whole request/response stream has to be completed before timing out. Ideally we'd be implementing a different kind of timeout for the request-response protocol: one that only times out if no request is received or responses are received for some time.
> fix(p2p_stream): change default request timeout

- crates/pathfinder/examples/recompute_state_diff_length.rs
This tool fixes inconsistencies in state diff lengths we store for headers. It recomputes the state diff length based on the actual state diff we return based on our data and updates the value in the headers table in case it does not match.
> feat(pathfinder/examples): add `recompute_state_diff_length` tool

- crates/p2p/src/client/peer_agnostic.rs
- crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
- crates/pathfinder/src/sync/checkpoint.rs
- crates/pathfinder/src/sync/headers.rs
- crates/pathfinder/src/sync/stream.rs
- crates/pathfinder/src/sync/track.rs
- crates/pathfinder/src/sync/transactions.rs
- crates/storage/src/connection/block.rs
Title :arrow_up: 
One major flow change:
- commitment verification does not require db reads because the expected commitment is streamed along expected transaction count
> refactor transaction checkpoint sync to use the stages framework

- crates/storage/src/connection/block.rs
We now have that as part of the header row. Plus, the old code fails if the parent block is not in the DB yet (possible during P2P header sync).
> fix(storage/block): remove code fetching parent block hash from parent block

- crates/p2p/src/client/peer_agnostic.rs
- crates/pathfinder/src/sync/checkpoint.rs
- crates/pathfinder/src/sync/headers.rs
- crates/pathfinder/src/sync/stream.rs
- crates/storage/src/connection/block.rs
This PR fixes a few unrelated issues in header sync:
- finding the next gap to be synced
- stop condition for the sync
- start/stop point of the actual sync
It also temporarily disables signature verification as the signatures produced by the feeder gateway are invalid for some state diffs we produce due to feeder gateway bugs.
This is probably the easiest to review commit-by-commit.
> fix(pathfinder/sync/headers): fix header sync

- crates/p2p/src/client/peer_agnostic.rs
- crates/pathfinder/src/sync/class_definitions.rs
- crates/pathfinder/src/sync/state_updates.rs
- crates/pathfinder/src/sync/transactions.rs
- crates/storage/src/connection/block.rs
- crates/storage/src/connection/state_update.rs
This PR fixes a few unrelated issues in transaction sync:
- queries returning counts from the block header now return data in-order in a VecDeque
- "counts" streams now pop the next element off of the front of the queue
- "counts" streams now properly yield all elements from the last chunk
- SQL query for transaction counts / commitments contained a syntax error
- `peer_agnostic::Client::transaction_stream()` should handle FIN as the stream termination, not as a block separator
> fix(pathfinder/sync/transactions): fix transaction sync

- crates/common/src/state_update.rs
- crates/p2p/src/client/peer_agnostic.rs
- crates/pathfinder/src/sync/state_updates.rs
- crates/storage/src/connection/state_update.rs
This PR fixes a few unrelated issues in state update sync:
- querying the highest block with a state update should check nonces and class definitions in addition to storage updates
- counting declared classes for a block cannot use `definition` for the counting because unsynced classes have their definition set to NULL
- fix finding the start of the state update gap: now handles the case where there are no updates at all
- `peer_agnostic::Client::state_diff_stream()` should handle FIN as the stream terminator, not as a block delimiter
> fix(pathfinder/sync/state_updates): fix state update sync

- crates/p2p/src/client/peer_agnostic.rs
- crates/pathfinder/src/sync/class_definitions.rs
- crates/storage/src/connection/block.rs
This PR fixes a few unrelated issues in class definition sync:
- finding class definition gap: there was an error in the SQL query and an off-by-one in `next_missing()`
- `verify_declared_at()` did not properly go on to the next block after processing all declared classes
- `peer_agnostic::Client::class_definitions_stream()` now handles FIN as the terminator of the response stream
- `peer_agnostic::Client::class_definitions_stream()` did not handle class definition counts of zero (that is, blocks that did not declare classes)
> fix(pathfinder/sync/class_definitions): fix class definitions sync

- crates/p2p/src/client/peer_agnostic.rs
- crates/pathfinder/src/sync/events.rs
- crates/storage/src/connection/block.rs
- crates/storage/src/connection/event.rs
- crates/storage/src/connection/transaction.rs
This PR fixes a few issues in checkpoint events sync:
- Fix ordering of per-block event counts in the event counts stream.
- The event counts stream no longer loses the last chunk of counts.
- The per-block Bloom filters are now properly updated when inserting events, also fixing the function finding the next gap to be synced.
- peer_agnostic::Client::events_stream() now handles FIN as the terminator of the response stream
> fix(pathfinder/sync/events): fix events sync

- Cargo.lock
This version has the fix for the missed EOF issue triggered by Golang peers. (https://github.com/libp2p/rust-yamux/issues/189)
> chore(Cargo.lock): upgrade `yamux` to 0.13.3

- CHANGELOG.md
- crates/rpc/src/dto/receipt.rs
There were two problems in the new DTO serialization code:
- L1 handler receipts were not serialized and instead just threw an internal error
- `execution_status` / `revert_reason` was missing from common receipt properties.
Closes #2085 
Closes #2086
> fix(rpc/dto): fix JSON-RPC receipt response serialization

- crates/rpc/src/dto/receipt.rs
> fix(rpc/dto/receipt): add missing `payload` property to MSG_TO_L1

- CHANGELOG.md
- crates/executor/src/types.rs
When converting a blockifier `CallInfo` to a FUNCTION_INVOCATION we must _not_ process all messages from inner calls recursively. Doing so results in duplicating all messages from inner calls on the outer level, leading to an inconsistency with the output from the feeder gateway.
Easy to reproduce with Sepolia testnet transaction 0x04faf2a913828ab965de32bf3004ce183e035e92ddbf9517772c5beaa4edb216 where the message is emitted by an inner call and not the top-level contract.
Closes #2094
> fix(executor): don't duplicate messages from internal calls

- .github/workflows/release.yml
- CHANGELOG.md
This PR adds a workflow that automatically creates a draft release and builds and uploads a set of pathfinder binaries (for various architectures) upon pushing a release tag to the repository.
With the recent changes that enable building P2P crates some of our users are facing issues building pathfinder: our dependency on a recent version of `protoc` is causing problems for users trying to build on old Linux distributions.
Uploading "official" release binaries can help these users get pathfinder up-and-running without requiring the use of the Docker image.
> feat(ci): add release workflow

- crates/crypto/benches/bench.rs
Benchmark failed inside arkworks [as seen in this job](https://github.com/eqlabs/pathfinder/actions/runs/9648301093/job/26609133075).
This PR makes sure to only benchmark valid representations, that is most likely the cause of this.
> fix(crypto-bench) ensure valid representations

- crates/p2p/src/main_loop.rs
- crates/pathfinder/src/sync/checkpoint.rs
- crates/pathfinder/src/sync/stream.rs
We're not yet updating the state tries, so rolling back just means we have to remove data block-by-block until we reach the anchor.
This PR also fixes some trace/panic messages and moves stream processing logs to the `trace` level to avoid making debug logs unreadable.
> feat(pathfinder/sync/checkpoint): add rollback_to_anchor implementation to checkpoint sync

- CHANGELOG.md
- crates/pathfinder/examples/feeder_gateway.rs
- crates/storage/src/connection/trie.rs
When inserting a new trie root (or contract state hash) we were first pruning the old values (so that data that is out of the number-of-blocks-kept window is removed). The pruning functions make sure that there's at least one value kept at or before the first block of the availability window.
This was working correctly for non-zero number-of-blocks-kept values, but was causing missed removals for the no-history case. When number-of-block-kept is zero we were keeping the _previous_ value (root / state hash) in addition to the new value we were being inserting. This lead to missing a required revert operation upon a one-block reorg because the global storage root index was still in place for the target block.
This change fixes this by reordering insertion of the new node and pruning. This …
> fix(storage/trie): fix reorg failure for no-history pruning mode

- CHANGELOG.md
- crates/rpc/src/dto/receipt.rs
This is technically breaking the JSON-RPC 0.7.0 specification, but it turns out that there are mainnet transactions for which `n_steps` is zero in the receipt: 0x04026b1598e5915737d439e8b8493cce9e47a5a334948e28f55c391bc2e0c2e2. Returning 0 here risks SDKs doing proper validation rejecting the response anyway -- but even in that case the result is not worse than it is now.
Before this fix querying the receipt for the transaction above lead to an internal error but just returning zero might be more sensible until we get the specification fixed.
Closes #2117
> fix(rpc/dto/receipt): allow `steps` to be zero in COMPUTATION_RESOURCES

- crates/p2p/src/behaviour.rs
- crates/p2p/src/client/peer_agnostic.rs
- crates/p2p/src/client/peer_aware.rs
- crates/p2p/src/lib.rs
- crates/p2p/src/main_loop.rs
Fixes: #2119 
Random peers are obtained by querying for closest peer to a random peerId (essentially a random key).
> feat: use random peers instead of querying for capabilities

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/main.rs
To make it easier to start up pathfinder with a new database we now create a new directory if the database path specified does not exist.
Closes: #2126
> feat(pathfinder): create database directory if it does not exist

- CHANGELOG.md
- crates/executor/src/call.rs
- crates/executor/src/estimate.rs
- crates/executor/src/execution_state.rs
- crates/executor/src/lib.rs
- crates/executor/src/simulate.rs
- crates/pathfinder/Cargo.toml
- crates/pathfinder/examples/re_execute.rs
- crates/pathfinder/resources/invalid_versioned_constants.json
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/src/context.rs
- crates/rpc/src/v04/method/simulate_transactions.rs
- crates/rpc/src/v05/method/call.rs
- crates/rpc/src/v05/method/estimate_fee.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v05/method/trace_transaction.rs
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v06/method/estimate_message_fee.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
This allows loading a custom versioned constants JSON to use instead of the latest version (0.13.2 currently) of constants built into blockifier.
Closes: #2127
> feat: add `--rpc.custom-versioned-constants-json-path` CLI option

- crates/pathfinder/src/bin/pathfinder/config.rs
`p2p.experimental.l1-checkpoint-override` becomes
`p2p.experimental.l1-checkpoint-override-json-path`
> chore: rename cli option

- CHANGELOG.md
- crates/executor/src/simulate.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/src/v04/method/simulate_transactions.rs
- crates/rpc/src/v05/method/estimate_fee.rs
- crates/rpc/src/v05/method/simulate_transactions.rs
- crates/rpc/src/v05/method/trace_block_transactions.rs
- crates/rpc/src/v05/method/trace_transaction.rs
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
- crates/storage/src/lib.rs
Pathfinder has the `rpc.execution-concurrency` CLI option that is supposed to set the upper limit for the number of execution-related RPC methods being served in parallel. This option works by creating a new storage instance that is supposed to be used for execution and setting the connection pool size to the number configured.
Unfortunately we did not use the correct storage instance for execution-related methods, so the CLI option was not actually effective.
This PR fixes these method implementations to use the execution storage instance, plus it also forces both the RPC and execution storage to use read-only database connections.
> fix(rpc): use execution storage for execution-related RPC methods

- CHANGELOG.md
- crates/rpc/src/dto/class.rs
The `type` property of this object was `event` instead of `struct`.
Closes #2137
> fix(rpc): fix serialization of `STRUCT_ABI_ENTRY`

- CHANGELOG.md
- crates/rpc/src/dto/state_update.rs
The contract address was being incorrectly serialized as `address` instead of `contract_address`
Closes #2139
> fix(rpc): fix serialization of `replaced_classes`

- Cargo.lock
This fixes some Dependabot warnings.
> chore: upgrade `openssl` and `curve25519-dalek` dependencies

- Cargo.lock
PR #2144 has accidentally upgraded the compiler version in our lock file -- this PR just reverts to the previous state.
> fix(cargo): revert cairo-lang upgrade

- .github/workflows/ci.yml
This PR makes three modifications that result in slight improvements in the `test` job:
- Removes `--build-jobs 1` from the compilation command: the runner we're running this on has 2 CPUs. We did limit this because occasionally we were running out of memory. According to my tests this is not a problem with the deps / compiler we are using now.
- Changes configuration of the `maximize-build-space` action: removing Docker container images seems to take really long (~2 minutes) and it seems that we do not actually need the ~20GB extra space removing unnecessary software and Docker images brings us.
- We have nightly scheduled jobs that test a full compilation (cleans build artifacts before the build). We now store the resulting build artifacts in the Rust build cache for scheduled jobs.
> chore(ci): speed up `test` job

- CHANGELOG.md
- README.md
- crates/rpc/src/lib.rs
This PR adds an HTTP endpoint that conforms with the URL convention (`v0_x`) used elsewhere.
Closes #1866
> pathfinder RPC extension endpoint should follow convention

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
This defaulted to the L2 poll interval, which is 2s right now. This is completely unjustified and just results in us polling L1 with a much higher rate than expected.
This change adds the `--sync.l1-poll-interval` CLI option that defaults to 30s.
> feat(pathfinder): add CLI option for setting L1 poll interval

- Cargo.lock
- crates/p2p/Cargo.toml
- crates/p2p/src/client/peer_agnostic.rs
- crates/p2p/src/client/peer_agnostic/tests.rs
- crates/p2p/src/client/peer_agnostic/traits.rs
- crates/p2p/src/main_loop.rs
- crates/pathfinder/src/sync/checkpoint.rs
This PR:
- fixes #2148 
- fixes #2101
- fixes p2p outbound failure handling in the main loop
- improves readability of p2p stream methods at the expense of more smaller fns
> followup for PR #2136

- crates/gateway-client/Cargo.toml
- crates/gateway-client/src/builder.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
TL;DR: timeouts are not logged clearly enough, which can be misleading
--------
1. When fetching a really large block [(sepolia/99902, ~2000txns)](https://alpha-sepolia.starknet.io/feeder_gateway/get_state_update?blockNumber=99902&includeBlock=true) my local pathfinder instance just hanged. It turned out that I was getting a [decode error](https://docs.rs/reqwest/latest/src/reqwest/error.rs.html#191):
"Request failed, retrying _reason_=error decoding response body"
2. But The core reason for this error was that the reply was timing out mid-way, so there was no way decode could succeed. However the problem in the log was that we logged the `Display` impl of  `reqwest::Error` which does not take the real __source__ into account (`TimedOut`), but only the outer kind of the error …
> feat(gateway-client): improve logging upon timeout

- crates/pathfinder/examples/compute_pre0132_hashes.rs
- crates/pathfinder/src/state/block_hash.rs
Introduces a simple tool meant for internal use which:
1. Computes block hashes in v0.13.2 style for all blocks previous to v0.13.2.
2. Stores these hashes in a CSV file with the format: `block_number,block_hash`
See also: #2079
> chore: add pre-0.13.2 block hash computing tool

- CHANGELOG.md
- crates/rpc/src/method/get_events.rs
- crates/rpc/src/v03/method/get_events.rs
We do check the continuation token before appending pending events to the result set. However, the check was too strict: in case of an extract block number match we used the offset from the token and we returned an error in all other cases.
Unfortunately this breaks in the completely valid case where a continuation token was in the request pointing to the non-pending block but the page was not full with results from the database yet so we go on appending events from the pending block.
This change fixes the check: if the block number in the token is _before_ the pending block we simply start from offset 0 instead of returning an error.
Closes: #2191
> fix(rpc): fix continuation token checking for pending events

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/class.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/state/sync/pending.rs
Just like we do checkpoint sync as a first step of a P2P sync this change implements a special "bulk" sync mode for feeder gateway sync.
In bulk mode we do _not_ expect reorgs to happen so the fetch logic is way simpler. We also concurrently fetch and verify data for multiple blocks at once, improving fetching throughput even if latency is high.
Block fetching _and verification_ now happens in individual futures of a buffered stream. The level of buffering determines the level of concurrency we're doing with fetching. To avoid deadlocks all events are emitted in the consumer of the stream.
Initial measurements are very promising: together with the Pedersen hash improvements we can now sync the first 80k blocks of the Sepolia testnet in ~1h 30s.
> feat(pathfinder/sync/l2): add a bulk fetch mode to feeder gateway sync

- crates/pathfinder/src/state/sync/l2.rs
Depends on: #2175 
This PR swaps `buffered` for `buffer_unordered` in the bulk sync logic increasing sync speed a bit more. A coarse test on mainnet in the range `65351..68251` shows a roughly 18% speed up (4625s vs 3810s). The test was done by running the previous ("ordered") and the new ("unordered") impls in parallel with the assumptions that:
- the OS is pretty fair wrt resource allocation,
- the qos of my internet connection should be the same for both processes during the test and this is hard to do otherwise (my internet connection is 4G and the qos can vary over time).
Downloaded blocks are cached in an ordered map which acts as a queue that allows for easy detection of a contiguous range of blocks at its head. This range at the head of the queue is then emitted to the rest of the …
> unordered block fetching in fgw sync

- CHANGELOG.md
- crates/gateway-client/Cargo.toml
- crates/gateway-client/src/builder.rs
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
- crates/rpc/src/method/get_events.rs
- crates/rpc/src/v03/method/get_events.rs
This PR backports bugfixes and some improvements from `main` to 0.14.2:
- increasing the L1 poll interval from 2s to 30s and adding a CLI option for the poll interval
- JSON-RPC `starknet_getEvents` bugfixes
- improved logging if a feeder gateway request times out
> chore: backport some fixes to 0.14.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/load-test/Cargo.lock
- crates/pathfinder/src/bin/pathfinder/main.rs
Also reverts a "fix" that we don't need.
> chore: bump version number to 0.14.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/compiler/Cargo.toml
- crates/executor/resources/versioned_constants_13_2.json
- crates/executor/src/execution_state.rs
- crates/load-test/Cargo.lock
- crates/rpc/src/method/estimate_fee.rs
There are two distinct changes that were made on 0.14.2 that need to be merged:
- The blockifier upgrade (containing Starknet 0.13.2.1 constants).
- Version bump and CHANGELOG.
> chore: merge 0.14.2 release into `main`

- Cargo.lock
- Cargo.toml
- build/cargo-build.sh
- build/cargo-chef-cook.sh
- build/prepare.sh
Currently we're using `native-tls` which is a bit problematic on Linux. Build time we're linking to the version of OpenSSL that is available on the build host.
For example, Ubuntu 20.04 uses OpenSSL 1.1 so that the release binaries we're building now are linked to that version of the library. That binary won't work on Ubuntu 22.04 (and up) since those versions use OpenSSL 3.0.
This change switches `reqwest` to use `rustls` instead (with native certs, meaning we're still using the same certificate store as OpenSSL). This way we're no longer linking to OpenSSL and so our release binaries will be more portable.
> feat: use rustls instead of native-tls

- crates/rpc/src/method/estimate_fee.rs
Broke `main` because I merged without rebasing.
> fix(rpc): should have rebased

- crates/p2p/src/main_loop.rs
- crates/pathfinder/src/sync/checkpoint.rs
- crates/pathfinder/src/sync/stream.rs
This PR
- Moves queue stats logging to trace level.
- Fixes a log message in transaction sync.
- Makes sure we log _every_ swarm event in full detail on trace level.
> chore(p2p): change/add some logs

- crates/p2p/src/client/peer_agnostic.rs
Some nodes (like Juno) do not limit how many responses they return for a sync query. Since Pathfinder requests the whole gap (possibly hundreds of thousands of blocks) by default this leads to a sync request that then times out (because we currently have a "global" timeout on the sync protocol streams).
This change makes sure that we never request more than 500 blocks worth of data at once.
Closes #2121
> fix(p2p/client/peer_agnostic): limit sync request block ranges

- crates/p2p/src/client/conv.rs
- crates/p2p_proto/src/receipt.rs
Juno does not send gas costs for old transactions so we should make these optional and default these to zero.
The feeder gateway does _not_ return these values either, so making these optional is a sane choice I think.
> fix(p2p_proto/receipt): make gas consumption data optional

- crates/p2p/src/client/conv.rs
- crates/p2p_proto/proto/common.proto
- crates/p2p_proto/proto/receipt.proto
- crates/p2p_proto/src/common.rs
- crates/p2p_proto/src/receipt.rs
L1 message hashes are Keccak256 output, but since we parse the `Hash` message contents as felts there are some hash values that cause a parse error (felt out of range). 
This change introduces a `Hash256` type to describe fields which represent 256 bit hash values (like the output of Keccak256) and changes the L1 transaction receipt to use that for the message hash.
P2P protocol specification change: https://github.com/starknet-io/starknet-p2p-specs/pull/46
> fix(p2p_proto/receipt): L1->L2 message hashes are 256 bit hashes

- crates/pathfinder/src/sync/checkpoint.rs
- crates/pathfinder/src/sync/class_definitions.rs
- crates/pathfinder/src/sync/events.rs
- crates/pathfinder/src/sync/headers.rs
- crates/pathfinder/src/sync/state_updates.rs
- crates/pathfinder/src/sync/track.rs
- crates/pathfinder/src/sync/transactions.rs
In case one of the pipe stages fails we should print a log message with all information we have in addition to returning an error.
This PR also moves some of the logs from INFO level to DEBUG so that we don't do per-message-received log lines when running with the default log level.
> chore(pathfinder/sync): add logging for P2P stage failures

- CHANGELOG.md
- crates/merkle-tree/src/contract_state.rs
- crates/pathfinder/src/state/sync/revert.rs
- crates/storage/src/connection/trie.rs
When reverting Merkle tries to a previous state we have been checking if we still have the tree root for the revert target. This seems like a good idea, because if we _still_ have the trie(s) for the target block then why bother applying reverse state updates from the current state?
It turns out that's not so simple. First, trie nodes added in blocks that are being deleted (right after the revert when pruning the block range that has been reorged away) will be permanently leaked. There's no way around that because we do not keep track of per-block trie node _additions_, only _removals_.
Second -- and this is _much_ more problematic -- the way we were handling trie removals data was just plain wrong. When reverting trie state to block N we've just moved removals data for all blocks > N …
> fix(pathfinder/state/revert): fix potential reorg Merkle trie corruption

- crates/pathfinder/src/state/sync/l2.rs
Otherwise there's an edge case where we're getting into a loop of continuing to try and fetch blocks even though we're getting "block not found" errors from the feeder gateway.
We _might_ just lose some data we've fetched and verified but overall not having this optimization feels safer.
> fix(pathfinder/state/sync): bulk sync should exit right after first error

- crates/p2p/src/behaviour/builder.rs
- crates/p2p/src/builder.rs
- crates/p2p/src/lib.rs
- crates/p2p/src/main_loop.rs
- crates/p2p/src/test_utils/peer.rs
- crates/p2p/src/tests.rs
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
> feat: use libp2p::kad internal bootstrap trigger

- CHANGELOG.md
- README.md
- crates/pathfinder/src/bin/pathfinder/main.rs
Add a metric tracking the start time of the process.
Most L1 clients have this kind of metric, which allows alerting in case of crash/failure and restart.  This adds the `process_start_time_seconds` metric which is set to a suitable value when pathfinder starts.
> Add process_start_time_seconds metric

- crates/gateway-types/src/class_hash.rs
This function has been unused for quite long, let's remove it.
> chore(gateway-types/class_hash): remove unused `extract_abi_code_hash`

- README.md
This updates the links with recent snapshots and removes old (pre-0.14.0) snapshot versions.
> chore(README): update DB snapshot links

- crates/rpc/src/method/syncing.rs
This change modifies the `starknet_syncing` method to just return false when we're caught up. "Caught up" means within 5 blocks of the tip of the chain for now.
This PR does change behavior only for the JSON-RPC 0.7.1 API though -- we plan to remove the 0.6 API soon anyway so we should not be making semantic changes there.
Closes: #2253
> fix(rpc/method/syncing): `starknet_syncing` should return false when caught up

- crates/common/src/signature.rs
- crates/common/src/state_update.rs
- crates/gateway-client/src/lib.rs
- crates/gateway-types/src/reply.rs
- crates/pathfinder/examples/compute_pre0132_hashes.rs
- crates/pathfinder/examples/feeder_gateway.rs
- crates/pathfinder/examples/recompute_state_diff_length.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/sync/checkpoint/fixture.rs
- crates/pathfinder/src/sync/headers.rs
- crates/pathfinder/src/sync/state_updates.rs
- crates/pathfinder/src/sync/track.rs
- crates/storage/src/fake.rs
Now that all networks have been upgraded to 0.13.2 we can remove support for pre-0.13.2 block signatures and the pre-0.13.2 state diff commitment calculation arguments used to verify those signatures.
Now we _always_ calculate, store and verify the new (0.13.2-style) state diff commitment values.
> chore: remove support for pre-0.13.2 block signatures and state diff commitments

- crates/p2p/src/behaviour.rs
- crates/p2p/src/behaviour/builder.rs
- crates/p2p/src/builder.rs
- crates/p2p/src/lib.rs
- crates/p2p/src/short_id.rs
- crates/p2p/src/tests.rs
- Attempt to remove the sloppiness from `evicted_peer_reconnection` and `inbound_peer_eviction`.
- Switch to using `ToSwarm` for peer disconnection.
- A `Short[Peer]Id` utility for debugging.
> Fix flaky tests

- CHANGELOG.md
- crates/pathfinder/examples/verify_transaction_commitment.rs
- crates/pathfinder/src/state/block_hash.rs
Turns out our 0.13.2 transaction commitment calculation algorithm was slightly different compared to the one used by the sequencer: for transaction types that _do_ have a signature field but it's empty we are required to use `[0]` as the signature when calculating the commitment leaf value.
This issue was triggered in Sepolia testnet block 218484 that contains an Invoke v1 transaction with an empty signature field.
Closes: #2282
> fix(pathfinder/block_hash): fix transaction commitment calculation for empty signatures

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
Enable JSON logging.
This adds a `--log-output-json` CLI option which outputs log entries in JSON.  This is useful for feeding to structured logging systems, as well as making it easier to search for and output particular log entries.
Note that this adds a new dependency (or at least a change to an existing dependency).  I'm unsure if there are additional steps here to carry out in this situation.
> Add --log-output-json CLI option.

- crates/rpc/src/lib.rs
- crates/rpc/src/v08.rs
- doc/rpc/v08/starknet_api_openrpc.json
- doc/rpc/v08/starknet_trace_api_openrpc.json
- doc/rpc/v08/starknet_write_api.json
- doc/rpc/v08/starknet_ws_api.json
This PR adds the OpenRPC specification for 0.8.0-rc0 to our source tree along with some tests that we implement all methods from the specification. Missing methods are whitelisted for now.
Websocket subscriptions are _not_ tested currently -- to do that we would need some additional tests as those are only available via a Websocket connection.
It also adds the `pathfinder_getProof` method since we do support that Pathfinder-specific extension for all versions of the JSON-RPC API.
> chore(doc/rpc): add 0.8.0-rc0 JSON-RPC specification

- crates/pathfinder/src/sync.rs
- crates/pathfinder/src/sync/track.rs
This PR adds storage and class trie updates to tracking sync.
So far I tested the change in the following manner:
1. sync via p2p from a pathfinder proxy, starting at block ~219k till block 220007, this involves checkpoint sync till 219218.
2. sync from the fgw using db from previous point (at block 220007) till 220053.
The assumption in the test is that fgw sync (2) would not be possible if the tracking p2p sync does not update the state tries as we would soon encounter a state commitment mismatch.
The same test performed with pathfinder form `main` fails instantly in (2).
> feat(sync/track): update storage and class tries

- crates/rpc/src/jsonrpc/error.rs
- crates/rpc/src/jsonrpc/response.rs
- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/jsonrpc/websocket/data.rs
- crates/rpc/src/jsonrpc/websocket/logic.rs
- crates/rpc/src/method/add_declare_transaction.rs
- crates/rpc/src/method/add_deploy_account_transaction.rs
- crates/rpc/src/method/add_invoke_transaction.rs
- crates/rpc/src/v06/method/add_declare_transaction.rs
- crates/rpc/src/v06/method/add_deploy_account_transaction.rs
- crates/rpc/src/v06/method/add_invoke_transaction.rs
There are multiple changes in the JSON-RPC 0.8.0 specification that require us to change the _error_ types we're returning.
Currently we use `SerializeForVersion` to implement version-dependent serialization of JSON-RPC results -- but we don't have that facility for error types.
This PR adds `SerializeForVersion` to RPC errors (and results in general) that makes implementing version-dependent behavior in error types easier.
> JSON-RPC: implement SerializeForVersion for RpcResponse

- crates/common/src/error.rs
- crates/common/src/lib.rs
- crates/pathfinder/src/lib.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/sync.rs
This PR plugs a few holes in the p2p sync logic:
|Sync Type|Was|Now|
|------------|----|----|
|Checkpoint|bails without retrying, if L1 API fails|Loop forever until L1 API returns some valid checkpoint, then proceed with checkpoint sync iteration|
|Checkpoint|retry on every error % L1 (see :arrow_up:) |bail on fatal errors, retry on other|
|Track|bail on first error|retry if error is recoverable|
_Fatal errors_  fall in the `SyncError[2]::Other` category, which means for example DB, or runtime related.
All other errors are recoverable assuming that config is valid. These errors stem from temporary problems like network partition (which is indistinguishable from increased latency, hence peers unavailable) or outright malicious or _sloopy_ peers (ie. who treat the protocol standard without …
> p2p sync: restart on recoverable error

- crates/executor/src/types.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
Ignore new clippy warnings after recent update to rust stable
> chore: fix new clippy warnings (rust 1.82.0)

- .github/workflows/ci.yml
- crates/common/src/error.rs
- crates/common/src/header.rs
- doc/rpc/v03/starknet_api_openrpc.json
- doc/rpc/v03/starknet_trace_api_openrpc.json
- doc/rpc/v04/starknet_api_openrpc.json
- doc/rpc/v04/starknet_trace_api_openrpc.json
- doc/rpc/v06/starknet_api_openrpc.json
- doc/rpc/v06/starknet_trace_api_openrpc.json
- doc/rpc/v07/starknet_api_openrpc.json
- doc/rpc/v07/starknet_trace_api_openrpc.json
- doc/rpc/v08/starknet_api_openrpc.json
- doc/rpc/v08/starknet_trace_api_openrpc.json
And also fix all typos that are found by the new version.
> chore(ci): use typos 1.26.0

- crates/executor/src/types.rs
- crates/rpc/src/dto/simulation.rs
- crates/rpc/src/method/trace_block_transactions.rs
This PR implements https://github.com/starkware-libs/starknet-specs/pull/233 so that we don't expose compute resources for inner calls only L1 and L2 gas.
Closes #2322
> fix(rpc/v08): follow-up spec change for inner call execution resources

- crates/rpc/src/error.rs
- crates/rpc/src/jsonrpc/error.rs
- crates/rpc/src/jsonrpc/response.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/method/add_declare_transaction.rs
- crates/rpc/src/method/add_deploy_account_transaction.rs
- crates/rpc/src/method/add_invoke_transaction.rs
- crates/rpc/src/v06/method/add_declare_transaction.rs
- crates/rpc/src/v06/method/add_deploy_account_transaction.rs
- crates/rpc/src/v06/method/add_invoke_transaction.rs
- crates/rpc/src/v08.rs
This PR follow up a change in the JSON-RPC 0.8.0 specification that renames the error (and changes its message). This was the only change for the `starknet_addXYZTransaction` methods so we now also add those to the JSON-RPC 0.8.0 API.
Closes #2263
> feat(rpc/v08): rename INSUFFICIENT_MAX_FEE error and add `starknet_addXYZTransaction`methods

- crates/common/src/state_update.rs
- crates/make-stream/src/lib.rs
- crates/merkle-tree/src/contract_state.rs
- crates/p2p/src/builder.rs
- crates/p2p/src/client/peer_agnostic.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/sync.rs
- crates/pathfinder/src/sync/checkpoint.rs
- crates/pathfinder/src/sync/error.rs
- crates/pathfinder/src/sync/state_updates.rs
- crates/pathfinder/src/sync/track.rs
- crates/rpc/src/lib.rs
The `*Ref<'_>` structs were necessary to achieve an acceptable equilibrium:
- use the same impl of applying state update for both single- and multi-block state updates,
- avoid generics explosion when trying to use `[Parallel]Iterator` trying to achieve above (with which I eventually failed anyway),
- keep number of allocations low.
> feat(checkpoint/state_diff): merge trie updates

- crates/executor/src/types.rs
- crates/pathfinder/examples/re_execute.rs
- crates/rpc/src/dto/fee.rs
- crates/rpc/src/method/estimate_fee.rs
- crates/rpc/src/method/estimate_message_fee.rs
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v06/method/estimate_message_fee.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
Adjusts `FeeEstimate` to match new Starknet spec, including new L2 gas data and renaming the L1 fields.
Maintains backwards compatibility.
Closes #2310
> feat(rpc): add L2 gas data to `FeeEstimate`

- crates/p2p/src/client/conv.rs
- crates/p2p/src/client/peer_agnostic.rs
- crates/p2p/src/client/peer_agnostic/fixtures.rs
- crates/p2p/src/client/peer_agnostic/tests.rs
- crates/p2p/src/client/peer_agnostic/traits.rs
- crates/p2p/src/client/types.rs
- crates/pathfinder/src/sync/checkpoint.rs
- crates/pathfinder/src/sync/class_definitions.rs
- crates/pathfinder/src/sync/error.rs
- crates/pathfinder/src/sync/track.rs
- crates/pathfinder/src/sync/transactions.rs
for equality with locally-computed hashes (and fail on mismatch).
Fixes #2346.
> feat: check class & transaction hashes

- crates/common/src/lib.rs
- crates/pathfinder/examples/compute_pre0132_hashes.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/sync/headers.rs
As specified in #2328, for Starknet version from 0.13.4 (subject to change). Also missing L2 prices for the hash calculation from Starknet gateway reply block (they aren't there yet).
Fixes  #2328.
> feat: computing new block hash

- crates/p2p/src/client/peer_agnostic.rs
- crates/p2p/src/client/peer_agnostic/traits.rs
- crates/p2p/src/peer_data.rs
- crates/pathfinder/examples/compute_pre0132_hashes.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/sync.rs
- crates/pathfinder/src/sync/checkpoint.rs
- crates/pathfinder/src/sync/class_definitions.rs
- crates/pathfinder/src/sync/error.rs
- crates/pathfinder/src/sync/events.rs
- crates/pathfinder/src/sync/headers.rs
- crates/pathfinder/src/sync/state_updates.rs
- crates/pathfinder/src/sync/stream.rs
- crates/pathfinder/src/sync/track.rs
- crates/pathfinder/src/sync/transactions.rs
- crates/storage/src/fake.rs
Fixes: #2302
Some ideas from the issue :arrow_up: were not implemented or a more convenient solution was chosen (for example: log errors at source in checkpoint sync, keep variants small, allow for implicit conversion from `anyhow::Error` because only one variant uses it).
> Audit p2p sync errors

- crates/executor/src/simulate.rs
- crates/executor/src/types.rs
- crates/rpc/src/dto/simulation.rs
- crates/rpc/src/method/trace_block_transactions.rs
EXECUTION_RESOURCES should contain gas info exclusively now.
Closes: #2359
> fix(rpc/v08): fix EXECUTION_RESOURCES serialization in transaction traces

- crates/rpc/src/method/subscribe_transaction_status.rs
- doc/rpc/v08/starknet_api_openrpc.json
- doc/rpc/v08/starknet_executables.json
- doc/rpc/v08/starknet_trace_api_openrpc.json
- doc/rpc/v08/starknet_write_api.json
- doc/rpc/v08/starknet_ws_api.json
This PR updates our in-tree specs to the latest available in the repository.
It also applies a last-minute change that was made to the spec to our code: renaming of the `starknet_subscriptionTransactionsStatus` notification to `starknet_subscriptionTransactionStatus` on the WebSocket subscriptions API.
> chore(rpc/v08): update OpenRPC specifications

- crates/common/src/casm_class.rs
`bytecode_segment_lengths` isn't a required property in the response so it's actually better to just skip serializing it. `null` is not a valid value according to the spec.
> fix(rpc/v08/get_compiled_casm): omit `bytecode_segment_lengths` if missing

- crates/rpc/src/method/get_compiled_casm.rs
Minor fix. 
Method was returning the `COMPILATION_FAILED` and that's just not the case at all.
Switched to a generic internal error.
> fix(rpc): Returning wrong error on rpc `getCompiledCasm`

- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/method/subscribe_events.rs
- crates/rpc/src/method/subscribe_new_heads.rs
- crates/rpc/src/method/subscribe_pending_transactions.rs
- crates/rpc/src/method/subscribe_transaction_status.rs
Addresses the nested vs. non-nested new subscription result.
We've settled on non-nested (e.g. flattened version) after explicit comment from Starkware.
Closes #2344
> fix(rpc): flatten `subscription_id` on new subscription result

- crates/rpc/src/lib.rs
- doc/rpc/v08/starknet_api_openrpc.json
- doc/rpc/v08/starknet_executables.json
- doc/rpc/v08/starknet_ws_api.json
This PR just updates our in-repo specs with the 0.8.0-rc1 ones and makes sure that we use all of those in the RPC routing tests.
> chore(doc/rpc/v08): upgrade OpenRPC specs to 0.8.0-rc1

- crates/pathfinder/src/sync/class_definitions.rs
- crates/pathfinder/src/sync/stream.rs
- crates/pathfinder/src/sync/track.rs
Fixes: #2158
(Although by not expanding on the idea of `pipe_each` but rather removing it entirely and using pipe to just process entire batches.)
> rayonize class hash verification and class compilation in track sync, remove pipe_each

- crates/rpc/src/error.rs
- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/method/subscribe_events.rs
- crates/rpc/src/method/subscribe_new_heads.rs
Adds the newly introduced `CALL_ON_PENDING` subscription error.
Also added the other missing errors on the subscription endpoints.
> feat(rpc): add starknet subs errors to ws endpoints

- crates/executor/src/lru_cache.rs
- crates/executor/src/state_reader.rs
- crates/storage/src/bloom.rs
- crates/storage/src/connection/event.rs
Replacing the existing ad-hoc error handling.
Fixes #2381.
> Handling Mutex.lock() failures by calling unwrap()

- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/sync/checkpoint.rs
- crates/pathfinder/src/sync/track.rs
- crates/rpc/src/method/call.rs
- crates/rpc/src/pathfinder/methods/get_proof.rs
- crates/rpc/src/test_setup.rs
- crates/rpc/src/v06/method/call.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
- crates/storage/src/lib.rs
We're using shared cache mode with our in-memory DB to allow multiple connections from within the same process. This means that in contrast to a file-based DB we immediately get locking errors in case of concurrent writes -- a pool size of one avoids this.
There are certain tests that _do_ need multiple connections to the in-memory DB though so we add a constructor that allows specifying the size of the pool we require.
> fix(storage): work around in-memory DB locking issues

- crates/rpc/src/method/subscribe_transaction_status.rs
Instead of an internal error error we should return the new-ish CALL_ON_PENDING error code.
> fix(rpc/subscribe_transaction_status): return CALL_ON_PENDING error for pending block id

- crates/pathfinder/examples/compute_contract_state_hash.rs
was off by one (b/c it was incremented to make it 1-based, twice), plus checked as if it was 0-based.
> fix: compute_contract_hash_example argument index

- crates/load-test/src/main.rs
- crates/load-test/src/requests.rs
- crates/load-test/src/requests/v08.rs
- crates/load-test/src/tasks.rs
- crates/load-test/src/tasks/scripted.rs
- crates/load-test/src/tasks/v08.rs
All tasks use JSON-RPC 0.8 now instead of the 0.5 API we've removed.
> feat(load-test): update for JSON-RPC 0.8

- doc/rpc/pathfinder_rpc_api.json
Looks like there is a copy-paste error in the pathfinder rpc spec.
> doc(pathfinder_rpc_api): PROOF_MISSING is 10001

- crates/p2p/src/client/conv.rs
- crates/p2p_proto/proto/receipt.proto
- crates/p2p_proto/src/receipt.rs
- crates/storage/src/connection/transaction.rs
- crates/storage/src/fake.rs
Common execution resources already had it. Fixes #2413.
Note that the change to DTO is backwards-incompatible with the previous version, and should be considered atomic with https://github.com/eqlabs/pathfinder/commit/71ab4f3fe9d2496bc4ad279aeff01a665006f7ea (which _is_ compatible with its previous versions).
> feat: added l2_gas to P2P & DTO ExecutionResources

- CHANGELOG.md
- crates/rpc/src/dto/transaction.rs
- crates/rpc/src/method/get_block_with_receipts.rs
- crates/rpc/src/method/get_block_with_txs.rs
- crates/rpc/src/method/get_transaction_by_hash.rs
- crates/rpc/src/method/subscribe_pending_transactions.rs
The OpenRPC specification requires sending an array of {transaction, receipt} objects.
Note that the transaction in this schema is #/components/schemas/TXN, which does not contain a transaction_hash property. We're always serializing transactions with the transaction_hash property present which makes our responses to starknet_getBlockWithReceipts not compliant with the specification.
Closes: #2420
> fix(rpc/v08): fix spec compliance in `starknet_getBlockWithReceipts` response

- crates/common/src/transaction.rs
- crates/p2p/src/client/conv.rs
- crates/p2p/src/client/peer_agnostic/fixtures.rs
- crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
- crates/pathfinder/src/sync/transactions.rs
Fixes: #2074 
A quick test on my pc (ryzen 3700x) shows that `ContractAddress::deployed_contract_address` on average takes > 150us, which is more than the rule of thumb in https://ryhl.io/blog/async-what-is-blocking/ of 10-100us.
> fix(sync): deployed_contract_address computed in async context

- crates/rpc/src/dto/block.rs
- crates/rpc/src/method/get_block_with_receipts.rs
Fixes #2424. Tested and the field is gone in `/rpc/v0_7` as expected.
> fix: extra `l2_gas_price` in rpc v0.7 block headers

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/load-test/Cargo.lock
Also adds some missing changelog entries.
> chore: bump version to 0.15.1

- CHANGELOG.md
- crates/storage/src/connection/block.rs
As part of the still-in-development "aggregate bloom filters feature we have added a SQL statement to `purge_block()` that causes issues during a reorg because it references a non-existent table when compiling Pathfinder _without_ the "aggregate_bloom" feature.
This change fixes that by gating the SQL statement behind the feature.
Closes: #2430
> fix(storage/block): fix reorg storage problem

- Cargo.lock
- Cargo.toml
- crates/p2p/Cargo.toml
- crates/p2p/src/client/peer_agnostic/tests.rs
- crates/p2p/src/tests.rs
test_log attribute already does that.
Fixes #2398.
> chore: remove explicit initialization of env_logger in tests

- CHANGELOG.md
- crates/pathfinder/src/state/sync.rs
The starting block number is used exclusively for serving the `starknet_syncing` JSON-RPC method -- so using zero unstead of `u64::MAX` is more appropriate.
Closes: #2443
> fix(sync): fix sync status starting block when starting with empty storage

- crates/executor/src/types.rs
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/src/dto/simulation.rs
- crates/rpc/src/error.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/method/call.rs
- crates/rpc/src/method/estimate_message_fee.rs
- crates/rpc/src/method/get_transaction_by_block_id_and_index.rs
- crates/rpc/src/method/simulate_transactions.rs
- crates/rpc/src/method/trace_block_transactions.rs
- crates/rpc/src/method/trace_transaction.rs
- crates/rpc/src/types.rs
- crates/rpc/src/types/receipt.rs
- crates/rpc/src/types/transaction.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v07/dto/receipt.rs
This PR is part of #2220 
This PR removes the existing dependencies the current RPC versions (v07 and beyond) have on the legacy v06 RPC version, effectively decoupling the two. 
Key changes include:
- **Migration of types:** All relevant types, methods and tests from v06 have been migrated to common modules, allowing for reusability on newer RPC versions.
- **DTO Removal:** A number of data transfer objects (DTOs) from the v06 version have been removed and replaced with the actual types they were wrapping. This simplifies the code by eliminating unnecessary abstraction. The `SerializeForVersion` is implemented in the `Input` and `Output` DTO types for every method.
- **V06 Module Disabled:** The v06 module is now fully disabled and will no longer be built as part of the project. This …
> feat(rpc): Decouple `v07` from `v06` types and methods

- crates/rpc/src/dto/block.rs
- crates/rpc/src/dto/primitives.rs
- crates/rpc/src/dto/simulation.rs
- crates/rpc/src/dto/transaction.rs
- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/method/add_declare_transaction.rs
- crates/rpc/src/method/add_deploy_account_transaction.rs
- crates/rpc/src/method/add_invoke_transaction.rs
- crates/rpc/src/method/call.rs
- crates/rpc/src/method/estimate_fee.rs
- crates/rpc/src/method/get_block_with_receipts.rs
- crates/rpc/src/method/get_events.rs
- crates/rpc/src/method/get_messages_status.rs
- crates/rpc/src/types.rs
- crates/rpc/src/types/receipt.rs
- crates/rpc/src/v06/method/add_declare_transaction.rs
- crates/rpc/src/v06/method/add_deploy_account_transaction.rs
- crates/rpc/src/v06/method/add_invoke_transaction.rs
- crates/rpc/src/v06/method/call.rs
- crates/rpc/src/v06/method/estimate_fee.rs
- crates/rpc/src/v06/method/estimate_message_fee.rs
- crates/rpc/src/v06/method/get_block_with_tx_hashes.rs
- crates/rpc/src/v06/method/get_block_with_txs.rs
- crates/rpc/src/v06/method/get_transaction_receipt.rs
- crates/rpc/src/v06/method/get_transaction_status.rs
- crates/rpc/src/v06/method/simulate_transactions.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
This PR is part of https://github.com/eqlabs/pathfinder/issues/2220
Remove all `.deserialize_serde()` calls for primitive types and common types when possible.
Implementations of `DeserializeForVersion` for primitive types and some common types.
Using `deserialize_serde` on some types (mostly in `class.rs`) is still required.
> feat(rpc): remove `deserialize_serde` for primitives and common types

- CHANGELOG.md
- crates/common/src/class_definition.rs
- crates/p2p/src/client/conv.rs
- crates/rpc/src/types/class.rs
Make sure the uncompressed size of Cairo 0 class definitions does not exceed our limit of 4 MiB.
Closes #2471
> fix(p2p,rpc): limit Cairo 0 class definition size

- crates/gateway-test-fixtures/fixtures/0.13.4/block/sepolia_integration_63881.json
- crates/gateway-test-fixtures/fixtures/0.13.4/state_update/sepolia_integration_63881.json
- crates/gateway-test-fixtures/src/lib.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/state/sync.rs
- crates/rpc/src/jsonrpc/websocket/logic.rs
- crates/rpc/src/method/trace_block_transactions.rs
- crates/rpc/src/pending.rs
- crates/rpc/src/v06/method/trace_block_transactions.rs
- crates/rpc/src/v06/method/trace_transaction.rs
...where it was missed last time.
> fixup: add support for l2 gas

- crates/rpc/src/method/simulate_transactions.rs
- crates/rpc/src/method/trace_block_transactions.rs
Fixes the test fixtures of `test_multiple_transactions` for RPC v08.
See also: #2457
> chore(rpc): fix `test_multiple_transactions` for rpc `v08`

- utils/pathfinder-probe/Cargo.lock
- utils/pathfinder-probe/Cargo.toml
- utils/pathfinder-probe/src/main.rs
This PR upgrades dependencies of our `pathfinder-probe` tool that's used by the mainnet node monitoring infrastructure.
> chore(pathfinder-probe): upgrade dependencies

- Dockerfile
The Cairo compiler does not compile with Rust 1.80.0 anymore.
> chore(Dockerfile): upgrade Rust to 1.84.0

- crates/gateway-types/src/reply.rs
- crates/rpc/src/method/trace_block_transactions.rs
The gateway ResourceBounds conversion was missing l1 data gas.
> fix: sending l1 data gas to gateway

- Cargo.toml
The Cairo compiler no longer compiles using Rust 1.80.
> chore(cargo): bump MSRV to Rust 1.81.0

- crates/rpc/src/error.rs
- crates/rpc/src/method/call.rs
Mapped from CallError::InvalidMessageSelector.
Fixes https://github.com/eqlabs/pathfinder/issues/2497 .
> feat: add ApplicationError::EntrypointNotFound

- crates/common/src/state_update.rs
- crates/merkle-tree/src/contract_state.rs
- crates/merkle-tree/src/starknet_state.rs
- crates/pathfinder/src/sync.rs
- crates/pathfinder/src/sync/error.rs
- crates/pathfinder/src/sync/state_updates.rs
- crates/pathfinder/src/sync/track.rs
- crates/storage/src/fake.rs
This PR fixes 2 things:
- syncing fake contract update which does not have a valid underlying class hash is a recoverable error, not a fatal one,
- removes flakiness from a related test, by improving how sync done watch works.
> flaky p2p sync test

- crates/executor/src/types.rs
- crates/rpc/src/dto/simulation.rs
- crates/rpc/src/method/simulate_transactions.rs
- crates/rpc/src/method/trace_block_transactions.rs
- doc/rpc/v08/starknet_api_openrpc.json
- doc/rpc/v08/starknet_executables.json
- doc/rpc/v08/starknet_trace_api_openrpc.json
- doc/rpc/v08/starknet_write_api.json
- doc/rpc/v08/starknet_ws_api.json
Starting from Starknet 0.13.4 panics in calls can be caught and handled by callers, so failure in an individual call does not cause the transaction to fail (and revert) immediately.
To be able to find out which calls have failed an update to the 0.8 OpenRPC spec now requires the `is_reverted` flag for function invocations.
Closes: #2496
> feat(rpc/trace): add `is_reverted` flag to `FUNCTION_INVOCATION`

- crates/rpc/src/method/subscribe_transaction_status.rs
- doc/rpc/v08/starknet_ws_api.json
Fixes https://github.com/eqlabs/pathfinder/issues/2495 .
> fix: remove block_id from starknet_subscribeTransactionStatus

- crates/rpc/src/jsonrpc/router/method.rs
- crates/rpc/src/jsonrpc/websocket.rs
Prevents intermittent failures of `cargo test`.
> fix: exclude from doctests example code that isn't meant to compile

- Cargo.lock
- Cargo.toml
- crates/class-hash/Cargo.toml
- crates/class-hash/src/lib.rs
- crates/gateway-types/src/lib.rs
- crates/pathfinder/Cargo.toml
- crates/pathfinder/examples/compute_class_hash.rs
- crates/pathfinder/src/state/sync/class.rs
- crates/pathfinder/src/sync/class_definitions.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/types/class.rs
- crates/storage/Cargo.toml
- crates/storage/src/fake.rs
This PR exposes the [requested](https://github.com/eqlabs/pathfinder/pull/2465) class hash functionality in the simplest way possible *
- Moves the class hashing functionality from `starknet-gateway-types` to a publicly accessible crate.
- Adds a CI job to publish dependent crates (`crypto`, `common`, `serde`) and the new class hash crate itself `class-hash` to crates.io on every pathfinder release.
Closes #2466 
\* Ideally our `common` crate should be refactored to expose a more organized API/types with cleaner docs. I attempted this a couple times but our macros make it hard to organize types based on their domain/concerns. It's still a WIP, but didn't want to drag this further, so I'll continue some other time.
> Expose class hashing functionality

- crates/rpc/src/method/add_declare_transaction.rs
- crates/rpc/src/method/add_deploy_account_transaction.rs
- crates/rpc/src/method/add_invoke_transaction.rs
- crates/rpc/src/v08.rs
- crates/rpc/src/v08/method.rs
- crates/rpc/src/v08/method/add_declare_transaction.rs
- crates/rpc/src/v08/method/add_deploy_account_transaction.rs
- crates/rpc/src/v08/method/add_invoke_transaction.rs
Fixes: https://github.com/eqlabs/pathfinder/issues/2498
I decided to add a "filtering layer" in v08 specific implementations instead of fiddling with deserialization, which would be against existing convention, ie. we deserialize older transaction versions correctly and then return `UnsupportedTxVersion`.
Most of the code is just test related boilerplate which could be shrunk, but then I'd have to litter all the dtos with `#[cfg_attr(test, derive(Dummy))]` which I'm not sure is better in this case.
> feat(rpc): v.0.8 only allows v3 transactions in the write api

- .github/workflows/publish-crates.yml
- .github/workflows/release.yml
- Cargo.lock
- crates/class-hash/Cargo.toml
- crates/common/Cargo.toml
- crates/common/src/event.rs
- crates/p2p/Cargo.toml
- crates/p2p/src/client/peer_agnostic/fixtures.rs
- crates/p2p/src/client/types.rs
- crates/p2p_proto/Cargo.toml
- crates/p2p_proto/src/class.rs
- crates/p2p_proto/src/event.rs
- crates/p2p_proto/src/header.rs
- crates/p2p_proto/src/state.rs
- crates/serde/Cargo.toml
- crates/tagged-debug-derive/Cargo.toml
- crates/tagged/Cargo.toml
- crates/tagged/src/lib.rs
- justfile
- scripts/release.sh
This PR adds automation for our release process and crates.io publishing workflow.
Added a simple `release` command that automates all tedious release prep:
- Version format validation
- CHANGELOG updates
- Workspace version updates
- Dependency version updates for publishable crates
- Git branch, release commit and tag creation
- User confirmation before pushing changes
Usage: `just release X.Y.Z` 
1. Dry run `cargo publish` before creating draft release.
2. Introduce `publish-crates` CI job to be linked to manual release publication.
Closes #2509
> Streamline our release process

- crates/executor/src/estimate.rs
- crates/executor/src/simulate.rs
- crates/executor/src/transaction.rs
- crates/executor/src/types.rs
- crates/rpc/src/method/simulate_transactions.rs
This PR fixes inner-call gas usage estimation for transaction traces. On the JSON-RPC 0.8 interface we now return `l1_gas` and `l2_gas` cost estimation for inner calls instead of the raw VM resources (which are not available anyway when running with L2 gas).
We now determine the gas vector computation mode (whether to use L2 gas) from the resource bounds in the transaction and then consistently use that when computing costs.
> fix(executor): fix L2 gas computation and inner-call gas estimation 

- crates/rpc/src/lib.rs
And fix tests for the root to use the default (v07) API.
I've left the websocket-specific tests commented out for now, since that would require duplicating the list of exemptions -- we should re-add those when we have all the methods we want properly registered/working.
> feat(rpc): re-enable route tests for v06

- crates/rpc/src/lib.rs
- crates/rpc/src/v06.rs
The `TXN` type is the same as we have in JSON-RPC 0.7, so the input and output of these methods already matches the JSON-RPC 0.6 spec.
Closes #2552
> feat(rpc/v06): re-add transaction getter methods

- crates/rpc/src/lib.rs
- crates/rpc/src/v06.rs
These methods are trivial and the specs are the same in all JSON-RPC versions, so we can just re-add these to v06.
While adding `pathfinder_getProof` I also figured out that we were missing the registration for the v06-specific Websocket route, so I've re-added that.
> feat(rpc/v06): re-add trivial and unchanged methods

- crates/rpc/src/dto/block.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v06.rs
For `starknet_getBlockWithTxHashes` and `starknet_getBlockWithTxs` the only difference compared to v07 is that the block header and pending block header types are missing L1 data gas and L1 DA mode fields.
This change also adds some rudimentary tests for testing the serialization of the block header for all the different JSON-RPC versions we're supporting.
Closes: #2554
> feat(rpc/v06): re-add block getters

- crates/rpc/src/lib.rs
- crates/rpc/src/v06.rs
The serialization format of classes has not changed between JSON-RPC versions. Since the input is the same in all versions, we can safely re-add JSON-RPC 0.6 `starknet_getClass` and `starknet_getClassAt` methods.
Closes #2556
> feat(rpc/v06): re-add class getter methods

- Cargo.toml
The recent libp2p upgrade bumped the MSRV to 1.83.0, so we have to do the same.
Should fix the MSRV check CI job failure: https://github.com/eqlabs/pathfinder/actions/runs/13103900577
> fix(cargo): bump MSRV to 1.83.0

- crates/rpc/src/dto/simulation.rs
- crates/rpc/src/error.rs
- crates/rpc/src/jsonrpc/error.rs
- crates/rpc/src/jsonrpc/response.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v06.rs
Note that this PR doesn't include the update of fee estimate serialization - that should be implemented in https://github.com/eqlabs/pathfinder/pull/2550 .
Fixes https://github.com/eqlabs/pathfinder/issues/2555 .
> feat(rpc/v06): re-add execution methods

- crates/rpc/src/lib.rs
- crates/rpc/src/v06.rs
add `starknet_estimateMessageFee` and enable ws route testing
Closes #2514
> Wrap up JSON RPC v06 re-introduction

- crates/rpc/src/v08.rs
The implementation of `starknet_estimateFee` was being registered for this method -- that's wrong and was causing requests to fail.
> fix(rpc/v08): register proper implementation for `starknet_estimateMessageFee`

- crates/rpc/src/dto/transaction.rs
In JSON-RPC 0.8 the `l1_data_gas` bound has been added which we did not serialize correctly.
> fix(rpc/v08): fix serialization of `ResourceBounds`

- .github/workflows/deploy_website.yml
- docs/docs/database-snapshots.md
- docs/docs/incidents/2023-06-17_mainnet_incident.md
- docs/docs/incidents/_category_.json
- docs/docs/interacting-with-pathfinder/websocket-api.md
- docs/docusaurus.config.js
This PR fixes some issues in the new website contents / configuration, adds the single incident page the old website had and changes our deployment workflow to deploy the new site to https://eqlabs.github.io/pathfinder.
Removal of the old website and redundant parts of the README will be done in a follow-up PR once the deployment has been done.
> chore(docs): publish Docusaurus-based new website

- .github/workflows/deploy_website.yml
Turns out the website deploy workflow was using deprecated versions of some actiosn that do not work anymore.
> chore(github): upgrade actions in website deploy workflow

- .github/workflows/deploy_website.yml
Another dumb issue fixed. This time it's actually [building fine](https://github.com/eqlabs/pathfinder/actions/runs/13196848488/job/36839941462).
> fix(github/deploy_website): run build commands in the right directory

- .github/workflows/publish-crates.yml
The crate publishing job should now run as soon as we publish a new release!
> Publish crates on release published trigger

- crates/rpc/src/method/simulate_transactions.rs
This PR adds a test using an invoke transaction that does have L1 data gas resource bounds specified. Our expectation is that the transaction will use L2 gas (while not _yet_ using full-fledged Sierra 1.7 gas metering, because the test contract has not been recompiled with a new compiler).
> feat(rpc): add Starknet 0.13.4 simulation test using L2 gas

- crates/rpc/src/error.rs
- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/method/subscribe_events.rs
- crates/rpc/src/method/subscribe_new_heads.rs
- crates/rpc/src/types.rs
A change in the JSON-RPC 0.8.0-rc.3 specification made it explicit that the pending block is not allowed as the starting block for any subscription.
The `block_id` parameter in a subscription request should now be of type `SUBSCRIPTION_BLOCK_ID` and the `CALL_ON_PENDING` error has been removed.
Closes #2583
> fix(rpc/v08): remove `CALL_ON_PENDING` error and introduce `SUBSCRIPTION_BLOCK_ID`

- crates/executor/src/call.rs
- crates/executor/src/error.rs
- crates/rpc/src/method/call.rs
In Starknet 0.13.4 calls can fail without reverting the whole execution. This means that any call can now just fail without throwing an error and we have to use the retdata to find out what was the cause of failure.
Blockifier seems to have special cases for OUT_OF_GAS and ENTRYPOINT_NOT_FOUND errors, so we handle these two cases separately.
The rest of failures gets converted into a ContractError with the actual retdata part of the error message.
> fix(rpc/call): properly handle failed Sierra 1.7 calls

- .github/workflows/docker.yml
- Dockerfile
- build/cargo-build.sh
- build/cargo-chef-cook.sh
We have previously disabled our aarch64 Docker image builds because a build script in on of the dependencies of blockifier was not working when we were cross-compiling Pathfinder.
It turned out that there's an easy workaround: instead of specifying `--target XXX` to our `cargo build` invocation we should just use the CARGO_BUILD_TARGET environment variable. That gets properly inherited by the `cargo install` command ran by the build script and the binary is properly compiled for our target architecture.
> fix(docker): fix and re-enable aarch64 Docker image builds

- crates/executor/src/error_stack.rs
- crates/executor/src/estimate.rs
- crates/executor/src/lib.rs
- crates/executor/src/simulate.rs
- crates/executor/src/transaction.rs
- crates/rpc/src/method/estimate_fee.rs
This change aligns the behavior of `starknet_estimateFee` with `starknet_simulateTransactions`, ensuring that fee estimation fails for reverted transactions, while simulation continues to provide estimates and traces with revert reasons.
In the expected output for the test we can also see that our handling of `Cairo1RevertSummary` within an error stack is suboptimal: instead of having the string representation in there we should properly convert the summary into multiple frames. I've created https://github.com/eqlabs/pathfinder/issues/2596 for that problem.
> fix(executor/estimate): fee estimation should fail for reverts

- crates/executor/src/error_stack.rs
- crates/rpc/src/method/estimate_fee.rs
Currently, `Cairo1RevertSummary`` is converted into a string representation in our error stack. However, this type is an error stack on its own, containing multiple call frames followed by more information on the actual revert.
To provide better structured information on JSON-RPC 0.8, we now properly convert Cairo1RevertSummary into a series of call fames followed by a single string describing the cause of the revert.
Closes #2596
> fix(executor): improve error stack for Cairo reverts

- Cargo.toml
- crates/executor/src/simulate.rs
- crates/executor/src/types.rs
After having upgraded blockifier to 0.14.0-rc.1 we can now use the built-in inner call gas vector calculation we have contributed.
> refactor(executor): use blockifier's inner call gas vector calculation

- crates/executor/src/transaction.rs
- crates/pathfinder/examples/re_execute.rs
Blockifier has a pre-check for `AccountTransaction` that checks that the account has sufficient balance to cover all committed resource bounds.
Because of this `starknet_simulateTransaction` fails with "insufficient balance" when we're initially running the transaction with L2 gas max amount set to u64::MAX.
We should derive the max L2 gas amount so that the balance of the account still covers all the resource bounds.
This PR fixes another small issue: when we're re-executing the transaction with an L2 gas limit of zero so that we get a detailed error, we now explicitly request execution to fail in case of a reverted transaction.
> fix(executor): derive max L2 fee from balance

- scripts/release.sh
This PR makes some adjustments to the release script:
- The script now updates and commits `crates/load-test/Cargo.lock` as well.
- The script does not create and push the version tag. We usually release from `main`, so the workflow is the following: 
- We create a release branch, do the version bump and push it to GitHub.
- We open a PR with the change which will be merged to `main`.
- We tag the merge commit on `main` and push the tag to GitHub.
- Pushing the tag triggers the release workflow, which creates draft release notes and binary builds.
> chore(scripts/upgrade): update release script

- crates/gateway-types/src/reply.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/src/context.rs
Make token addresses in get_contract_addresses optional, when they aren't returned use defaults.
Fixes #2621.
> fix: optional token addresses in feeder gateway's get_contract_addresses

- crates/rpc/src/method/get_block_with_txs.rs
Transactions in the response were serialized without the transaction hash, which is required by the specification for all RPC versions.
Closes #2623
> fix(rpc): fix response for `starknet_getBlockWithTxns`

- CHANGELOG.md
- crates/rpc/src/method/get_compiled_casm.rs
According to the JSON-RPC 0.8.0-rc3 specs the output CASM class should not be wrapped inside a `casm` property.
This PR removes that additional wrapping.
Closes #2635
> fix(rpc/get_compiled_casm): don't wrap CASM class in a `casm` property

- crates/executor/src/types.rs
If L2 gas accounting is enabled the minimal gas vector has a non-zero L2 gas component. We should make sure we consider that value when calculating the fee estimate.
> fix(executor): consider L2 gas when calculating minimum gas limit

- Cargo.lock
This PR updates some of our dependencies to fix some potential security problems and to avoid using yanked versions of dependencies.
- Upgrade `hickory-resolver`: fixes RUSTSEC-2025-0006
- Upgrade `rustls`: fixes RUSTSEC-2024-0399
- Upgrade `url`: version 2.5.3 has been yanked
> chore(cargo): update some dependencies

- crates/load-test/Cargo.lock
- crates/load-test/Cargo.toml
- crates/load-test/src/tasks/v08.rs
In particular, upgrade to `goose` 0.18.0 that has finally upgraded its transitive dependencies.
This PR also enables using `rustls` for the load-test tool so that we no longer depend on `openssl`.
> chore(load-test): upgrade dependencies

- CHANGELOG.md
- crates/gateway-test-fixtures/fixtures/0.13.4/traces/sepolia_testnet_30000.json
- crates/gateway-test-fixtures/src/lib.rs
- crates/gateway-types/src/trace.rs
- crates/rpc/src/method/trace_block_transactions.rs
Starknet 0.13.4 has added a new `failed` field to function invocations, causing parsing to fail. This change adds the new field as optional and also uses that value when converting gateway function invocations to JSON-RPC function invocations (`is_reverted` property).
This latter conversion is not really used though, as we're not falling back to the feeder gateway for traces for Starknet 0.13.4 blocks.
Closes: #2647
> fix(gateway-types): add missing `failed` field to transaction trace function invocation

- crates/p2p_stream/src/handler.rs
- crates/p2p_stream/tests/error_reporting.rs
Codec read response timeout was not properly propagated to the connection handler, causing the swarm not being notified about the timeout.
This has also caused test flakyness in the respective  test (`report_outbound_timeout_on_read_response_timeout`) which wasn't really testing read response timeout, but was timing out because of the stream timeout.
> fix(p2p_stream): fix propagation of read response timeout

- CHANGELOG.md
- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/method/subscribe_events.rs
- crates/rpc/src/method/subscribe_new_heads.rs
- crates/rpc/src/method/subscribe_pending_transactions.rs
When subscribing with the `latest` block, we still have to do catch-up. The JSON-RPC specification says that the starting point for the subscription should be the block specified by `block_id` in the subscription request. This means that we have to send a notification for the `latest` block, irrespective if it was requested explicitly or implicitly and if we used the `latest` label or its specific block number or hash.
Closes #2642
> fix(rpc/subscription): send notifications for `latest` block

- crates/rpc/src/lib.rs
Successful subscription requests can still lead to notifications being received (even though we are unsubscribing immediately after there's a race condition between sending the notifications and closing the subscription).
Instead, this change ensures that subscriptions cannot succeed by passing an invalid parameter.
> fix(rpc/lib/routing_test): fix flaky routing test

- CHANGELOG.md
- crates/rpc/src/method/subscribe_events.rs
This PR adds the ability to send events matching the filter from the pending block to the client right as they are included in the pending block. This minimizes the latency it takes for users to receive relevant updates.
One side effect is that since the pending block has no block hash, we send out emitted events without the block hash as a context. Since almost all events show up first in the pending block, in practice this means that we are no longer sending block hashes for the emitted events...
Closes #2640
> feat(rpc/subscribe_events): send matching events from the pending block

- CHANGELOG.md
- Cargo.lock
- crates/ethereum/Cargo.toml
- crates/ethereum/src/lib.rs
This PR adds handling of subscription close / error cases by resubscribing to logs.
It also upgrades `alloy` to 0.12.4 and adds some trace events so that we can have a better understanding of what's happening in the L1 update task.
Closes: #2652
> fix(ethereum): handle closing of LogStateUpdate subscription

- Cargo.lock
- crates/p2p/Cargo.toml
- crates/p2p/src/behaviour.rs
- crates/p2p/src/behaviour/builder.rs
- crates/p2p/src/client/peer_agnostic.rs
- crates/p2p/src/client/peer_aware.rs
- crates/p2p/src/lib.rs
- crates/p2p/src/main_loop.rs
- crates/p2p/src/test_utils/main_loop.rs
- crates/p2p/src/tests.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/p2p_network.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
We're moving towards a two-network approach:
1. **Sync:** How nodes sync with each other.
2. **Consensus:** Handling real-time chain updates (etc.)
This PR trims out all code that was related to `2` from our current P2P implementation, leaving just everything related to `1`. as we start moving towards this new two-network approach.
> feat/p2p: remove consensus-related functionality ahead of network split

- crates/pathfinder/src/bin/pathfinder/config.rs
After the Starknet mainnet upgrade to 0.13.5 there were a few blocks (like 1256131) for which state updates cannot be reliably fetched within five seconds.
This change increases the default request timeout to 10 seconds.
Closes #2673
> fix(pathfinder/config): increase default request timeout to 10 seconds

- crates/class-hash/src/lib.rs
Hi! I fixed broken links in the Starknet documentation within the `crates/class-hash/src/lib.rs` file. The links were outdated and pointed to incorrect URLs.
Delete once completed:
> chore: fixed broken links

- utils/pathfinder-probe/Cargo.lock
- utils/pathfinder-probe/Cargo.toml
`pathfinder-probe` was using reqwest with an outdated openssl crate that is vulnerable to CVE-2025-24898.
This change updates all dependencies and switches to using rustls instead of openssl to align better with the rest of our code.
> chore(pathfinder-probe): update dependencies and use rustls

- crates/rpc/src/jsonrpc/router.rs
- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/method/subscribe_events.rs
- crates/rpc/src/middleware/tracing.rs
This PR adds some more tracing spans and events in the JSON-RPC code, especially for subscriptions. Now per-call and per-subscription spans are created that capture the request and subscription ID for the whole duration of the processing code.
> chore(rpc): improve RPC and subscriptions tracing

- CHANGELOG.md
- crates/rpc/src/jsonrpc/router/subscription.rs
Code sending Websocket notifications had a check that skipped notifications that were not sent for the next block number. This check might make sense for block header subscriptions, but definitely does not work for events and transaction status changes.
This PR removes that check.
Closes #2682
> fix(rpc/subscription): don't ignore notifications after skipped blocks

- CHANGELOG.md
- crates/rpc/src/lib.rs
- docs/docs/interacting-with-pathfinder/json-rpc-api.md
- docs/docs/interacting-with-pathfinder/websocket-api.md
To make it easier for users to route Websocket connections to our API for all supported JSON-RPC versions, this PR adds the `/ws/rpc/v0_8` route as an alias for `/rpc/v0_8` if the (legacy) Websocket APIs are enabled (that serve JSON-RPC 0.6 and 0.7).
Closes #2688
> feat(rpc): add `/ws/rpc/v0_8` route for the JSON-RPC 0.8.0 API

- CHANGELOG.md
- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/method/subscribe_events.rs
- crates/rpc/src/method/subscribe_new_heads.rs
- crates/rpc/src/method/subscribe_pending_transactions.rs
To follow up a change in the JSON-RPC 0.8.1 specification, subscription_id is now a string instead of an integer.
Closes #2692
> feat(rpc/subscription): make `subscription_id` a string

- CHANGELOG.md
- crates/rpc/src/v08.rs
- docs/docs/interacting-with-pathfinder/json-rpc-api.md
- docs/docs/interacting-with-pathfinder/websocket-api.md
- specs/rpc/v08/starknet_api_openrpc.json
- specs/rpc/v08/starknet_executables.json
- specs/rpc/v08/starknet_trace_api_openrpc.json
- specs/rpc/v08/starknet_ws_api.json
This PR:
- Updates the OpenRPC specifications in our repo.
- Changes the value returned by `starknet_specVersion` to `0.8.1`.
- Adds a changelog entry.
Please note that upstream OpenRPC files have been reformatted (using Prettier), so please check this PR commit-by-commit to get the _real_ diff to the spec.
Closes: #2693
> chore(rpc): update OpenRPC specification to 0.8.1

- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/lib.rs
Instead of using a global subscription ID counter, we now use a per-connection counter to generate unique subscription IDs. This has the advantage of not leaking global state (like: total number of subscriptions so far) to individual clients.
> refactor(rpc): use per-connection subscription IDs

- CHANGELOG.md
- crates/storage/src/schema/revision_0066.rs
Fixes the aggregate bloom filter migration. It now accounts for the possibility that a block might not have an associated entry in the `starknet_events_filters` table.
Closes https://github.com/eqlabs/pathfinder/issues/2691.
> fix: aggregate bloom filter migration

- CHANGELOG.md
- crates/executor/src/estimate.rs
- crates/executor/src/simulate.rs
- crates/executor/src/transaction.rs
- crates/executor/src/types.rs
- crates/rpc/fixtures/0.8.0/simulations/declare_deploy_and_invoke_sierra_class_starknet_0_13_4.json
During fee estimation, after finding the minimum L2 gas, we are re-running the transaction in case the initial L2 gas value in the transaction is too low. This is done so that simulate can return the proper error / reverted transaction.
There were two issues with our code:
1. We were always executing using `ExecutionBehaviorOnRevert::Fail`, which means that we were not able to return the reverted transaction (but return an error instead).
2. We were using an L2 gas vale of zero instead of the initial L2 gas during execution, which potentially lead to a different error.
This change addresses these issues and also fixes an imprecision. We have been using the transaction receipt in `TransactionExecutionInfo` to return the proper minimun L2 gas value to the caller in …
> fix(executor): simulate should return reverted transaction if L2 cap is too low

- CHANGELOG.md
- crates/rpc/src/method/trace_block_transactions.rs
- crates/rpc/src/method/trace_transaction.rs
When doing transaction traces we have a check that checks if the Starknet version is supported. If it's less than the earliest version we support for execution, then we try and fall back to the feeder gateway before even trying execution.
We also had a check that if a `TransactionExecutionError` was returned during tracing, we would fall back to the feeder gateway. This is not needed and can be removed, since at that point we can be sure that the version is supported and the feeder gateway will just return an error (it doesn't actually have traces from 0.13.1.1, our earliest supported version).
This change removes this fallback, which in turn was masking the error message that was generated during execution: the feeder gateway error was transformed into an `InternalError` and no details …
> fix(rpc/trace): don't fall back to fetching traces from feeder gateway for unsupported versions

- CHANGELOG.md
- crates/storage/src/connection/event.rs
There's a bug in the processing logic when we combine `max_event_filters_to_load` in the SQLite query and cached filters that are within the block range.
Due to simply appending the cached aggregate filters to the set of filters returned it's possible that there's a hole in the block range covered by the filters. In case there are more than `max_event_filters_to_load` filters in the database, we stop loading filters when we reach the limit. However, the cached filters that are appended to the result set may not be contiguous with the last filter in the result set.
This breaks the assumption that the filters returned by `load_event_filter_range()` are contiguous, which causes `events()` to just skip evaluating ranges of blocks that are not covered by the filters.
Closes #2709
> fix(storage/events): don't return non-contiguous aggregate filters in `load_event_filter_range()`

- CHANGELOG.md
- crates/rpc/src/dto.rs
- crates/rpc/src/jsonrpc/request.rs
- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/method/subscribe_new_heads.rs
`starknet_unsubscribe` was not parsing the subscription id correctly. Instead of using the `DeserializeForVersion` implementation for the subscription id, it was simply using `serde::Deserialize` which was defaulting to parsing the subscription id as an integer.
Closes: #2720
> fix(rpc): fix subscription id parsing for `starknet_unsubscribe`

- .github/workflows/ci.yml
- .github/workflows/publish-crates.yml
- .github/workflows/release.yml
- Dockerfile
- rust-toolchain.toml
Add `rust-toolchain.toml`, pinning the version of Rust we use to 1.85.1.
> chore: add rust-toolchain.toml

- crates/pathfinder/examples/dump_events.rs
A script for event queries "below" RPC API (for test purposes), i.e. a completely unoptimized walk through all events in a block range, as envisioned in https://github.com/eqlabs/pathfinder/issues/2715 . Generates JSONL files, uses existing Pathfinder public interface.
> feat: data generator for starknet-event-query test

- CHANGELOG.md
- crates/executor/src/transaction.rs
- crates/rpc/src/method/estimate_fee.rs
Turns out that we have two issues with DEPLOY_ACCOUNT estimation, both triggered by Braavos account deployments.
The first one is that `l2_gas_accounting_enabled()` does not work for all DEPLOY_ACCOUNT transactions. We were trying to fetch the class hash for the sender of the transaction, but for DEPLOY_ACCOUNT that is the address of the account that is being deployed, so no class hash is present yet. Because of this we were always running DEPLOY_ACCOUNT transactions with L2 gas accounting disabled.
Even if we had the class hash, we would still fail for Braavos accounts. The trick is that Braavos accounds are deployed in a special way: they are always using the same class hash, and the constructor immediately replaces the deployed class hash with a new one that is received as part of the …
> fix(executor): fix DEPLOY_ACCOUNT transaction estimation

- CHANGELOG.md
- crates/executor/src/types.rs
- crates/rpc/fixtures/mainnet-200.json
- crates/rpc/src/dto/simulation.rs
- crates/rpc/src/method/simulate_transactions.rs
- crates/rpc/src/method/trace_block_transactions.rs
For pre-0.9 Starknet blocks the feeder gateway returns a block trace response that is missing the call_type field for all function invocations.
Turns out it's not just `call_type` that might be missing, but -- based on our `starknet_gateway_types::trace::FunctionInvocation` type `selector` and `entry_point_type` might also be  missing.
According to Starkware we cannot simply default `call_type` to any value, since these pre-0.9 calls are neither CALL nor DELEGATE, so we would be inaccurate if we were to return those values.
This doesn't leave too much choice but to break the JSON-RPC spec by not including these properties in function invocation responses if they are missing from the feeder gateway response.
Closes #2728
> fix(rpc): handle missing call_type field in feeder gateway block trace responses

- crates/pathfinder/src/bin/pathfinder/main.rs
Previously they didn't, unless they were directly from the pathfinder crate.
> chore: showing tracing errors by default

- .github/workflows/release.yml
This PR adds a new release binary for `aarch64-unknown-linux-gnu`.
Closes #2742
> chore(github): build aarch64 Linux release binary

- crates/pathfinder/src/state/block_hash.rs
https://docs.starknet.io/docs/Blocks/header/#block-hash - 404 link
https://docs.starknet.io/architecture-and-concepts/network-architecture/block-structure/#block-hash - work link
> replace 404 reference block_hash.rs

- crates/executor/src/execution_state.rs
- crates/rpc/fixtures/0.6.0/simulations/declare_deploy_and_invoke_sierra_class_starknet_0_13_4.json
- crates/rpc/fixtures/0.6.0/simulations/declare_deploy_and_invoke_sierra_class_starknet_0_14_0.json
- crates/rpc/fixtures/0.7.0/simulations/declare_deploy_and_invoke_sierra_class_starknet_0_13_4.json
- crates/rpc/fixtures/0.7.0/simulations/declare_deploy_and_invoke_sierra_class_starknet_0_14_0.json
- crates/rpc/fixtures/0.8.0/simulations/declare_deploy_and_invoke_sierra_class_starknet_0_14_0.json
- crates/rpc/fixtures/0.9.0/simulations/declare_deploy_and_invoke_sierra_class_starknet_0_14_0.json
- crates/rpc/src/method/simulate_transactions.rs
This PR fixes an oversight we've made when adding Starknet 0.14.0 support: we have to explicitly add the new versioned constants, otherwise execution on 0.14.0  will _still_ use 0.13.5 constants.
> fix(executor): add versioned constants for 0.14.0

- crates/rpc/src/context.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/method/call.rs
- crates/rpc/src/method/estimate_fee.rs
- crates/rpc/src/method/estimate_message_fee.rs
- crates/rpc/src/method/get_block_transaction_count.rs
- crates/rpc/src/method/get_block_with_receipts.rs
- crates/rpc/src/method/get_block_with_tx_hashes.rs
- crates/rpc/src/method/get_block_with_txs.rs
- crates/rpc/src/method/get_class.rs
- crates/rpc/src/method/get_class_at.rs
- crates/rpc/src/method/get_class_hash_at.rs
- crates/rpc/src/method/get_events.rs
- crates/rpc/src/method/get_messages_status.rs
- crates/rpc/src/method/get_nonce.rs
- crates/rpc/src/method/get_state_update.rs
- crates/rpc/src/method/get_storage_at.rs
- crates/rpc/src/method/get_transaction_by_block_id_and_index.rs
- crates/rpc/src/method/get_transaction_by_hash.rs
- crates/rpc/src/method/get_transaction_receipt.rs
- crates/rpc/src/method/get_transaction_status.rs
- crates/rpc/src/method/simulate_transactions.rs
- crates/rpc/src/method/trace_block_transactions.rs
- crates/rpc/src/method/trace_transaction.rs
- crates/rpc/src/pathfinder/methods/get_transaction_status.rs
- crates/rpc/src/pending.rs
`PendingWatcher::get()` now uses the JSON-RPC API version number to decide whether to return the pre-committed block data.
For JSON-RPC 0.9 and up, the data is returned as is.
For older JSON-RPC versions we return an empty pre-committed block instead.
Closes: #2801
> fix(rpc/pending): use pre-confirmed block only for JSON-RPC 0.9 and up

- CHANGELOG.md
- crates/executor/src/transaction.rs
- crates/rpc/src/method/estimate_fee.rs
Previously, we have introduced a change that sets the maximum L2 gas limit for the initial transaction run to the maximal value that the account balance allows. This is done because blockifier _does_ check that the committed resources are covered by the account balance.
However, that check is done only if the `charge_fee` flag is set (which is the case for `starknet_simulateTransactions` only, unless `SKIP_FEE_CHARGE` is set).
This means that for `starknet_estimateFee` we cannot estimate transactions for accounts that are not yet funded properly, even though blockifier would allow it.
This commit changes the logic to use the balance-dependent limit only when the `charge_fee` flag is set, and uses blockifier's default limit for per-transaction L2 gas otherwise.
Closes: #2807
> fix(executor): correct max L2 limit in L2 gas estimation logic

- crates/consensus/src/internal.rs
Noticed that I hadn't implemented Malachite's `Effect::ResetTimeouts` effect, so this this PR adds support for it and includes comprehensive unit tests for the timeout manager, which uncovered  a bug in the cancellation logic which has now been fixed.
> Consensus: Add `ResetTimeouts` effect handling

- crates/rpc/src/error.rs
- crates/rpc/src/method/add_declare_transaction.rs
- crates/rpc/src/method/add_deploy_account_transaction.rs
- crates/rpc/src/method/add_invoke_transaction.rs
And make sure we return the INVALID_TRANSACTION_NONCE error in case the gateway is returning an invalid nonce error.
This is slightly complicated by the fact that the gateway is returning a "validation failure" error instead of the "invalid nonce" error, so the only way for us to detect this is to check the error message for the presence of the "invalid nonce" string.
Closes: #2799
> feat(rpc/v09): update INVALID_TRANSACTION_NONCE error with additional data

- crates/rpc/src/dto/block.rs
We treat it as a synonym for "pending" right now: the internal representation is BlockId::Pending, because that's what our code handles.
Semantic differences between "pre_confirmed" and "pending" are already handled based on the actual type of the pending data we have.
Closes: #2793
> feat(rpc): parse "pre_confirmed" block ID in JSON-RPC 0.9

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/class-hash/Cargo.toml
- crates/common/Cargo.toml
- crates/load-test/Cargo.lock
- crates/p2p/Cargo.toml
- crates/serde/Cargo.toml
I've aggregated all `0.17.0-beta.X` changes into a single v0.17.0 `CHANGELOG.md` entry.
If anyone believes this is not the way to go, feel free to speak up.
> chore: bump version to 0.17.0

- Cargo.lock
- crates/consensus/Cargo.toml
- crates/consensus/src/config.rs
- crates/consensus/src/internal.rs
- crates/consensus/src/lib.rs
- crates/consensus/src/wal.rs
- crates/consensus/tests/common.rs
- crates/consensus/tests/consensus_sim.rs
- crates/consensus/tests/timeouts.rs
- crates/consensus/tests/wal.rs
This PR implements recovery from the write-ahead log (WAL), allowing the consensus engine to resume from previously incomplete heights on startup. The engine now scans persisted WAL files, identifies which heights were not finalized, and replays their entries into the consensus logic to continue where it left off.
It is up to the host application to start a fresh Consensus engine with `Consensus::new(config)` or, if we're recovering from a crash, use `Consensus::recover(config, validator_set_provider)` instead.
Includes a test to verify recovery flows correctly from persisted state.
> Consensus: Introduce WAL recovery

- CHANGELOG.md
- crates/storage/src/lib.rs
The blockchain pruning flag was updated _before_ the actual validation was performed, leading to a situation where on the next run the blockchain pruning mode was already enabled for a database that was _not_ created with pruning enabled.
Closes: #2839
> fix(storage): fix blockchain pruning check

- crates/common/src/lib.rs
- crates/gateway-types/src/request.rs
Turns out we were not using the serde serialization implementations, and some of the related types in the gateway types crate.
> refactor: remove unused BlockId-related implementations and types

- crates/class-hash/README.md
Self-explanatory.
I chose to link MIT license for no particular reason, although the badge will display we allow both.
> Fix broken license badge link in `class-hash` crate

- scripts/release.sh
The consensus crate depends on `crypto` and `common`, so it has to be updated when bumping the version number.
Closes #2822
> chore(release): add consensus crate

- crates/rpc/src/jsonrpc/router/subscription.rs
- crates/rpc/src/method/subscribe_events.rs
The `SubscribeEvents::subscribe()` method did not exit properly if sending the notification failed due to the channel being closed (usually triggered by the underlying Websocket connection closing).
The issue was that for some error cases `break` was being used inside a `for` loop that simply exited that loop instead of exiting the method.
> fix(rpc/subscribe_events): fix event subscription task leak

- CHANGELOG.md
- Dockerfile
This is especially useful for running Pathfinder on an IPv6-enabled host, where `localhost` might resolve to `::1` and exposing the JSON-RPC port via Docker requires internally binding to the IPv6 wildcard address `[::]`.
> fix(Dockerfile): change default JSON-RPC listen address IPv6 wildcard address

- CHANGELOG.md
- crates/rpc/src/executor.rs
This commit updates the RPC executor to use non-strict nonce checking when estimating or simulating transactions. This matches the behavior of Starknet 0.14.0, where nonce checking does not require that the nonce is exactly one more than the last known nonce.
> fix(rpc): use non-strict nonce checking for estimation / simulation

- CHANGELOG.md
- crates/rpc/src/method/get_transaction_status.rs
for locally unknown transactions.
Fixes #2886 .
> fix(rpc): do not return ACCEPTED_* transaction status from gateway

- justfile
So that it's easier to test potential problems locally.
> chore(justfile): add recipes enabling all features

- crates/common/src/transaction.rs
- crates/rpc/src/dto/receipt.rs
- crates/rpc/src/method.rs
- crates/rpc/src/method/subscribe_new_transaction_receipts.rs
- crates/rpc/src/types/receipt.rs
- crates/rpc/src/v09.rs
This PR adds an implementation for the `subscribe_newTransactionReceipts` JSON-RPC method introduced in JSON-RPC 0.9.0-rc.3.
This method sends notifications for new transaction receipts with a finality state specified in the request (defaults to ACCEPTED_ON_L2, but users can request PRE_CONFIRMED receipts as well).
> feat(rpc/v09): implement `subscribe_newTransactionReceipts` RPC method

- crates/rpc/src/dto/receipt.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/method.rs
- crates/rpc/src/method/get_transaction_status.rs
- crates/rpc/src/method/subscribe_new_transactions.rs
- crates/rpc/src/v09.rs
- specs/rpc/v09/starknet_api_openrpc.json
- specs/rpc/v09/starknet_executables.json
- specs/rpc/v09/starknet_trace_api_openrpc.json
- specs/rpc/v09/starknet_write_api.json
- specs/rpc/v09/starknet_ws_api.json
JSON-RPC 0.9.0-rc.3 has introduced `starknet_subscribeNewTransactions` that is an extension of the previous `starknet_subscribePendingTransactions`.
It implements reliable streaming of transactions candidate/pre-confirmed/accepted_on_l2 transactions, where a new notification is sent for each new transaction and each finality status change.
This PR also updates the in-tree OpenRPC specification files to 0.9.0-rc.3.
> feat(rpc/v09): implement `starknet_subscribeNewTransactions`

- justfile
So that we indeed skip the P2P serialization proptests.
> chore(justfile): fix proptest names

- .github/workflows/publish-crates.yml
Publishing the `consensus` crate not only allows it to be used by anyone, but more importantly it is the only way I've found that will make the [docs link](https://github.com/eqlabs/pathfinder/tree/main/crates/consensus) work.
> chore(ci): publish `consensus` crate

- crates/rpc/fixtures/0.9.0/transactions/receipt_pending.json
- crates/rpc/fixtures/0.9.0/transactions/receipt_pre_confirmed.json
- crates/rpc/fixtures/0.9.0/transactions/receipt_reverted_pending.json
- crates/rpc/src/dto/receipt.rs
- crates/rpc/src/method/get_transaction_receipt.rs
- crates/rpc/src/method/subscribe_new_transaction_receipts.rs
Short description of what this PR does.
---------------------
Adds `block_number` to `TXN_RECEIPT_WITH_BLOCK_INFO` for `Pending`
Fixes #2889
> JSON-RPC: block_number is now required in TXN_RECEIPT_WITH_BLOCK_INFO

- crates/rpc/src/method/get_transaction_status.rs
even if they aren't in local storage (yet).
The fix for https://github.com/eqlabs/pathfinder/issues/2886 was too radical - the node shouldn't deny knowing about transactions passed through it.
> fix(rpc): admit knowing about own transactions accepted by gateway

- crates/rpc/src/method/subscribe_new_transactions.rs
Fixes #2910.
Typo in RPC method name `starknet_subscriptionNewTransactions`. Should be `starknet_subscriptionNewTransaction`.
> fix: wrong rpc method name `starknet_subscriptionNewTransactions`

- Dockerfile
Ever since we've added `rust-toolchain.toml` to the repository, Docker builds do re-download the toolchain even though we should just be using the one already installed in the image.
This commit updates the Dockerfile to exclude the `rust-toolchain.toml` file from the build context, so that the toolchain is not reinstalled.
> fix(docker): don't reinstall Rust toolchain

- CHANGELOG.md
- crates/storage/src/connection/transaction.rs
When processing a query with a block range that involves empty blocks (blocks with zero transactions / events) `starknet_getEvents` would stop scanning at the first empty block.
This is bad, because it doesn't even return a continuation token so users would have no way of knowing that there are more events.
The issue is that `query_events_by_block()` is returning an `Option`, and `None` is being interpreted as "no block found", which causes the scan to stop prematurely when encountering empty blocks.
To fix this, we need to ensure that we handle no events correctly in `events_for_block()` and just return an empty vector of events instead of returning `None`.
Closes #2913
> fix(rpc/method/get_events): fix `starknet_getEvents` for empty blocks

- Dockerfile
According to the Dockerfile [reference](https://docs.docker.com/reference/dockerfile/#copy) the `--exclude` COPY option is only available starting from the `1.7-labs` Dockerfile version.
> chore(Dockerfile): add version to dockerfile

- .github/workflows/publish-crates.yml
- Cargo.lock
- crates/consensus/Cargo.toml
- crates/p2p/Cargo.toml
- scripts/release.sh
The `consensus` crate could not be published because it still had an old `p2p_proto` dependency sitting there.
> fix(ci): remove `p2p_proto` dependency form `consensus`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
`cairo-vm` and `cairo-native` have been upgraded as well to match the dependencies of the new `blockifier` version.
Closes #2958
> chore: upgrade `blockifier` to 0.15.0-rc.3

- crates/p2p_proto/Cargo.toml
For some reason which I haven't dug into, this was missing, causing a simple `cargo c -p p2p_proto` to fail.
> fix(`p2p_proto`): add `derive` feature to `serde`

- crates/gateway-test-fixtures/fixtures/traces/transaction_sepolia_testnet_0x6a4a.json
- crates/gateway-test-fixtures/src/lib.rs
- crates/gateway-types/src/trace.rs
- crates/rpc/src/method/trace_block_transactions.rs
and also `cairo_native`. The `gas_consumed` value is interpreted as L2 gas.
Fixes #2954.
> fix: extended trace function invocation with optional `gas_consumed`

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
Pathfinder can only do reorgs within the capacity of the block cache.
Unfortunately the recent L2 reorg on Starknet Mainnet was larger than the previous cache size of 1k blocks, which caused the reorg attempt to fail and Pathfinder was stuck in a loop trying to do the reorg again and again.
> fix(sync): bump block cache size to 10k blocks

- crates/p2p_proto/Makefile
- crates/p2p_proto/README.md
Checks for minimum required Python version before attempting to run the `sync` scripts.
Otherwise, the user gets a really ugly error.
Also, added a simple README.md
> fix(p2p_proto): check for minimum required python version on `make sync`

- CHANGELOG.md
- crates/rpc/src/method/subscribe_new_transaction_receipts.rs
- crates/rpc/src/method/subscribe_new_transactions.rs
Analogous to `starknet_subscribeEvents`.
Fixes https://github.com/eqlabs/pathfinder/issues/2947 .
> feat: reorg notifications for `starknet_subscribeNewTransactions` and `starknet_subscribeNewTransactionReceipts`

- CHANGELOG.md
- crates/pathfinder/src/state/sync/l2.rs
When performing a bulk sync, we need to validate that the blocks we are receiving are indeed a continuation of our current chain. This is done after performing all other validations.
Note that we do _not_ handle reorgs during bulk sync, but simply give up bulk syncing and revert back to the block-by-block sync algorithm that then handles the reorg itself.
Closes #2992
> fix(pathfinder/sync/l2): properly check for reorgs during bulk sync

- CHANGELOG.md
- crates/rpc/src/method/subscribe_pending_transactions.rs
After the Starknet 0.14.0 update, the pending block is no more. Some code has been added to the `subscribe_pendingTransactions` handler to ignore pre-confirmed block updates, but unfortunately it has resulted in a busy loop, as we never actually wait for a new pending update before checking the block again.
This change fixes that loop and makes sure we actually wait for an update before performing the check again.
> fix(rpc/v0_8/subscribe_pending_transactions): avoid busy loop with Starknet 0.14.0

- crates/feeder-gateway/src/main.rs
- crates/p2p/src/sync/client/peer_agnostic.rs
- crates/pathfinder/examples/dump_events.rs
- crates/pathfinder/src/p2p_network/consensus.rs
- crates/pathfinder/src/p2p_network/sync.rs
- crates/pathfinder/src/p2p_network/sync/sync_handlers.rs
- crates/rpc/src/types.rs
... for Options used in functions/closures returning `anyhow::Result`.
[Because `Option` implements `Context::context`.](https://docs.rs/anyhow/latest/src/anyhow/context.rs.html#90-113)
> refactor: use anyhow::Context::context instead of ok_or_else paired with anyhow::anyhow

- crates/common/src/lib.rs
- crates/consensus/src/internal.rs
- crates/consensus/src/internal/wal.rs
- crates/consensus/src/lib.rs
- crates/consensus/tests/consensus_sim.rs
- crates/consensus/tests/wal.rs
- crates/ethereum/src/lib.rs
- crates/executor/src/execution_state.rs
- crates/feeder-gateway/Cargo.toml
- crates/gateway-client/src/builder.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/consensus/inner.rs
- crates/pathfinder/src/consensus/inner/consensus_task.rs
- crates/pathfinder/src/consensus/inner/p2p_task.rs
- crates/pathfinder/src/p2p_network/common.rs
- crates/pathfinder/src/sync.rs
- crates/pathfinder/src/validator.rs
- crates/pathfinder/tests/consensus_smoke.rs
- crates/rpc/src/dto/primitives.rs
- crates/rpc/src/method/consensus_info.rs
This PR introduces the following changes:
- Fixes: https://github.com/eqlabs/pathfinder/issues/2930
- Fixes: https://github.com/eqlabs/pathfinder/issues/2931
- Fixes: https://github.com/eqlabs/pathfinder/issues/2938
- a Pathfinder instance that is configured as a proposer will produce empty proposals which are consistent from genesis and beyond the 10th block boundary. Previously we just used a hard-coded proposal commitment that was only valid for block range `0..=9`, because from block `10` onward, the state diff contains system contract `0x1` with the historical block hash value (ie. 10 blocks back in history)
Important stuff when running a manual test:
- [scripts.zip](https://github.com/user-attachments/files/22256629/scripts.zip)
- a mock feeder gateway is used because it then …
> commit decided upon block

- CHANGELOG.md
- crates/storage/src/schema/revision_0074.rs
When rebuilding the running event filter, ensure that the block range (from_block to to_block) is also updated to reflect the range of blocks covered by the rebuilt filter.
The database might have a completely outdated running event filter, so it's important to ensure that the correct block range is set.
Closes: #2983
> fix(storage/schema/revision_0074): update block range in running event filter

- crates/executor/src/execution_state.rs
When using custom versioned constants without the JSON version mapping file, the custom versioned constants are supposed to be used for the _latest_ Starknet version known to Pathfinder.
This change updates the latest version to Starknet 0.14.0 -- this was left out when we have added support for Starknet 0.14.0...
> fix(executor): fix custom versioned constants legacy setting

- crates/pathfinder/src/consensus/inner/consensus_task.rs
- crates/pathfinder/src/consensus/inner/p2p_task.rs
- crates/pathfinder/src/validator.rs
Also added ProposalCommitment to the empty proposal (which is being flaky, and fixes to it will probably require changes to this PR as well).
Fixes https://github.com/eqlabs/pathfinder/issues/3009 .
> feat: using ProposalPart's ProposalCommitment for validation

- crates/consensus/src/internal.rs
- crates/consensus/src/internal/malachite.rs
- crates/consensus/src/internal/wal.rs
- crates/consensus/src/lib.rs
- crates/consensus/tests/common.rs
- crates/consensus/tests/consensus_sim.rs
- crates/consensus/tests/custom_proposer.rs
- crates/consensus/tests/timeouts.rs
- crates/consensus/tests/wal.rs
- crates/pathfinder/src/config.rs
- crates/pathfinder/src/consensus/inner.rs
- crates/pathfinder/src/consensus/inner/consensus_task.rs
- crates/pathfinder/src/consensus/inner/select_proposer.rs
This PR adds the ability to customize how proposers are selected in the consensus engine. Instead of being stuck with round-robin, you can now plug in your own proposer selection logic via the new `ProposerSelector<A>` trait.
I've tried to keep the API as backwards-compatible as possible, leaving the previous `new(..)` and `recover(..)` methods untouched.
To set your own proposer selection logic, you can use the builder pattern: 
```rust
Consensus::new(config)
.with_proposer_selector(your_selector);
```
Using `recover(..)` will default to the `RoundRobinProposerSelector` (we can always change that), unless chained with `.with_proposer_selector(your_selector)`. So again, same easy, backwards-compatible logic.
```rust
// Will default to round-robin
Consensus::recover(..)?;
// Will use your …
```
> feat(consensus): Configurable proposer selection

- scripts/release.sh
The whole goal of [automating tag creation](https://github.com/eqlabs/pathfinder/pull/2967) was that anyone, without prior knowledge, could cut a release.
Apparently, the auto-tag feature won't work due to a Github limitation that prevents other workflows (e.g. Docker) from triggering.
So I've [rolled back](https://github.com/eqlabs/pathfinder/pull/3028) the auto-tag and instead added it to our release script. This preserves my initial intention of guiding anyone through the process seamlessly, while circumventing this dumb Github restriction.
🍻 
---
See also #3028
> feat(ci): add tag creation to our release script

- CHANGELOG.md
- crates/executor/src/transaction.rs
When a transaction runs out of gas during the validation phase, it should be re-attempted with a higher gas limit. Unlike execution phase failures, validation failures due to insufficient gas do not cause a transaction to be reverted.
This change introduces logic to detect out-of-gas errors during validation so that we correctly adjust the gas limit during the binary search for the appropriate gas limit.
Closes #3037
> fix(executor): detect and handle out-of-gas errors during validation
