eqlabs/pathfinder

- examples/fact_retrieval.rs
- resources/contracts/core_impl.json
- resources/contracts/gps_statement_verifier.json
- resources/contracts/memory_page_fact_registry.json
- src/bin/pathfinder.rs
- src/ethereum.rs
- src/ethereum/starknet.rs
- src/ethereum/starknet/contract.rs
- src/ethereum/starknet/contract/core.rs
- src/ethereum/starknet/contract/gps.rs
- src/ethereum/starknet/contract/mempage.rs
- src/ethereum/starknet/state_root.rs
The main focus of this PR is twofold:
1. Support state update and state transition logs
2. A mechanism for retrieving a stream of state update logs from L1, while checking for reorgs
Unfortunately, there is quite a bit of refactoring as collateral damage. And this is an area that needs further refactoring still (I had previously added a bunch of abstractions that I now know is not required). I would suggest not focusing too much on these parts if possible.
The main thing I would like some thoughts on, is the approach used for the [state update stream](https://github.com/eqlabs/pathfinder/pull/34/files#diff-89971bac4a720b97e52dbbb50390385b7281b308bcfd9c14b31ee4ac95984e90).
> state update and transition logs

- Cargo.toml
- benches/pedersen.rs
- src/lib.rs
- src/pedersen.rs
This is an initial, not-optimized version with only basic testing.
More test cases are required before we are comfortable it is correct.
Note: `ff` dependency is reliant on a [fork I made](https://github.com/eqlabs/ff/tree/derive_bitvec) in order to work-around the `bitvec`-`funty` nonsense.
> feat: add pedersen hash

- .github/workflows/ci.yml
- Cargo.toml
- src/rpc.rs
- src/rpc/rpc_impl.rs
- src/rpc/rpc_trait.rs
- src/rpc/types.rs
- src/sequencer.rs
- src/sequencer/reply.rs
Upgrade sequencer client to handle alpha4 api changes. At the moment the main problem are gateway timeouts on the sequencer side, so tests which tend to get 504 most of the time are ignored until this is resolved.
> fix(sequencer): upgrade to alpha4 API, block related changes

- rpc_examples.sh
- src/ethereum/log/fetch/backward.rs
- src/rpc.rs
- src/rpc/api.rs
- src/rpc/types.rs
- src/sequencer.rs
- src/sequencer/reply.rs
- src/sequencer/request.rs
This PR adds:
- proper reply types for JSON-RPC methods, which means that each method will not return sequencer API specific structs anymore, but perform appropriate mapping instead,
- Starkware specific error codes, as described in the spec.
> Proper RPC reply types and error codes

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/error.rs
- crates/pathfinder/src/sequencer/reply.rs
This is an attempt to clean up how sequencer errors are handled.
* I grouped the types of errors into 4 categories.
* `anyhow::Error` is only used as a vehicle for various parsing errors which are not `serde_json` specific and cannot be really wrapped in the latter.
* Moreover the rpc code has become simpler as there is now a single point of converting sequencer errors into `jsonrpsee::types::Error`.
* Oh, and starknet specific errors have to be handled in a special way as they are accompanied by HTTP status code 500.
Lemme know what you think.
> fix(sequencer): clean up sequencer error types

- py/README.md
- py/src/generate_test_global_tree.py
- py/src/test_generate_test_global_tree.py
Tests pass:
- single contract tree
- two instances of the same contract tree
Contract state json is just expected to exist, not asserted. We don't need to care about this cairo-lang impl detail.
> feat(py): cairo-lang generator for main trees

- crates/pathfinder/examples/fact_retrieval.rs
- crates/pathfinder/resources/contracts/core_impl.json
- crates/pathfinder/src/ethereum/contract.rs
- crates/pathfinder/src/ethereum/log.rs
- crates/pathfinder/src/ethereum/log/parse.rs
- crates/pathfinder/src/ethereum/state_update.rs
- crates/pathfinder/src/ethereum/state_update/state_root.rs
The `0.7` upgrade included a change to the StarkNet L1 core contract implementation. The core contract consists of a proxy contract, which points to the actual implementation contract. The proxy remains the same, but the implementation address and ABI were updated as part of the upgrade.
The only ABI change that we care about, was the change in the `StateUpdateLog`. Thankfully it is just a cosmetic change - `sequenceNumber` became `blockNumber`. And thankfully we can still parse the logs from the previous contract (with `sequenceNumber`) using the current contract (with `blockNumber`). I presume this is because the parameter names don't matter, only the types and amounts.
PR change log
- updated the contract ABI
- updated internal naming to match starknet naming (`sequence_number` -> …
> feat: updated ethereum for `0.7` changes

- .github/workflows/ci.yml
- crates/pathfinder/rpc_examples.sh
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/reply.rs
Included changes
* align with api changes that version 0.7.0 introduced
* add a default timeout for sequencer client requests
* use a single inner reqwest::Client
* add named ctors for both goerli and mainnet
> feat: align with cairo release 0.7.0

- crates/pedersen/src/curve.rs
- crates/pedersen/src/field.rs
- crates/pedersen/src/lib.rs
Modified the curve to in-place ops. and added projective coordinates -- improving time for Pedersen hash about 10x.
> Faster curve with projective coordinates

- crates/pathfinder/src/core.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/contract.rs
- crates/pathfinder/src/storage/state.rs
This PR essentially removes all the table prototypes we had before (these weren't in use yet).
It keeps the foreign key and migration logic (more or less), and adds support for storing contract information as well as contract state hashes (with its pre-image).
There are still many tables missing, but we can add those as we need them.
I'm looking for early feedback on the general storage layout and design before repeating the same style on the other tables.
> refactor and update storage

- .github/workflows/ci.yml
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/reply.rs
* support named arguments
* txn status is copied from block status
* try with ci running all tests again as the number of requests is much smaller now
> feat(rpc): support named args, fix txn status and ci btw

- crates/pathfinder/src/core.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/ethereum.rs
- crates/pathfinder/src/storage/state.rs
- crates/pedersen/src/lib.rs
This PR primarily adds support for storing global StarkNet state.
A state update needs to be linked to its origin point on Ethereum. Specifically, we need to track which Ethereum log created the state update. To enable the tracking I've created two Ethereum tables, `ethereum_blocks` and `ethereum_transactions`. The transactions table references (foreign key) the block table.
The global state table then links to a specific Ethereum transaction (which in turn links to the Ethereum block).
I separated out the blocks and transactions because in the future we will likely have more information referencing these as well. In addition there can be many logs per transaction and many transactions per block. So it made sense to normalize them.
> Add global state storage support

- crates/pedersen/src/lib.rs
Extends StarkHash formatting options with support for `Fmt`, `UpperHex`, `LowerHex` (`Debug` already existed).
`Fmt` and `Debug`  add the `0x` prefix. e.g.
```
0x...0123456789ABCDEF  // Fmt
StarkHash(0x...0123456789ABCDEF) // Debug
```
Currently all options do print leading zeros. I'm considering not printing them - thoughts?
> feat(pedersen): add Starkhash fmt and hex fmt

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/error.rs
- crates/pathfinder/src/sequencer/reply.rs
It turned out that using `get_block_hash_by_id` was already deprecated a long time ago (`get_block?blockNumber=` was introduced in mid December '21), hence we got the wrong hashes when querying by block number.
By the way I fixed some things that changed in the last few days:
- error mapping,
- I finally spotted a `nonce` field in the L1 to L2 message,
- more fields are now optional since pending block does not supply those values anyway
> fix: block_by_name, error mapping, nonce field

- .github/workflows/ci.yml
- README.md
- crates/pathfinder/examples/fact_retrieval.rs
- crates/pathfinder/src/config.rs
- crates/pathfinder/src/config/builder.rs
- crates/pathfinder/src/config/cli.rs
- crates/pathfinder/src/config/file.rs
- crates/pathfinder/src/ethereum.rs
- crates/pathfinder/src/ethereum/contract.rs
- crates/pathfinder/src/ethereum/state_update.rs
- crates/pathfinder/src/ethereum/state_update/state_root.rs
- crates/pathfinder/src/state.rs
This PR adds support for identifying the Ethereum chain. This will allow us to determine which network we are on.
In addition, I've replaced WebSockets with HTTP transports for the Ethereum endpoints. The original reason for using WebSockets was to utilize the pub/sub functionality. This proved to not be useful. Web3 support for WebSockets is also limited -- doesn't support setting passwords or user-agents.
Our internals are written to be transport agnostic, so this refactor mainly targets user configuration and CI / test setup.
I've also added the required CI secrets internally. Note that you will require new environment variables to run the tests locally (see README.md).
> Ethereum chain identification and websocket removal

- .github/workflows/ci.yml
- py/README.md
- py/requirements-dev.in
Keeping this upgrade separate from others. Maybe it works to highlight how the version is currently managed (in README.md and ci.yml) :)
> chore(py): upgrade cairo-lang==0.7.0

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/contract.rs
The main feature of this PR is adding a dedicated storage / database entry-point. This allows creating / migrating the database and passing the resulting entry-point to the components that require it e.g. RPC and sync process.
This entry-point has been added to the RPC component, and the `get_code` call has been updated to use it. The other calls have not been updated; want feedback before we move on to doing more.
In addition, a simplified `ContractCode` using `String` for its ABI has been added and used instead. As I understand it, only the contract definition needs to be understood / parsed so for now this is okay.
> Upgrade storage

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/sequencer.rs
* Add one more test case for `get_full_contract`.
* Remove redundant test cases, as `StarkHash` prevents sending overflowing values to the endpoints.
> test: remove redundant cases, extend full_contract test

- crates/pathfinder/src/ethereum/log/fetch.rs
- crates/pathfinder/src/ethereum/log/fetch/backward.rs
- crates/pathfinder/src/ethereum/log/fetch/forward.rs
The log fetchers rely on fetching logs from the last retrieved log. This last retrieved log was not updated on a successful fetch, so the fetch process would loop over and over at the same spot.
> fix: log fetchers do not update internal state

- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/contract.rs
- crates/pathfinder/src/storage/ethereum.rs
- crates/pathfinder/src/storage/state.rs
* Contract address to contract hash mapping is kept in a separate table now.
* I added this v1 to v2 migration "exercise" in this PR to essentially have a look at whatever problems could be encountered when considering coding such a migration. In all honesty I think it could be removed as rework to the very PR, so as not to increase the number of available versions artificially.
> Deduplicate contract definitions in the db

- crates/pathfinder/src/state.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/ethereum.rs
- crates/pathfinder/src/storage/foreign_key.rs
- crates/pathfinder/src/storage/state.rs
This demonstrates a prototype for a new constraint type -- `ForeignKey<T>`. It allows us to add foreign-key constraints to table inserts. This requires the user to demonstrate that the foreign key does already exist before being allowed to insert it as a foreign key in another table.
For example, given the following two tables:
```
Child:     |  ID  |
Parent:    |  ID, child.id  |
```
we can do this:
```rust
impl Parent {
fn insert(parent_id: ParentId, child_id: ForeignKey<ChildID>) {
// do insertation
}
}
impl Child {
fn insert(child_id: ChildID) -> ForeignKey<ChildID> {
// do insertion
ForeignKey(child_id)
}
fn get(child_id: ChildID) -> Option<ForeignKey<ChildID>> {
match id_exists(child_id) {
true => Some(ForeignKey(child_id)),
false => None,
}
}
}
fn usage() {
// This can only be …
```
> feat(storage): foreign key type

- crates/pathfinder/src/ethereum/log/fetch/forward.rs
The log fetcher updated its internal state even when no logs are found.
This condition occurs when no further logs are available i.e. when reaching the HEAD of the chain.
The backwards log fetcher does not have this issue as it can never reach HEAD.
> fix(logs): log fetching breaks upon reaching HEAD

- crates/pathfinder/src/rpc.rs
This was always broken, I must've caused this while trusting for the tests to be run on CI but this is skipped.
> test: fix wrong literal

- crates/pathfinder/examples/reorg_detection.rs
- crates/pathfinder/src/ethereum.rs
- crates/pathfinder/src/ethereum/contract.rs
- crates/pathfinder/src/ethereum/log/fetch/backward.rs
- crates/pathfinder/src/ethereum/log/fetch/forward.rs
- crates/pathfinder/src/ethereum/state_update.rs
- crates/pathfinder/src/ethereum/state_update/state_root.rs
- crates/pathfinder/src/state.rs
This PR adds an example which demonstrates how L1 chain reorgs can be:
1. detected and,
2. synchronised with local history
Includes a minor async removal from a test function.
~So far I haven't spotted a reorg an action yet, so lets not merge until that does occur.~
> feat(example): handle L1 reorgs

- .github/workflows/ci.yml
- crates/pathfinder/src/ethereum.rs
- crates/pathfinder/src/state/merkle_tree.rs
- crates/pathfinder/src/state/state_tree.rs
This PR marks unused constants and functions `_xxx` and enables `clippy:dead_code` lint again.
This was originally disabled while developing disconnected components, but these have since mostly been integrated.
Fixes #95.
> ci: enable clippy dead code

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/serde.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/state_tree.rs
- crates/pathfinder/src/storage/state.rs
- crates/pedersen/src/hash.rs
* `pending` is forwarded to the sequencer
* in  other cases read from storage
* some tests marked `todo!()` until we can mock state in an easier way
* "real data" test left as is for the time being, as it's not run in the CI anyway
> Get storage at

- crates/pathfinder/examples/fact_retrieval.rs
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/ethereum.rs
- crates/pathfinder/src/ethereum/contract.rs
- crates/pathfinder/src/ethereum/log/fetch.rs
- crates/pathfinder/src/ethereum/log/fetch/backward.rs
- crates/pathfinder/src/ethereum/log/fetch/forward.rs
- crates/pathfinder/src/ethereum/state_update.rs
- crates/pathfinder/src/ethereum/state_update/retrieve.rs
- crates/pathfinder/src/ethereum/state_update/state_root.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/state.rs
This PR adds support for mainnet contract addresses. As a consequence, we can now fetch logs etc for the Starknet mainnet chain. Previously this only worked correctly for Goerli.
A consequence of this change is that the `Chain` type must now be passed around to many locations. This is why so many files are touched -- but most of them are minor changes.
There is probably a more elegant solution to this, probably by creating a type more similar to the `Sequencer` which owns its chain parameter. But since the current functions are mostly free functions, this meant passing the chain parameter downwards.
> feat(ethereum): logs now support mainnet chain

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/state.rs
- remove `#[ignore]` for tests which seem to work now
- add `#[ignore]` for tests marked with `todo!()`
> Minor test cleanup

- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/state/contract_hash.rs
Smaller preparatory changes before the larger PR.
* Simplify the state building in get_code tests
* add EntryPoint::hashed because why not (used in call tests)
* pull RpcApi creation out of `run_server`
* test case
The RpcApi creation will save me from editing all of the places where `run_server` is called again, and I can't really see any reason why it should be created by `run_server`.
> Smaller changes

- .github/workflows/ci.yml
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/cairo.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/de.rs
- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/cairo/ext_py/service.rs
- crates/pathfinder/src/cairo/ext_py/sub_process.rs
- crates/pathfinder/src/lib.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/storage.rs
- py/README.md
- py/requirements-dev.in
- py/requirements-dev.txt
- py/src/call.py
- py/src/test_call.py
Follow-up on #110.
As said in the commit message, this cannot be yet tested, we need to sync with L2 info to get those compared sequencer responses going and then to find the good states to test in.
I don't think I managed any add linuxisms (but was close, thinking about `choom`) but I have no clue if this could work under windows. Mac os would probably work.
Serialization in the communication is very naive, partly because we cannot use the schema-libraries over at python, and partly because I don't know how to do the best practices thing. So we end up having these refined statuses and responses.
> Call rpc implementation using cairo-lang from python

- crates/pathfinder/src/state/contract_hash.rs
it seems the structure has changed, attributes have gone optional. found on a goerli contract, I'll tune the regression test in a follow-up to start recording the different observed versions of these contracts, I might have the earlier version for this still.
> fix: contract_hash on latest contracts

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/service.rs
- crates/pathfinder/src/cairo/ext_py/sub_process.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/sequencer.rs
This PR adds `tracing` usage such:
- with missing `RUST_LOG` env variable `info` is used
- rpc methods are wrapped in spans which tell the name of rpc method
- there's no access to more information from jsonrpsee
- sequencer calls have all `#[instrument]`'d span
- ext_py is the one with mostly missing tracing, and it required some changes
- it might be interesting to see how the span is continued in the worker process
- there's no "normal" logging however, an example is provided for demoing this
> Add tracing in some parts

- crates/pathfinder/src/state/merkle_tree.rs
- crates/pathfinder/src/state/state_tree.rs
- crates/pathfinder/src/storage/merkle_tree.rs
This PR separates a `trait NodeStorage` from the MerkleTree implementation. Originally done for fuzzing in `tree_tool` branch, but it's most likely useful with the upcoming block hashing, which will still need configured depth=64.
Included is one additional backing implementations for `()`. There's a `RefCell<HashMap<_, _>>` in `tree_tool`, since only `()` should be needed for transaction trie.
The old api is kept for not requiring changes anywhere else:
- `MerkleTree::<RcNodeStorage<'_>>::load` still exists
- `MerkleTree::<T: NodeStorage + Default>::default()` is added
- `MerkleTree::<T>::commit_mut(&mut self)` is added next to `commit(self)` which just doesn't consume self
> Separate nodestorage from merkletree

- .github/workflows/ci.yml
The current 5min timeout includes compilation time which causes test failures depending on build cache.
> ci: pre-compile cairo tests

- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/state.rs
This PR re-enables `rpc::get_storage_at` functionality. This was previously commented out by #121 due to schema changes.
This required re-adding the missing functionality to storage again.
> rpc: re-enable get_storage_at

- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/contract.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0001.rs
- crates/pathfinder/src/storage/schema/revision_0002.rs
- crates/pathfinder/src/storage/schema/revision_0003.rs
- crates/pathfinder/src/storage/schema/revision_0004.rs
- crates/pathfinder/src/storage/state.rs
- py/src/call.py
- py/src/test_call.py
This PR adds compression to the Starknet transaction data in our storage.
As an overview of the changes:
- add a migration which compresses existing database data
- add post-migration action to enable selective database vacuuming - to take advantage of the compression space saving
- add compression to database insertion
- fix-up some tests which relied on old versions instead of the full migration
- migrations are now committed independently instead of one bulk transaction
- refactor migration naming 
The compression saves me around 300MB on a 2GB database file after 40k blocks.
> Storage: compress transaction data

- crates/pathfinder/src/bin/pathfinder.rs
`pathfinder` binary now determines the network chain using Ethereum and uses this information to configure the database path as well as the sequencer endpoint.
Closes #132.
> feat(pathfinder): use ethereum chain to configure

- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l1.rs
- crates/pathfinder/src/state/sync/l2.rs
With this PR, the sync process now automatically restarts the L1 and L2 sync sub-processes if they fail.
This required splitting the event channel for each sub-process, so that it could be checked for closure (which indicates sub-process failure).
Likely failure reasons are largely just transport related, for example the sequencer rate-limiting us (although this should go away once we have the auto-retry work in).
~Currently, the sync process can't retrieve the failure reason as `sync` is blocking and the sub-processes are async. I'm working on changing `sync` to async which will let us access the failure reason. I'll add this in a commit soon.~ Done.
Please throw a careful eye at the [feat(sync): retrieve L1 and L2 process errors and add primitive …
> feat(sync): auto-restart L1 and L2 sync processes

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/lib.rs
- crates/pathfinder/src/retry.rs
A simple wrapper around `tokio-retry` that allows for exponential backoff with some options:
- saturating max delay at a given value,
- limiting the max number to retries,
- specifying on which errors to retry and which to pass through.
> feat: retry

- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
This PR adds the sync process to the `pathfinder` binary.
Also removed a spammy `println!` (these will get reworked into tracing soon).
Closes #138.
> feat(pathfinder): add sync

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/storage/state.rs
This PR lets RPC queries fetch from storage where-ever they are able to.
It has also shown that the way we currently store transactions is not amenable for the `get_transaction_by_hash` variants. This needs to be fixed ASAP.
The RPC code also is not tested :( We really need a way of doing so.
> Connect RPC to storage

- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0005.rs
- crates/pathfinder/src/storage/state.rs
- py/src/call.py
- py/src/test_call.py
This enables the various RPC functions that need to query by transaction hash.
Closes #131
> Storage: move Starknet transactions to a separate table

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/state/sync.rs
This was incorrectly routed to chain_id. Also enabled tests for this.
> fix(rpc): starknet_syncing returns wrong value

- .github/workflows/ci.yml
Github secrets are not available to actions run on PRs from forks. This means our CI tests fail for PRs from forks as these secrets are missing.
This PR sets the tests to use `CI` github environment instead, which now contains the same keys.
> ci: use github env to enable external contribs

- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
RPC and sync code now gets an explicit state object that is used to store
and query sync state.
This avoids issues with tests, too: previously running
`rpc::tests::syncing::{syncing,not_syncing}` in parallel would lead to
test failures.
> fix(sync): inject a state object instead of using a global state

- .github/workflows/ci.yml
This PR reverts the change in #169 whose change did not help with sharing secrets to fork CI runs.
This appears not to be possible with github due to security concerns.
> ci: revert environment change

- crates/pathfinder/src/cairo/ext_py/service.rs
This change fixes a busy loop where the expiration of wait_before_spawning
wakes up the select!() again and again if the number of Python subprocesses
match what we're expecting.
The logic is now: check if the number of subprocesses matches expectations
once per second. Start _one_ new subprocess if that's not the case.
> fix(ext_py): fix busy-loop in task handling Python subprocesses

- crates/pathfinder/src/state/sync.rs
~Replaces a `std::thread::sleep` with `tokio::time::sleep` in the sync function.~
Replaces separate `try_recv` queries for L1 and L2 sync events with a single `select!` over both. This removes the need for the sleep (which was incorrectly blocking in the first place).
> fix(sync): blocking sleep in async

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/state/sync/l2.rs
Adds a universal retry behavior behind each `sequencer::Client` method. At the moment backoff params are hard coded.
> Sequencer retry

- README.md
On new fresh installation, libgmp need to be installed before setup to avoid failed installation on fastecdsa library.
```bash
building 'fastecdsa.curvemath' extension
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/src
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc
/ -I/starknet/pathfinder/py/.venv/include -I/usr/include/python3.9 -c src/curve.c -o build/temp.linux-x86_64-3.9/src/curve.o -O2
In file included from src/curve.c:1:
src/curve.h:4:10: fatal error: gmp.h: No such file or directory
4 | #include "gmp.h"
|          ^~~~~~~
compilation …
```
> Add instruction for README.md

- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
This PR removes `sequencer::block_by_number_with_timeout`. This was a work-around for the sequencer's poor performance on old blocks. This has since been fixed and is hopefully no longer necessary.
> feat(sequencer): remove get block with timeout

- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0005.rs
- crates/pathfinder/src/storage/schema/revision_0006.rs
- py/src/call.py
- py/src/test_call.py
This PR adds a new storage migration 6 to fix a non-fatal bug in migration 5.
Migration 5 fails to drop the transaction and receipts columns if the table is empty due to an early exit condition.
> fix(storage): transaction and receipts not dropped

- README.md
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/cairo/ext_py/service.rs
- crates/pathfinder/src/cairo/ext_py/sub_process.rs
`call.py` is now included in the `pathfinder` executable and we're creating
temporary script files to execute the included source with a Python
interpreter.
This way we're not using the VIRTUAL_ENV environment variable anymore
and only depend on the PATH being set up properly so that running
`python3` results in a Python interpreter set up with our `cairo`
dependencies.
This makes it possible to just install those Python dependencies globally
in a Docker image and run `pathfinder` without a virtualenv.
> feat(pathfinder): work without a Python virtualenv

- .dockerignore
- Dockerfile
- README.md
I created a docker image so it's easier to run the node. It can also persist data between restarts.
> Add Docker image

- .github/workflows/docker.yml
- README.md
This PR adds the `docker.yml` workflow which will:
- automatically push to `latest` on merges to main
- automatically push to a versioned tag on new git tag publication
This will also require two GitHub secrets: `DOCKER_HUB_USERNAME` and `DOCKER_HUB_ACCESS_TOKEN`
> feat: add docker GH workflow

- py/requirements-dev.in
- py/requirements-dev.txt
- py/src/call.py
- py/src/test_call.py
Upgrades to latest with minor refactoring to allow for easier testing in future as the old tests all went through the json per line i/o and as such formatted exceptions.
Sets `max_fee = 0` at least for now, perhaps a better value for this is learned later. The same value is used by the cairo-lang test support as well by default.
This will most likely not support calling post 0.8.0 contracts, which would use the new additions.
> Upgrade to cairo-lang 0.8.0

- crates/pathfinder/resources/contracts/core_impl.json
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/storage/contract.rs
This PR fixes two bugs in the L2 sync process:
1. After an L2 reorg, the sync process would continue from the old local block head, instead of taking into account the reorg'd blocks.
2. The sync process would crash due to inserting a duplicate contract. This can occur when after a reorg as we never delete the old contracts (this prevents us downloading them again), and the "new blocks" will contain the same contract again.
As an aside this really should have been caught by tests -- which I didn't write due to time crunch.
> Fix L2 reorg

- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/storage/contract.rs
- crates/pathfinder/src/storage/ethereum.rs
- crates/pathfinder/src/storage/state.rs
This PR fixes two separate bugs.
1. The L2 reorg tail was off-by-one block which means afterL2 reorg we would skip a block which would fail due to the state root not matching.
2. After an L2 reorg, we don't clean up transaction data which meant following new blocks could fail due to already existing transactions.
> Fix L2 reorg related issues

- crates/pathfinder/src/core.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pedersen/src/hash.rs
It turned out that `state_update_by_number` contained a typo which caused to always return the result for `latest`.
> fix: state_update_by_number

- crates/pathfinder/src/ethereum/log.rs
- crates/pathfinder/src/ethereum/log/fetch/forward.rs
- crates/pathfinder/src/ethereum/state_update/state_root.rs
Fixes #207 as suggested in the comments.
This patches an issue where some L1 nodes (geth), perform poorly for large search ranges. We have large search ranges while traversing the initial void where no Starknet exists on L1.
We circumvent this by starting from the first L1 block containing Starknet, instead of starting from L1 genesis.
> fix(logs): genesis query block range too long

- .github/workflows/docker.yml
- Dockerfile
- start-node.sh
Hey everyone!
I made some modifications to the Docker image to better support odyslam/starknet-node and a multi-arch environment
- Dockerfile downloads the repo  as part of the build process (so that it can run without needing the rest of the repo)
- pathfinder binary is copied to hardcoded paths after they are built so we can copy them to the final destination no matter the arch (target/<arch>/pathfinder)
- start-script replaced pathfinder in entry point to easily support env variables and provide flexibility with the start process (it's easy to change a bash script to add any arbitrary step, env variable, etc.)
- start-script supports IDLING. This is super helpful in case we want to start the container, but not the binary inside it. That way we can ssh (in reality attach a pseudo-tty) …
> feat: multi arch Dockerfile

- crates/pathfinder/src/ethereum/contract.rs
This change fixes the failing test after Starknet 0.8 has been deployed
to mainnet.
It also adds a comment about these tests (from Mirko) that provide some
context around these tests in general.
> fix(ethereum/contract): update mainnet core contract address in test

- .github/workflows/docker.yml
As mentioned by @odyslam in #210, alpine doesn't support this platform. Eventually we might need to switch back to Debian-based images, but this is a consideration that needs time and discussion.
In the meantime, we should remove this platform to get the Docker builds running again.
> Removing arm/v7 from multi-platform build

- py/README.md
- py/src/call.py
Assert it like schema version. Forbids running with outdated python dependencies. Also adds:
- error message on schema version mismatch (most likely development time)
- error message on cairo-lang version (most likely end-user forgot upgrade venv)
- README note on how to upgrade dependencies
> feat(py): assert cairo-lang version

- crates/pathfinder/src/storage/schema/revision_0007.rs
- crates/pathfinder/src/storage/state.rs
Just like @kkovaacs said: When a reorg occurs and Starknet blocks are deleted from the DB we
should be deleting events for transactions in those blocks, too.
This PR also adds a regression test.
> fix: rev7 l2_reorg failure

- .dockerignore
- Cargo.lock
- Dockerfile
- crates/pathfinder/Cargo.toml
- crates/pathfinder/build.rs
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/config/cli.rs
Embed it with vergen. Use it on the first tracing message, and `--help`.
The commits after the second one are questionable. I couldn't get the caching work, each time the build.rs execution failed with an libgit2 based error even though the `.git` directory was in place. ~I did the quick edits on start-node.sh as I noticed it didn't work like README.md says, which it again does after the changes.~ `start-node.sh` changes dropped to keep this minimal.
> Embed version tag

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/examples/fact_retrieval.rs
- crates/pathfinder/src/config/cli.rs
PATHFINDER_ETHEREUM_API_URL, PATHFINDER_ETHEREUM_API_USERNAME, PATHFINDER_ETHEREUM_API_PASSWORD and PATHFINDER_HTTP_RPC_ADDRESS environment variables can now be used instead of command line arguments.
This will make it possible to get rid of the Docker entrypoint script which is currently used to map environment variables to command line arguments.
The PR also updates `clap` to 3.1.6 -- which being a major version upgrade required some changes in our code.
> feat(cli): upgrade clap, add support for environment variables

- README.md
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/config.rs
- crates/pathfinder/src/config/builder.rs
- crates/pathfinder/src/config/cli.rs
- crates/pathfinder/src/config/file.rs
This command line argument can be used to set the value of the
User-Agent header, and _not_ the username for HTTP basic authentication.
This also changes fixes the name of the environment variable we have
been using for this argument.
> fix(cli): rename `ethereum.user` argument to `ethereum.user-agent`

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l1.rs
This PR adds some basic tests for `state::sync::sync()`, which essentially inject events from either `l1` or `l2` sync tasks and then assert the DB for respective updates.
I had to introduce some dependency injection for `sync()` to decouple from any concrete `l1` & `l2` sync implementations.
At the moment keeping this PR as draft as to get your opinion on these tests.
IMO it's better to have _some_ tests rather then _none_.
> Combined sync tests

- Dockerfile
We need to copy Cargo.lock, too, in addition to Cargo.toml when doing the build step for Rust dependencies.
Otherwise cargo generates a new lock file with incorrect versions of our dependencies, which leads to these being re-downloaded and rebuilt when we're building pathfinder.
> Fix caching layer for third party Rust dependencies

- py/requirements-dev.in
- py/requirements-dev.txt
- py/src/call.py
- py/src/generate_test_global_tree.py
This PR fixes up some imports and the `BlockInfo` constructor so that our code works with `cairo-lang==0.8.1`.
It also has some extra commits that fix some pylint warnings or just make our code conform to PEP8 better (like importing at the module level).
> Update Python code for cairo-lang 0.8.1 release

- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/storage/schema/revision_0005.rs
- crates/pathfinder/src/storage/schema/revision_0007.rs
- crates/pathfinder/src/storage/state.rs
Fixes in the sequencer client part.
> feat: align with cairo 0.8.1

- crates/pathfinder/src/storage/schema/revision_0005.rs
- crates/pathfinder/src/storage/schema/revision_0007.rs
- crates/pathfinder/src/storage/state.rs
in favor of `zstd::decode_all`. at the moment we cannot use bulk decompressor to decode, because we would either need a safe large allocation, leading to overestimation or having to update the estimates.
this way is slower because the allocation needs to grow, and there's no chance of reuse (which matters less for decompressing).
this can be later fixed by for example:
- recording the uncompressed size for each compressed payload, which would allow to use exact sized preallocations
- and/or use serde `from_reader` in the cases where `'static` types are deserialized
> fix: replace zstd::bulk::Decompressor usage

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/lib.rs
- crates/pathfinder/src/update.rs
This periodically checks github for updates and logs if a newer release is found.
Does not stop checking for newer releases, even once one is found -- this lets us update the log message to include the release if any. One thing I'm on the fence about my error handling for this. And whether I should be checking for process crash in the main binary (since this is a "minor" feature, maybe it crashing should not end the node?).
Closes #245.
> feat: add pathfinder release monitoring

- Cargo.lock
- crates/pathfinder/Cargo.toml
Looks like I've missed this last week when releasing 0.1.8.
> Bump pathfinder crate version to 0.1.8

- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/error.rs
This PR implements #246 with some slight deviations (ie. no distinction between other standard and other "non-standard" status codes).
In essence:
- **all** errors except for `StarknetError` cause a retry,
- upon retry each type of error is logged in a short form at the level described in #246 **unless** the `trace` level is enabled, in which case the full details of the error are logged,
- retrying is done **forever**, so the outer sync loop should in practice never have to restart the l2 sync task,
- backoff is still exponential, but the timings have changed: `{30s, 1m, 2m, 4m, ..., 32m, 1hr, 1hr,...}` - eventually saturating at 1hr,
- the `DeserializeError` variant has been removed as it was dead code.
> Improve l2 errors

- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/serde.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/state/sync.rs
- crates/pedersen/src/hash.rs
- crates/pedersen/src/serde.rs
I was about to _just_ add the block numbers into `starknet_syncing` but couldn't stop thinking about the unnecessary `String`s in serialization.
So now there are two conversion fns:
- the `as_hex_str` flavor, which takes a `&mut [u8]` and allows to get rid of the heap allocation,
- the old flavor, still named `to_hex_str`.
The `as_` naming is correct from [`clippy`'s perspective](https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention) and I guess is consistent with the general _rust_ way of doing things.
> Serialize on stack

- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l1.rs
- crates/pathfinder/src/state/sync/l2.rs
L1 was polling for updates every 5s. This PR changes this to match the L2 rate, which is based on the StarkNet block time.
> Increase L1 head poll rate

- README.md
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/config.rs
- crates/pathfinder/src/config/builder.rs
- crates/pathfinder/src/config/cli.rs
- crates/pathfinder/src/config/file.rs
This PR adds support for specifying the data directory the pathfinder node should use.
`--data-directory` can now be specified via cli or toml file, or alternatively `PATHFINDER_DATA_DIRECTORY` env variable.
> Support data directory config item

- crates/pathfinder/src/state/contract_hash.rs
The recent 0.8.2 rollout to the Starknet integration environment had
some incompatible API changes: we have to specify blockNumber explicitly
on the get_full_contract endpoint.
> fix(contract_hash/test): fix 0.8.2 API breakage causing test to fail

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/serde.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/state/sync.rs
This PR adds support for block numbers in `starknet_syncing` and is based on #264 (which splits `to_hex_str` into heap and stack based flavors).
> Block number in sync status

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/types.rs
This is a fix to #269.
`starknet_getTransactionReceipt` did not contain `events` as per spec ([1](https://github.com/starkware-libs/starknet-specs/blob/79ce68d55f4c5bc4796305bf8ed9b5b2f432653e/api/starknet_api_openrpc.json#L275) [2](https://github.com/starkware-libs/starknet-specs/blob/79ce68d55f4c5bc4796305bf8ed9b5b2f432653e/api/starknet_api_openrpc.json#L984)) but always emitted an empty JSON array.
I've also tested the fix manually on `mainnet`.
> fix: starknet_getTransactionReceipt does not contain events

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/serde.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0009.rs
- crates/pathfinder/src/storage/state.rs
- py/requirements-dev.in
- py/requirements-dev.txt
- py/src/call.py
- py/src/test_call.py
Changes:
- add `gas_price`, `sequencer_address`
- fix missing `old_root` in `pending` block
- minor test code deduplication
Important notes:
- required cairo lang version in py still 0.8.1 as it hasn't been released yet
- no db changes for `max_fee` and `actual_fee` as those fields are `Optional` so (de)serialization of `sequencer::reply::transaction::{Receipt, Transaction}` will not break upon 0.8.2
> align with cairo 0.8.2

- crates/pathfinder/src/state/sync.rs
PR changes L1 and L2 reorg events from `tracing::warn` to `tracing::info`.
Since reorgs are expected behaviour, `warn!` did not make sense (and also generated wen-token bug reports).
> fix(sync): changed reorg severity to info

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/error.rs
- crates/pathfinder/src/state/sync.rs
This is currently required for mainnet deployment operations. The
token gets passed on to the sequencer API as a query parameter.
> feat(rpc): add optional token for starknet_addDeployTransaction

- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/state/sync.rs
This PR fixes the sync status' highest block number not being updated.
Additionally, it adds `impl Display for SyncStatus`, which the debug trace output. This was an afterthought, and I'm not sure if its an improvement. (open to dropping the commit for this.)
> fix: sync status highest block number

- Cargo.lock
- crates/pathfinder/Cargo.toml
Looks like we forgot to do this (once again) when releasing 0.1.10.
> chore(pathfinder): bump crate version to 0.1.10

- Cargo.lock
- Cargo.toml
- crates/load-test/Cargo.toml
- crates/load-test/src/main.rs
These are meant to be running with a reasonably up-to-date mainnet state.
Unfortunately `goose` doesn't provide a way for just running _some_ scenarios, so I think right now the only option is commenting out the ones we don't want to run... :(
Fixes issue #250.
> feat(load-test): add a load-test for most of our RPC endpoints

- Dockerfile
The workspace-level Cargo.toml references `load-test`, which we didn't
create during the dependency change.
Note that we don't actually compile load-test in the Dockerfile since
we don't need that tool to be part of the actual Docker image.
> fix(docker): fix build after we've added load-test

- crates/pathfinder/src/state/sync.rs
This PR fixes an issue with sync status updates. 
The issue is caused because we have a poll to update latest. However because current is updated for every block we sync, its possible that current would exceed latest if latest was only polled after.
Unfortunately, this doesn't fix this issue perfectly. There is still this possibility:
1. L2 reorg
2. latest poll catches this
3. latest (highest) is now moved to before current
Fixing this would require some more substantial re-design of how this works.
> fix: sync status current running ahead of highest

- crates/load-test/src/main.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/state/sync.rs
Refactor avoid another field modified issues in the future.
> syncing: refactor with tuple type

- README.md
Real default is at https://github.com/eqlabs/pathfinder/blob/c04d0a6b6af204164ba6971b528890c633a58244/crates/pathfinder/src/config.rs#L11
> fix: wrong default bind address in README

- Dockerfile
Also comment on why the rpc listening address needs to be set within the docker container.
> Update docker rust base

- Dockerfile
- crates/pathfinder/rpc_examples.sh
And add notes on how to develop the dockerfile without having layers trashed all of the time.
I am not 100% sure if all upgrades are needed, but I can't think of an argument why they shouldn't be there. Caching is of course one.
> update docker base images, less copying more packages

- crates/pathfinder/src/config/cli.rs
IP:PORT was incorrect for a path to the data directory.
> fix(cli): fix value name of --data-directory

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/sequencer.rs
Use auto advancing time in tokio to speed up a test.
Duplicated dependency for prod and test albeit with a different feature set is possible due to [using resolver 2](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2).
> test: make the request_timeout test faster

- README.md
* Add mentions of `environment variables` under Configuration
* Remove table under docker section
* Add docker --help example
> Adjust readme on configuring

- .github/workflows/docker.yml
This PR is an attempt to fix the issue with `buildx` being a massive resource hog.
It adds a `config-inline` directive to the buildx action which adds a `max-parallelism` value of `1`.
Note that we may want to consider upgrading to the v2 version of the action when either time allows or necessity demands.
> fix: add max-parallelism to docker file

- crates/pathfinder/src/sequencer.rs
Based on the not-yet-reviewed-fully PR in order to decrease later rebase related fixes.
> feat: use latest instead of null for blockNumber

- crates/pathfinder/src/rpc/api.rs
forward them to sequencer because we can't support the two at the
moment, or at least the latest semantics would probably be different
from what py/src/call.py supports (queries highest l2 block number).
> fix: forward at tag calls

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/examples/call_against_sequencer.rs
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer/error.rs
i've started the process of upgrading to 0.11 to support configuring the hyper instance to handle health checks. it's mostly just adjusting imports/namespaces. im pretty new to rust, so would appreciate any feedback / guidance. in particular, i'm struggling to case the errors to the new type
> chore: upgrade jsonrpsee to 0.11

- crates/load-test/src/main.rs
- crates/pathfinder/examples/compute_class_hash.rs
- crates/pathfinder/examples/compute_contract_hash.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/ethereum/state_update.rs
- crates/pathfinder/src/ethereum/state_update/parse.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/sequencer/request.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/class_hash.rs
- crates/pathfinder/src/state/contract_hash.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/storage/contract.rs
- crates/pathfinder/src/storage/schema/revision_0002.rs
- crates/pathfinder/src/storage/state.rs
- py/src/compute_class_hash.py
`cairo-lang` 0.9.0 seems to have made this naming change. This PR renames ContractHash to ClassHash (and in general all references to contract hashes) so that we're consistent with the naming convention used by Starkware.
> Rename `ContractHash` to `ClassHash`

- .github/workflows/docker.yml
Based on the documentation here: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
> Use GitHub Actions cache when building the Docker images on GitHub

- .gitignore
I'm using google translate so I'm sorry if it's strange English.
I am running `pathfinder` with the following settings(systemctl).
I think there is no problem if I change the `PATHFINDER_DATA_DIRECTORY `.
However, depending on the environment, anyone may accidentally commit the entire sqlite file.
Therefore, I added a description to ignore the sqlite file in the ignore file.
```
[Unit]
Description=Pathfinder
[Service]
Type=simple
WorkingDirectory=/home/<username>/pathfinder
ExecStart=/home/<username>/pathfinder/target/release/pathfinder --ethereum.url <https://goerli.infura.io/v3/...> --http-rpc 0.0.0.0:9545
Restart=on-failure
RestartSec=60
User=<username>
[Install]
WantedBy=multi-user.target
```
> Add ignore files(*.sqlite)

- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/error.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema/revision_0010.rs
- crates/pathfinder/src/storage/state.rs
- Not required for the incoming release.
- Caused by 0.9.0.
- I plan to refactor `Transaction` on the sequencer side into a 3-variant enum to get rid of the majority of `Option`-al fields but at the same time I'd like to keep that change separate from just aligning the client to 0.9.0.
> Add new methods to the sequencer client api

- crates/pathfinder/src/rpc/types.rs
- As agreed with SW.
- Fixed some comments.
- Removed `#[serde_as]` annotations where they were unused.
> Omit nulls in the RPC api replies

- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state/sync/l2.rs
Looks like this field was introduced in the sequencer api some time ago.
I'm adding it to seal the structure and disallow unknown fields. Disallowing unknown fields iuuc would hopefully be used in some coming tests that would allow us to discover "quiet" api changes.
> fix: add block_hash field to state update reply

- .dockerignore
- Dockerfile
This PR changes our Dockerfile to use Debian-based base images.
Using a glibc-based distribution makes it possible to install wheels when we're setting up our Python dependencies. This helps a lot because on Alpine `numpy` compiles a lot of C++ code.
The resulting image sizes are significantly larger than what we had with Alpine, but not an order of magnitude worse (for `linux/amd64`, but `linux/arm64` is similar):
| | Debian-based  | Alpine-based |
| --- | --- | --- |
| Uncompressed size | 269 MiB | 160 MiB |
| Compressed size | 84 MiB | 48 MiB |
I've also tried to look into what makes the Debian-based image significantly larger. It seems there are two major factors:
- The base image is larger: 118 MiB vs 44.6 MiB
- The Python packages we're installing as wheels are larger: they contain …
> refactor(docker): use Debian base images

- Dockerfile
- replace use of `apt` with `apt-get` (warns without tty)
- only build `pathfinder` binary (even though nothing else gets built right now)
> Smaller docker adjustments

- crates/pathfinder/src/sequencer/reply.rs
This is not done by default because `TransactionVersion` is a newtype around `H256`.
> fix: deserialize transaction version as hex str

- Cargo.lock
After a quick peek, it would appear that `jsonrpsee` uses `regex` only through `globset` and doesn't compile `globset` matchers from user input, but through access control configuration, which are compiled out of developer input. `tracing-subscriber` only uses it to parse the initial env variable configuration with static regexs.
> chore: upgrade regex

- Dockerfile
defaulting it to `--help` made it to require any command line argument (`--http-rpc 0.0.0.0:9545`) as a workaround to get the process started.
could release a 0.2.1 afterwards as suggested by @kkovaacs.
> fix(Dockerfile): set cmd to empty

- crates/pathfinder/src/storage/state.rs
This does not include any migration or fixing the database since I am unsure if that's event possible without redownloading it all..
Fixes #331.
> fix(storage): event address is using tx address

- crates/pathfinder/src/rpc/api.rs
- py/src/call.py
it might not be the globally highest, but it has been decided to be the highest locally available.
> fix(call): latest is the highest local block number

- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0011.rs
- py/src/call.py
This fixes the database to match the fix in PR #346, which only fixed new event inserts.
One unknown for me is does this impact the triggers at all? And the indexing (if any)?
Draft PR until tested on actual database.
> fix(storage): migration to fix event addresses

- crates/pathfinder/src/rpc/api.rs
A perf and correctness fix while looking if some of the methods could be made just blocking, and seems that they can. But separated this fix as it's independent.
> fix(rpc): get_block_* used two transactions

- crates/pathfinder/examples/migrate_db.rs
- crates/pathfinder/src/storage/schema/revision_0011.rs
Follow-up to #351 to swap the index around, hopefully making this migration faster on ram limited devices. Includes a fix to disable vacuum on `examples/migrate_db` which is just trying to have less mandatory patches running around.
> fix: temporary index used by migration

- crates/pathfinder/src/rpc/api.rs
this will ensure the calling rpc_method=name span will exist in both the async and sync part, should there be need for it. outer async part doesn't need this because it will be entered once more when the poll execution continues.
marking this as a fix even though we probably never witnessed any of these being missing..
> fix: hoist spans into spawn_blocking

- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/fixtures/mod.rs
- crates/pathfinder/src/storage/schema/revision_0010.rs
- crates/pathfinder/src/storage/schema/revision_0012.rs
- py/src/call.py
This is required so that we can stop relying on non-stable rowids in
the FTS5 virtual table we're using for indexing keys.
According to https://www.sqlite.org/rowidtable.html:
> If the rowid is not aliased by INTEGER PRIMARY KEY then it is not
> persistent and might change. In particular the VACUUM command will
> change rowids for tables that do not declare an INTEGER PRIMARY KEY.
> Therefore, applications should not normally access the rowid directly,
> but instead use an INTEGER PRIMARY KEY."
This change adds a migration that re-creates the starknet_events table
with an explicit INTEGER PRIMARY KEY and then re-creates all indexes
for the events.
Fixes issue #353.
> fix(storage): add an integer primary key to the starknet_events table

- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/request.rs
Fixes #370
Added a dummy constructor param in the test, which does pick this bug if `SEQUENCER_TESTS_LIVE_API=1`.
> Fix: calldata format error when proxying deploy transactions #370

- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/builder.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/stark_hash/src/hash.rs
PR with my attempt at making a request builder for the sequencer queries. It uses the typestate pattern.
Current usage:
```rust
let block: Starknetlock = self
.request()    
.feeder_gateway()
.get_block()
.at_block(block_number)
.with_retry(Retry::Enabled)
.get()
.await
.unwrap();
```
Still todo:
~~Also somewhat strangely, the tests for the transaction write's fail when executed locally, but pass when using the sequencer. I suspect it has something to do with the test setup; but I haven't figured out what / how to fix it.~~ 
This is due to the warp test server requiring query params be set even when there aren't any. Our previous request implementation always set these params to `[]` whereas this new one never sets them if there aren't any (`None`).
I've also collapsed the `block_by_hash` …
> Sequencer builder

- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0001.rs
- crates/pathfinder/src/storage/schema/revision_0002.rs
- crates/pathfinder/src/storage/schema/revision_0003.rs
- crates/pathfinder/src/storage/schema/revision_0004.rs
- crates/pathfinder/src/storage/schema/revision_0005.rs
- crates/pathfinder/src/storage/schema/revision_0006.rs
- crates/pathfinder/src/storage/schema/revision_0007.rs
- crates/pathfinder/src/storage/schema/revision_0008.rs
- crates/pathfinder/src/storage/schema/revision_0009.rs
- crates/pathfinder/src/storage/schema/revision_0010.rs
- crates/pathfinder/src/storage/schema/revision_0011.rs
- crates/pathfinder/src/storage/schema/revision_0012.rs
This PR removes database vacuuming entirely. Performing a full vacuum takes an incredibly long time for testnet database, which makes it unfeasible.
We can consider adding documentation for the user to perform it manually if this becomes desired.
Fixes #352.
> feat(storage): remove vacuum option

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/storage.rs
Instead of re-opening the Sqlite database for each request Storage now contains a connection pool.
We're using `r2d2` with a blocking API because this was the smallest change (the `rusqlite` API is blocking, too, and these calls are already called from `spawn_blocking()` tasks). This also means that when we've reached the maximum number of connections ([10 by default](https://docs.rs/r2d2/0.8.9/r2d2/struct.Builder.html#method.max_size)) getting a connection from the pool will block. This is probably better behavior than running an arbitrary number of SQL queries in parallel (which we were doing) but it still means that we're using one thread from tokio's blocking thread pool for waiting for a new connection to be available.
The `load-test` tool shows significantly improved performance.
* …
> feat(storage): use a connection pool

- .github/workflows/docker.yml
The docker-metadata action explicitly does not tag pre-release semvers
as `latest` (and the documentation fails to mention this)...
This change forces that `latest` tag to be updated for pushed tags.
We also enable the `snapshot-*` tag for manually triggered builds.
> fix(github/docker): force `latest` to be updated for pushed tags

- README.md
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/config.rs
- crates/pathfinder/src/config/builder.rs
- crates/pathfinder/src/config/cli.rs
This PR adds the `python-subprocesses` command line argument, config file key and the corresponding environment variable, PATHFINDER_PYTHON_SUBPROCESSES.
By making the number of subprocesses configurable we provide an option to set up `pathfinder` for better `starknet_call` performance, which is limited by the number of Python subprocesses we use to service those requests.
Fixes issue #354
> feat: make number of Python subprocesses configurable

- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/de.rs
- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/cairo/ext_py/sub_process.rs
- crates/pathfinder/src/config/cli.rs
- crates/pathfinder/src/ethereum/transport.rs
- crates/pathfinder/src/lib.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/serde.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/state/sync.rs
- py/src/call.py
- py/src/test_call.py
`starknet_estimateFee` runs the given call and returns a fee estimate on it, essentially being a superset of call functionality. In hindsight this could had been made with just a Call which always does the fee_estimation as well, but different return values are thrown away at the rpc level, perhaps it will be simplified to such later on.
In the beginning there are more "general fixes" which are seemingly unrelated but would conflict if I'd put them in a different PR.
There's two implementations for the `eth_gasPrice` polling:
1. separate task, which just polls all of the time (removed, now in separate branch `with-want`)
3. `dyn crate::ethereum::EthereumTransport` one, which just coalesces requests
I think the (2) will be more API provider friendly. Without unifying `reqwest::Client` …
> feat: fee estimates

- crates/pathfinder/src/storage/state.rs
An attempt at gathering extra information for #381. This bug has been reported several times, but the code looks fool-proof i.e. no route for this to occur has been identified.
This PR adds additional checks to both the reorg and insert functions in order to shed some light on the matter.
> feat: accounting for L1 reorg bug tracking

- crates/pathfinder/src/config/file.rs
It looks like the [original PR](https://github.com/eqlabs/pathfinder/pull/385) that has added the command line option
was completely missing the config file part...
> fix(config): add python-subprocesses to the config file

- .github/workflows/docker.yml
unclear if this is even allowed, but worth a shot. this is done
following rust processes getting killed once more during a build.
> ci: lower worker.oci.max-parallelism

- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/consts.rs
- crates/pathfinder/src/sequencer.rs
This PR verifies the network type of the database matches the supplied Ethereum network. This PR does not need to be merged anytime soon.
At startup, we now check that the networks of `Ethereum == Sequencer == database` are all the same before proceeding.
Failure error looks like this:
```
Error: Verifying database
Caused by:
Database (Görli) does not much the expected network (Mainnet)
```
> Validate database chain

- README.md
- crates/pathfinder/examples/estimate_past_transactions.rs
- crates/pathfinder/examples/migrate_db.rs
- crates/pathfinder/examples/verify_block_hashes.rs
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/config.rs
- crates/pathfinder/src/config/builder.rs
- crates/pathfinder/src/config/cli.rs
- crates/pathfinder/src/config/file.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/storage.rs
Using SQLite write-ahead logging would make parallel readers (like JSON-RPC reads or reads from the Python subprocess) work much better, since a write to the database doesn't stop readers.
Fixes #384
> Add a configuration / command line option to enable SQLite write-ahead logging

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/state/class_hash.rs
- crates/pathfinder/src/storage/contract.rs
According to the OpenRPC specification the Base64 encoded, gzip
compressed JSON representation of the class should be returned. (The
same representation that is used by the write API.)
Just like the entry points, we don't store this in the database
directly, so we have to decompress our full JSON, extract the relevant
part, and then compress and encode it as expected by the specification.
Fixes #406
> fix(rpc): fix return type of `starknet_getClass` and `starknet_getClassAt`

- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/de.rs
- crates/pathfinder/src/cairo/ext_py/service.rs
- crates/pathfinder/src/cairo/ext_py/sub_process.rs
- py/src/call.py
- py/src/test_call.py
This PR will start logging full exceptions from the python side over as ERROR level messages, reproductions of failed inputs at DEBUG, timing information at TRACE via a simple `<level><message>` line protocol.
For the new "hoist" (not really sure if the word means what I hope it means), the ext_py::Handle level span is propagated to the stderr printing task via a mutex which is believed to be uncontented. This way any stderr output will be correlated to the ext_py request, and further to the context of the ext_py request.
This PR was developed and can easiest be seen in action with up to date snapshot and #418.
> feat(ext_py): logging via stderr

- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/config/builder.rs
- crates/pathfinder/src/ethereum/transport.rs
we really should not retry 4xx but ... unsure how all cases happen. this helps so that the copypasted url with placeholder will exit fast. I cannot see how 401 could be used for anything else than this. It really shouldn't :)
```
2022-06-30T07:07:59.862256Z  INFO 🏁 Starting node. version="v0.2.3-alpha-37-g6e43229-dirty"
Error: Determine Ethereum chain.
Hint: Make sure the provided ethereum.url and ethereum.password are good.
Caused by:
Transport error: response status code is not success: 401 Unauthorized
```
and:
```
Error: Parsing configuration
Caused by:
Invalid Ethereum URL (https://goerli.infura.io/v3/<project-id>): Cannot use the URL from examples!
Hint: Register your own account or run your own Ethereum node and put the real URL as the configuration value.
```
> fix(eth): stop retrying on 401

- .github/CODEOWNERS
not about ownership but just to avoid clicking in the normal operation.
> github: try automating reviewers

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder.rs
When running with data directory which is not writeable (but still might contain writable database files), this gives:
```
INFO 🏁 Starting node. version="v0.2.3-alpha-38-gf719abe"
Error: Failed to create a file in /.../tmpdir. Make sure the directory is writable by the user running pathfinder.
Caused by:
Permission denied (os error 13)
```
This check might of course cause issues for some users but helping these out are always confusing, especially if the error comes from sqlite because a journal file couldn't be removed or created or whatever.
> feat: startup permission check

- crates/pathfinder/src/cairo/ext_py.rs
- py/src/call.py
- py/src/test_call.py
this should be fixed in cairo-lang 0.9.1, there should be a triple returning api.
Unable to reproduce the original in #412, but I would assume this now the correct version, and overall fee doesn't change.
Fixes but maybe not: #412
> fix(py): find more correct gas_consumed

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/ethereum/transport.rs
This will remove at least the soketto older version dependency.
> chore: bump to web3 0.18

- .github/workflows/docker.yml
- Dockerfile
Turns out cargo index refresh is very memory hungry. Using cli `git` seems to be the solution.
Upgrades the rust base image to 1.62.
Compresses a few commands for less layers.
> chore: docker preparation for next release

- Cargo.lock
- crates/pathfinder/Cargo.toml
> chore: remove extra dependency

- py/src/call.py
original idea was that calls and fee estimations are rare, we should log them at error. after looking more into filtering with tracing_subscriber, i learned one cannot turn off by span, only to enable them, which is why these messages need to be under the default level of INFO in order to be opted-in.
> fix(py): lower logging levels

- crates/pathfinder/examples/verify_block_hashes.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
This PR creates a separate type for pending blocks. The current block type contains many `Option<T>` fields to cater for the pending variant for which these don't exist. This PR therefore also simplifies the non-pending block variant by removing the `Option` for these fields.
The Sequencer's block query now returns a `MaybePendingBlock` which is an enum with `Pending` and `Block` variants. An alternative solution is to separate the query for `pending` blocks from the rest, but I deemed too disruptive for now. To make it easier I added `as_block() -> Option<Block>` to the enum which means in cases where you are certain you didn't request a `pending` block you can `.unwrap()`.
This is an internal only change, so this does not need to be part of the current release.
> feat: separate type for pending blocks

- crates/pathfinder/src/config/builder.rs
Only `true|false` are currently accepted.
> fix: wal config suggests wrong options

- crates/pathfinder/src/core.rs
most obvious change here is that previous debug:
WrapperType(StarkHash(hash))
will now be:
WrapperType(hash)
which I think is much more informative. display implementations forward
directly to StarkHash, not that we can often use them. after looking the
trace output of a session for a while, I think outputting just the hash
would suffice, but I think we already had that discussion.
> refactor: display, thinner debug for core newtypes

- crates/pathfinder/src/state/sync.rs
As requested by StarkWare to match the new 30 minute block time.
> feat: reduce mainnet poll rate to 5 minutes

- crates/pathfinder/examples/verify_block_hashes.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/storage/schema/fixtures/mod.rs
- crates/pathfinder/src/storage/state.rs
this will make sure that all db access is transactional, which it
already was. hooray! also, I can add new stuff, which only works in
transactions.
> refactor: use more transactions

- crates/load-test/Cargo.toml
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/rpc/types.rs
Request types should only derive `Deserialize` by default, and reply
types should only have `Serialize` for production code.
Tests and the `load-test` tool (which both behave as clients) require
the other direction, too, so we conditionally derive the other trait
in those cases.
This adds the `rpc-full-serde` feature for `pathfinder_lib` so that
`load-test` can conditionally enable the functionality.
> refactor(rpc/types): serde derives cleanup

- crates/pathfinder/src/state/sync.rs
Sync should be the only one writing, but it might still be blocked because litestream is doing backup, leading into errors like:
```
Sync process ended unexpected with: Err(Update L2 state to 36363
Caused by:
0: Updating Starknet state
1: Update contract state
2: Apply contract storage tree changes
3: Failed to insert edge node
4: database is locked
5: Error code 517: Cannot promote read transaction to write transaction because of writes by another connection)
```
In this case, sqlite doesn't do any busy_timeout waiting, but it just fails instantly. This is because of serializable transactions I guess, which makes the transaction requiring a full retry. However, if we just `BEGIN IMMEDIATE` as documented, most of these should be avoided.
Cc: #293
> fix(sync): start write txs as immediate

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/test_client.rs
This is a workaround for `jsonrpsee::http_client::HttpClient` used in the rpc tests reporting a senseless error from our perspective when serde errors are encountered within any of the `RpcApi` output types (`rpc::types::reply::*`).
I wanted to avoid forking (because then we would have to maintain the fork) or relying on submitting a PR to the crate (which means we have to follow the very latest release in which the PR would get merged, not to mention if it ultimately would).
This way, I think, we have better control of the kind of errors reported and the way those errors are reported to make any future test fixing easier.
> test(rpc): add replacement for jsonrpsee's HttpClient

- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
Some minor refactors that I mentioned in #426.
This is a post-0.2.5-release PR ofc.
-----------------
Changes:
- "privatize" `RpcApi::get_block_transactions`,
- refactor getting block status based on L1/L2 head to a separate function,
- deduplicate redundant calls to `RefsTable::get_l1_l2_head` (first in `get_raw_block_by_*` followed by `get_block_transactions`) in `get_block_by_[hash|number]`,
- rename `TransactionReceipt::with_status` to `TransactionReceipt::with_block_status`.
> 426 related refactors

- crates/pathfinder/src/cairo/ext_py.rs
- py/requirements-dev.in
- py/requirements-dev.txt
- py/src/call.py
- py/src/test_call.py
Only the pythonic chores with some bumping of constants in tests.
> chore(py): upgrade to cairo-lang 0.9.1

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0005.rs
- crates/pathfinder/src/storage/schema/revision_0007.rs
- crates/pathfinder/src/storage/schema/revision_0011.rs
- crates/pathfinder/src/storage/schema/revision_0013.rs
- crates/pathfinder/src/storage/schema/revision_0015.rs
- crates/pathfinder/src/storage/state.rs
- py/src/call.py
This PR is a revert of the revert for PR #380 with the small optimization in PR #392 applied, plus a migration step that makes sure that the compressed transaction JSONs are compatible with the new `enum Transaction`.
This migration is necessary because serializing the old `struct Transaction` lead to fields irrelevant for the given transaction type being serialized into the JSON with `null` value, and this breaks de-serialization with the enum type with our standard `deny_unknown_fields` serde option.
During testing I've also discovered an edge case: very old versions of deploy transactions did not have the `class_hash` in the serialized JSON. `class_hash` is now a non-optional field of `DeployTransaction`, so this migration looks up the class hash corresponding to the contract address …
> refactor: retry converting Transaction into an enum

- crates/pathfinder/src/rpc.rs
Occasionally the feeder gateway API returns finalized blocks as pending,
which causes this test to be flaky and fail occasionally.
> fix(rpc/tests): remove asserting on pending block not having a number and hash

- README.md
- crates/load-test/src/main.rs
- crates/pathfinder/rpc_examples.sh
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
Instead of the previous `starknet_getTransactionByBlock{Hash,Numer}AndIndex`
methods, this new method takes a block_id parameter that can either be
a hash, a number or a tag.
> feat(rpc): implement `starknet_getTransactionByBlockIdAndIndex`

- crates/pathfinder/fixtures/rpc/0.21.0/block.json
- crates/pathfinder/fixtures/rpc/0.21.0/receipt.json
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
At the moment I didn't find any tool to automate random json generation based on open-rpc schema, so I resorted to just hand-crafting those 2 tests as regressions in Block, Txn, and Receipt serialization are probable to repeat and the current rpc tests won't fail in some specific cases. Recently those were:
- nulls popping out because there's undocumented side-effect of `serde(flatten)` on `skip_serializing_none`,
- `*AsDecStr*` used because of a copy-paste error from similar `sequencer::reply` code.
----
This PR builds on top of #451.
> fixtures for rpc serialization

- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/ethereum/state_update.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/state/sync/pending.rs
This is the sync portion of #446, which I am splitting into more manageable pieces.
This PR adds the polling of the `pending` block to the sync process while at the head of the chain. This PR does __not__ include configuration and does not actually enable this mode for the pathfinder binary. Nor does it include any RPC changes.
When pending is enabled, the sync process will enter `pending` mode once it has reached the head of the chain. While in this mode, `pending` blocks will be emitted until a disconnect between the pending block and our local head of the chain is detected.
Additional processing is done at the sync level:
1. Downloading any new pending classes (declared or deployed). These will be required to handle pending calls and fee estimations.
2. Verifies state diff by …
> feat: poll pending in sync process

- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/config.rs
- crates/pathfinder/src/config/builder.rs
- crates/pathfinder/src/config/cli.rs
- crates/pathfinder/src/config/file.rs
This PR follows #474 and adds configuration support to enable poll pending `--poll-pending=true|false`. It is the configuration portion of #446.
Some things worth pointing out:
1. This option is specifically disallowed on testnet. `pending` is meant as a work-around to mainnet's slow block times.
2. The current polling rate is hardcoded to 5s.
This does not yet do anything meaningful from the user's perspective as this is not yet connected to RPC. That will come in the next PR.
> feat: configuration for poll pending

- crates/pathfinder/fixtures/rpc/0.30.0/block.json
- crates/pathfinder/fixtures/rpc/0.30.0/receipt.json
- crates/pathfinder/src/rpc/types.rs
Version 0.30.0 of the OpenRPC specification has renamed these properties.
> fix(rpc): follow-up transaction/receipt property rename in 0.30.0

- README.md
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/storage/contract.rs
BREAKING CHANGE: this removes the above method, which has been deprecated since pathfinder v0.2.3-alpha.
> feat(rpc)!: remove deprecated `starknet_getCode` JSON-RPC method

- crates/pathfinder/examples/call_against_sequencer.rs
- crates/pathfinder/examples/estimate_past_transactions.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/cairo/ext_py/sub_process.rs
- crates/pathfinder/src/rpc/api.rs
- py/setup.cfg
- py/src/call.py
- py/src/test_call.py
This PR adds support for "streamed updates", which basically means supporting pulling the pending block's state diff down to python.
> feat(py): call/estimateFee with pending changes

- crates/pathfinder/src/rpc/types.rs
These have been removed from the OpenRPC specification in version 0.28.0.
> fix(rpc): remove nonexistent block and transaction status values

- crates/pathfinder/src/cairo/ext_py/sub_process.rs
When cancelling a request (due to the JSON-RPC client going away before
we've finished processing) we kill() Python subprocesses, this is part
of normal operation. However, currently we close stdin and stdout, wait
one second, and only then proceed with actually sending SIGKILL to the
subprocess.
In case the Python subprocess finishes processing the command when we
have already closed stdout then sending the result of the command will
fail with a BrokenPipe exception, leading to the exception being logged
as ERROR in the pathfinder log.
By removing the explicit close we're now closing stdout _only_ after
actually killing the subprocess. This avoids the BrokenPipe exception
because in the worst case (when there's not enough buffer space for
the result in the pipe we're using as stdout) the …
> fix(ext_py): avoid BrokenPipe exceptions in Python subprocesses

- crates/pathfinder/fixtures/rpc/0.31.0/receipt.json
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
These were marked required in version 0.29.0 of the specification.
> fix(rpc/types): add pending transaction receipt types

- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/state/sync.rs
- py/src/call.py
- py/src/test_call.py
While planning this, biggest changes from #462 are:
- rust side calls python with explicit hash when there are pending changes
- if python side cannot find the block, it'll disregard the pending changes and use latest block instead, but only if there were non-null `pending_updates` or non-null `pending_deployed`
- this could happen because of a reorg
- rpc serialization now uses null's meaningfully (before they were unimportant)
Python side has tests for this... ~I guess I'll add the same test on rust side tomorrow.~
> feat: plumb the pending data into calls and estimate fees

- crates/pathfinder/rpc_examples.sh
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
This is required by 0.31.0 of the OpenRPC specification.
> fix(rpc): update call and estimateFee to receive a block id parameter

- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer/error.rs
- crates/pathfinder/src/storage/state.rs
The primary purpose of this PR is to add support for [`starknet_blockHashAndNumber`](https://github.com/starkware-libs/starknet-specs/blob/v0.1.0/api/starknet_api_openrpc.json#L485-L507).
However, en-route there this PR also aligns our RPC errors witht the `0.1.0` spec. This required reworking how state key types get deserialized as there is no longer a custom RPC error for this.
> feat(rpc): `starknet_blockHashAndNumber`

- Cargo.lock
- crates/load-test/Cargo.toml
- crates/load-test/src/main.rs
This fixes the outdated JSON-RPC method names and parameters in all calls currently done by the load test.
This PR also upgrades `goose` to the latest release, so that the load test can be run for only a subset of scenarios with the `--scenarios` argument.
> Fix load-test JSON-RPC API and upgrade goose

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/request.rs
Since contract address calculation depends on the `abi` input clients
should be able to specify and ABI via the JSON-RPC interface, too.
> fix(rpc/write): add `abi` field to contract class definition

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/storage/state.rs
This PR adds support for [`starknet_pendingTransactions`](https://github.com/starkware-libs/starknet-specs/blob/v0.1.0/api/starknet_api_openrpc.json#L521-L535) RPC method.
Its unclear what utility this provides above querying for the pending block, but its in the spec so here goes..
It may also be worth wrapping/renaming the various `Transaction` types that we have. To date we have:
```
crate::rpc::types::reply::Transaction
crate::sequencer::reply::Transaction
crate::sequencer::reply::transaction::Transaction
rusqlite::Transaction
```
> feat(rpc): `starknet_pendingTransactions`

- crates/pathfinder/rpc_examples.sh
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
This will no longer form part of the RPC specification ([PR](https://github.com/starkware-libs/starknet-specs/pull/41)) and as such we won't implement it.
As an aside I've now noticed that none of my PR's have added/updated the examples..
> chore: remove `starknet_protocolVersion`

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/storage/contract.rs
This PR adds support for [`starknet_getNonce`](https://github.com/starkware-libs/starknet-specs/blob/v0.1.0/api/starknet_api_openrpc.json#L628-L653) for RPC specification v0.1.0.
Nonces are only part of StarkNet from version 0.10 onwards and as such aren't actually supported yet. This implementation therefore does the following:
- return the default nonce (`0x0`) for historical blocks pre-`0.10.0`
- return an error for blocks from `0.10.0` onwards
The version is gotten by caching the version of the latest starknet block in the sync process. It is not enough to simply query the latest local block, as this will return incorrect information while syncing.
> feat(rpc): `starknet_getNonce`

- README.md
This PR updates the readme for RPC v0.1.0 and also fixes some missing information.
First the minor changes:
- added a section describing how to update `pathfinder` from source.
- added `poll-pending` configuration item which I forgot to add in the implementation thereof.
Fixes #411 and closes #410.
The RPC section changes no longer list the individual methods we support, but instead link to the official v0.1.0 specification and its playground. I think this is better - and instead we should just list exceptions, or usage specifics if required.
I also added a section about the write API -- and unfortunately this required creating a copy of the spec to change the relative paths to absolute paths. The openrpc playground doesn't know how to resolve these. I stored this copy as a personal gist …
> docs(readme): rpc spec v0.1.0 and some fixes

- crates/pathfinder/src/bin/pathfinder.rs
Python init process requires database access, which could occasionally be locked by sync process during startup.
> fix: spawn python before sync

- crates/load-test/src/main.rs
- crates/pathfinder/examples/estimate_past_transactions.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/core/macros.rs
- crates/pathfinder/src/ethereum/state_update.rs
- crates/pathfinder/src/ethereum/state_update/parse.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/builder.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/state/class_hash.rs
- crates/pathfinder/src/state/state_tree.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/contract.rs
- crates/pathfinder/src/storage/fixtures.rs
- crates/pathfinder/src/storage/schema/revision_0007.rs
- crates/pathfinder/src/storage/schema/revision_0011.rs
- crates/pathfinder/src/storage/schema/revision_0015.rs
- crates/pathfinder/src/storage/state.rs
- crates/stark_hash/src/hash.rs
On the roll; similar to #510 but this time for 251-bit types.
Nothing to review for Michael, just had to constify the previously forgotten `has_more_than_251_bits()`.
Should be ready to go but this depends on #510.
> refactor: hide privates for 251-bit types

- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/config.rs
- crates/pathfinder/src/config/builder.rs
- crates/pathfinder/src/config/cli.rs
- crates/pathfinder/src/config/file.rs
- crates/pathfinder/src/lib.rs
- crates/pathfinder/src/monitoring.rs
This PR adds a configurable monitoring endpoint, `--monitor-address` with `/health` and `/ready` routes.
This feature is disabled by default and becomes enabled when the monitoring address is configured.
`/health` always returns `OK` as our critical errors should always be fatal currently. We could try spend some more effort here, but I suspect it is not worth it at this time.
`/ready` returns `SERVICE_UNAVAILABLE` until all systems are up and running, and from then on returns `OK`.
We can add a `/metrics` route to this endpoint in the future.
> feat: monitoring endpoints

- Cargo.lock
- crates/stark_hash/Cargo.toml
- crates/stark_hash/src/hash.rs
I think libraries are meant to lean on rand_core, and we already need the rand over at pathfinder (bench) side.
Rand introduced in #515.
> refactor(stark_hash): replace rand with rand_core

- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0012.rs
- crates/pathfinder/src/storage/schema/revision_0017.rs
- py/src/call.py
Our revision 12 step failed to do the schema upgrade in case the events table was empty.
This change adds a new step that checks if we have the explicit `id` primary key in the `starknet_events` table -- and re-does the actual schema migration step of revision 12 if it has not been done yet.
> fix(storage/schema): add migration step fixing starknet_events schema

- crates/pathfinder/src/state/merkle_tree.rs
just for safety, and possibly verification (for an example attempt see #521).
> fix: error for leaf at wrong height

- Dockerfile
I missed this in #515; without it cargo build will not find the bench, and will feel bad about it.
> build: copy benches over as well

- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/state.rs
This PR simplifies the process of adding a new migration. Essentially it removes the need for *updating version numbers and adding the migration to the list.
Unclear if this is a win or not, but I got annoyed after my migration rebase still resulted in errors because I forgot to update some numbers to 18 :D
Unfortunately, we must update `call.py` manually still.. could be fixable with some `build.rs` magic but hmm.
Happy to drop this one if we feel this is silly. Also I'm sad `Box` is not `const` yet.
> refactor: simplify adding a migration

- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0018.rs
- crates/pathfinder/src/storage/state.rs
- py/src/call.py
This PR adds a migration which allows for forks in our database. This PR __does not__ make any large changes to how sync operates, nor does it change what the RPC API uses. This is purely to allow for forks with the database -- it does not build any in yet.
To date `starknet_blocks` uses the block number as the primary key i.e. this must be unique. This allowed us to enforce only ever storing a single canonical chain of blocks. While useful, we now need to allow for forks to exist which will improve our ability to handle p2p situations.
This PR changes the primary key from block number to the hash instead. To achieve this with sqlite this requires recreating the table entirely.
We still need to track the canonical chain somehow. This PR adds a new `canonical_blocks` table to do this. …
> feat(storage): allow for forks

- README.md
The previous PR's link was only valid for 7 days. This one is permanent and came from StarkWare.
> docs(readme): update discord link again

- .github/workflows/ci.yml
Caching does not seem to get cleared in long runtime of https://github.com/eqlabs/pathfinder/actions/runs/2934439089, which is based on the merged main after #537. rust-cache's cache key generation should be sensitive to the configuration files, so lets see if this triggers a cache miss.
No it didn't, so trying with mold keyed caches. After merging to main and building there, we should see a rebased PR now use the caches.
> build: rekey caches for mold, enable for fuzzing

- README.md
In the Dockerfile we're explicitly setting UID 1000 for pathfinder to
avoid running it as root. However, this causes issues in case the
permissions of the data directory make it non-writable for UID 1000.
Running the recommended commands with a user whose UID is not 1000 is
pretty much guaranteed to fail: the `mkdir` command creates a directory
that pathfinder won't be able to access in the container.
To make that command less prone to permission failures this change adds
`--user` that explicitly runs pathfinder _inside_ the container as the
UID/GID of the user on the host.
> fix(readme): use the same UID/GID in Docker as on the host system

- crates/pathfinder/rpc_examples.sh
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/types.rs
v0.1.0 of the JSON-RPC specification requires `from_block` and
`to_block` in the event filter object. We somehow failed to make
this change in pathfinder and were using the old `fromBlock`
and `toBlock` names.
This change keeps the old names as aliases so that we don't break the
API for users who have updated their code to account for the bug.
Fixes #536.
> fix(rpc): use from_block and to_block in event filter

- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/state.rs
This PR removes a check preventing declare transactions from emitting events. This is now valid and allowed from StarkNet 0.10 onwards.
> fix: declare transactions cannot emit events

- crates/pathfinder/src/state/sync.rs
For example, when a contract definition fails to parse it crashes the L2 sync process, which is immedietely relaunched and crashes again.
Fixed by adding a 10s delay before relaunching the process. Is 10s enough? The crash will often indicate incompatibility with the starknet version -- should we therefore make it minutes instead?
> fix: DoS loop when sync processes crash

- crates/pathfinder/examples/call_against_sequencer.rs
- crates/pathfinder/examples/fact_retrieval.rs
- crates/pathfinder/examples/verify_block_hashes.rs
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/config.rs
- crates/pathfinder/src/config/builder.rs
- crates/pathfinder/src/config/cli.rs
- crates/pathfinder/src/consts.rs
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/ethereum.rs
- crates/pathfinder/src/ethereum/contract.rs
- crates/pathfinder/src/ethereum/log/fetch/backward.rs
- crates/pathfinder/src/ethereum/log/fetch/forward.rs
- crates/pathfinder/src/ethereum/state_update.rs
- crates/pathfinder/src/ethereum/state_update/state_root.rs
- crates/pathfinder/src/ethereum/transport.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/test_setup.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/state/class_hash.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l1.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/storage/schema/revision_0013.rs
- crates/pathfinder/src/storage/state.rs
This PR adds support for running pathfinder on the integration network. It facilitates this by adding a separate `EthereumChain` type which allows us to add `Chain::Integration` without touching Ethereum stuff directly.
The integration network is configured by providing `--integration` alongside a goerli L1 network. It will use `integration.sqlite` as its database filename. This cli option is hidden.
This PR once again touches many files (sorry), due to the required refactoring and renaming. This is mostly `Goerli -> Testnet` renaming (since both integration and testnet live on goerli). I once again recommend reviewing by commit to lessen the renaming noise..
Warning: I have not been able to test `--integration` properly, as L2 sync fails because we cannot parse the 0.10 blocks yet. …
> feat: support integration network

- crates/pathfinder/src/state.rs
- crates/pathfinder/src/state/sync.rs
Nonces were only updated if the contract also has storage updates. This PR fixes this by also updating nonces without storage updates.
Overall, our sequencer struct isn't really ideal for this, as it makes these bugs easy to make. Would be much better to group nonces with their storage updates by contract address. Won't attempt that now.
> fix: nonces are not updated if no storage update

- README.md
- crates/pathfinder/fixtures/sequencer/integration/block/1.json
- crates/pathfinder/fixtures/sequencer/integration/block/216171.json
- crates/pathfinder/fixtures/sequencer/integration/block/216591.json
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/types.rs
- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/storage.rs
- crates/pathfinder/src/storage/schema/revision_0015.rs
- crates/pathfinder/src/storage/state.rs
This PR:
- Adds a representation for the new invoke transaction version by converting `InvokeTransaction` into an enum with either a v0 or a v1 invoke transaction inside.
- Adds a defaulted `version` field to `deployTransaction` to match the REST representation on the feeder gateway.
- Adds a representation (sequencer/RPC) for the new L1 handler transaction type. The RPC [L1Handler transaction type from spec 0.2.0-rc1](https://github.com/starkware-libs/starknet-specs/blob/c74e12d0af311537febac8f1972168cf023cb257/api/starknet_api_openrpc.json#L1367) was added to fill the void created by a similar type in the feeder gateway api with cairo 0.10.0.
- Extends [Pending]DeclareOrDeploy variants to include [L1Handler receipts](https://github.com/starkware-libs/starknet-specs/blob/v0.2.0-rc1/api/st …
> Starknet 0.10 transaction types

- Cargo.lock
- README.md
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder.rs
- crates/pathfinder/src/monitoring.rs
- crates/pathfinder/src/monitoring/metrics.rs
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/test_setup.rs
This PR is the second attempt at adding metrics to pathfinder ([feature request issue](https://github.com/eqlabs/pathfinder/issues/258), [first attempt](https://github.com/eqlabs/pathfinder/pull/317)),
- It's based on the [metrics](https://docs.rs/metrics/0.20.1/metrics/) and [metrics-exporter-prometheus](https://docs.rs/metrics-exporter-prometheus/latest/metrics_exporter_prometheus/) crates.
- The default prometheus exporter is not used, instead the payload is rendered in the `/metrics` route.
- Only the basic total call counters were added for RPC methods to keep the PR small.
- `RecorderGuard` should be used when installing a per-test recorder, which takes care of recorder removal and avoids races between tests (`metrics` forces a global recorder instance per binary).
- At the moment …
> Initial metrics support

- README.md
We now require this because of the const Mutex initialization feature:
https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html#const-mutex-rwlock-condvar-initialization
> chore(README): bump MSRV to 1.63

- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/state/sync/l2.rs
To avoid issues like we had past week (where a REVERTED block showed up
on Starknet testnet and we only failed to commit on it because it was
missing transaction receipts) this change adds an explicit check on the
block status: we only ever want to process L1 or L2 accepted blocks.
Fixes #559.
> fix(sync/l2): check that downloaded blocks are L1/L2 accepted

- crates/pathfinder/src/state/class_hash.rs
- py/src/compute_class_hash.py
It turns out that the `cairo_type` fields under `identifiers` are not
the only place we can have Cairo type definitions...
References have a `value` that's a Cairo expression, which can also
contain type definitions via `cast()`:
https://cairo-lang.org/docs/reference/syntax.html#expressions
This change applies the replace hack "fix" to these properties too, so
that named tuples for pre-0.10 classes (without `compiler_version`) are
hashed properly.
> fix(class_hash): fix up named tuple types for references

- crates/pathfinder/src/rpc/types.rs
We forgot to update the code with the new data in the v1 invoke
transaction type, so the RPC API was returning invalid version and nonce
(both zero) for v1 invoke transactions.
> fix(rpc): properly return version and nonce for v1 invoke transactions

- crates/pathfinder/src/ethereum/contract.rs
This has changed during the Starknet 0.10.0 deployment.
> fix(ethereum): update mainnet core contract implementation address

- Cargo.lock
Forgotten amongst all the update bumping.
> chore: bump lockfile to 0.3.3

- crates/pathfinder/src/state/sync.rs
Same as before for L2 task in #570.
I may follow up with another commit to remove the `#[cfg(test)]` in favor of tokio test config.
> fix(sync): move l1 sleep to intended task

- crates/pathfinder/src/sequencer/reply.rs
- crates/pathfinder/src/storage/schema.rs
- crates/pathfinder/src/storage/schema/revision_0020.rs
- py/src/call.py
After deploying Starknet 0.10.0 to Testnet there was a period where the sequencer was returning blocks with extra "transfer" events added. These were not originally part of these blocks while on Starknet 0.9.1, so the event commitment used to calculate the block hash didn't have these.
This caused block hash mismatches for these affected blocks. Pathfinder databases might contain these extra events for blocks that were synced during this period.
This migration removes these bogus events from blocks in the affected range.
> Add new migration removing bogus transfer events

- README.md
- contributing.md
the [cairo-lang license](https://github.com/starkware-libs/cairo-lang/blob/master/LICENSE.txt) is custom, and it is unknown what it will be in future. Try to be explicit about this with regards to this in the contributing.md. I don't know if the legalese holds any water but at least it highlights the issue.
Possible relicensing could be that `py/` becomes GPL or whatever. This is not an issue for pathfinder especially if the py/src/call.py is not combined to the distributed binary.
> docs(contrib): special requirements for py/ future licensing

- crates/pathfinder/src/sequencer/reply.rs
This PR adds a work-around for a gateway bug.
The feeder gateway currently does not include the `nonce` field for `L1_HANDLER` transactions from historical blocks (pre StarkNet 0.10). This is blocking sync.
> fix: work around for L1_HANDLER gateway bug

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/api.rs
- crates/pathfinder/src/rpc/error.rs
This PR reworks the RPC framework in accordance with the lessons learnt in #568.
It defines a new `RpcError` variants which includes an `Internal(anyhow::Error)` variant. This improves the error handling situation as we no longer need to use `map_internal_error` to cast errors.
It also adds a macro to trivially create error subtypes so that our method signatures can be more readidible audited against the specification. i.e. only allow allowed errors as defined in the spec on a per-method basis.
It then adds a new `register_method` function to perform the required input parsing, error mapping and tracing setup.
The existing framework can be dismantled once the existing methods have been migrated to the new framework.
> refactor: RPC framework

- py/src/call.py
Before:
```
ERROR ext_py:subproc:stderr: Traceback (most recent call last): count=2 pid=8066
ERROR ext_py:subproc:stderr: File "/tmp/.tmpA3DbbZ", line 11, in <module> count=2 pid=8066
ERROR ext_py:subproc:stderr: from starkware.storage.storage import Storage count=2 pid=8066
ERROR ext_py:subproc:stderr: ModuleNotFoundError: No module named 'starkware' count=2 pid=8066
Error: Creating python process for call handling. Have you setup our Python dependencies?
Caused by:
0: Failed to start python subprocess
1: Failed to read 'ready' from python process, read: ""
```
After:
```
Error: Creating python process for call handling. Have you setup our Python dependencies?
Caused by:
0: Failed to start python subprocess
1: Failed to read 'ready' from python process, read: "unexpected cairo-lang …
```
> fix(py): less verbose missing dependencies failure

- README.md
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/service.rs
Adds the counters:
- extpy_processes_launched_total
- extpy_processes_exited_total -- labeled with the reason
- extpy_processes_failed_total
Against previous discussion didn't add any queuing counters, because those can already be calculated from the diff of started and completed call and estimatefee. Well, turns out there is only one counter for started requests. Later.
> feat(ext_py): expose basic metrics on subprocesses

- Cargo.lock
- crates/stark_curve/Cargo.toml
- crates/stark_curve/src/lib.rs
- crates/stark_hash/Cargo.toml
- crates/stark_hash/README.md
- crates/stark_hash/benches/stark_hash.rs
- crates/stark_hash/src/hash.rs
This comes at the cost of using a fork of `ff` which doesn't use constant-time Eq implementation. Luckily there are no changes required to switch back.
Adds benchmarks in stark_hash:
- random_stark_hash
- random_hashchain (len = 100)
"It works on my computer": criterion reports -23% or -24% for random_stark_hash and random_hashchain respectively, with core-pinning (taskset) with no frequency restrictions but with minimum 15s measurement time. Similarly executed but with minimum 30s measurement time pathfinder's `merkle_tree of 1000` show -20% time.
`ff` change:
- https://github.com/eqlabs/ff/commit/e4ce228a5da140465a620cb0a455fcb08f23fb52
I think it makes more sense for `PartialEq` to be variable time since there are the `ConstantTimeEq` implementations for FieldElement and Repr.
> chore: more variable time `stark_hash`

- py/requirements-dev.in
- py/requirements-dev.txt
- py/src/call.py
this should have non-negleable perf improvement on long call/estimate_fee runs.
cachetools is used instead of functools.lru_cache because apparently latter leaks instances using it.
cache is limited to only `patricia_node` prefixed keys, because only those and `starknet_storage_leaf`'s are repeatedly fetched from the Storage by PatriciaStateReader. However only `patricia_node`'s require looking it up from the database.
cache stats are added in timings reported by `call.py`. maxsize=512 was figured out with Harrison & Stetson method.
> feat(py): add lru cache for patricia_nodes

- crates/pathfinder/src/cairo/ext_py/sub_process.rs
- crates/pathfinder/src/core.rs
cairo-lang code checks that nonce is None for version 0 transactions when we're doing estimateFee.
We did have a check for version 0 transactions in the ext_py code, but we did not handle the QUERY_VERSION_BASE offset (that's used by clients when submitting transactions for `starknet_call` and `starknet_estimateFee`).
This change makes sure that we properly check for version 0.
> fix(ext_py): set nonce to None for version 0 transactions for estimateFee

- crates/pathfinder/src/rpc/v02.rs
- crates/pathfinder/src/rpc/v02/method.rs
- crates/pathfinder/src/rpc/v02/method/get_transaction_by_hash.rs
The method's not registered yet, so not really accessible with JSON-RPC.
> feat(rpc/v02): add `starknet_getTransactionByHash` implementation

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/v02.rs
- crates/pathfinder/src/rpc/v02/method.rs
- crates/pathfinder/src/rpc/v02/method/syncing.rs
This PR implements `starknet_syncing` for RPC v0.2.
The RPC specification for the [method](https://github.com/starkware-libs/starknet-specs/blob/v0.2.0/api/starknet_api_openrpc.json#L547-L567) and [status](https://github.com/starkware-libs/starknet-specs/blob/v0.2.0/api/starknet_api_openrpc.json#L803-L832) type.
This method is unchanged from version 0.1 but I decided to try make it a bit more safe by not having a `bool` which may only be false situation.
We could also let `v0.1` use this type instead but I didn't see the need to fiddle with this.
Closes #605.
> feat(rpc/v0.2): `syncing`

- crates/pathfinder/src/rpc/v02.rs
- crates/pathfinder/src/rpc/v02/method.rs
- crates/pathfinder/src/rpc/v02/method/chain_id.rs
Implements `starknet_chainId` for v0.2 of the RPC specification.
Closes #603.
> feat(rpc/v0.2): chain_id

- crates/pathfinder/src/rpc/v02.rs
- crates/pathfinder/src/rpc/v02/method.rs
- crates/pathfinder/src/rpc/v02/method/get_transaction_by_block_id_and_index.rs
Both the arguments and the result are the same as in the v0.1.0 version of the specification.
Closes #593
> feat(rpc/v02): add `starknet_getTransactionByBlockIdAndIndex` implementation

- crates/pathfinder/fixtures/rpc/0.44.0/state_update.json
- crates/pathfinder/src/rpc/v02.rs
- crates/pathfinder/src/rpc/v02/method.rs
- crates/pathfinder/src/rpc/v02/method/get_state_update.rs
This PR adds both the code (roughly equivalent to the v01 implementation) _and_ the types required to represent the reply.
The type code contains a significant number of From<> implementations so that we can convert both from the sequencer reply representation (for the pending block) _and_ from the RPC v01 representation (which is used in the storage layer).
Closes #590.
> feat(rpc/v02): add `starknet_getStateUpdate` method

- crates/pathfinder/examples/estimate_past_transactions.rs
- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc/serde.rs
- crates/pathfinder/src/rpc/v01.rs
- crates/pathfinder/src/rpc/v01/api.rs
- crates/pathfinder/src/rpc/v01/types.rs
- crates/pathfinder/src/rpc/v02/method/estimate_fee.rs
- crates/pathfinder/src/sequencer.rs
- crates/pathfinder/src/sequencer/request.rs
- crates/pathfinder/src/state/sync.rs
It's the same as a `TransactionSignatureElem`.
> refactor(core): remove `CallSignatureElem`

- crates/pathfinder/fixtures/rpc/0.44.0/broadcasted_transactions.json
- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc/v02/method/estimate_fee.rs
- crates/pathfinder/src/rpc/v02/types.rs
Previously only version zero and one were accepted for `BroadcastedInvokeTransaction` but that was incorrect. Clients can add QUERY_VERSION_BASE (2**128) to the actual version when submitting a transaction for call or estimateFee. The Starknet gateway does not accept these transaction versions for inclusion on the chain so this mechanism prevents replaying these signed transactions through the gateway.
Closes #629
> fix(rpc/v02/types): fix handling of query versions for `BroadcastedInvokeTransaction`

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/serde.rs
- crates/pathfinder/src/rpc/v02.rs
- crates/pathfinder/src/rpc/v02/method.rs
- crates/pathfinder/src/rpc/v02/method/get_class.rs
- crates/pathfinder/src/rpc/v02/types.rs
- crates/pathfinder/src/rpc/v02/types/class.rs
I've pre-emptively moved the class definition into its own types file. It will also be used by `starknet_getClassAt`.
I've run the class definition parsing against all mainnet and testnet classes. The ABI currently fails for a single class, which has an ABI: `[ "bogus": "bogus" ]` so I think that's okay.
There are two parts of the ABI which are currently still marked with `TODO` because StarkWare still needs to comment on whether they are a bug and should be catered for, or whether we just reject those ABIs.
Closes #595
> feat(rpc/v0.2): implement `starknet_getClass`

- crates/pathfinder/fixtures/rpc/0.44.0/broadcasted_transactions.json
- crates/pathfinder/src/rpc/v02/types.rs
- crates/pathfinder/src/rpc/v02/types/class.rs
Previously the `ContractDefinition` type was missing so only a placeholder class hash was present in the transactions.
> fix(rpc/v02/types): declare and deploy transactions contain a contract definition

- crates/pathfinder/examples/estimate_past_transactions.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/cairo/ext_py/sub_process.rs
- crates/pathfinder/src/rpc/v01/api.rs
- crates/pathfinder/src/rpc/v02/method/estimate_fee.rs
- py/src/call.py
- py/src/test_call.py
And change the Rust layer to use `BroadcastedTransaction` as the input to `estimate_fee`.
This PR doesn't _yet_ add support for estimating non-invoke transactions (although it has a single test case in the Python code). Functionally this refactor is still equivalent to our previous code, but it adds the infrastructure required to represent broadcasted transactions as an input to fee estimation both in the Rust and the Python code.
> refactor(ext_py): use marshmallow-based deserialization in Python subprocess

- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/rpc/v02/method/estimate_fee.rs
- crates/pathfinder/src/rpc/v02/types/class.rs
- crates/pathfinder/src/sequencer/request.rs
- py/src/call.py
Deploys are not supported (no support in the underlying Python layer).
This also fixes a serialization issue in the `ContractClass` type: previously we did an extra string conversion so the gzip-encoded program definition was represented as _string_ containing the JSON representation (instead of the JSON itself).
Closes #600.
> feat(v02/rpc/estimate_fee): add support for estimating declare transactions

- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/cairo/ext_py/sub_process.rs
- crates/pathfinder/src/rpc/v02.rs
- crates/pathfinder/src/rpc/v02/method.rs
- crates/pathfinder/src/rpc/v02/method/call.rs
- crates/pathfinder/src/rpc/v02/method/estimate_fee.rs
- py/src/call.py
- py/src/test_call.py
This is the same underlying code as we use for v01.
I've made a refactor (in a separate commit) that removes some unused arguments from the Python `do_call` implementation.
Closes #599.
> feat(rpc/v02): add `starknet_call`

- crates/pathfinder/src/cairo/ext_py.rs
cairo-lang 0.10.0 does not yet support DEPLOY_ACCOUNT transactions so estimation would fail on the Python subprocess not being able to de-serialize the transaction.
Instead of the cryptic error this leads to we should just return with a straightforward error.
> fix(rpc/v02): `starknet_estimateFee` does not work for DEPLOY_ACCOUNT

- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/v02/method/get_class_at.rs
We're storing contract definitions in a compressed form in the database.
The decompression step was missing in this method so that parsing the zstd-compressed byte stream as JSON was always failing.
> fix(rpc/v02/get_class_at): add decompression of contract definition

- Cargo.lock
- crates/load-test/Cargo.toml
- crates/load-test/src/main.rs
- crates/load-test/src/requests.rs
- crates/load-test/src/types.rs
This PR adds simplified types for JSON-RPC request construction and request parsing. Scenarios in the load test don't depend on parsing the full response for the requests we're making so we can do away which much simpler types for parsing.
Closes #652.
> refactor(load-test): make load-test independent of pathfinder_lib

- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/ser.rs
The Python-side dataclass expects `at_block` to be a string (so that "latest" can be properly represented).
In our custom serialization implemented for `BlockHashNumberOrLatest` we were serializing block numbers as numbers which broke command parsing on the Python-side.
Fixes #696.
> fix(ext_py): fix serialization of block numbers

- crates/pathfinder/src/rpc/v01/api.rs
- crates/pathfinder/src/rpc/v02/method/get_block.rs
- crates/pathfinder/src/rpc/v02/method/get_state_update.rs
Closes #702 . Fixes the following:
- `v0.1`:
- `getStateUpdate`: pending should be supported
- all calls to pending when it's disabled should trigger an internal server error while now a more generic error is returned
- `v0.2`: fix inconsistencies between `getBlockWith*` and `getStateUpdate`:
- `getStateUpdate` does not return internal error when pending is requested but disabled
- `getBlockWith*` falls back to latest when pending is empty, while it should return `BlockNotFound`
> minor rpc fixes

- crates/pathfinder/src/rpc/v02.rs
This PR plugs a hole in `v0.2` tests coverage by checking that method registration actually yields JSON-RPC callable methods. This is done by picking 2 existing methods to avoid mocking and in consequence some `RpcServer` refactor:
- `starknet_blockNumber` for `register_method_with_no_input`
- `starknet_getBlockTransactionCount` for `register_method`
> v02 registration test

- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc/v02/method/chain_id.rs
Closes https://github.com/eqlabs/pathfinder/issues/711
> fix: testnet and testnet2 chain_id

- crates/pathfinder/src/core.rs
- crates/pathfinder/src/rpc/v02/method/chain_id.rs
Reverts #711 as this is StarkNet bug and not a pathfinder one.
> feat: revert SN_GOERLI2 changes

- .github/workflows/ci.yml
- .github/workflows/docker.yml
- Cargo.toml
This PR splits the test CI into separate jobs that can be executed in parallel. This has the dual benefit of speeding it up, as well as increasing the visibility into which test failed.
This is achieved by doing a single test compilation job, which archives the test binary. This is then downloaded by each test job to use.
Also version updates for some github actions (this removes the deprecation warnings in our actions).
> ci: split test commands into separate steps

- crates/pathfinder/src/rpc/v02/method/add_declare_transaction.rs
- crates/pathfinder/src/rpc/v02/method/add_deploy_account_transaction.rs
- crates/pathfinder/src/rpc/v02/method/add_deploy_transaction.rs
- crates/pathfinder/src/rpc/v02/method/add_invoke_transaction.rs
An attempt at "fixing" our RPC CI timeouts by ignoring the culprit tests.
The gateway sends us 429s because it is overloaded. Switching to testnet2 helps, but still ultimately fails, likely because we are sending too many transaction related queries in close succession.
> feat(rpc): ignore gateway related tests

- crates/pathfinder/src/rpc/v01/types.rs
- crates/pathfinder/src/rpc/v02/types.rs
- crates/pathfinder/src/sequencer/reply.rs
This supports an upcoming change (StarkNet v0.11) in the gateway's response for V1 Invoke transactions.
Closes #727.
> feat(sequencer): support v1 invoke sender_address

- crates/pathfinder/pathfinder_rpc_api.json
- crates/pathfinder/src/rpc.rs
- crates/pathfinder/src/rpc/pathfinder.rs
Adds support for querying a node's version via RPC.
To enable this, this PR adds a new RPC route: `/rpc/pathfinder/v0.1/pathfinder_version`. I've defaulted to using the version'd approach right from the start. This will also be used by any other extensions we do the rpc api.
I also want to refactor / move the existing rpc code one level deeper, something like:
```
rpc/starknet/v01.rs
rpc/starknet/v02.rs
```
to separate it from the pathfinder one's. But I'll save that for a different PR.
Closes #725.
> feat(rpc): `pathfinder_version`

- .github/workflows/ci.yml
Instead of using `find` to find the test executable we now request detailed JSON output from cargo and use `jq` to extract the name of the test executable for the `pathfinder_lib` crate.
> chore(github): get test executable name directly from cargo

- crates/pathfinder/examples/estimate_past_transactions.rs
- crates/pathfinder/src/cairo/ext_py.rs
- crates/pathfinder/src/cairo/ext_py/ser.rs
- crates/pathfinder/src/cairo/ext_py/sub_process.rs
- crates/pathfinder/src/rpc/v01/api.rs
- crates/pathfinder/src/rpc/v02/method/call.rs
- crates/pathfinder/src/rpc/v02/method/estimate_fee.rs
- crates/pathfinder/src/state/sync.rs
- py/src/pathfinder_worker/call.py
- py/tests/pathfinder_worker/test_call.py
The pending block has a timestamp included, so we have to make sure that one gets used. Otherwise timestamp-dependent code might just fail to execute properly.
This means that now we include an optional block timestamp in both Call and EstimateFee commands sent to the Python subprocess that contains the timestamp from the pending block (if non-zero). The Python code setting up the execution environment then overrides the block timestamp in `BlockInfo` with the exact data received in the command.
Closes #737
> fix(ext_py): use pending block timestamp when executing code on the pending block

- Dockerfile
Our Dockerfile contains some hacks to compile dependencies in a separate layer. This involves creating "empty" crates for all crates in our workspace and copying just the Cargo.toml files from the project, then compiling the project.
Because of the new crates we've been adding our Dockerfile was out-of-date.
> fix(Dockerfile): follow-up new crates in Dockerfile

- py/pyproject.toml
- py/requirements-dev.txt
- py/src/pathfinder_worker/call.py
So that we use the latest non-alpha version.
> chore(py): upgrade to cairo-lang 0.10.2

- crates/pathfinder/src/rpc/v02/types/class.rs
We're using the `rpc::v02::types::class::ContractClass` type for
parsing input parameters for `starknet_estimateFee` calls. After
parsing the method parameters, the transaction param is converted into
an AddTransaction type for serialization to the Python worker.
This conversion involves serializing the class ABI to JSON. Here the same
derived `Serialize` implementation is used that we're using to serialize
replies to `starknet_getClass`. To be compliant with the JSON-RPC
specification we were omitting some ABI fields from the serialization:
- "input" and "output" for event ABI entries,
- and "stateMutability" for function ABI entries.
This leads to a slightly different class declaration to be sent to the
subprocess: it's missing these fields from the ABI.
During estimation the Python …
> fix(rpc/estimate_fee): fix ABI serialization for estimateFee

- .github/workflows/ci.yml
- crates/gateway-types/src/error.rs
- crates/pathfinder/src/rpc/v01.rs
- crates/pathfinder/src/rpc/v01/api.rs
This PR fixes the workflow so that it runs all the tests that used to be run before the pathfinder crate was split into more crates. As there are more big test binaries all of those that were above ~25MB are also stripped. The archive download action does not allow to download a single file from the archived set, so I decided to introduce separate actions for each stripped binary.
Tests are grouped in the yml file in the following order:
1. alphabetically, stripped test binaries
2. alphabetically, non-stripped test binaries
The file itself got a bit big but from my perspective this is not a big inconvenience whilst having the ability to see test actions for different crates being executed in parallel.
> ci: run tests for all the new crates

- py/pyproject.toml
- py/requirements-dev.txt
- py/src/pathfinder_worker/call.py
This PR upgrades cairo-lang to the latest version available.
The upgrade seems trivial: it's really just bumping the version number this time. (I know, famous last words...)
> chore(py): upgrade cairo-lang to 0.10.3

- .github/workflows/ci.yml
The `ubuntu-latest` image has been updated and now comes with Python 3.10 installed. This change modifies the Python test job to use the setup-python action to install Python 3.8 like we already do in the other jobs.
The PR also removes the part from the "Python" job that runs ignored Rust tests in `cairo::ext_py` -- those are not ignored now since we do have a proper Python environment set up during in the rust test job, too.
> chore(github): fix Python version for Python test job

- crates/pathfinder/src/cairo/ext_py/ser.rs
- py/src/pathfinder_worker/call.py
- py/tests/pathfinder_worker/test_call.py
Now that we have the Testnet2 chain ID available in cairo-lang 0.10.3 we should use the correct (updated) chain ID.
> fix(py): use proper chain id for testnet2 `starknet_estimateFee` calls

- .github/workflows/ci.yml
We're caching our installed Python dependencies but are only storing the site-packages directory. This leads to the pytest wrapper script not being available after restoring the cache. We should use "pytest -m pytest" instead that doesn't realy on scripts being present in the "bin" directory of the Python root.
> fix(ci/python): run pytest with "python -m pytest"

- .github/workflows/ci.yml
Since we're only storing the site-packages directory in the cache the wrapper script installed to the bin subdirectory of the Python root dir might not be available.
> fix(github): don't rely on wrapper scripts for black and flake8 either

- Dockerfile
- crates/common/build.rs
Our own hack tried to mimic what cargo-chef does: creating a fake project that has the exact same dependencies as our main one, compiling those dependencies and then compiling the pathfinder binary using those pre-compiled deps as a separate step. This is to allow the dependencies to be cached as a layer so that those are not re-compiled every time.
This change modifies the Dockerfile to just use cargo-chef that does all this in a maintanable manner.
> refactor(Dockerfile): use cargo-chef for build-dependency caching

- crates/load-test/src/requests/v01.rs
- crates/load-test/src/requests/v02.rs
This PR fixes load-test parsing issues for both v0.1 and v0.2 `get_events`.
These were the only failures when running this locally.
> fix: load test

- Cargo.lock
- crates/common/Cargo.toml
- crates/ethereum/Cargo.toml
- crates/gateway-client/Cargo.toml
- crates/gateway-types/Cargo.toml
- crates/gateway-types/src/class_hash.rs
- crates/merkle-tree/Cargo.toml
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/config/builder.rs
- crates/retry/Cargo.toml
- crates/rpc/Cargo.toml
- crates/serde/Cargo.toml
- crates/stark_curve/Cargo.toml
- crates/stark_hash/Cargo.toml
- crates/storage/Cargo.toml
This PR upgrades all of our Rust dependencies except `clap` and `bitvec` to the latest version in the main workspace.
> chore: upgrade Rust dependencies

- .dockerignore
- .github/workflows/docker.yml
- Dockerfile
- crates/common/build.rs
Copying the .git directory in the Dockerfile results in cache layer invalidation even for changes that have no effect at all on the source code we're building.
We needed the .git directory just so that we can generate a version number. Instead of copying that into the container we can just generate the version number first and pass that as a build argument into the build process.
> chore(docker): inject version number explicitly and don't rely on Git

- py/requirements-dev.txt
This fixes the Dependabot alert for certifi <2022.12.07. (https://github.com/eqlabs/pathfinder/security/dependabot/11)
> chore(py): upgrade Python deps

- Dockerfile
- build/cargo-build.sh
- build/cargo-chef-cook.sh
- build/prepare-stark_hash_python.sh
- build/prepare.sh
Instead of running Rust compilation steps via qemu this change adds cross-compilation both for the pathfinder binary and the stark_hash Python wrapper.
It turns out Docker has support for using layers from the build architecture instead of the target architecture. This makes it possible to use cross-compilers to produce binaries for the target architecture and use those in QEMU-emulated build layers. For more details check out this blog post:
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
Setting up an environment for cross-compilation is tricky though, since our Rust code depends on some native libraries (like OpenSSL  and Python) and a working C/C++ cross-compiler (for SQLite and zstd). This is taken care by manually downloading the …
> feat(Dockerfile): cross-compile Rust code instead of running an emulated compiler on aarch64

- .github/workflows/ci.yml
- README.md
- crates/pathfinder/Cargo.toml
This PR adds a CI check for pathfinder's minimum support rust version.
Since we usually are at the latest Rust version, we very often invalidate the MSRV specified in the pathfinder `Cargo.toml`.
Case in point, `package.rust-version = "1.62"` but in reality MSRV is `1.64.0`.
The `cargo-msrv` tool is used to verify the MSRV. It does this by installing the rust version specified and ensuring the project is compilable with `cargo check`. Installing the MSRV version of course takes a while, but once cached its very fast.
This tool can also be used to determine the actual MSRV, which it does by installing a rust version and checking it until it finds the MSRV. By default this is done using a bisect method so its not as terrible as it seems. This should be run locally and not on CI of course.
A …
> ci: add MSRV check

- crates/rpc/src/error.rs
- crates/rpc/src/pathfinder/methods/get_proof.rs
- pathfinder_rpc_api.json
This addresses a potential DoS vector by restricting the number of storage addresses a single `pathfinder_getProof` query can have. The current limit is set to 100 (no scientific method applied here, just seems like a reasonable number).
Unfortunately this new error type contains state and is therefore incompatible with our RPC macro. I've spent / wasted some time on getting this to work, but its quite complex. For the time being I think this is fine as is.
> feat(rpc): limit getProof to 100 storage keys

- crates/gateway-client/Cargo.toml
- crates/gateway-types/Cargo.toml
For crates that use `#[tokio::test]` this is required to be able to build the tests.
> fix: add missing tokio `macros` feature to dev-dependencies

- README.md
- doc/install-from-source.md
This PR makes the following changes to our README:
- added some stuff in "Features"
- moved "install from source" section to a new document (tucked away in the doc directory)
- README now clearly suggests using Docker
- the example docker run command starts pathfinder in the backround with automatic restart (after reboot) enabled
> feat(doc): move install-from-source documentation to a separate file

- .github/workflows/release.yml
This PR attempts to add a release workflow which can only be triggered manually on the `main` branch.
It does the following:
1. Update the pathfinder crate version
2. Tag that commit as `vx.y.z`
3. Push that tag & commit to `main`
4. Create draft release notes
The flow is as follows:
1. provide release version (`x.y.z` format)
2. disable `main` branch protections (so we can push to `main`)
3. make changes, commit, tag and push
4. restore `main` branch protections
Some caveats:
1. This can only be fully tested once its on main..
1. I've tested it on a private repo and it works
2. But that's a personal repo and not an org repo so the token may work differently.
2. The version is not validated as semver. Could be added but its a bit of pita.
3. This requires a personal access token (normal …
> feat: release github action

- crates/storage/src/lib.rs
The SQLite documentation suggests using normal mode when in WAL mode.
Thanks to @koivunej for pointing this out. 
Closes issue #810.
> fix(storage): set synchronous flag to normal in WAL mode

- Cargo.lock
- Cargo.toml
- crates/ethereum/Cargo.toml
- crates/gateway-client/Cargo.toml
- crates/gateway-types/Cargo.toml
- crates/load-test/Cargo.lock
- crates/load-test/Cargo.toml
- crates/pathfinder/Cargo.toml
- crates/retry/Cargo.toml
- crates/rpc/Cargo.toml
- crates/storage/Cargo.toml
This closes [dependabot #12](https://github.com/eqlabs/pathfinder/security/dependabot/12) and [dependabot #13](https://github.com/eqlabs/pathfinder/security/dependabot/13). While these issues did not actually affect pathfinder directly (because we don't run on Windows), the fix was simpler than dismissing them.
In addition, [tokio 1.24](https://github.com/tokio-rs/tokio/releases/tag/tokio-1.24.0) comes with a nice performance boost to IO tasks which made upgrading desireable.
I've also changed to using a workspace dependency for tokio - we can / should do this for all major deps imo.
> chore: bump tokio version

- CHANGELOG.md
Adds `CHANGELOG.md` according to [keepachangelog](https://keepachangelog.com/en/1.0.0/).
Hopefully this makes compiling release notes easier, and also gives users a place to spot unreleased features.
I've only added historical release notes up to `v0.4.0` because I'm lazy.
> docs: keepachangelog

- crates/storage/src/lib.rs
- py/src/pathfinder_worker/call.py
SQLite requires some pragmas and configuration options to be set on each and every connection we're having to the database.
Previously we've only set up these flags during migrating the databse, that is, on one single connection we might have in our connection pool.
This change fixes that by moving setup steps into a function and setting up SqliteConnectionManager to call that as an initialization step for each connection it's creating.
As an additional change this also makes sure the Python worker process opens the SQLite database as read-only.
> fix(storage): properly initialize connections from the pool

- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
Add `BlockValidationMode` enum (default: `Strict` check for hash match)
Avoid `#[cfg(not(test))]` in `state::l2::download_block` and use `BlockValidationMode::AllowMismatch` for testing explicitly.
> Add `BlockValidationMode` switch

- crates/rpc/src/felt.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v02/method/add_declare_transaction.rs
- crates/rpc/src/v02/method/add_deploy_account_transaction.rs
- crates/rpc/src/v02/method/add_deploy_transaction.rs
- crates/rpc/src/v02/method/add_invoke_transaction.rs
- crates/rpc/src/v02/method/block_hash_and_number.rs
- crates/rpc/src/v02/method/call.rs
- crates/rpc/src/v02/method/chain_id.rs
- crates/rpc/src/v02/method/get_block.rs
- crates/rpc/src/v02/method/get_class_hash_at.rs
- crates/rpc/src/v02/method/get_events.rs
- crates/rpc/src/v02/method/get_nonce.rs
- crates/rpc/src/v02/method/get_state_update.rs
- crates/rpc/src/v02/method/get_storage_at.rs
- crates/rpc/src/v02/method/get_transaction_receipt.rs
- crates/rpc/src/v02/method/syncing.rs
- crates/rpc/src/v02/types.rs
- crates/rpc/src/v02/types/class.rs
This PR allows us to separately encode / decode `Felt`s in the RPC setting. This is required by the RPC specification, where the serde may diverge from both the gateway and our storage implementations.
In general this is also a positive in that it decouples our RPC implementation from our other components. It would be good to perform similar surgery on other components where possible.
This PR adds `RpcFelt` and `RpcFelt251` types which implement custom serde - currently these are just the original, but can be trivially changed. We could also expand on this if we need more types or if we need different encodings for different RPC versions.
The `serde_with::SerializeAs` trait also allows specifying container types which is really nice:
```rust
#[serde_with::serde_as] …
```
> refactor(rpc): specialize `Felt` serde for RPC

- crates/ethereum/src/provider.rs
- crates/gateway-client/src/builder.rs
- crates/gateway-client/src/lib.rs
- crates/pathfinder/src/state/sync/l1.rs
Don't wait more than 10 minutes before retrying an HTTP request again.
Block time is ~10 minutes on mainnet now so this change tries to make sure that we don't fall too much behind even if a request to the feeder gateway failed.
Closes #893.
> fix(retry): set retry backoff saturation to 10 minutes

- Cargo.lock
- crates/common/Cargo.toml
- crates/common/src/lib.rs
- crates/merkle-tree/Cargo.toml
- crates/merkle-tree/src/lib.rs
- crates/merkle-tree/src/state_tree.rs
- crates/rpc/src/v02/method/get_state_update.rs
This PR implements changes in the state commitment scheme for Starknet 0.11. In particular:
- The classes tree will be computed with the Poseidon hash function, while the global state tree will continue to use Pedersen
- The leaves in the classes tree will be h(compiled_class_hash, leaf_version) where leaf_version is a field added to allow forward compatability and is currently set to 0
-  If the classes tree is none empty, the state commitment will be computed by h(global_tree_root, classes_root, commitment_version) where h is the Poseidon hash function and commitment_version is a field added to allow forward compatability and is currently set to 0
Source: https://docs.starknet.io/documentation/starknet_versions/upcoming_versions/#state_commitment
Closes #895
> Update state commitment code for Starknet 0.11

- .github/CODEOWNERS
- crates/common/src/lib.rs
- crates/merkle-tree/src/lib.rs
- crates/merkle-tree/src/state_tree.rs
- crates/rpc/src/v02/method/get_state_update.rs
- crates/stark_poseidon/README.md
- crates/stark_poseidon/poseidon.ipynb
- crates/stark_poseidon/src/hash.rs
- crates/stark_poseidon/src/lib.rs
It turned out that the sponge construction used by Starknet is different compared to what we had implemented.
This PR updates our code to match the Cairo (and Python) implementation in the pre-release of `cairo-lang` 0.11. Test vectors were added by feeding the Python implementation in `cairo-lang` random input and asserting that our result is the same as that of the Python code.
We also update state commitment computation where it was involving the Poseidon hash functions to use the proper constructs (based on code in the pre-release, again). Some constants involved in commitment calculation are also updated.
> fix(poseidon): update Poseidon sponge construct

- crates/rpc/fixtures/0.50.0/state_update.json
- crates/rpc/src/v03.rs
- crates/rpc/src/v03/method.rs
- crates/rpc/src/v03/method/get_state_update.rs
Same as v02 except for the returned type which takes into account [changes introduced by v03](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L943):
- deprecated_declared_contracts,
- declared_contracts.
`replaced_classes` is not present as it is not mentioned in the spec, we should clarify this with SW.
Depends on #917 . Fixes #865 .
> v03 get state update

- crates/pathfinder/src/state/sync.rs
When applying a state update we now update the class commitment tree with the newly declared Sierra classes.
Closes #833.
> fix(sync): add Sierra classes to the class commitment tree

- Cargo.lock
- Cargo.toml
- crates/load-test/Cargo.lock
- crates/load-test/Cargo.toml
- crates/pathfinder/Cargo.toml
- crates/rpc/Cargo.toml
Fixes dependabot alerts [#17](https://github.com/eqlabs/pathfinder/security/dependabot/17), [#18](https://github.com/eqlabs/pathfinder/security/dependabot/18), [#19](https://github.com/eqlabs/pathfinder/security/dependabot/19).
Closes #926
> chore: bump deps to solve (minor) CVEs

- crates/rpc/src/v02/method.rs
- crates/rpc/src/v03.rs
Fixes: #877 
Similarly to add_invoke_transaction - I cannot see any changes between 0.2 & 0.3, the test passes on integration as well.
> feat(rpc/v03): register add_deploy_account_transaction

- crates/common/src/test_utils.rs
- crates/pathfinder/build.rs
- crates/storage/src/test_fixtures.rs
When running the build script during a GitHub Actions build (like clippy) we're starting with an empty cargo cache. Unfortunately this breaks `cargo metadata` completely when using it with `--frozen` and `--offline` because some required crate data might be missing from the cache.
> fix(pathfinder/build.rs): fix `cargo-metadata` issues

- CHANGELOG.md
- crates/ethereum/src/provider.rs
The Ethereum Nethermind node responds with an error message if we query `eth_getLogs` with `toBlock` set a block beyond the latest known block. This PR adds support for the Nethermind specific error response, similar to what we already have for geth.
Note that this PR simply maps this error to `QueryLimit` which in turn gets handled [here](https://github.com/eqlabs/pathfinder/blob/296511628446b02195860bd3c575d6b918134423/crates/ethereum/src/state_update.rs#L124-L129). Returning `QueryLimit` is therefore sufficient because the log fetcher will respond by reducing its `toBlock` value.
Fixes #941 and fixes #689.
Complete error message format:
```
reason=(code: -32001, message: 8633830 could not be found, data: None)
```
> feat: support nethermind L1 node in `eth_getLogs`

- CHANGELOG.md
- crates/rpc/src/felt.rs
~~This PR changes `Felt::from_hex_str` to only accept `0x` prefix'd hex strings. Without this, we erroneously accepted non-prefixed felt strings in RPC, including interpretting decimal inputs silently as hex values.~~
~~In addition, this PR also adds a deserialisation exception for the gateway's `Block.state_commitment` property which unfortunately sends the value without the prefix (which was the reason for the lax felt deserialisation in the 1st place).~~
I've very much simplified the PR to only apply the "fix" to the RPC felt decoding. Initially I tried to fix it in general, but it had too many cascading effects.
This leverages the previous solution with the `RpcFelt` wrapper type - which certainly has been convenient as a quick fix. The time I sunk into this PR originally still …
> fix: rpc felt decoding does not enforce 0x prefix

- crates/rpc/src/cairo/ext_py.rs
This is temporary until we have a supporting cairo-lang release which works.
> chore(rpc): error on declare v2 fee estimation

- Cargo.lock
- crates/common/Cargo.toml
- crates/ethereum/Cargo.toml
- crates/gateway-client/Cargo.toml
- crates/gateway-test-fixtures/Cargo.toml
- crates/gateway-types/Cargo.toml
- crates/merkle-tree/Cargo.toml
- crates/p2p/Cargo.toml
- crates/pathfinder/Cargo.toml
- crates/rpc/Cargo.toml
- crates/storage/Cargo.toml
Purges `hex-literal` from the various `Cargo.toml` files.
No longer required after work done in #944.
> chore: remove hex-literal dep

- crates/pathfinder/rpc_examples_v02.sh
- crates/pathfinder/rpc_examples_v03.sh
- Minor changes to v0.2 examples.
- v0.3 examples are the same as v0.2 except for `getEvents` which shows new key filter semantics.
Fixes: #901
> rpc examples

- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
Adds an `INFO` log when ignoring sierra -> casm compilation failure on integration
> chore: log ignored compile errors

- CHANGELOG.md
- crates/pathfinder/src/state/sync/pending.rs
This PR adds a 3 minute time-cap to `gateway::state_update(pending)`.
We've previously reduced our maximum backoff time for retries, however this is not enough to ensure that pathfinder won't fall quite far behind ito actual blocks.
What can occur is that the gateway never replies `Ok(200)` to our query, but instead always 502/503s. This will cause us to sit and loop infitenitely until we get an Ok response. This PR fixes this.
> fix: pending state update never gives up

- crates/ethereum/src/contract.rs
Unable to verify the ABI as the contract has not been verified on ethscan. However, I don't anticipate that the log ABI has changed so it shouldn't matter.
> chore: update testnet core impl address

- py/tests/pathfinder_worker/test_call.py
Due to issues with the previous pre-release of cairo-lang 0.11.0 we couldn't properly use query versions in transactions and estimating Declare v2 was broken too.
This PR fixes all of these remaining test issues.
> fix(py/test_call): fix some FIXMEs that were left in tests

- Dockerfile
Fetching the full crate index via git already required some workarounds to avoid using too much memory, so switching to use the new sparse registry protocol both simplifies our Dockerfile and should make the build quicker as well.
> chore(Dockerfile): upgrade Rust to 1.68 and use cargo sparse registry protocol

- CHANGELOG.md
- crates/ethereum/src/state_update.rs
This is a bandaid fix for a bug in how we fetch L1 logs. This is an edgecase / papercut in the current algorithm which will pretty much only occur for nethermind nodes - because they don't allow querying past latest block.
Once we are in sync for L1, nethermind does not allow us to query past the `latest` block. Our algorithm handles this well, and this means that `stride_cap = 1` i.e. our max query range is 1. Which makes sense as essentially we have to query block by block.
If there is then a block with no logs, then we should query by at least two blocks. However, the stride calculation is:
```
self.stride = (self.stride.saturating_add(max + 1)) / 2
```
and if both `stride` and `max` are `1`, then `stride` remains `1` and we hit an infinite loop.
I opted to special case the `stride_cap …
> fix: nethermind L1 node spam

- CHANGELOG.md
- crates/pathfinder/src/sierra.rs
Looks like there are classes on testnet that use libfuncs only allowed in the experimental libfuncs list.
> fix(pathfinder/sierra): use experimental libfunc list

- crates/pathfinder/examples/estimate_past_transactions.rs
- crates/rpc/src/cairo/ext_py.rs
- crates/rpc/src/cairo/ext_py/de.rs
- crates/rpc/src/cairo/ext_py/ser.rs
- crates/rpc/src/cairo/ext_py/sub_process.rs
- crates/rpc/src/v02/method/estimate_fee.rs
- crates/rpc/src/v03.rs
- crates/rpc/src/v03/method.rs
- crates/rpc/src/v03/method/estimate_fee.rs
- py/src/pathfinder_worker/call.py
- py/tests/pathfinder_worker/test_call.py
- py/tools/compute_class_hash.py
This includes adding the ability to estimate a list of transactions to the underlying Python worker process, and the inter-process communication too.
Closes #862
> feat: implement JSON-RPC API v0.3 `starknet_estimateFee`

- .github/workflows/ci.yml
- crates/stark_hash_python/Cargo.lock
- crates/stark_hash_python/Cargo.toml
- crates/stark_hash_python/src/lib.rs
- py/src/pathfinder_worker/call.py
This change exports our Poseidon implementation functions into Python via the stark_hash_rust Python module and then monkey-patches the cairo-lang module to use our Rust impls instead of the default Python implementation.
This leads to significantly faster execution of some operations, like computing the class hash of a Sierra class: in one test case this has gone down from 17s to 3s.
> feat(stark_hash_python): add Poseidon hash function implementations

- Cargo.lock
- crates/load-test/Cargo.lock
Closes six openssl related security alerts. Three from pathfinder, three from load-test (the same three), since they have separate lockfiles.
Fixes [#1](https://github.com/eqlabs/pathfinder/security/dependabot/20), [#2](https://github.com/eqlabs/pathfinder/security/dependabot/21), [#3](https://github.com/eqlabs/pathfinder/security/dependabot/22), [#4](https://github.com/eqlabs/pathfinder/security/dependabot/23), [#5](https://github.com/eqlabs/pathfinder/security/dependabot/24), [#6](https://github.com/eqlabs/pathfinder/security/dependabot/25)
> chore: bump openssl for security

- CHANGELOG.md
- crates/common/src/lib.rs
- crates/gateway-client/src/lib.rs
- crates/gateway-types/src/reply.rs
- crates/gateway-types/src/request.rs
- crates/pathfinder/examples/estimate_past_transactions.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v02/method/add_declare_transaction.rs
- crates/rpc/src/v02/method/add_deploy_account_transaction.rs
- crates/rpc/src/v02/method/add_invoke_transaction.rs
- crates/rpc/src/v02/method/estimate_fee.rs
- crates/rpc/src/v02/method/get_transaction_by_hash.rs
- crates/rpc/src/v02/method/get_transaction_receipt.rs
- crates/rpc/src/v02/types.rs
- crates/rpc/src/v03/method/estimate_fee.rs
- crates/serde/src/lib.rs
- crates/storage/src/schema/revision_0007.rs
- crates/storage/src/schema/revision_0015.rs
- crates/storage/src/schema/revision_0020.rs
- crates/storage/src/state.rs
- crates/storage/src/test_utils.rs
This PR changes the `Fee` inner type from `H128` to `Felt`. The primary reason is to deal with #989 - the RPC specification defines `Fee` as a felt, and our deserialization restricted `Fee` to be `< 32 hex characters` - this meant it rejected `0x000000...0000000000001` for example. Which is valid and technically even more correct since the spec actually says to use 64 digits.
`H128` stems from the gateway (and cairo-lang) restriction of `max_fee = 2^128`, however considering `Felt` allows for this (and some more), we can let the cairo-lang / gateway deal with this rejection.
A side-effect of this PR is to also prettify the test constants used for `Fee`, and we also got rid of an extra `FeeAsHexStr` cast.
Please take a second to think whether this `H128 -> Felt` has any further impact …
> refactor: change fee to felt

- crates/rpc/src/cairo/ext_py.rs
- crates/rpc/src/cairo/ext_py/ser.rs
- crates/rpc/src/v02/types/class.rs
- py/src/pathfinder_worker/call.py
- py/tests/pathfinder_worker/test_call.py
Instead of re-computing class hashes in Python (which is in fact just calling the Cairo implementation) this PR pre-computes class hashes for all `BroadcastedDeclareTransaction`s in Rust and sends that as a class hash hint to the transaction to the Python worker.
The worker then injects these class hash values for the classes in declare transactions into a class hash cache so that we avoid actually calling the Cairo class hash calculation.
This leads to a very significant speed-up, especially with Sierra classes. Estimating a Declare v2 declaring a standard ERC20 token contract went from 17s to 0.8s.
> feat(ext_py): speed up fee estimation for declare transactions

- CHANGELOG.md
- Cargo.lock
- crates/pathfinder/Cargo.toml
We can also wait for #977 and #987 before making this release. That way we have complete v0.3 RPC support.
> chore: v0.5.2 release

- Dockerfile
The `stark_poseidon` crate is now a dependency of the Python wrapper, so we'll have to copy that crate into the containers.
> fix(Dockerfile): fix `rust-python-starknet-*`

- .github/workflows/ci.yml
- crates/common/src/test_utils.rs
- crates/gateway-client/Cargo.toml
- crates/gateway-client/src/lib.rs
- crates/gateway-client/tests/metrics.rs
- crates/pathfinder/src/monitoring.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/context.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/test_client.rs
- crates/rpc/src/versioning.rs
- crates/rpc/tests/versioning.rs
1. Remove RecorderGuard. A Scoped guard remains but just as a mean to deregister the global recorder.
2. Tests that fiddle with metrics and rely on them are in separate binaries, which makes the locking unnecessary. Test inter-dependencies are removed.
3. Integration tests are made explicitly callable __intentionally__. This is because they require respective crates to provide a feature `test-utils` and otherwise without explicitly marking those integration test targets one would have to specify `--features test-utils` for clippy :facepalm: and other non-integration tests. Essentially I chose the lesser evil, plus I think integration tests should be easily "spot-able", which in this case means that you need to invoke `cargo test` with `--test integration*` as all of them should be named …
> remove recorder guard

- .github/workflows/docker.yml
- Cargo.lock
- crates/common/Cargo.toml
- crates/common/build.rs
- crates/common/src/consts.rs
- crates/gateway-client/src/lib.rs
- crates/load-test/Cargo.lock
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/bin/pathfinder/update.rs
- crates/rpc/src/pathfinder.rs
This PR does minor patch bumps for `h2` and `spin` depedencies and a major bump for `vergen` to fix security issues.
Also fixes an issue with `pathfinder --version` which was displaying the crate version and not the more informative `git describe`.
Closes dependabot alerts [#28](https://github.com/eqlabs/pathfinder/security/dependabot/28), [#33](https://github.com/eqlabs/pathfinder/security/dependabot/33), [#34](https://github.com/eqlabs/pathfinder/security/dependabot/34), [#35](https://github.com/eqlabs/pathfinder/security/dependabot/35).
Unfortunately I'm not able to close the remaining `time` related warnings at this time. This comes in via `chrono` (which is unmaintained), which in turn comes in via `ethers` and `cairo-lang-utils`. Technically `serde_with` also pulls in `chrono` -- …
> chore: bump deps for security fixes

- CHANGELOG.md
- Cargo.lock
- crates/common/src/lib.rs
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/lib.rs
- crates/rpc/src/metrics.rs
- crates/rpc/src/middleware.rs
- crates/rpc/src/middleware/cors.rs
- crates/rpc/src/middleware/versioning.rs
- crates/rpc/src/module.rs
- crates/rpc/tests/versioning.rs
Fixes: #784 
- new command line option: `http-rpc.cors-domains` (cors domains instead of imo more intuitive "cors-allowed-origins" because this seems to be the convention followed by geth), maybe the latter is better though, wdyt?
- btw I noticed a peculiar bug with metrics and the unfortunate way we now version the api, so I fixed it,
- I also did a manual "live" test with a more proper setup: a simple server serving a simple page with a script that fetches from the rpc server which is of different origin, preflight requests are auto generated by the browser, and it works for me :shrug: 
- as for proper integration tests there's a simple preflight test
> cors support

- crates/ethereum/resources/contracts/core_impl_0.11.1.json
- crates/ethereum/src/contract.rs
- crates/ethereum/src/log.rs
- crates/ethereum/src/state_update.rs
This PR adds support for the new L1 starknet contract ABI introduced with v0.11.1. This ABI change is not backwards compatible ito the state update event, which we (currently) use to fetch starknet state on L1.
As of starknet v0.11.1 we have two incompatible state update log ABIs. This means they have different topics, and are decoded differently.
Note: I didn't spend too much time on naming etc, in anticipation of this code getting removed in the short term future.
Closes #1053.
> feat: support v0.11.1 L1 contract

- crates/common/src/lib.rs
- crates/gateway-test-fixtures/fixtures/integration/block/285915.json
- crates/gateway-test-fixtures/src/lib.rs
- crates/gateway-types/src/reply.rs
- crates/pathfinder/examples/calculate_commitments.rs
- crates/pathfinder/examples/verify_block_hashes.rs
- crates/pathfinder/src/state/block_hash.rs
- crates/pathfinder/src/state/sync.rs
- crates/rpc/src/cairo/ext_py.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/v02/method/estimate_fee.rs
- crates/rpc/src/v02/method/get_block.rs
- crates/storage/src/state.rs
- crates/storage/src/test_fixtures.rs
- crates/storage/src/test_utils.rs
Starknet 0.11.1 block hash calculation contains a change that includes the transaction signature into the transaction commitment for all transaction types having a signature -- and not just invokes.
This is an incompatible change: we have to use the new commitment calculation for blocks with version >= 0.11.1, and the old one for older blocks.
> fix(pathfinder/block_hash): update block hash verification for Starknet 0.11.1

- Dockerfile
Some stark_hash deps are now workspace dependencies, so we need the workspace Cargo.toml as well...
> fix(Dockerfile): fix Python stark_hash wrapper build

- Dockerfile
- build/prepare-stark_hash_python.sh
- build/prepare.sh
The cargo-chef base image seems to be missing Python 3.9 and pkg-config now so we have to install those in our prepare scripts.
I've also removed setting CARGO_REGISTRIES_CRATES_IO_PROTOCOL to `sparse` since the cargo-chef base image already has that.
> feat(Dockerfile): upgrade cargo-chef and Rust to 1.69

- crates/gateway-client/src/builder.rs
- crates/gateway-client/src/lib.rs
- crates/gateway-client/tests/metrics.rs
- crates/pathfinder/examples/download_state_updates.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/state/sync/pending.rs
- crates/rpc/src/pathfinder/methods/get_transaction_status.rs
- crates/rpc/src/v02/method/add_declare_transaction.rs
- crates/rpc/src/v02/method/add_deploy_account_transaction.rs
- crates/rpc/src/v02/method/add_invoke_transaction.rs
- crates/storage/src/schema/revision_0013.rs
I noticed a couple of unused gateway APIs so I removed them. And then I refactored the trait a bit. 
The 2nd and 3rd commits are optional, and I'm happy to remove them if they are useless churn.
> feat: cleanup gateway api

- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
Defaults the tracing level to `warn` for dependencies. `jsonrpsee_server` has started logging connection events at the `info` level, so this change silences those.
Also attempted to improve the CORS description, however I'm unsure if its correct as is.
> chore: minor usage improvements

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/main.rs
Some dependencies are rather chatty even at `warn` level. For example, [jsonrpsee](https://github.com/paritytech/jsonrpsee/issues/1120)currently emits `warn` when a client disconnects during the connection process which can happen rather frequently for public facing services.
We should consider re-enabling dependency logs once it is fixed and we have upgraded jsonrpsee.
> fix: spammy rpc connection logs

- CHANGELOG.md
- crates/gateway-client/src/builder.rs
- crates/gateway-client/src/lib.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/src/gas_price.rs
This PR fixes pathfinder estimate fee gas price being considerably off compared to the sequencers estimate. The sequencer has changed its gas estimation algorithm to compensate for strange gas prices in particular on Goerli. Since we use `eth_gasPrice` directly, this now means we are using different numbers to the sequencer.
Instead of querying gas price directly from ethereum, we instead rely on the sequencers own gas price estimate. This data is fetched from the pending block.
I'm not wholly convinced of the robustness of this approach given the gateway's proclivity for rate-limiting. In particular, this will be prone to breaking especially during sync, where the node is likely to hit rate-limiting.
Fixes #1082.
> feat: use starknet gas price instead of ethereum

- crates/rpc/src/gas_price.rs
Contrary to what you'd expect `H256::from_sice` succeeds _only_ if the length of the input slice is exactly 32 bytes.
> fix(rpc/gas_price): fix gas price H256 conversion

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/ethereum/Cargo.toml
- crates/gateway-client/Cargo.toml
- crates/gateway-types/Cargo.toml
- crates/gateway-types/src/reply.rs
- crates/gateway-types/src/transaction_hash.rs
- crates/p2p/Cargo.toml
- crates/pathfinder/Cargo.toml
- crates/rpc/Cargo.toml
- crates/stark_hash/Cargo.toml
- crates/storage/Cargo.toml
In the times before L1 Handler was a transaction type, these were instead served as Invoke V0 transactions. This can be confusing, especially as the gateway retroactively changed these, and now serves them as L1 Handler. Really old pathfinder databases still store these as Invoke V0 which can cause pathfinder RPC output to appear different, even though they are technically equivalent.
This PR fixes that by adding a deserialization step which maps these Invoke V0 to L1 Handler.
Alternative solution is a database migration, but this would require opening every single tx which would be costly.
Note that this doesn't fix all instances, as there also exist transactions which also do not contain the `entry_points_type` but one would instead have to check the transaction's contract to match its …
> fix: historic L1 handler txs are identified as Invoke

- crates/rpc/src/cairo/ext_py.rs
- crates/rpc/src/v02/method/estimate_fee.rs
- crates/storage/src/state_update.rs
- py/src/pathfinder_worker/call.py
- py/src/pathfinder_worker/storage.py
- py/tests/pathfinder_worker/test_call.py
This PR implements a `StateReader` using the flattened state data from our database for the Python execution layer.
Most of the state set-up code in tests (setting up the global and contract Merkle trees) is not strictly needed but I've still left it as is. We can get rid of that code if we think it's not required.
> feat(py): implement storage adapter for flattened state

- .github/workflows/ci.yml
- crates/pathfinder/src/p2p_network.rs
- crates/pathfinder/src/p2p_network/sync_handlers.rs
And modify CI job to run clippy and `cargo test` with `--all-features` so that we catch these issues on CI.
> fix(p2p): fix compile errors in the disabled-by-default P2P integration code

- crates/gateway-types/src/reply.rs
- crates/pathfinder/examples/feeder_gateway.rs
The feeder_gateway example emulates the feeder gateway REST endpoints pathfinder requires for syncing. This way, given an already populated pathfinder SQLite database this tool can be used as a _source_ of syncing making quick experiments with our data storage / sync logic possible.
> feat(pathfinder): add feeder_gateway mock

- Cargo.lock
- crates/gateway-client/src/lib.rs
- crates/gateway-types/Cargo.toml
- crates/gateway-types/src/lib.rs
- crates/gateway-types/src/websocket.rs
- crates/pathfinder/Cargo.toml
- crates/pathfinder/examples/compute_class_hash.rs
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/lib.rs
- crates/rpc/src/module.rs
- crates/rpc/src/websocket.rs
- crates/rpc/src/websocket/subscription.rs
- crates/rpc/src/websocket/subscription/subscribe_new_heads.rs
- doc/rpc/pathfinder_rpc_api.json
Hello pathfinder team, thanks for your patience. It's been a long journey but here we are.
This PR is a proof of concept implementation that allows event subscription with websockets. Larger objective is to discuss and get a consensus with the community on event subscription API and supported events with the publication of a [SNIP](https://github.com/matthieuauger/SNIPs/blob/main/SNIPS/snip-5.md). 
Currently code implements one event: `newHeads`.
You can subscribe to this event with function `starknet_subscribe_newHeads`.
Architecture is ready for multiple events once we defined them in the SNIP.
If current implementation is ok for you, we will update the SNIP and have interviews with Pathfinder community to understand.
PR is authored by @shramee and myself. If you want to we can plan a …
> Allow event subscription with websockets

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/sierra.rs
This PR adds support for the new Sierra compiler required for starknet v0.11.2.
Compiler selection relies on the block's starknet version, which means this PR is safe to release already i.e. is backwards compatible.
I also renamed things a bit, as its getting awkward with 3 compilers in the mix now.
Closes #1099
> feat: support sierra compiler for starknet v0.11.2

- CHANGELOG.md
- crates/rpc/src/v03/method/simulate_transaction.rs
Main issue is that the RPC spec uses poor wording tbh :)
[Link](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_trace_api_openrpc.json#L53) to the spec line.
> fix(rpc): simulate input has a type

- Cargo.lock
- crates/rpc/src/v02/method/call.rs
- crates/rpc/src/v02/method/estimate_fee.rs
- crates/storage/Cargo.toml
- crates/storage/src/lib.rs
This PR isolates and fixes tests that were using `crate/rpc/fixtures/mainnet.sqlite` and causing weird side-effects in PRs (updates to the file that can slip into PR via `git add .`).
> Always use copy of `fixtures/mainnet.sqlite`

- crates/gateway-client/src/builder.rs
- crates/gateway-client/src/lib.rs
- crates/gateway-client/tests/metrics.rs
- crates/gateway-types/src/error.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/rpc/src/v02/method/add_declare_transaction.rs
Instead of handling unknown error codes as de-serialization errors this PR adds a catch-all error variant that just stores the code we've received as a string -- this helps because then we include this string representation in the internal error we're returning over JSON-RPC.
We also add the INVALID_CONTRACT_CLASS error code as a known error so that we can return the proper JSON-RPC response code in `starknet_addDeclareTransaction`.
Fixes #1122
> fix(gateway-types/error): handle unknown Starknet error codes

- crates/rpc/src/v03/method/simulate_transaction.rs
So that we allow naming the argument "transaction" and "transactions" too.
Version 0.3.0 of the specification requires "transaction", but this will be fixed in a future version because "transactions" makes more sense.
> fix(rpc/v03/simulate_tranasction): add "transactions" alias

- crates/common/src/lib.rs
- crates/ethereum/src/lib.rs
- crates/pathfinder/src/state/sync/l1.rs
This PR changes the L1 producer to only emit an update if a change is detected.
Current behaviour emits an update event even if nothing has changed resulting in pretty spammy logs:
```
2023-06-12T10:29:59  INFO L1/L2 block hash match block_number=BlockNumber(817909)
2023-06-12T10:29:59  INFO L1 sync updated to block 817909
2023-06-12T10:30:29  INFO At head of chain poll_interval=30s
2023-06-12T10:30:30  INFO L1/L2 block hash match block_number=BlockNumber(817909)
2023-06-12T10:30:30  INFO L1 sync updated to block 817909
2023-06-12T10:30:59  INFO At head of chain poll_interval=30s
2023-06-12T10:31:00  INFO L1/L2 block hash match block_number=BlockNumber(817909)
2023-06-12T10:31:00  INFO L1 sync updated to block 817909
2023-06-12T10:31:29  INFO At head of chain poll_interval=30s …
```
> fix: L1 logs update even if no change occurred

- crates/gateway-types/src/class_hash.rs
Code is rough and a bit inefficient, but this is an emergency so maybe worth merging and releasing first, and optimize it later.
I've tested this on my own mainnet node deployment and it's able to successfully sync the problematic block `84448`.
> fix: wrong class hash on non-ascii artifacts

- CHANGELOG.md
- crates/pathfinder/examples/feeder_gateway.rs
- crates/pathfinder/examples/verify_block_hashes.rs
- crates/pathfinder/examples/verify_transaction_hashes.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
- crates/rpc/src/cairo/ext_py.rs
- crates/rpc/src/v02/method/call.rs
- crates/rpc/src/v02/method/estimate_fee.rs
- crates/rpc/src/v03/method/simulate_transaction.rs
- crates/storage/src/lib.rs
This PR creates separate database connection pools for sync, rpc and p2p.
Currently there is only a single shared connection pool. Slow RPC queries can therefore exhaust the connection pool, causing the sync process to halt as no connection can be obtained.
> fix: slow rpc queries can exhaust db connection pool

- crates/storage/src/connection/trie.rs
- crates/storage/src/schema/revision_0035.rs
This PR removes storage schema migration 35 entirely. It was slow and gave no benefit.
We'll have to revisit reference counting again when we add deleting tries.
> feat(storage): remove revision 35

- CHANGELOG.md
- README.md
- crates/pathfinder/src/state/sync.rs
This PR adds several new metrics related to time spent processing a block.
Fairly sure I've done the metrics wrong - can one even add meta-data like block number? Naming is also poor.. suggestions welcome. 
I would also like to add more fine grained metrics, e.g. trie mutation, trie hash calcs, trie db writing, but that requires separating out those parts properly - another day.
I'll update the changelog once we've settled on naming.
New metrics:
```
block_download             // time taken to download block data excl classes
block_processing
block_latency              // diff between block timestamp and local time i.e. delay between block publish and us inserting it
block_time                 // timestamp diff between this block and previous one on chain
```
Any better ideas for naming …
> feat: block timing metrics

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l1.rs
- crates/pathfinder/src/state/sync/l2.rs
This PR makes head and pending poll intervals configurable.
I decided to stick to static CLI config and not to add endpoints to overwrite "live" values.
To change the poll intervals, respective parameter (or env variable) must be changed and Pathfinder restarted.
> Make head & pending poll intervals configurable

- crates/pathfinder/src/state/sync.rs
Fixes the block height related metrics.
The `counter!` macro was used which actually just increments the counter and doesn't set it. While there is `absolute_counter!` which would sort of work, the bigger issue is that a counter must be monotonically incrementing which means it cannot handle reorgs.
This PR therefore changes these to gauages.
> fix: block height metrics should be gauges

- .github/workflows/deploy_website.yml
- .gitignore
- website/book.toml
- website/src/SUMMARY.md
- website/src/blog/2023-05-17_mainnet_incident.md
- website/src/introduction.md
This PR adds a manually triggered workflow which deploys a github pages website.
We want to publish our post-mortem here, and one day an mdbook docs for pathfinder. And maybe other blog posts and interesting things :) 
Maybe the `website` should be inside docs folder instead?
> docs: github pages deploy action

- .github/workflows/deploy_website.yml
Fixes the github pages workflow. Since a workflow must be on `main` before it can be triggered, this makes it difficult to test, but I believe it is now correct.
> docs: fix mdbook deployment

- crates/rpc/src/v02/method/get_transaction_receipt.rs
This PR changes the status of a pending transaction to L2 accepted in accordance with v0.12 starknet.
Closes #1166
> feat(rpc): remove pending tx status

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
This PR reduces the sync poll rates and matches the rpc db and network connection pools.
The default sync poll rates are reduced from 30s to 5s and the pending poll rate from 5s to 3s. This is in anticipation of much shorter v0.12 block times.
I've also matched the RPC db connection limit to the network connection limit. I'm sure this is overkill, but its not clear to me if this is actually costly?
These changes are not ideal, but time is in short supply.
> feat: config updates for starknet v0.12

- crates/common/src/lib.rs
- crates/merkle-tree/src/contract_state.rs
This PR adds support for the special contract at address 0x1 introduced in starknet v0.12.
The special contract is never deployed and always has class hash and nonce set to 0. This PR adds an exception for this special case.
The situation here isn't great, but this will work for now.
> feat: support special 0x1 contract

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/main.rs
Change the rpc db pool size from rpc network pool size to 1/8th thereof.
Having it match the network limit would set the default to 1024 which would likely fail since that is often the file handle limit on unix. In addition, having too many open is counter-productive as all queries would become slower instead of only a few that idle.
> chore:  rpc db connections to 1/8 network limit

- CHANGELOG.md
- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/sierra.rs
This PR replaces the v1.1 sierra compiler with ~~v2.0.0-rc5~~ v2.0.0-rc6.
The compiler is backwards compatible. ~~We still need confirmation on whether this is the final release candidate; will keep the PR unmerged until then.~~
Closes #1168
> feat: sierra 2.0.0-rc5 compiler

- CHANGELOG.md
- crates/rpc/src/v02/method/get_events.rs
- crates/rpc/src/v03/method/get_events.rs
- crates/storage/src/connection/event.rs
We seem to have performance issues with `starknet_getEvents`. The issue is that we need different query strategies for different cases but unfortunately the SQLite query optimizer does not have all the information it would need to select the best query plan...
Previously we queried the key FTS table first, but this has been changed in https://github.com/eqlabs/pathfinder/pull/1132 to always do the range-based lookup first and _then_ filter the result set with the key filter. Unfortunately this caused a regression for some queries that were working before...
There are two main cases we would like to optimize for:
-  The block range (and optionally `address`) present in the filter is quite narrow, but the key filter would return at least an order of magnitude …
> Select query strategy for `starknet_getEvents` dynamically

- Cargo.lock
- Cargo.toml
- crates/load-test/Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/stark_hash/Cargo.toml
- crates/stark_poseidon/Cargo.toml
This PR bumps criterion and openssl to fix security advisories.
The criterion bump addresses our own dependency on `atty` but unfortunately it still remains due to the sierra compiler.
> chore: bump deps for security advisories

- crates/common/src/lib.rs
- crates/rpc/src/context.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/module.rs
- crates/rpc/src/v02/method/get_block_transaction_count.rs
- crates/rpc/src/v02/method/get_transaction_receipt.rs
- crates/rpc/src/v03/method/simulate_transaction.rs
Closes https://github.com/eqlabs/pathfinder/issues/1180
`RpcContext` becomes version-aware, which is necessary to fit both v0.2 and v0.3 versions of the spec:
- In v0.3 a mandatory field `from_address` is added to `MSG_TO_L1` entity
- For v0.2 method, the response is patched effectively removing `from_address`
- AFAICT for v0.2 only `get_transaction_receipt` method is affected
It is an ugly but tiny & working solution which avoids copying lots of code from v02 to v03.
> fix(rpc/v0.3): add `from_address` to `MSG_TO_L1`

- crates/pathfinder/src/state/sync.rs
In the recent refactor system contract updates have been separated in the `StateUpdate` struct -- but the `update_starknet_state` function was not properly updated to handle these updates, leading to state root mismatches.
> fix(pathfinder/sync): apply system contract updates

- CHANGELOG.md
- crates/gateway-client/src/builder.rs
Starknet 0.12 seems to have changed the HTTP status code for at least some Starknet errors (like BLOCK_NOT_FOUND). Up to now these errors always came with HTTP status code 500 so we weren't properly parsing them now.
This causes all kinds of unintended side effects, like sync not polling properly and not entering poll pending mode.
> fix(gateway-client): handle Starknet errors with HTTP status code 400

- CHANGELOG.md
- crates/common/src/state_update.rs
- crates/gateway-client/src/lib.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/state/sync/pending.rs
This PR ignores inconsistent pending data from the gateway.
The gateway can emit inconsistent pending data, which we are in-turn currently passing onto our users. This occurs because the gateway has multiple feeder servers which store independent cached copies of the pending state which are not synchronized. This does not affect non-pending data as that is backed by a single database.
This PR works-around this by ensuring that only monotonically increasing pending data is emitted. i.e. only emit pending data if there are more transactions than before. Currently it is possible that pending calls will contain less txs than the call before.
~~I'm still trying to figure out how to test this with the mock.~~
-- edit -- 
I've refactored it entirely to separate the state update and block …
> feat(sync): ensure pending data is consistent

- py/src/pathfinder_worker/call.py
This PR increases the python error message limit from 200 to 50 000
We originally introduced this truncation as the error messages could reach ridiculous sizes in extreme cases. However, the current limit of 200 isn't very useful for users trying to debug their transactions. See [here](https://github.com/xJonathanLEI/starkli/issues/13) for some additional context. 
A simple contract declaration can fail with errors around 3 000 characters. With more complex contracts and a deeper call-stack, 50 000 seems like a reasonable compromise.
> feat: increase python error message limit

- .github/workflows/docker.yml
This PR removes the space and swapfile work-arounds in the docker workflow.
The space savings are no longer required on the larger runner we are now using.
The swapfile work-around should no longer be required with cargo using sparse checkouts.
> ci: remove docker build hacks

- CHANGELOG.md
- crates/gateway-types/src/reply.rs
This PR fixes cairo 0 class declarations being missed.
This bug was introduced in v0.6.4 with the internal state update changes.
> fix: missing cairo 0 classes

- CHANGELOG.md
- crates/rpc/src/error.rs
- crates/rpc/src/v02/method/add_declare_transaction.rs
- crates/rpc/src/v02/method/add_deploy_account_transaction.rs
- crates/rpc/src/v02/method/add_invoke_transaction.rs
This PR includes the `anyhow` backtrace in the internal RPC error message.
Previousl we used `#[error(transparent)]` which forwards to anyhow's display impl - which in turn exludes the error's backtrace. This led to somewhat useless error messages.
Closes #1211.
> fix(rpc): gateway errors are not passed through

- CHANGELOG.md
- crates/storage/src/connection/state_update.rs
- crates/storage/src/schema.rs
- crates/storage/src/schema/revision_0036.rs
- py/src/pathfinder_worker/call.py
This PR fixes system storage updates not being stored.
The state update refactor separated the system contract updates from the user contract storage updates. I forgot to change the storage method which inserts state updates to handle this correctly.
This PR:
1. fixes the state update insert method
2. adds a migration to re-insert the missing updates
(2) relies on the fact that only a single system contract exists and is well-defined ito storage values. It also implicitly relies on the fact that we will require another release before another system contract is released i.e. users should not be able to continue running without upgrading before another system contract is
> fix: system updates are not stored

- CHANGELOG.md
- crates/gateway-types/Cargo.toml
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
This PR adds configuration for tracing log color output.
Currently we always (afaict) output logs in color.
Adds the configuration option `--color = auto | always | never` where `auto` is the default. Technically this is a breaking change if we consider text color to be part of the guarantee - which I don't.
`auto` will output color if stdout is going to terminal, false otherwise.
For context here is what ripgrep does:
```
--color <WHEN>                           
This flag controls when to use colors. The default setting is 'auto', which
means ripgrep will try to guess when to use colors. For example, if ripgrep is
printing to a terminal, then it will use colors, but if it is redirected to a
file or a pipe, then it will suppress color output. ripgrep will suppress color
output in some …
```
> feat: suppport color output configuration

- CHANGELOG.md
- crates/rpc/fixtures/ext_py/tx_traces.json
- crates/rpc/src/cairo/ext_py/types.rs
- crates/rpc/src/v03/method/simulate_transaction.rs
Our type used to parse L2->L1 messages didn't match what the cairo-lang code in the Python subprocess was outputting: these message objects don't have a `from_address` property.
Unfortunately neither the test fixture we are using for testing deserialization nor the end-to-end test has any of these messages so we didn't have sufficient test coverage here.
I've added a single example message (from a real trace) to the JSON fixture.
Fixes #1225
> Fix `starknet_simulateTransaction` for transactions sending L2->L1 message

- README.md
v0.2 was associated with `/` instead of v03.
I'm unsure if newton faq is still actively supported. I recall seeing somewhere that the answers were outdated.. should we just yank them entirely?
Closes #1221
> docs: fix readme jsonrpc api routing info

- crates/gateway-types/src/reply.rs
- crates/pathfinder/src/p2p_network/client.rs
- crates/pathfinder/src/p2p_network/sync_handlers.rs
- crates/rpc/src/lib.rs
- crates/storage/src/connection/event.rs
- crates/storage/src/connection/transaction.rs
- crates/storage/src/test_utils.rs
- justfile
This PR adds support for deserializing receipts for starknet v0.12.1 which now have execution status and an optional revert_error fields.
This change is backwards compatible as the status defaults to success if missing which allows for receipts currently in storage to still operate.
One downside of this implementation is that ideally we would combine the two fields:
```rust
enum ExecutionStatus {
Succeeded,
Reverted(String)
}
```
Is there an easy way to achieve this?
I also wonder if we shouldn't start separating storage from the gateway types..
> feat: support reverted receipts from gateway 

- crates/rpc/src/context.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/middleware/versioning.rs
- crates/rpc/src/v03/method.rs
- crates/rpc/src/v03/method/estimate_message_fee.rs
- crates/rpc/src/v04.rs
- crates/rpc/src/v04/method.rs
- crates/rpc/src/v04/method/estimate_message_fee.rs
This PR bootstraps initial v0.4 RPC support and updates `starknet_estimateMessageFee` to match the latest schema.
I've bootstrapepd v0.4 support by just copying across the v0.3 methods. 
`starknet_estimateMessageFee` is split into v0.3 and v0.4 by mapping the latters input changes to the formers.
> feat: estimate message fee schema changes

- crates/gateway-types/src/reply.rs
- crates/pathfinder/src/p2p_network/client.rs
- crates/pathfinder/src/p2p_network/sync_handlers.rs
- crates/rpc/src/lib.rs
- crates/storage/src/connection/event.rs
- crates/storage/src/test_utils.rs
Fixes builtin's not being correctly parsed.
I've opted to go with default to zero values, instead of options to represent the builtins. I'm happy to change this, but I think less remapping / indirection is better ergonomincally.
Closes #1237.
> fix: receipt builtins are not parsed

- crates/rpc/src/lib.rs
- crates/rpc/src/pathfinder/methods/get_transaction_status.rs
- crates/rpc/src/v02/method/get_block_transaction_count.rs
- crates/rpc/src/v02/method/get_transaction_receipt.rs
- crates/rpc/src/v02/method/pending_transactions.rs
This PR adds support for reverted transactions in `starknet_getTransactionReceipt` and `pathfinder_getTransactionStatus`.
`starknet_getTransactionReceipt` throws an error for reverted transactions as it cannot represent them in the v0.3 RPC specification and this is the closest analogue to what currently occurs.
`pathfinder_getTransactionStatus` now checks the receipt for the reverted status and maps it accordingly.
Closes #1234 and #1232.
> feat: partial reverted txn support for v0.3 rpc

- CHANGELOG.md
- crates/gateway-client/src/builder.rs
- crates/gateway-client/src/lib.rs
- crates/pathfinder/src/state/sync/class.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/state/sync/pending.rs
In case of a Sierra to CASM compilation failure pathfinder now falls back to fetching the compiled class definition from the feeder gateway.
We've seen countless issues with the Sierra to CASM compiler in the past few weeks and have now found an incompatibility of cairo 2.0.2 with a class defined on Starknet 0.11.2 (using compiler 1.1.0). ([This class](https://testnet.starkscan.co/class/0x034807a4ea6dcdd18ff5cf577c4d8c62c87f0d58f1592605d2d33f168f2a7296).)
To make pathfinder sync operation more robust in the future this PR adds a fallback: if compilation fails we now fall back to just fetching the compiled CASM definition from the feeder gateway.
> Fall back to fetching CASM from feeder gateway

- crates/gateway-types/src/reply.rs
- crates/pathfinder/src/p2p_network/client.rs
For some reason this was not on the ALL_BUILTINS list in cairo-lang but still shows up in transaction receipt execution resources.
> fix(gateway-types/receipt): add `segment_arena` builtin

- Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/sierra.rs
Since the 2.0.2 compiler turned out to be not fully-compatible this change adds the 1.1.1 compiler version explicitly for Starknet 0.11.2.
> fix(pathfinder/sierra): add Cairo 1.1.1 compiler for Starknet 0.11.2

- crates/storage/src/connection/transaction.rs
- crates/storage/src/schema.rs
- crates/storage/src/schema/revision_0037.rs
- py/src/pathfinder_worker/call.py
This PR stores a transaction's execution status as a separate column.
Starknet v0.12.1 introduces reverted transactions. We need to ignore reverted transactions for RPC v0.3 and therefore need this change to be able to filter them out.
The status is also still embedded in the compressed json that we store, and I elected not to change it during reads i.e. this column is currently only used to write into, and will only be used to filter on byt RPC methods.
> feat: store transaction execution status

- crates/rpc/src/cairo/ext_py.rs
- crates/rpc/src/cairo/ext_py/ser.rs
- crates/rpc/src/cairo/ext_py/types.rs
- crates/rpc/src/gas_price.rs
- crates/rpc/src/v02/types.rs
- crates/rpc/src/v03/method/estimate_message_fee.rs
- crates/rpc/src/v03/method/simulate_transaction.rs
- crates/serde/src/lib.rs
Using H256 makes comparing/using the gas price values harder with no added benefit.
This chaneg converts gas price to U256 -- with no changes on the Python interface (it still serializes/deserializes into a hex representation).
This PR has been extracted from the starknet_in_rust executor work.
> feat(rpc): make gas price an U256

- CHANGELOG.md
- Cargo.lock
- Dockerfile
- crates/load-test/Cargo.lock
- crates/pathfinder/Cargo.toml
- crates/stark_hash_python/Cargo.lock
This PR upgrades our Cairo compiler from 2.0.2 to 2.1.0-rc1 so that we're up-to-date with Starknet 0.12.1.
2.1.0-rc1 is supposed to be compatible with 2.0.2 so we're not adding it as an additional version. (Now that we have the feeder gateway fallback for CASM compilation the impact of a potential incompatibility is mitigated.)
Fixes: #1250
> feat(pathfinder): upgrade Cairo compiler to 2.1.0-rc1

- crates/rpc/src/v04.rs
- crates/rpc/src/v04/method.rs
- crates/rpc/src/v04/method/get_transaction_receipt.rs
- crates/rpc/src/v04/method/syncing.rs
This PR adds support for `starknet_syncing` and `starknet_getTransactionReceipt` for RPC v0.4.
`starknet_syncing` changed the block height representation from hex string to integer.
`starknet_getTransactionReceipt` requires allowing for reverted txns whereas in v0.3 those are explicity converted to errors. I tried to converge to a single overall type, but the result types also changed.
Closes #1271 and #1273
> feat(rpc/v0.4): syncing and receipt

- crates/gateway-types/src/error.rs
- crates/rpc/src/error.rs
- crates/rpc/src/v04.rs
- crates/rpc/src/v04/method.rs
- crates/rpc/src/v04/method/add_declare_transaction.rs
- crates/rpc/src/v04/method/add_deploy_account_transaction.rs
- crates/rpc/src/v04/method/add_invoke_transaction.rs
This PR adds a `v04` variant of `starknet_addDeclareTransaction`, `starknet_addDeployAccountTransaction` and `starknet_addInvokeTransaction`.
The 0.4 JSON-RPC specification for the write API is _almost_ the same as the 0.3 one but provides more detailed error codes on why the transaction failed. Starknet 0.12.0 is now doing more thorough validation on the gateway and now returns errors for:
* invalid signature
* invalid nonce
* insufficient balance
* insufficient max_fee
This PR adds the required `StarknetErrorCode` variants and the `RpcError` variants as well as the proper error mapping code in the JSON-RPC methods.
Fixes #1253
Fixes #1254
Fixes #1255
> feat(rpc/v04): add new error codes for `starknet_addXXXTransaction` methods

- CHANGELOG.md
- README.md
- crates/gateway-types/src/error.rs
- crates/rpc/src/error.rs
- crates/rpc/src/v02/method/call.rs
- crates/rpc/src/v02/method/get_transaction_by_hash.rs
- crates/rpc/src/v02/method/get_transaction_receipt.rs
- crates/rpc/src/v03/method/estimate_fee.rs
- crates/rpc/src/v03/method/simulate_transaction.rs
- crates/rpc/src/v04.rs
- crates/rpc/src/v04/method.rs
- crates/rpc/src/v04/method/add_declare_transaction.rs
- crates/rpc/src/v04/method/add_deploy_account_transaction.rs
- crates/rpc/src/v04/method/add_invoke_transaction.rs
- crates/rpc/src/v04/method/get_transaction_receipt.rs
- crates/rpc/src/v04/method/simulate_transactions.rs
Fixes #1283 
~~I'm unsure about [removing `InvalidMessageSelector`](https://github.com/eqlabs/pathfinder/pull/1289/commits/a2758fbe146bb3af51747a2ea8a8fe1e54951ce1) which was removed in v03 spec but is used in our version of v03 in call and estimate fee, which makes our impl deviate from the spec.
I don't know if any libs/services rely on that specific variant (but still this is a breaking change).~~
Edit: it's bug fix as we need to stick to the spec.
There's no such issue with the other removed variant as it was dead code.
> Chris/rpc v0.4 new error codes

- CHANGELOG.md
- Cargo.lock
- README.md
- crates/pathfinder/Cargo.toml
- crates/rpc/Cargo.toml
- crates/rpc/src/lib.rs
- crates/rpc/src/middleware/versioning.rs
Fixes #1218 
The rpc server now returns HTTP status 200 with an empty body on:
- `/` (root), only if the request body is empty,
- `/health`, regardless of the request body (which is not even read).
Http method is in those cases ignored just in case to maintain backward compatibility, as [chichi13](https://github.com/chichi13) you don't mention which http method is used by the bots.
An additional http method check has been added for valid RPC paths (including `/` with a non-empty request body) as I discovered we had a bug where one could for example send a GET request (with valid json) and receive a reply with an RPC error code instead of HTTP 405 (Method not allowed).
> ok on root

- CHANGELOG.md
- crates/rpc/src/v04/method/get_transaction_receipt.rs
Execution and finality status values were incorrect -- they were using camel case instead of the screaming snake case expected by the spec.
Closes #1297
> fix(rpc/v04/get_transaction_receipt): fix execution and finality status JSON representation

- .github/workflows/ci.yml
This action caches the installed tools instead of compiling `cargo-msrv` and `cargo-sort` again and again.
> chore(github): use cargo-install action

- Cargo.lock
- crates/ethereum/Cargo.toml
- crates/p2p/Cargo.toml
- crates/p2p_proto/Cargo.toml
- crates/pathfinder/Cargo.toml
- crates/storage/Cargo.toml
The list of deps to remove was generated using
`cargo +nightly udeps --all-targets --workspace --all-features`
> chore: remove unused deps from Cargo.toml files

- README.md
- crates/stark_poseidon/src/poseidon.rs
Fixes readme stating rpc v0.4 is served at `/` and a missing negation in the poseidon matrix doc comment.
Closes #1292
> docs: readme and comment fixes

- .github/CODEOWNERS
- .github/workflows/ci.yml
This PR replaces the failing MSRV action with a simple custom one and removes mikdk from codeowners to reduce the spam.
The MSRV check is replaced by a simple:
1. grep for msrv from manifest
2. install that rust version
3. cargo check
> ci: fix msrv check

- CHANGELOG.md
- crates/rpc/src/cairo/ext_py.rs
- crates/rpc/src/v02/method/add_declare_transaction.rs
- crates/rpc/src/v02/types.rs
- crates/rpc/src/v03/method/estimate_fee.rs
- crates/rpc/src/v04/method/add_declare_transaction.rs
This PR adds Declare v0 transaction support for "broadcasted" transactions -- which was the only thing missing for our support for the JSON-RPC 0.4.0 specification.
Closes #1305
> feat(rpc): add support for final JSON-RPC 0.4.0 specification

- CHANGELOG.md
- crates/storage/src/connection/state_update.rs
This PR fixes a bug in our storage query for a contract's class hash.
When querying by block hash, it would only work correctly when queried at exactly the deployed block.
Closes #1317
> fix: get contract class hash only works on the deployed block

- .github/workflows/ci.yml
It turns out `nextest` runs _all_ tests, including the ones we've been running separately.
> chore(github/ci): 'integration*' tests were already run by nextest

- CHANGELOG.md
- crates/rpc/src/cairo/ext_py.rs
- py/pyproject.toml
- py/requirements-dev.txt
- py/src/pathfinder_worker/call.py
- py/tests/pathfinder_worker/test_call.py
This involves following up some renames and updating expected fee estimation results.
> chore(py): upgrade `cairo-lang` to 0.12.2a0

- CHANGELOG.md
- crates/common/src/test_utils.rs
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/rpc/src/lib.rs
- crates/rpc/src/metrics.rs
- crates/rpc/src/middleware/cors.rs
- crates/rpc/src/middleware/versioning.rs
- crates/rpc/tests/versioning.rs
This PR adds the `rpc.root-version` command line argument (and the corresponding `PATHFINDER_RPC_ROOT_VERSION` environment variable) that can be used to select which version of the JSON-RPC API gets served on the root path.
The default is the `v0.3` API we've been using previously.
Fixes #1321
> feat(rpc): make version of the JSON-RPC API served on the root path configurable

- CHANGELOG.md
- crates/rpc/src/middleware/versioning.rs
Users could call an RPC method whose name was prefixed with correct version in the method name field, for example both work correctly:
```
{"jsonrpc":"2.0","id":"0","method":"starknet_chainId"}
{"jsonrpc":"2.0","id":"0","method":"v0.3_starknet_chainId"}
```
even though the latter (`v0.3_starknet_chainId`) is a non-existent method name.
> fix prefix leakage

- crates/rpc/src/middleware/versioning.rs
- crates/rpc/tests/versioning.rs
Additionally:
- fix race condition in integration test if using `cargo test` - global recorder set twice.
> fix: build errors after sloppy merge

- .github/workflows/ci.yml
- Cargo.lock
- crates/gateway-client/src/lib.rs
- crates/p2p/Cargo.toml
- crates/p2p/examples/generate_key.rs
- crates/p2p/examples/peer.rs
- crates/p2p/src/behaviour.rs
- crates/p2p/src/lib.rs
- crates/p2p/src/test_utils.rs
- crates/p2p/src/tests.rs
- crates/p2p_bootstrap/Cargo.toml
- crates/p2p_bootstrap/src/behaviour.rs
- crates/p2p_bootstrap/src/main.rs
- crates/p2p_proto/src/sync.rs
- crates/pathfinder/Cargo.toml
- crates/pathfinder/src/bin/pathfinder/config.rs
- crates/pathfinder/src/bin/pathfinder/main.rs
- crates/pathfinder/src/p2p_network.rs
- crates/pathfinder/src/p2p_network/client.rs
- crates/pathfinder/src/p2p_network/sync_handlers.rs
- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/storage/src/connection/event.rs
- crates/storage/src/fake.rs
This PR glues existing p2p implementation to the sync logic.
How:
- implementing GatewayApi for a new **temporary** entity that combines the feeder gateway client and a new "sync p2p client"
- I had to do a minor `GatewayApi` change to ease integration (introduced `head()` used in place of `block(Latest)`)
- I also added a temporary `GossipApi` to allow the client to propagate hew head (ie. when the node is of "proxy" type)
Caveats:
- there are 3 types of nodes:
- bootstrap (from example)
- gateway proxy
- syncs from feeder gateway,
- propagates **global** feeder gateway l2 head via gossipsub,
- responds to sync requests from other nodes
- pure p2p
- syncs from other nodes (proxy and pure p2p),
- responds to sync requests from other nodes
- now the "sync stack" …
> PoC p2p sync behind GatewayApi

- crates/pathfinder/src/p2p_network/sync_handlers.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/rpc/src/pathfinder/methods/get_transaction_status.rs
- crates/storage/src/connection/state_update.rs
- crates/storage/src/connection/transaction.rs
Fix new warnings that were introduced by upgrading to Rust 1.72.
> chore: fix Rust 1.72 clippy warnings and formatting

- CHANGELOG.md
- crates/pathfinder/src/bin/pathfinder/config.rs
That is, this PR changes the API version we serve on root to 0.4.
> feat(rpc): make JSON-RPC v0.4 the default

- Dockerfile
So that it matches what pathfinder is using internally.
> fix(Dockerfile): bump version of the Cairo compiler for Python

- crates/load-test/Cargo.lock
- crates/stark_hash_python/Cargo.lock
Otherwise it won't compile with `cargo --locked` which our Dockerfile relies on.
> fix(crates/{load-test, stark_hash_python}): follow up bitvec update

- Cargo.lock
- Cargo.toml
- crates/common/Cargo.toml
- crates/ethereum/Cargo.toml
- crates/executor/Cargo.toml
- crates/gateway-client/Cargo.toml
- crates/gateway-types/Cargo.toml
- crates/load-test/Cargo.toml
- crates/merkle-tree/Cargo.toml
- crates/p2p/Cargo.toml
- crates/p2p_bootstrap/Cargo.toml
- crates/p2p_proto/Cargo.toml
- crates/p2p_proto_derive/Cargo.toml
- crates/pathfinder/Cargo.toml
- crates/rpc/Cargo.toml
- crates/serde/Cargo.toml
- crates/stark_curve/Cargo.toml
- crates/stark_hash/Cargo.toml
- crates/stark_poseidon/Cargo.toml
- crates/storage/Cargo.toml
Mostly compatible versions, except for `serde_with` -- where the new version seems to work just fine. According to release notes of serde_with 3.0.0:
"This breaking release should not impact most users. It only affects custom character sets used for base64 of which there are no instances of on GitHub."
> chore: upgrade dependencies

- README.md
The links and website are dead.
Closes #1354.
> docs: remove newton from readme

- Dockerfile
Upgrade the `cargo-chef` image to the latest one having Rust 1.72.
> chore(Dockerfile): upgrade Rust to 1.72

- crates/pathfinder/src/state/sync.rs
- crates/pathfinder/src/state/sync/l2.rs
- crates/pathfinder/src/state/sync/pending.rs
After 0.12.2 has been rolled out to all networks we can now remove the old function fetching the pending block and state update from separate endpoints.
> feat(pathfinder/sync/l2): remove pre-0.12.2 poll_pending

- crates/rpc/src/executor.rs
Previously these were converted to starknet_api's `DeclareTransaction::V0` which is incorrect.
Internally blockifier executes these just the same, so there are no real implications of this fix.
> fix(rpc/executor): fix Declare v1 transaction conversion

- CHANGELOG.md
- crates/rpc/src/v02/types/class.rs
starknet_api::deprecated_contract_class::Program requires `debug_info` to be present in the program. That should actually be optional and now this causes a regression where declare transactions with Cairo v0 classes with no `debug_info` present are rejected by pathfinder.
This change adds a workaround for that issue: adds an empty debug info to the program if it's not present in the input before parsing the class with starknet_api.
Closes #1371
> fix(rpc/class): work around starknet_api Cairo 0 class parsing issue

- crates/pathfinder/src/state/sync/pending.rs
poll_pending() already had an optimization: in case it was receiving a full block instead of pending it returned the data it had to the l2 sync code which could then process the block data without re-fetching it from the feeder gateway.
Unfortunately the code was _not_ returning the state update even though we're now fetching the block data _and_ the state update for the pending block with a single call.
> fix(sync): return state update as well when receiving a full block in poll_pending()
