Cargo.toml
rpc_examples.sh
src/bin/pathfinder.rs
src/rpc.rs

Upgrade jsonrpsee to 0.6.1. Fix rpc examples.

refactor(rpc): upgrade jsonrpsee to 0.6.1

---

crates/pathfinder/Cargo.toml
crates/pathfinder/rpc_examples.sh
crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/types.rs
crates/pathfinder/src/sequencer.rs
crates/pathfinder/src/sequencer/reply.rs
crates/pedersen/Cargo.toml

* Implement RPC API changes [introduced in 0.4.0](https://github.com/starkware-libs/starknet-specs/blob/3b554cf056c71a4fc63e8eb8627a55535340d39d/api/starknet_api_openrpc.json), except for `starknet_getEvents`
* Implement support for the [`pending` tag](https://community.starknet.io/t/cairo-v0-6-2-api-change-pending-block/195)

Rpc api upgrade 0.4.0

---

crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/types.rs
crates/pathfinder/src/sequencer/error.rs

As Lior pointed out these error codes should not be -32000 based as they are not json-rpc server specific.

fix: starknet rpc error codes

---

crates/pathfinder/src/config/builder.rs
crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/types.rs
crates/pathfinder/src/sequencer/error.rs

Fix error code duplication as per [spec update to 0.4.1](https://github.com/starkware-libs/starknet-specs/commit/64044c2c8be136b6fdf7f13896ea0422bf211a74).

Rpc spec update to 0.4.1

---

.github/workflows/ci.yml

Instead use dtolnay toolchain action.

ci: replace action-rs

---

crates/pathfinder/src/state/merkle_node.rs
crates/pathfinder/src/state/merkle_tree.rs

This fixes a bug in the Merkle-Tree implementation where consecutive edges were not being merge __IF__ the child was an unresolved node (but would resolve to an edge node and should therefore be merged).
The fix involves moving the edge merging code up one level, in order to access the storage to resolve the node.
Also added a test case exercising this bug, which was RED before the fix and GREEN after.

Fix Merkle-Tree not checking unresolved nodes while merging edges

---

crates/pathfinder/Cargo.toml
crates/pathfinder/src/sequencer.rs

Add basic support for `get_full_contract` sequencer query.

feat: get_full_contract

---

crates/pathfinder/src/sequencer.rs
crates/pathfinder/src/state.rs

This is a work-around for an issue with the sequencer where it is randomly unresponsive to early block queries. Essentially adds a small timeout (instead of the 2minute default) for `sequencer.block(...)` calls and loops on timeout.
This is the only query which is such a major issue currently. However, we should figure out a more general solution to this problem but this will likely require a bigger internal change. For now this should be okay (? thoughts ?).
Note that the state genesis test now works due to this work-around.

feat: add timeout to sequencer block calls

---

crates/pathfinder/Cargo.toml
crates/pathfinder/examples/compute_contract_hash.rs
crates/pathfinder/src/state.rs
crates/pathfinder/src/state/contract_hash.rs
py/src/compute_contract_hash.py

First version, this one has now an automated test using the integration testing env, which we may or may want to keep.

Compute contract hash

---

crates/pathfinder/src/state.rs

This fixes a bug in the sync process. Newly deployed contracts should be added to the global state tree with a contract root of ZERO. This was not happening.
This went unnoticed thus far because of a Starkware bug where contracts without any storage changes during deployment, would still write ZERO to a storage field. This meant that even though we weren't init these contracts to ZERO for deployment, the same update would contain storage updates forcing the contract root to ZERO anyway. Once this bug was fixed, our bug became an issue.
This PR does __not__ contain any regression tests because the current format of the `sync` and `update` functions don't easily allow for it. Since we are also re-working this code currently, I've opted to do this later instead -- opened issue #91 to remind …

fix(sync): new contracts missing from global state

---

crates/pathfinder/Cargo.toml
crates/pathfinder/src/rpc/serde.rs

drop the `bigdecimal` dependency

refactor: drop bigdecimal dependency

---

crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/types.rs

* add code `27` for invalid txn index
* sync status `highest_block` is now a block hash

feat: align with rpc spec 0.4.2

---

crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/storage.rs

Less mixing of sync and async contexts. The different commits are more readable than the total.

Rpc async sync split

---

crates/pathfinder/src/cairo/ext_py.rs
crates/pathfinder/src/cairo/ext_py/service.rs
crates/pathfinder/src/cairo/ext_py/sub_process.rs

this could had been done all along with the return value of the future, but since we needed the subprocessevent to let us know of a successful start, I got them mixed up. one less variant to handle now.

refactor: remove unnecessary subprocessevent

---

crates/pathfinder/examples/call_against_sequencer.rs
crates/pathfinder/src/cairo/ext_py/sub_process.rs
crates/pathfinder/src/rpc/api.rs
py/README.md
py/src/call.py

Most came from our walkthrough call earlier today.
Currently the example doesn't yet get the same result as it used to get, I think.

ext_py drivebys

---

crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/types.rs
crates/pathfinder/src/state.rs
crates/pathfinder/src/state/sync.rs

This currently just tracks our L2 progress.
Closes #134

feat: add sync status support

---

README.md
crates/pathfinder/src/bin/pathfinder.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l2.rs

Add tracing to sync process

---

crates/pathfinder/src/state/sync.rs

This PR de-duplicates the tracing logs emitted for an L2 update.
Currently, two events are emitted
1. `info!` level, and
2. `debug!` level with timing information.
This PR emits only one of these events based on the current log level.

feat(sync): deduplicated debug trace for L2 update

---

crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/types.rs
crates/pathfinder/src/storage/state.rs

This is a draft PR for some tests for the `rpc` module.
Some tests are not fixed yet.

Rpc storage tests

---

crates/pathfinder/src/storage/schema/revision_0005.rs

As per [sqlite documentation](https://www.sqlite.org/c3ref/changes.html) `changes()` will only report proper row counts only in case of `INSERT`, `UPDATE` or `DELETE`. We expected similar behavior for `ALTER TABLE` which unfortunately resulted in an error being returned during migration.

fix: remove altered rows check

---

crates/pathfinder/src/rpc.rs
crates/pathfinder/src/sequencer.rs

Small test cleanup in `rpc` and `sequencer`.

Remove retry from tests

---

crates/pathfinder/src/rpc.rs
crates/pathfinder/src/state.rs

I removed those `#[ignore]`s and a manual test and added the missing test cases.

Get storage at tests

---

README.md

This PR fixes the Docker command in the readme

fix: bash script typos etc

---

crates/pathfinder/src/sequencer.rs

Looking at those retry tests I realized that timeouts weren't tested at all so I added two more test cases and reworked the server factories btw.

test: more sequencer retry tests

---

crates/pathfinder/src/state/contract_hash.rs

This PR fixes the contract hash calculation for cairo 0.8 update which introduced new fields in the contract definition and broke our calculation for older blocks.

Fix contract hash for 0.8 cairo update

---

Cargo.lock
crates/pathfinder/Cargo.toml
crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/types.rs
crates/pathfinder/src/sequencer/reply.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/storage.rs
crates/pathfinder/src/storage/schema.rs
crates/pathfinder/src/storage/schema/revision_0007.rs
crates/pathfinder/src/storage/state.rs
py/src/call.py
py/src/test_call.py

This is a draft PR to facilitate easy review of the storage layer for events.

Add events storage and RPC interface

---

crates/pathfinder/examples/call_against_sequencer.rs
crates/pathfinder/src/core.rs
crates/pathfinder/src/ethereum/state_update.rs
crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/types.rs
crates/pathfinder/src/sequencer.rs
crates/pathfinder/src/sequencer/reply.rs
crates/pathfinder/src/sequencer/request.rs
crates/pathfinder/src/state.rs
crates/pathfinder/src/state/contract_hash.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l2.rs

~~Still a work in progress.~~
I noticed that the l2 sync task did not properly recognize a reorg at genesis which is the head at the same time - hence a minor fix for that.

L2 sync tests

---

crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs

It now fetches the information from storage instead.

fix: transaction_by_hash delegates to sequencer

---

Cargo.lock
crates/pathfinder/Cargo.toml
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l2.rs

This PR is done as a patch against the latest release (v0.1.6-alpha) instead of main as we want to release this patch asap.

Reduce sequencer spam when at head of chain

---

Cargo.lock
crates/pathfinder/Cargo.toml
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l2.rs

There were a few conflicts (caused by the L2 sync tests Chris has added).

Merge 0.1.7-alpha release branch

---

crates/pathfinder/src/state/sync.rs

Instead of silently ignoring the error and retrying immediately we now
log it and then proceed to wait a bit before retrying.

fix(sync_status): do not busy-loop on deserialization failures

---

crates/pathfinder/src/sequencer.rs

This allows the sequencer to ID our node and version.
Closes #244.

feat(sequencer): user agent to pathfinder/version

---

crates/pathfinder/src/update.rs

etag was being cast from `HeaderValue` to `String` for no reason.
This also meant it would default to empty string if missing.

fix(github): unnecessary etag value casting

---

crates/pathfinder/src/storage.rs
crates/pathfinder/src/storage/schema.rs
crates/pathfinder/src/storage/schema/revision_0008.rs
py/src/call.py
py/src/test_call.py

According to load tests this speeds up starknet_getBlock* operations significantly.

fix(storage): add missing index on block hash for transactions

---

crates/pathfinder/src/state/sync/l2.rs

chore: clippy

---

Cargo.lock
crates/pathfinder/Cargo.toml

chore: release prep

---

.github/workflows/docker.yml

This PR adds the `with:` that I forgot to add in the last one. 😑

fix: add with

---

crates/pathfinder/src/config.rs
crates/pathfinder/src/config/builder.rs
crates/pathfinder/src/config/cli.rs
crates/pathfinder/src/config/file.rs

deprecated and warned in #275.

chore: remove deprecated eth user agent option

---

crates/pathfinder/resources/contracts/core_impl.json
crates/pathfinder/src/ethereum/contract.rs

Only minor ABI changes, none of which impact us thankfully.

feat(eth): update core goerli contract for 0.9

---

Cargo.lock
crates/pathfinder/Cargo.toml

rationale:
- #335
- #330
- #323

chore: bump to 0.2.0

---

.github/workflows/docker.yml

After learning about https://github.com/easimon/maximize-build-space/blob/master/action.yml#L97-L105 but not using it because we are already using the other swap file adjusting one.

ci: try to free up space

---

.github/workflows/docker.yml

14GB was too much, unsure why, or maybe fallocate lengthens the file?

ci: revert swap back to 10GB

---

Cargo.lock
crates/pathfinder/Cargo.toml

by removing jsonrpsee features.

chore: lighten jsonrpsee features

---

crates/pathfinder/examples/migrate_db.rs
crates/pathfinder/src/storage/schema/revision_0011.rs

This gets the per-row values to microseconds which makes this migration feasible.

fix: make migration_0011.rs faster

---

crates/pathfinder/src/rpc/serde.rs
crates/stark_hash/src/hash.rs

fix: misleading hex parsing error message

---

crates/pathfinder/src/sequencer/builder.rs

fix: remove stray `dbg!`

---

crates/pathfinder/src/cairo/ext_py.rs
crates/pathfinder/src/cairo/ext_py/de.rs
crates/pathfinder/src/rpc/api.rs
py/src/call.py
py/src/test_call.py

just a random new feature while doing the fixes.

feat(call): recognize invalid entry point

---

Cargo.lock

chore: forgot to run cargo check after bumping

---

crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l2.rs

fix: download classes in declare transactions

---

README.md
crates/pathfinder/src/ethereum/transport.rs

This option has already been removed.
Fixes #398.

fix: remove mention of user-agent configuration option

---

crates/pathfinder/examples/estimate_past_transactions.rs
py/src/test_call.py

Drive-by changes, forgotten constant changing.

chore: Smaller test updates

---

py/src/call.py

this is for patricia nodes, I haven't been able to detect any change in numbers which come visible with #416.

fix(py): single query instead of two

---

crates/pathfinder/src/rpc.rs

Another common support question. This includes some removing of `use`'s for the name Error, which was quite confusing for me.

feat: hints on addr already in use

---

crates/pathfinder/src/state/sync.rs

this required changing the bound on L1Sync from `FnOnce(...) -> _ + Copy` which is a bit strange choice allowing only fn items or closures which coerce to function pointers. `FnMut` without `Copy` is more natural esp if it's meant to be tested with closures.
also, less relaxed atomics.
Found in run of #421.

refactor(sync): rewrite flaky test with channels

---

crates/pathfinder/Cargo.toml
crates/pathfinder/src/state/sync.rs
crates/stark_hash/build.rs

Nothing special, and we get to see if codeowners based review correctly asks michael to review :)

chore: 1.62 clippies

---

crates/pathfinder/src/storage/schema/revision_0007.rs
crates/pathfinder/src/storage/schema/revision_0010.rs
crates/pathfinder/src/storage/state.rs

Includes a regression test -- fails before fix, passes after.
Closes #428.

fix: events ordering

---

Cargo.lock
crates/pathfinder/Cargo.toml

chore: prep for 0.2.5 release

---

.github/workflows/ci.yml

--frozen requires also the cache to be up to date.

ci: require up to date Cargo.lock with locked

---

crates/pathfinder/rpc_examples.sh
crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs

This matches version 0.29.0 of the specification.

feat(rpc): update starknet_getStorageAt to take a block_id

---

crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs

The new `block_id` parameter is now required.
The methods return the class hash or definition only for contracts that were already deployed at the block specified by `block_id`. This PR adds logic that checks if a contract at the given address exists in the global state tree of the block.

feat(rpc): add `block_id` parameter to `starknet_getClass{,Hash}At`

---

crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs

This new method (which takes a `block_id` parameter) replaces `starknet_getBlockTransactionCountByHash` and `starknet_getBlockTransactionCountByNumber`.

feat(rpc): implement `starknet_getBlockTransactionCount`

---

README.md
crates/pathfinder/rpc_examples.sh

This was missing from the PR adding the `starknet_getTransactionCount` method.

fix(rpc): update `starknet_getTransactionCount` readme and examples

---

crates/load-test/src/main.rs
crates/pathfinder/src/bin/pathfinder.rs
crates/pathfinder/src/core.rs
crates/pathfinder/src/ethereum/log/fetch/forward.rs
crates/pathfinder/src/ethereum/state_update/state_root.rs
crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/types.rs
crates/pathfinder/src/sequencer.rs
crates/pathfinder/src/sequencer/reply.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l1.rs
crates/pathfinder/src/storage/contract.rs
crates/pathfinder/src/storage/state.rs

This is quite a large PR but I have tried my best to make the commits sensible. I would recommend reviewing by commit at least until the last few which are the events related changes.
This PR does not include `starknet_call` and `starknet_feeEstimate` as those are still brewing in #462.
The most complex code is the `get_events` related code, which could use some sharp eyeballs.

feat: support local pending in RPC

---

crates/pathfinder/examples/download_state_updates.rs
crates/pathfinder/rpc_examples.sh
crates/pathfinder/src/bin/pathfinder.rs
crates/pathfinder/src/cairo/ext_py/ser.rs
crates/pathfinder/src/core.rs
crates/pathfinder/src/ethereum/state_update.rs
crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/api.rs
crates/pathfinder/src/rpc/test_setup.rs
crates/pathfinder/src/rpc/types.rs
crates/pathfinder/src/sequencer.rs
crates/pathfinder/src/sequencer/reply.rs
crates/pathfinder/src/state.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l2.rs
crates/pathfinder/src/storage.rs
crates/pathfinder/src/storage/fixtures.rs
crates/pathfinder/src/storage/schema.rs
crates/pathfinder/src/storage/schema/revision_0016.rs
crates/pathfinder/src/storage/state.rs
py/src/call.py

This is a pretty big PR, so I tried to separate it into commits that carry specific steps towards the ultimate functionality.

Add support for starknet_getStateUpdate

---

crates/pathfinder/examples/download_state_updates.rs

changes the tool to work from 0..x to just query what is missing, then
do them one by one, committing each as they are ready. these are now
done in a seemingly random order, one can guess how much work is still
left undone.

fix: fill in missing state updates

---

crates/pathfinder/src/storage/schema/revision_0015.rs

It seems that there was a period where transaction JSONs from the feeder
gateway didn't have `max_fee`. This is now causing migration failures
when users are trying to upgrade to revision 15 of the schema.
This change adds makes `max_fee` optional in the migration-specific
`InvokeTransaction` type so that de-serialization works if it's missing
but fixes up the missing `max_fee` with 0 before serializing the
transaction so that it's compatible with our prod `enum Transaction`.

fix(storage/schema): fix transaction migration for missing max_fee

---

README.md
crates/pathfinder/Cargo.toml

Bump minimum Rust version

---

crates/pathfinder/src/storage/state.rs

This is based off on `sql_niceties`, I just split the PR and reordered these commits to the end. It might have dependencies unsure.

refactor: events queries

---

crates/pathfinder/src/state/block_hash.rs
crates/pathfinder/src/state/merkle_node.rs
crates/pathfinder/src/state/merkle_tree.rs
crates/pathfinder/src/storage.rs
crates/pathfinder/src/storage/merkle_tree.rs
crates/pathfinder/src/storage/schema.rs
crates/pathfinder/src/storage/schema/revision_0017.rs
py/src/call.py

Depends on #515, which was ripped out of this. Also ripped the format! and `prepare_cached` related changes over to #516.

refactor: No more leafs

---

crates/pathfinder/src/state/merkle_tree.rs

testing the colliding tree triggered the assertion on a binarynode.

fix: stricter assert

---

README.md

docs(readme): document monitoring endpoint

---

crates/pathfinder/src/state.rs
crates/pathfinder/src/state/merkle_tree.rs
crates/pathfinder/src/state/state_tree.rs

feat(dfs): user-controllable visit

---

README.md

If you could test the new link that would be great.

docs(readme): update discord link

---

crates/pathfinder/src/state/merkle_tree.rs
crates/pathfinder/src/state/state_tree.rs

Done in the past in closed #485 I re-did it because I didn't see I might need it in #521.

refactor(dfs): expose path, resolve error

---

py/src/test_call.py

instead of compiling and having to port the partial test.cairo to new
versions of cairo-lang, as was done for 0.9.

refactor(py): use contract def fixture

---

crates/pathfinder/src/state/class_hash.rs

This is a new property that was added in Starknet 0.10.0 and contains
the version of the compiler that has been used to compile the program.
We add it as an optional field so that old class definitions can still
be parsed.

fix(class_hash): add `compiler_version` property to Program

---

crates/pathfinder/src/state/class_hash.rs

Required an additional backwards compatibility hack.
Essentially, 
```
"cairo_type": "(A: B, C: D)"
```
must have an additional space before each tuple's colon:
```
"cairo_type": "(A : B, C : D)"
```
iff it is a modern compiler i.e. if `compiler_version` is present.
Note that it is only for inside tuples - `cairo_type` may also contain an empty tuple `"()"` or just a plain string value `"abcde"` which doesn't get this treatment.

fix: class hash calculation for 0.10

---

crates/pathfinder/resources/contracts/core_impl.json
crates/pathfinder/src/ethereum/contract.rs

Also updates the abi which is still compatible with mainnet.

feat: update testnet core contract impl

---

crates/pathfinder/src/state/sync/l2.rs

This PR promotes the block hash mismatch to a hard error. This will prevent block hash mismatches from entering the database.

fix(sync): block hash mismatch only warns

---

crates/pathfinder/src/cairo/ext_py/sub_process.rs
py/src/call.py

enabled with debug_assertions, you get a WARN about dev mode being enabled, and full tracebacks.

feat(ext_py): dev profile with tracebacks

---

py/src/call.py

call is ... from times when only call was used.

chore(py): rename .call to more self-explanatory

---

crates/pathfinder/src/rpc/error.rs

Simply rename by adding a verb to make it more descriptive:
```
rpc_error_subset! -> generate_rpc_error_subset!
```

chore: improve name for rpc error macro

---

crates/pathfinder/fixtures/rpc/0.44.0/receipt.json
crates/pathfinder/src/rpc/v02/method.rs
crates/pathfinder/src/rpc/v02/method/get_transaction_receipt.rs
crates/pathfinder/src/rpc/v02/types.rs

feat(rpc/v02): add `starknet_getTransactionReceipt` method

---

crates/pathfinder/src/rpc/v01/api.rs
crates/pathfinder/src/rpc/v02.rs
crates/pathfinder/src/rpc/v02/method.rs
crates/pathfinder/src/rpc/v02/method/get_class_hash_at.rs

Relevant specification [link](https://github.com/starkware-libs/starknet-specs/blob/v0.2.0/api/starknet_api_openrpc.json#L277-L313).
Closes #596.

feat(rpc/v0.2): implement `starknet_getClassHashAt`

---

crates/pathfinder/src/rpc/v01/api.rs
crates/pathfinder/src/rpc/v02/method/get_class_hash_at.rs
crates/pathfinder/src/rpc/v02/method/get_nonce.rs
crates/pathfinder/src/state.rs
crates/pathfinder/src/state/merkle_tree.rs
crates/pathfinder/src/state/state_tree.rs
crates/stark_hash/src/chain.rs
crates/stark_hash/src/hash.rs

Closes https://github.com/eqlabs/pathfinder/issues/639

refactor: tree lookup returns Option

---

crates/pathfinder/src/rpc/v02.rs
crates/pathfinder/src/rpc/v02/method.rs
crates/pathfinder/src/rpc/v02/method/get_block_transaction_count.rs

Closes https://github.com/eqlabs/pathfinder/issues/598

feat(rpc/v02): add `starknet_getBlockTransactionCount` method

---

crates/pathfinder/src/core.rs
crates/pathfinder/src/rpc/v02.rs
crates/pathfinder/src/rpc/v02/method.rs
crates/pathfinder/src/rpc/v02/method/pending_transactions.rs

feat(rpc/v0.2): starknet_pendingTransactions

---

crates/pathfinder/src/rpc/v02.rs
crates/pathfinder/src/rpc/v02/method.rs
crates/pathfinder/src/rpc/v02/method/add_invoke_transaction.rs
crates/pathfinder/src/rpc/v02/method/estimate_fee.rs
crates/pathfinder/src/rpc/v02/method/get_state_update.rs
crates/pathfinder/src/rpc/v02/types.rs
crates/pathfinder/src/sequencer/error.rs

I have some concerns as there are no proper tests we can do for this? v0.1 implementation also has no tests for it afaict.
Closes #608

feat(rpc/v0.2): starknet_addInvokeTransaction

---

crates/pathfinder/src/rpc/v01.rs

I added the 2 very same test cases to v0.1 that are in v0.2:
- pending block is empty, which should fall back to the latest block,
- pending support is disabled which should result in an error.

test: add pending empty and disabled tests

---

crates/pathfinder/src/rpc/error.rs
crates/pathfinder/src/rpc/v02.rs
crates/pathfinder/src/rpc/v02/method.rs
crates/pathfinder/src/rpc/v02/method/add_declare_transaction.rs
crates/pathfinder/src/sequencer/error.rs

feat(rpc/v02): add `starknet_addDeclareTransaction`

---

crates/pathfinder/src/rpc/v02.rs
crates/pathfinder/src/rpc/v02/method.rs
crates/pathfinder/src/rpc/v02/method/add_deploy_transaction.rs

feat(rpc/v02): add `starknet_addDeployTransaction`

---

crates/pathfinder/src/rpc/v02/method/add_invoke_transaction.rs

Previously parsing failed for input confirming to the specification because the `type` property wasn't taken care of.
Closes #673.

fix(rpc/v02): fix input parsing for `starknet_addInvokeTransaction`

---

crates/pathfinder/src/rpc/v02/method/add_declare_transaction.rs

This is still required on Starknet mainnet according to Starkware.
Closes #678.

fix(rpc/v02): add optional token parameter to `starknet_addDeclareTransaction`

---

crates/pathfinder/src/rpc/v01.rs
crates/pathfinder/src/rpc/v01/api.rs
crates/pathfinder/src/rpc/v02.rs
crates/pathfinder/src/rpc/v02/method.rs
crates/pathfinder/src/rpc/v02/method/get_events.rs
crates/pathfinder/src/storage.rs
crates/pathfinder/src/storage/state.rs

rpc v0.2.1 get_events

---

crates/pathfinder/src/sequencer/builder.rs
crates/pathfinder/src/sequencer/error.rs
crates/pathfinder/src/sequencer/metrics.rs

invalid error variant

---

crates/load-test/src/types.rs
crates/pathfinder/src/rpc/v01/api.rs
crates/pathfinder/src/rpc/v01/types.rs
crates/pathfinder/src/rpc/v02/method/get_transaction_receipt.rs
crates/pathfinder/src/storage/state.rs

Closes #445 .
RPS gain is around 20%.

get transaction receipt perf

---

README.md
crates/pathfinder/src/bin/pathfinder.rs
crates/pathfinder/src/cairo/ext_py/ser.rs
crates/pathfinder/src/config.rs
crates/pathfinder/src/config/builder.rs
crates/pathfinder/src/config/cli.rs
crates/pathfinder/src/consts.rs
crates/pathfinder/src/core.rs
crates/pathfinder/src/ethereum/contract.rs
crates/pathfinder/src/ethereum/state_update/state_root.rs
crates/pathfinder/src/ethereum/transport.rs
crates/pathfinder/src/sequencer.rs
crates/pathfinder/src/state/block_hash.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/storage/state.rs

feat(pathfinder): add command line flag for supporting testnet 2

---

crates/pathfinder/src/rpc.rs
crates/pathfinder/src/rpc/test_client.rs
crates/pathfinder/src/rpc/test_setup.rs
crates/pathfinder/src/rpc/v01.rs
crates/pathfinder/src/rpc/v02.rs

This is of course a breaking change.
-- edit --
I fixed the tests in a pretty hacky way; but I think that's okay given that this code will all get deleted soon.

feat!(rpc): serve v0.2 at root instead of v0.1

---

crates/pathfinder/src/bin/pathfinder/config/cli.rs

fix: cli gateway url env args

---

Cargo.lock
crates/pathfinder/Cargo.toml
crates/pathfinder/src/bin/pathfinder/config/cli.rs

And bump the crate version to v0.4.2.

fix: cfg tests

---

crates/pathfinder/src/bin/pathfinder/main.rs

This fixes a bug where `--network custom` used in a proxy setup would not sync due to the block hash calculation not accounting for the work-arounds. Work-arounds don't exist for custom networks, so the fix detects the proxy setup and treats it as the original network.

fix: proxy networks can't sync

---

py/src/pathfinder_worker/call.py

According to Starkware a large amount of time is spent on de-serializing classes from their JSON representation. To make things faster they've added a cache for the parsed class instances.
This PR adds a shared LRU cache that caches the parsed classes between commands -- we hope to have better performance this way. This should be especially noticeable for quick calls.

feat(python): add LRU cache for parsed contract classes

---

crates/rpc/src/v01.rs
crates/rpc/src/v01/api.rs
crates/rpc/src/v02/method/get_events.rs

`latest` is a no-op when used as the upper end of the block range, but it's a _real_ lower limit when used as the lower end (`from_block`).

fix(rpc/v02/get_events): correctly map `latest` from_block to block number

---

crates/pathfinder/rpc_pathfinder_examples.sh
pathfinder_rpc_api.json

This PR fixes the get proof node RPC specification to match the reality. In addition also fixes the quotes in the example curl.

docs: fix get proof example json

---

crates/pathfinder/src/bin/pathfinder/config/cli.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l1.rs
crates/rpc/src/error.rs
crates/rpc/src/pathfinder/methods/get_proof.rs

These came in with Rust 1.66.0.

chore: new clippies and doc fixes

---

README.md

added common asked questions to readme

Update README.md with FAQ section

---

.github/workflows/ci.yml
crates/load-test/readme.md
crates/load-test/src/requests/v01.rs
crates/load-test/src/requests/v02.rs
crates/load-test/src/tasks/v01.rs
crates/load-test/src/tasks/v02.rs
crates/load-test/src/types.rs

Closes #813.
I did not add the CI step for running the load test itself.

fix: load test

---

crates/gateway-client/src/builder.rs
crates/gateway-client/src/lib.rs
crates/merkle-tree/src/state_tree.rs
crates/pathfinder/src/state/sync.rs

refactor: remove the gateway `class_hash_at` method

---

CHANGELOG.md

I forgot adding this entry when closing issue #847.

fix(changelog): add changelog entry for more detailed Python errors

---

crates/pathfinder/src/p2p_network/sync_handlers.rs
crates/storage/src/state.rs
crates/storage/src/test_utils.rs

Final logical completion of https://github.com/eqlabs/pathfinder/issues/765
To run tests locally: `cargo test --all-features --tests p2p_network::sync_handlers::tests`

chore: add tx/ev commitments propagation via p2p

---

README.md
doc/install-from-source.md

chore(docs): fix typos

---

crates/common/src/macros.rs
crates/gateway-client/src/builder.rs
crates/gateway-client/src/lib.rs
crates/pathfinder/src/state/sync.rs

feat: get_compiled_class_by_class_hash

---

crates/gateway-client/src/lib.rs
crates/gateway-types/src/pending.rs
crates/gateway-types/src/reply.rs
crates/pathfinder/examples/download_state_updates.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l2.rs
crates/pathfinder/src/state/sync/pending.rs
crates/rpc/src/cairo/ext_py.rs
crates/rpc/src/cairo/ext_py/ser.rs
crates/rpc/src/lib.rs
crates/rpc/src/v02/method/estimate_fee.rs
crates/rpc/src/v02/method/get_nonce.rs
crates/rpc/src/v02/method/get_state_update.rs
crates/rpc/src/v03/method/get_state_update.rs
crates/storage/src/test_fixtures.rs
crates/storage/src/types.rs

feat(state_update): make new root optional

---

crates/rpc/src/v02/method.rs
crates/rpc/src/v03.rs

Fixes: #874 
:eyes: I don't see any difference between add_invoke in v02 & v03.

feat(rpc/v03): register add_invoke_transaction

---

py/tests/pathfinder_worker/test_call.py

Contract state hash values and Merkle tree edge nodes are now constructed instead of hard-coded.
This makes it _much_ easier to change things in the state setup code and add new test cases.

fix(py/test_call): calculate constants used in test setup

---

CHANGELOG.md

```
- file configuration
- `--config` ...
```
are describing the same change, so removed one.

chore: duplicate changelog entry

---

crates/pathfinder/src/state/sync.rs

Temporary hack to ignore broken classes on integration by replacing the `casm` definition with empty bytes instead.

feat: ignore sierra compile errors on integration

---

py/src/pathfinder_worker/call.py

This PR constructs the cairo-lang configuration using more constants pre-defined by the cairo-lang package itself. This means we will no longer have to manually update things such as weights.
This is based on the same approach done by [devnet](https://github.com/Shard-Labs/starknet-devnet/blob/804e391f61e7465ed85d9e7a6f2c1b6d16ca1742/starknet_devnet/general_config.py#L20). Even though the constructor is more verbose, it does use only constants.
One notable exception is the transaction version which we still have to define manually it seems.
I also created a local-only test which ensures that our previous constructor and this new one matched exactly. I didn't include it as a permanent test as it doesn't really make much sense to keep imo.

feat: use cairo-lang config generator

---

CHANGELOG.md

In anticipation of next pathfinder version release.

chore: update changelog for v0.5.0

---

crates/pathfinder/src/bin/pathfinder/main.rs

This PR attempts to simplify our main function by splitting out functions and establishing some order using structs and function names.
I'm not entirely happy with everything (some names could be better), but I think its a big improvement.
Easiest to review by commit I think.

refactor: simplify pathfinder main

---

crates/rpc/src/versioning.rs

Fixes https://github.com/eqlabs/pathfinder/issues/992

fix: handle invalid json-rpc request

---

crates/rpc/src/versioning.rs

It turns out that the examples that I listed in a comment to #993 are not entirely correct when looking at the jsonrpc spec:
```
v0.4.5
Request:
{"jsonrpc":"2.0","id":"4","ethod":"starknet_getBlockWithTxs","params":["latest"]}
Reply:
{"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":"4"}
Request:
{"jsonrpc":"2.0","idx":"4","method":"starknet_getBlockWithTxs","params":["latest"]}
Reply:
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}
```
In the former case, rightly so this should be an invalid request. But in the latter case there should be no error as an json-rpc request that does not contain an `id` field is a [notification](https://www.jsonrpc.org/specification#notification) which should just be consumed without a reply. The latter …

fix(rpc/middleware): handle notifications correctly

---

crates/p2p/Cargo.toml
crates/pathfinder/src/bin/pathfinder/main.rs
crates/pathfinder/src/state/sync.rs
crates/rpc/src/cairo/ext_py/service.rs
crates/rpc/src/cairo/ext_py/sub_process.rs
crates/serde/src/lib.rs
crates/stark_curve/src/field.rs

There are stale (>1yo) `TODO`s. Just checking if any of them is still actionable.

chore: remove stale todo items

---

README.md

I was browsing the docs, and i missed this link :)

doc: add Starknet link to README.md

---

crates/pathfinder/src/bin/pathfinder/main.rs

fix: default trace level is invalid

---

crates/storage/src/schema/revision_0032.rs

Only nonce and storage values should be.

fix(storage): state update felts are compressed

---

crates/storage/src/lib.rs

A minor fix to how particular migrations wrt current revision number are logged.
Currently the `revision` record is being appended on each iteration, which gives a rather strange result, where I assume the intention was to overwrite its value:
```
2023-05-24T08:38:25  INFO Performing database migrations current_revision=0 latest_revision=33 migrations=33
2023-05-24T08:38:25  INFO db migration: Re-created the starknet_events table and copied data revision=1 revision=2 revision=3 revision=4 revision=5 revision=6 revision=7 revision=8 revision=9 revision=10 revision=11 revision=12 revision=13 revision=14 revision=15 revision=16 revision=17
2023-05-24T08:38:25  INFO db migration: Re-created the indexes for starknet_events revision=1 revision=2 revision=3 revision=4 revision=5 revision=6 …
```

fix(migration): revision record being added to span on each iteration

---

crates/common/src/macros.rs
crates/ethereum/src/contract.rs
crates/gateway-client/src/lib.rs

Also update mainnet and integration versions.

chore: update mainnet core contract address

---

crates/pathfinder/src/state/sync.rs

This PR fixes sierra compilation happening in an async context. The flow is unified into a single blocking task instead.

fix(sync): sierra compilation is blocking

---

crates/rpc/src/middleware/versioning.rs

feat(middleware): disallow json rpc notifications from clients

---

crates/pathfinder/src/state/sync/class.rs

After the recent incident it became apparent that even subtle differences between the Python JSON encoder and serde-json can lead to production outages because of differences in how we compute class hashes.
This change removes the check that our computed class hash matches the class hash we were expecting and converts the previous error stopping the sync process to a warning.

fix(pathfinder): remove class hash verification for Cairo 0 classes

---

crates/gateway-types/src/class_hash.rs

This PR replaces the cairo 0 unicode hack with the solution from starknet-rs.
Closes #1143

feat: improve cairo 0 unicode handling

---

CHANGELOG.md
Cargo.lock
crates/pathfinder/Cargo.toml

chore: v0.6.2 release prep

---

CHANGELOG.md
crates/pathfinder/src/state/sync/l2.rs

This PR fixes a race condition with downloading sierra classes.

fix: sierra classes sync bug

---

CHANGELOG.md
Cargo.lock
crates/pathfinder/Cargo.toml

chore: v0.6.4 release prep

---

justfile

This PR adds a [justfile](https://github.com/casey/just) for common repo actions.
Feel free to add recipes for running a node on a network etc if we can figure out a nice default setup.

chore: add justfile

---

website/src/blog/2023-06-17_mainnet_incident.md

docs: fix typo in post-mortem

---

CHANGELOG.md
crates/rpc/src/cairo/ext_py.rs
py/pyproject.toml
py/requirements-dev.txt
py/src/pathfinder_worker/call.py
py/tests/pathfinder_worker/test_call.py

Cairo 0.12.0 contains an important change that causes significant differences in transaction fee estimates.
Fixes: #1208

feat(py): upgrade to cairo-lang 0.12.0

---

CHANGELOG.md
crates/rpc/src/pathfinder/methods/get_transaction_status.rs

fix: transaction status returns pending

---

crates/rpc/src/lib.rs
crates/rpc/src/middleware/versioning.rs
crates/rpc/tests/versioning.rs

This PR adds v0.4 API registration and updates tests respectively.

feat: register v0.4 rpc api

---

utils/pathfinder-probe/src/main.rs

Extract function to build a stream of pulled values (from Pathfinder and Gateway) to avoid code duplication.

refactor(probe): extract function

---

CHANGELOG.md
Cargo.lock
crates/pathfinder/Cargo.toml

Preparations for the 0.7.2 release.

chore: bump version to 0.7.2

---

CHANGELOG.md
doc/rpc/rpc_examples_v03.sh

fix: estimateFee example

---

Cargo.toml
Dockerfile

This seems to result in a ~15% improvement for the Cairo VM.

chore(Dockerfile): enable LTO for pathfinder

---

README.md

Now that we actually implement SKIP_FEE_CHARGE.

chore(README): remove `starknet_simulateTransactions` limitation

---

crates/storage/src/lib.rs

"synchronous" is not persistent through sessions. We've previously set "synchronous" when setting the journal mode -- but we _do_ close the database connection after running migrate, so "synchronous" was reset to default when the connection pool was creating new connections.
This change moves the setting to setup_connection() which gets called as an init function from within the connection pool -- thus makes sure that it's correctly set for the journal mode.

fix(storage): really set "synchronous" pragma

---

crates/load-test/src/main.rs
crates/load-test/src/tasks/v03.rs

And the block_explorer scenario now chooses a random block from the first 200k blocks to make it more realistic.

fix(load-test): fix scenario names

---

crates/rpc/src/lib.rs
crates/rpc/src/v05.rs
crates/rpc/src/v05/method.rs
crates/rpc/src/v05/method/spec_version.rs

Add `starknet_specVersion` to JSON-RPC 0.5 API.
Closes #1399

feat(rpc/v0.5): add `starknet_specVersion`

---

Cargo.lock
Cargo.toml
crates/executor/src/block_context.rs

This allows us to have custom changes to the blockifier crate.

chore(executor): use our blockifier fork

---

crates/rpc/src/v05/method/trace_block_transactions.rs

The specification requires `BLOCK_NOT_FOUND` but we were still returning `INVALID_BLOCK_HASH`.

fix(rpc/v05/trace_block_transactions): fix block not found error

---

crates/rpc/src/v05/method/trace_block_transactions.rs

This PR adds support for creating a trace for the pending block.

feat(rpc/v05/trace_block_transactions): add pending block support

---

crates/rpc/src/v05/method/trace_block_transactions.rs
crates/rpc/src/v05/method/trace_transaction.rs

This PR adds support for getting transaction traces for transactions in the pending block.
It re-uses some parts of the transaction fetching and conversion code from the `starknet_traceBlockTransactions` implementation so it also makes some small changes in there.

fix(rpc/v05/trace_transaction): add support for pending transactions

---

crates/rpc/src/v05/method/get_transaction_receipt.rs

Pretty straightforward - field names are wrong.

fix: wrong field names in ExecutionResources

---

CHANGELOG.md
crates/gateway-types/src/reply.rs
crates/rpc/src/v05/method/get_transaction_receipt.rs
crates/serde/src/lib.rs

fix(rpc/v0.5): L1 Handler receipts are missing message hash

---

crates/rpc/src/lib.rs
crates/rpc/src/v06.rs

This PR adds some more methods to v06 that are the same as in JSON-RPC 0.5.1.

feat(rpc/v06): add more methods from v05

---

crates/rpc/src/v06/method/simulate_transactions.rs
crates/rpc/src/v06/method/trace_block_transactions.rs
crates/rpc/src/v06/method/trace_transaction.rs

The JSON-RPC specification requires `constructor_invocation` for DEPLOY_ACCOUNT traces and `function_invocation` for INVOKE_FUNCTION traces.
This change makes these fields non-optional in our JSON-RPC response types. Since the underlying fields both in the executor output and in the feeder gateway output are optional we map missing fields to a new custom error.

fix(rpc/v06): align `TRANSACTION_TRACE` output with the spec

---

crates/compiler/src/lib.rs

The Cairo compiler panics for certain input programs, possibly panicking our JSON-RPC handler or sync tasks.
This commit catches compiler panics and simply converts those to errors so that we can gracefully handle those errors (eg. fall back to fetching the CASM definition from the gateway).

fix(compiler): handle compiler panics as error

---

crates/p2p/src/sync.rs

Fixes: #1614 
Depends on: #1613

Requests should not be varint delimited.

---

crates/common/src/signature.rs
crates/p2p/src/client/peer_agnostic.rs
crates/p2p/src/client/peer_agnostic/parse.rs
crates/p2p/src/client/types.rs
crates/pathfinder/src/p2p_network/client.rs
crates/pathfinder/src/p2p_network/sync_handlers.rs
crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
crates/rpc/src/v03/method/get_state_update.rs
crates/storage/src/fake.rs

add block header signature support to p2p

---

crates/storage/src/connection/block.rs
crates/storage/src/connection/class.rs
crates/storage/src/connection/state_update.rs

Profiling results show that for execution there are some hot paths that have not been using cached prepared statements. This lead to the SQLite query parser showing up in the profiler output.
That's fairly easy to avoid by using cached prepared statements.
This change has been observed to improve performance of simple `starknet_call` calls by roughly 10%.

feat(storage): use cached prepared statements on execution hot-path

---

crates/gateway-types/src/reply.rs
crates/p2p/src/client/types.rs
crates/p2p_proto/proto/transaction.proto
crates/p2p_proto/src/transaction.rs
crates/pathfinder/src/p2p_network/sync_handlers/conv.rs

Some of those fields that I added in anticipation of being added to the spec were actually not needed. This PR fixes this issue.

remove extra p2p txn fields

---

.github/workflows/ci.yml
.github/workflows/msrv.yml

This hopefully resolves issues with the `protoc` setup failing because of rate limiting on the GitHub API.
Closes #1678
Closes #1680

chore(github): use `arduino/setup-protoc` and set GitHub auth token

---

crates/p2p_stream/README.md

doc(p2p_stream): add readme

---

crates/common/src/lib.rs
crates/common/src/receipt.rs
crates/gateway-types/src/reply.rs

Title.
Required for p2p sync to not rely on gateway types.
Closes #1721

feat(common): add receipts type

---

README.md

These new files require Pathfinder 0.11.0-rc0 to work.

chore: add new snapshots to README

---

crates/common/src/receipt.rs
crates/gateway-types/src/reply.rs
crates/p2p/src/client/types.rs
crates/pathfinder/src/p2p_network/sync_handlers/conv.rs
crates/rpc/src/lib.rs
crates/rpc/src/v06/method/get_transaction_receipt.rs
crates/storage/src/connection/transaction.rs
crates/storage/src/test_utils.rs

refactor: common execution resources are mandatory

---

crates/rpc/src/lib.rs
crates/rpc/src/v07.rs

This PR adds all unchanged RPC methods.
Closes #1776

feat(rpc/v0.7): unchanged methods

---

crates/rpc/src/v07.rs

chore(rpc): bump spec version to v0.7.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/rpc/src/v06/method/simulate_transactions.rs
crates/rpc/src/v07/method/estimate_fee.rs
crates/rpc/src/v07/method/simulate_transactions.rs

Upgrade blockifier to 0.6.0-rc.1.

feat(executor): upgrade blockifier to 0.6.0-rc.1

---

crates/common/src/event.rs
crates/p2p/src/client/peer_agnostic.rs
crates/pathfinder/src/state/block_hash.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/sync.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/class_definitions.rs
crates/pathfinder/src/sync/error.rs
crates/pathfinder/src/sync/events.rs
crates/pathfinder/src/sync/headers.rs
crates/pathfinder/src/sync/state_updates.rs
crates/storage/src/connection/block.rs
crates/storage/src/connection/state_update.rs
crates/storage/src/connection/transaction.rs
crates/storage/src/fake.rs

Fixes https://github.com/eqlabs/pathfinder/issues/1702

p2p event sync

---

crates/p2p/Cargo.toml
crates/p2p/src/client/peer_agnostic.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/events.rs
crates/storage/src/connection/transaction.rs
crates/storage/src/fake.rs

test: event sync

---

crates/storage/src/connection/trie.rs

hen pruning state tries we have to be careful with removing trie roots and leaves (specifically contract state hashes, as we never remove leaves from the contracts and classes tries).
State tries for block N might use roots/leaves added _before_ that block. We insert trie roots only for a specific block only if the value has changed. That means that at block N the state contains the _last_ trie root indices added before or at block N.
This PR changes all trie root deletion methods to determine the block number with the last update and remove data _before_ that block.

fix(storage/trie): don't remove roots and leaves that might still be used

---

crates/pathfinder/examples/feeder_gateway.rs

This change adds reorg simulation support to our `feeder_gateway` tool.
If enabled via the `--reorg-at-block` and `--reorg-to-block` CLI options the tool returns "Block not found" errors just so that pathfinder's sync logic performs a reorg.

feat(examples/feeder_gateway): add optional support for reorg simulation

---

crates/p2p/src/client/peer_agnostic.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/class_definitions.rs
crates/pathfinder/src/sync/error.rs
crates/storage/src/connection/class.rs
crates/storage/src/connection/state_update.rs

p2p class sync tests

---

crates/ethereum/src/lib.rs
crates/p2p/src/client/conv.rs
crates/p2p/src/client/peer_agnostic.rs
crates/pathfinder/proptest-regressions/p2p_network/sync_handlers/tests.txt
crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
crates/pathfinder/src/sync.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/class_definitions.rs
crates/pathfinder/src/sync/error.rs
crates/pathfinder/src/sync/events.rs
crates/pathfinder/src/sync/state_updates.rs
crates/pathfinder/src/sync/transactions.rs
crates/storage/src/connection/block.rs
crates/storage/src/connection/transaction.rs
crates/storage/src/fake.rs
utils/pathfinder-probe/src/main.rs

added:
- transaction hash computation
- transaction commitment verification
refactored:
- transaction sync loop into more streamed style processing
fixed:
- fake storage generated Deploy txns with duplicate hashes
test added:
- happy path
still TODO:
- some failure paths, which ~~I'm happy to~~ __will__ do in a follow up PR because this one is big enough

p2p sync transactions test

---

crates/pathfinder/src/sync/checkpoint.rs

Add error scenarios for transaction sync.

test(checkpoint/transactions): add failure scenarios

---

crates/p2p/src/behaviour.rs
crates/p2p/src/client/conv.rs
crates/p2p/src/client/peer_agnostic.rs
crates/p2p/src/sync.rs
crates/p2p_proto/proto/class.proto
crates/p2p_proto/proto/common.proto
crates/p2p_proto/proto/event.proto
crates/p2p_proto/proto/header.proto
crates/p2p_proto/proto/receipt.proto
crates/p2p_proto/proto/state.proto
crates/p2p_proto/proto/transaction.proto
crates/p2p_proto/src/class.rs
crates/p2p_proto/src/common.rs
crates/p2p_proto/src/state.rs
crates/p2p_proto/src/transaction.rs
crates/pathfinder/src/p2p_network/sync_handlers.rs
crates/pathfinder/src/p2p_network/sync_handlers/conv.rs
crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/class_definitions.rs
crates/pathfinder/src/sync/error.rs

Fixes: #2017 
Fixes: #2018 
Fixes: #2023 
Disclaimer: I'm still not sure what the Identity and Kad protocol names should be so I left those out of the scope

p2p: final spec alignment

---

crates/p2p/src/client/peer_agnostic.rs
crates/pathfinder/src/sync.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/class_definitions.rs

p2p checkpoint sync: compile sierra to casm and fall back to the fgw on failure

---

crates/p2p/src/client/peer_agnostic.rs
crates/pathfinder/src/p2p_network/sync_handlers.rs
crates/pathfinder/src/p2p_network/sync_handlers/tests.rs

p2p: emit declared

---

crates/common/src/lib.rs
crates/p2p/src/behaviour.rs
crates/p2p/src/bin/bootstrap/behaviour.rs
crates/p2p/src/lib.rs

As in the title.
Related [spec PR](https://github.com/starknet-io/starknet-p2p-specs/pull/33).

feat: update kad and indentify protocol names

---

crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/error.rs
crates/pathfinder/src/sync/headers.rs
crates/pathfinder/src/sync/stream.rs

This has lost the persistance chunking, but we can easily add that back in.

refactor: checkpoint header sync now uses stages

---

crates/common/src/header.rs
crates/p2p/src/client/conv.rs
crates/p2p/src/client/peer_agnostic.rs
crates/p2p_stream/tests/utils/mod.rs
crates/pathfinder/examples/verify_block_hashes.rs
crates/pathfinder/src/bin/pathfinder/main.rs
crates/pathfinder/src/p2p_network/sync_handlers/tests.rs
crates/pathfinder/src/state/block_hash.rs
crates/pathfinder/src/state/sync/l2.rs
crates/pathfinder/src/sync.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/class_definitions.rs
crates/pathfinder/src/sync/error.rs
crates/pathfinder/src/sync/events.rs
crates/pathfinder/src/sync/fixtures/sepolia_headers.json
crates/pathfinder/src/sync/headers.rs
crates/pathfinder/src/sync/track.rs

checkpoint header sync tests

---

Cargo.lock
crates/compiler/Cargo.toml
crates/compiler/src/lib.rs
crates/p2p/src/main_loop.rs
crates/pathfinder/src/sync.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/class_definitions.rs
crates/pathfinder/src/sync/headers.rs

Also converts a `todo!()` into a log and a comment so that we can start testing.

chore(p2p): add some log lines

---

crates/p2p/src/client/peer_agnostic.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/state_updates.rs
crates/pathfinder/src/sync/track.rs
crates/pathfinder/src/sync/transactions.rs
crates/storage/src/connection/block.rs
crates/storage/src/connection/state_update.rs

refactor checkpoint state diff sync

---

Dockerfile

To align better with the version we use in CI.

chore(Dockerfile): upgrade Rust to 1.79

---

crates/tagged/src/lib.rs

fix(tagged): warnings in release build

---

Cargo.lock
Cargo.toml
crates/p2p/Cargo.toml
crates/pathfinder/Cargo.toml
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/class_definitions.rs
crates/pathfinder/src/sync/events.rs
crates/pathfinder/src/sync/state_updates.rs
crates/pathfinder/src/sync/transactions.rs

refactor: finally remove async_stream

---

crates/p2p/src/client/peer_aware.rs
crates/pathfinder/src/bin/pathfinder/config.rs
crates/pathfinder/src/p2p_network.rs
crates/pathfinder/src/sync.rs

Fixes: #2177 
Also fixes:
- invalid default kad protocol name

error: "protocol not supported" plus minor improvements

---

doc/install-from-source.md

Updates `install-from-source.md` with correct minimum rust version requirement as per project specs.
Closes #2174

docs: update minimum rust version requirement

---

crates/rpc/src/method/get_events.rs

fix: handle edge case when from_block is greater than latest_block_number

---

crates/pathfinder/src/sync/headers.rs

Add a log message for block hash verification errors. Otherwise we won't even know which block has failed...

chore(pathfinder/sync): log block hash verification errors

---

crates/p2p/src/client/peer_agnostic.rs

fix(p2p): initial 60s delay in get_random_peers

---

crates/pathfinder/src/state/sync/l1.rs

Removes a couple logs that somehow re-surfaced

fix: remove logs

---

crates/pathfinder/examples/compute_pre0132_hashes.rs

Re-compute `transaction_commitment`, `event_commitment`, `state_diff_commitment` using 0.13.2 calculation in our pre-0.13.2 compute tool

fix: re-compute inconsistent commitments for every pre-0.13.2 block using the 0.13.2 hashing method

---

Cargo.lock
crates/ethereum/Cargo.toml

Remove `native-tls` dependency from `alloy`

---

Cargo.lock
crates/p2p/src/behaviour.rs
crates/p2p/src/behaviour/builder.rs
crates/p2p/src/bin/bootstrap/main.rs
crates/p2p/src/builder.rs
crates/p2p/src/lib.rs
crates/p2p/src/main_loop.rs
crates/p2p/src/test_utils/peer.rs
crates/p2p/src/tests.rs
crates/p2p_stream/Cargo.toml
crates/pathfinder/src/bin/pathfinder/config.rs
crates/pathfinder/src/bin/pathfinder/main.rs

feat: allow one custom kad name in config

---

README.md

This PR make some small fixes and removes obsolete parts of the README, plus adds a new section with hardware requirements.

chore: some more README updates

---

crates/pathfinder/src/sync.rs
crates/pathfinder/src/sync/checkpoint.rs

`checkpoint_sync()` returns the point from where tracking sync should start. If the latest L1 confirmed state (checkpoint) was behind what we already had in storage (because tracking sync has started previously) then this continuation point was wrong: it was always the block after the latest L1 confirmed state, which then caused tracking sync to fail on the first block.

fix(pathfinder/sync): fix checkpoint sync continuation point

---

crates/pathfinder/src/sync/checkpoint.rs

I personally have problems remembering what is an anchor as opposed to what is a checkpoint (and which is which), so I added these small comments for clarity.

doc: explain what anchor and checkpoint mean in LocalState

---

CHANGELOG.md
crates/pathfinder/src/bin/pathfinder/config.rs
crates/rpc/src/lib.rs
crates/rpc/src/middleware/cors.rs

Defaults to `v07` RPC version
Closes #2197

chore: default to `v07` RPC version

---

Cargo.lock
Cargo.toml
crates/make-stream/Cargo.toml
crates/make-stream/src/lib.rs
crates/p2p/Cargo.toml
crates/p2p/src/client/peer_agnostic.rs
crates/pathfinder/Cargo.toml
crates/pathfinder/src/bin/pathfinder/config.rs
crates/pathfinder/src/sync/checkpoint.rs
crates/pathfinder/src/sync/class_definitions.rs
crates/pathfinder/src/sync/error.rs
crates/pathfinder/src/sync/storage_adapters.rs

Tested on sepolia in block range ` 220007..=221000`:
- `main`: 212 sec (100%)
- with this PR: 91 sec (42%, ~2.3x speedup)

Rayonize compilation and hashing in class-definition-checkpoint-sync

---

doc/rpc/v08/starknet_api_openrpc.json
doc/rpc/v08/starknet_trace_api_openrpc.json

From latest specifications available in the `starknet-specs` repo.

chore(doc/rpc/v08): update OpenRPC specifications

---

crates/common/src/error.rs

`RUST_BACKTRACE=1|full` causes `anyhow::Error` to append the backtrace to the debug representation. Calling `just test` resulted in a failing test because of the this.
Backtraces for compared instances of the error differ because there are created at different source lines, so we just skip comparing them.

test(common/error): fix test failure when RUST_BACKTRACE enabled

---

crates/rpc/src/lib.rs
crates/rpc/src/v08.rs

Adds support for `starknet_getTransactionReceipt` in RPC v08

feat(rpc): add `starknet_getTransactionReceipt`

---

crates/pathfinder/src/sync/class_definitions.rs

Keeping a transaction open causes the SQLite WAL file to grow over 2GiB because changes cannot be merged back into the database as long as there are open read transactions.
Re-creating the SQLite transaction for each and every object seems suboptimal but according to measurements there's no significant difference in sync performance so implementing a batch query scheme would add considerable complexity without apparent benefits.
Closes #2242

fix(sync/class_definitions): don't keep a read transaction open during checkpoint sync

---

crates/pathfinder/src/sync.rs
crates/pathfinder/src/sync/track.rs

Fixes: #2364 
Also:
Fixes: #2373
(A just discovered `LatestStream` inconsistency).

fix(sync/track): missing transactions is a fatal error

---

crates/rpc/src/method/subscribe_events.rs
crates/rpc/src/method/subscribe_new_heads.rs
crates/rpc/src/method/subscribe_transaction_status.rs

feat(rpc): rename `block` to `block_id` as per updated starknet spec

---

CHANGELOG.md
crates/rpc/src/v08.rs

And add JSON-RPC 0.8.0-rc1 support to the changelog.

feat(rpc/v08): bump JSON-RPC spec version to 0.8.0-rc1

---

crates/common/src/transaction.rs

feat: using l1_data_gas in transaction hash

---

crates/storage/src/connection/event.rs

There was a bug in the code that made the limit on loading uncached Bloom filters ineffective. This change fixes that by moving the check to the correct place in the loop so that it's actually enforced.
Closes: #2431

fix(storage/event): really check max uncached bloom filter load limit

---

crates/merkle-tree/src/tree.rs
crates/rpc/src/method/estimate_fee.rs
crates/rpc/src/v06/method/estimate_fee.rs

Short description of what this PR does.
fix some typos in comment
Delete once completed:

chore: fix some typos in comment

---

crates/gateway-types/src/reply.rs
crates/pathfinder/examples/feeder_gateway.rs
crates/pathfinder/src/state/block_hash.rs
crates/pathfinder/src/state/sync.rs
crates/pathfinder/src/state/sync/l2.rs
crates/pathfinder/src/state/sync/pending.rs
crates/rpc/src/jsonrpc/websocket/logic.rs

Starknet 0.13.4, update feeder gateway interface

---

crates/pathfinder/src/bin/pathfinder/config.rs
crates/pathfinder/src/bin/pathfinder/main.rs

feat(rpc): allow defaulting to v08 from cli argument

---

crates/pathfinder/src/bin/pathfinder/config.rs
crates/pathfinder/src/bin/pathfinder/main.rs

fix: add RootRpcVersion::V06

---

crates/rpc/fixtures/0.6.0/broadcasted_transactions.json
crates/rpc/src/types.rs

feat(rpc): fix serialization of `l1_data_gas`

---

crates/ethereum/src/lib.rs

Optimally the address should be effective in the filter, but for some reason that doesn't happen (not even using the syntax documented at https://alloy.rs/building-with-alloy/queries.html , i.e. `Filter::new().event("LogStateUpdate(uint256,int256,uint256)").address(core_address)`)... The other filter in the source file (`LogMessageToL2_filter()`) is also used explicitly.
Fixes https://github.com/eqlabs/pathfinder/issues/2599 .

fix: drop "LogStateUpdate"s from unknown addresses without parsing

---

Cargo.lock
Cargo.toml
crates/class-hash/Cargo.toml
crates/compiler/Cargo.toml
crates/ethereum/Cargo.toml
crates/executor/Cargo.toml
crates/gateway-types/Cargo.toml
crates/merkle-tree/Cargo.toml
crates/p2p/Cargo.toml
crates/p2p_proto/Cargo.toml
crates/storage/Cargo.toml
crates/util/Cargo.toml

Found by running `cargo +nightly udeps --workspace --all-targets`.

chore(deps): remove unused dependencies

---

docs/docs/interacting-with-pathfinder/json-rpc-api.md

Seems like the version should be rc3 now :)

chore(docs): update json-rpc version

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
Dockerfile
build/cargo-build.sh
build/cargo-chef-cook.sh
build/prepare.sh
crates/executor/Cargo.toml
crates/executor/src/execution_state.rs
crates/executor/src/lib.rs
crates/executor/src/state_reader.rs
crates/executor/src/state_reader/native.rs
crates/pathfinder/Cargo.toml
crates/pathfinder/examples/re_execute.rs
crates/pathfinder/src/bin/pathfinder/config.rs
crates/pathfinder/src/bin/pathfinder/main.rs
crates/rpc/src/context.rs
crates/rpc/src/jsonrpc/router/subscription.rs
crates/rpc/src/method/call.rs
crates/rpc/src/method/estimate_fee.rs
crates/rpc/src/method/estimate_message_fee.rs
crates/rpc/src/method/simulate_transactions.rs
crates/rpc/src/method/subscribe_events.rs
crates/rpc/src/method/subscribe_new_heads.rs
crates/rpc/src/method/subscribe_pending_transactions.rs
crates/rpc/src/method/subscribe_transaction_status.rs
crates/rpc/src/method/trace_block_transactions.rs
crates/rpc/src/method/trace_transaction.rs

This PR adds a new (disabled by default) feature called `cairo-native` that enables compiling of Sierra >= 1.7.0 classes to Cairo Native artifacts and uses those during execution.
When the feature is enabled, native execution can be enabled using `--rpc.native-execution true`. That enables the following behavior:
- `PathfinderStateReader` will utilize a `NativeClassCache` to look up compiled (native) classes when loading a class definition and return native classes (if available)  in `get_compiled_class()`.
- `NativeClassCache` is utilizing on-demand, delayed compilation. That is, when a native class is requested for a Sierra class that has not been compiled yet, it starts compilation on a background thread and returns that the native class is not (yet) available. `PathfinderStateReader` …

Add Cairo Native support

---

crates/rpc/src/error.rs
crates/rpc/src/v08.rs
specs/rpc/v08/starknet_api_openrpc.json
specs/rpc/v08/starknet_executables.json
specs/rpc/v08/starknet_trace_api_openrpc.json
specs/rpc/v08/starknet_write_api.json
specs/rpc/v08/starknet_ws_api.json

chore(rpc): update JSON-RPC 0.8 specification to the v0.8.0 version

---

crates/pathfinder/src/bin/pathfinder/config.rs
crates/rpc/src/error.rs
crates/rpc/src/jsonrpc/error.rs
crates/storage/src/connection/block.rs
crates/storage/src/connection/trie.rs

chore: fix clippy for `1.86.0`

---

crates/p2p-v2/src/builder.rs
crates/p2p-v2/src/consensus.rs
crates/p2p-v2/src/consensus/behaviour.rs
crates/p2p-v2/src/core.rs
crates/p2p-v2/src/core/behaviour/builder.rs
crates/p2p-v2/src/core/client.rs
crates/p2p-v2/src/lib.rs
crates/p2p-v2/src/sync.rs
crates/p2p-v2/src/sync/behaviour.rs
crates/p2p-v2/src/sync/behaviour/builder.rs
crates/p2p-v2/src/sync/protocol.rs

Minor housekeeping on module visibility and docs

feat(p2p): minor module visibility and doc enhancements

---

crates/rpc/src/pathfinder/methods/get_proof.rs

hey team! I found duplicate words and fixed them.

docs: remove consecutive duplicate words

---

CHANGELOG.md
Cargo.lock
crates/pathfinder/src/bin/pathfinder/config.rs
crates/pathfinder/src/bin/pathfinder/main.rs
crates/rpc/Cargo.toml
crates/rpc/src/context.rs
crates/rpc/src/lib.rs
crates/rpc/src/mempool.rs
crates/rpc/src/method/add_declare_transaction.rs
crates/rpc/src/method/add_deploy_account_transaction.rs
crates/rpc/src/method/add_invoke_transaction.rs
crates/rpc/src/method/get_transaction_status.rs
crates/rpc/src/tracker.rs

Fixes #2727 .
Adds a "minimal mempool", which is just a cache of transaction hashes recently added to the gateway by this node.
`pathfinder-rpc` dependency on the `cached` package was made explicit, but implicitly it was already there...

feat: minimal mempool

---

crates/pathfinder/examples/dump_events.rs

Extended `dump_events` with key filtering.
Allowing empty keys and combination with address filtering (unlike the scripts in starknet-event-query').

feat: optional filtering by keys

---

specs/rpc/v09/starknet_api_openrpc.json
specs/rpc/v09/starknet_executables.json
specs/rpc/v09/starknet_trace_api_openrpc.json
specs/rpc/v09/starknet_write_api.json
specs/rpc/v09/starknet_ws_api.json

Technically this is still _not_ v0.9.0-rc.1, but still much more up-to-date than our previous state.

feat(specs/rpc/v09): update specs to the current candidate version

---

docs/docs/interacting-with-pathfinder/websocket-api.md

Fixes https://github.com/eqlabs/pathfinder/issues/2829 .

chore(docs): mentioning disabled-by-default websocket API

---

CHANGELOG.md

Changelog entry for https://github.com/eqlabs/pathfinder/issues/2777 .

chore: mentioning stricter --rpc.websocket.enabled in Changelog

---

crates/consensus/src/wal.rs

Fixes the WAL filename height extraction code, which was not accounting for the WAL file prefix.

fix(consensus): wal filename height extraction fix

---

crates/rpc/src/error.rs
crates/rpc/src/v09.rs
specs/rpc/v09/starknet_api_openrpc.json
specs/rpc/v09/starknet_write_api.json

And fix the response of `starknet_specVersion` on the `v09` API.

chore(rpc/v09): upgrade specs to 0.9.0-rc.2

---

CHANGELOG.md
crates/rpc/src/method.rs
crates/rpc/src/method/last_l1_accepted_block_hash_and_number.rs
crates/rpc/src/pathfinder.rs
crates/rpc/src/v06.rs
crates/rpc/src/v07.rs
crates/rpc/src/v08.rs
crates/rpc/src/v09.rs
specs/rpc/pathfinder_rpc_api.json

feat(rpc): added `pathfinder_lastL1AcceptedBlockHashAndNumber`

---

crates/consensus/src/internal.rs
crates/consensus/src/lib.rs
crates/consensus/tests/consensus_sim.rs
crates/consensus/tests/wal.rs

No business logic changes, just aesthetic changes for clarity.
Also removed a leftover `NetworkCommand` that somehow slipped from the `malachite v0.3.0` upgrade. Thanks @CHr15F0x!

chore(consensus): Aesthetic housekeeping after interop. meeting

---

crates/pathfinder/src/bin/pathfinder/main.rs
crates/pathfinder/src/state/sync.rs
crates/rpc/src/dto/block.rs
crates/rpc/src/lib.rs
crates/rpc/src/method.rs
crates/rpc/src/method/add_declare_transaction.rs
crates/rpc/src/method/add_deploy_account_transaction.rs
crates/rpc/src/method/add_invoke_transaction.rs
crates/rpc/src/method/call.rs
crates/rpc/src/method/subscribe_transaction_status.rs
crates/rpc/src/pending.rs
crates/rpc/src/tracker.rs

Closes https://github.com/eqlabs/pathfinder/issues/2879.

fix(rpc): subscribe tx status follow-up

---

crates/executor/src/types.rs
crates/pathfinder/src/bin/pathfinder/main.rs
crates/pathfinder/src/consensus.rs
crates/pathfinder/src/consensus/inner.rs
crates/pathfinder/src/consensus/inner/consensus_task.rs
crates/pathfinder/src/consensus/inner/p2p_task.rs
crates/pathfinder/src/validator.rs

Now with working smoke test.
Closes https://github.com/eqlabs/pathfinder/issues/2921.

P2P proposal validation 2

---

Cargo.lock
crates/consensus/Cargo.toml
crates/consensus/src/internal.rs

Still running some tests, but seems like this should do it

feat(consensus): upgrade malachite to `v0.5`
